# This was autogenerated! Do not modify
SUMMARY = "Informational list of cross-build-essential packages"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "build-essential"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/build-essential/crossbuild-essential-arm64_12.12_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0cca07ddeff6dc9fc800d681a87ecdf3"
SRC_URI[deb0.sha1sum] = "b6a8130640ca0582005d277b9c9d8e34cdedf383"
SRC_URI[deb0.sha256sum] = "1c980751db9a22cf5340f8137dcd33d54cbacc1f4dc5c0b747966eca6c3ea3c6"
SRC_URI[deb0.sha512sum] = "a0fdaa83e35a80d7733b924a57cf51d27247f69044f5ad3c6aa49f050b34645d091897f1bcc3f29c0be92a403247344ff828c557a426c4ba902ec8dc3a72d25b"

RDEPENDS = " \
    g++-aarch64-linux-gnu \
    gcc-aarch64-linux-gnu \
"

