# This was autogenerated! Do not modify
SUMMARY = "XML parsing C library - runtime library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "expat"
HOMEPAGE = "https://libexpat.github.io/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/expat/libexpat1_2.8.2-1~deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/expat/libexpat1_2.8.2-1~deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "bf4cd0ad8944d661f68c1c4118c00db8"
SRC_URI[deb0.sha1sum] = "704850b2261219c166e0492d8ca88b0eafc57e0a"
SRC_URI[deb0.sha256sum] = "f5258ad21bc9f92da3beeca78258a799c6418a5021cb9bcaf45e842fd4d480c2"
SRC_URI[deb0.sha512sum] = "ac50a764238fac05ec1e012f462d6ccbb6cf91ab72c0206d5c9cfc62315fd1bdd334d21c0e0e10db68278d7631464b3019f0ef79fcce939eaadaa018cbf5b8f5"
SRC_URI[deb1.md5sum] = "1ca09a74067db3d8666e8c0f327a63e4"
SRC_URI[deb1.sha1sum] = "65324ea558ec6aaec4718bf1c720fd9de21d793c"
SRC_URI[deb1.sha256sum] = "576b7a9c2dbdde2b195575fef5718dbdb83ec3727e9a73adf6d275667ef05d2b"
SRC_URI[deb1.sha512sum] = "958662f25de1eace8fc0812e2a5a94ebe374b4f00a76c6d248640fabf03871d5f7db6854dc75614c27fa4dd3f9bb769a5c5aa39e293d7a0bacb30f9ea361aacb"

RDEPENDS = " \
    libc6 \
"

