# This was autogenerated! Do not modify
SUMMARY = "palette quantization library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libimagequant"
HOMEPAGE = "https://github.com/ImageOptim/libimagequant"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libi/libimagequant/libimagequant0_2.18.0-1+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libi/libimagequant/libimagequant0_2.18.0-1+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "044a559e73758ac98071f5c87e7eda6b"
SRC_URI[deb0.sha1sum] = "a947ce4cf140d340d9e79ddc454be56752dbf390"
SRC_URI[deb0.sha256sum] = "83a86fe813ca44d5c6ede86684d6ebe5c8f8b1b01d19743fa382315b38080b64"
SRC_URI[deb0.sha512sum] = "9bc4b8fb2b29412685b2f7c2a900f1ba0efa37a2e293ac62ba0d2206494764dca390a16ff9721ee9fdc2ba6d6cf9c1ef54ba7c486eda28b07a4872c440284597"
SRC_URI[deb1.md5sum] = "a8ea5a3bfcde99c3a2a3d341d1e374e1"
SRC_URI[deb1.sha1sum] = "4dd5f959745fde6c4baabf66ad0bd39460692f54"
SRC_URI[deb1.sha256sum] = "cac78241d9022f4107c9e167aa9e3fe68878eb8b0c6388b780b99ea1ad7eb628"
SRC_URI[deb1.sha512sum] = "c588f0b1b22327e885d9cf1bc1b7f57d765225b20f89b4d7c0919ecb4e42cd8a3ab9ede7c14bc1ba6be5494581cf9021deea370d8447ef28d8a4a0920f9f9b95"

RDEPENDS = " \
    libc6 \
    libgomp1 \
"

