# This was autogenerated! Do not modify
SUMMARY = "high level interface to Linux seccomp filter"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libseccomp"
HOMEPAGE = "https://github.com/seccomp/libseccomp"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libseccomp/libseccomp2_2.6.0-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libseccomp/libseccomp2_2.6.0-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "6f3ecc3a1c0ddc47dd96b83f366596a1"
SRC_URI[deb0.sha1sum] = "24123b32b6afb1f186a31ab8a2175dc438558653"
SRC_URI[deb0.sha256sum] = "89d5138e05fb6a86b9afd8b54dc0fb4b14f4c27c05e6c5f767c2132bdf808531"
SRC_URI[deb0.sha512sum] = "dd09d9c921ca2c06c6689616d5ef2462f75d1b524cdb33ca417d2e86c70780b8b3ae6a9f7c102355b7db64449540247c2148c1cbb9513ccf6b91567054c336a0"
SRC_URI[deb1.md5sum] = "9a6ec6b41e1d9ff664b1f6800c09e4d1"
SRC_URI[deb1.sha1sum] = "619e147ea8a187a6b091eca36a868b5db6e605a9"
SRC_URI[deb1.sha256sum] = "013d0af0444177960d5899f4673e35d492f31edfc40cb8d5a82bb56147ab2e35"
SRC_URI[deb1.sha512sum] = "d0e085a8f6f5d8bea1372bb2b17d7ed147640ef04553d3b7457361abd37082f42d213a19c00308d359d3377546b9813bace5b1f609f8532cc6186cbdcd328207"

RDEPENDS = " \
    libc6 \
"

