# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format (kmsg scanner plugin)"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Oomkiller scanner plugin."
SECTION = "admin"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elos-plugin-scanner-oomkiller_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f85e55dfaa676493ee3338b76265396c"
SRC_URI[deb0.sha1sum] = "e30eedbf4ab658686b316ad7ef54bf919f59eac5"
SRC_URI[deb0.sha256sum] = "59f01248099d51b1b1cb234922bf374dbdf63d6003f78b19d078954a0857d644"

RDEPENDS = " \
    libc6 \
    libelosplugin1 \
    libsafu0 \
"

