# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format (TCP client plugin)"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
A plugin to communicate with elos via TCP connections. It supports client authorization \
for local connections."
SECTION = "admin"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elos-plugin-client-tcp_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "66ae342f9c6bfc3bd13a3e7dc129a433"
SRC_URI[deb0.sha1sum] = "c7800b202c136fad0d712912153289b324931180"
SRC_URI[deb0.sha256sum] = "2759014d3b04b2d4ebe3f0a2c60520940a339a6c16c779fa4c66181aa2a653a8"

RDEPENDS = " \
    libc6 \
    libelosplugin1 \
    libmnl0 \
    libsafu0 \
"

