# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format (DLT plugin)"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
DLT backend plugin."
SECTION = "libs"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elos-plugin-backend-dlt_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "8292f3189fe7b059cdfa563f0df12d3e"
SRC_URI[deb0.sha1sum] = "c2f8af94c6d648f9528e5b3bfe2cea6ec49c0b02"
SRC_URI[deb0.sha256sum] = "0f2d37526dcee62ce528ccb60727f367b344a023f11650d0ee899b08747053ac"

RDEPENDS = " \
    libc6 \
    libelosdlt1 \
    libelosplugin1 \
    libsafu0 \
    libsamconf0 \
"

