# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format (syslog plugin)"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Syslog scanner plugin."
SECTION = "libs"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elos-plugin-scanner-syslog_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "39d35b33254fd8dda65b5c084be34e2c"
SRC_URI[deb0.sha1sum] = "6e4ca408328712336a8327011e8d5f535e0c6b5c"
SRC_URI[deb0.sha256sum] = "cf3d11e4edee8a8898060220a5d360a3b7bd497c07fe31c97a29e3c53220ea3e"

RDEPENDS = " \
    libc6 \
    libelosplugin1 \
    libsafu0 \
    libsamconf0 \
"

