# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format DLT library"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Common parts used in multiple packages shared library package."
SECTION = "libs"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/libelos-common1_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a2cc202351a2e653b55b6f09591d4538"
SRC_URI[deb0.sha1sum] = "5b26e088957d62c1126806710670dc3947bf9784"
SRC_URI[deb0.sha256sum] = "a76fb0f129914751afe297c47f129d4988dfcc17c1120c95eecaf59c96168ead"

RDEPENDS = " \
    libc6 \
"

