# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format plugin library"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Plugin shared library package."
SECTION = "libs"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/libelosplugin1_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "83bf56cba415b7eb2e2056c2a949810f"
SRC_URI[deb0.sha1sum] = "f6eda69a9e8542bc15d06f5cf871a72b0bb0dcb6"
SRC_URI[deb0.sha256sum] = "f6515d6ade57f401682e9080e2dd3b0e45ab940edb0dd70f2f873afa66b6ece9"

RDEPENDS = " \
    libc6 \
    libelos-common1 \
    libjson-c5 \
    libsafu0 \
    libsamconf0 \
"

