# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format library"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Shared library package."
SECTION = "libs"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/libelos1_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "700f87cf5a9f56d5b665abe7b8b2d31b"
SRC_URI[deb0.sha1sum] = "f41efa76c2b418fb8e6f061ed2e9a626f069ba4d"
SRC_URI[deb0.sha256sum] = "333e463e3a27b589094cb9328c88e6c26732e5667bc0d04d73ec3adb5564e510"

RDEPENDS = " \
    libc6 \
    libelos-common1 \
    libjson-c5 \
    libsafu0 \
"

