# This was autogenerated! Do not modify
SUMMARY = "Linux support headers for userspace development"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "linux"
HOMEPAGE = "https://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/linux/linux-libc-dev_6.12.96-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "4c64f90ca4875fa61aa37f34eb8831da"
SRC_URI[deb0.sha1sum] = "66b33fe93d5d572e06cdabdd49d01c7b4947cfc7"
SRC_URI[deb0.sha256sum] = "c514b81492fc01c573ecfc809f9b460023d50e5006848c4caf78997bf1f776a5"
SRC_URI[deb0.sha512sum] = "db0e66eaf40fc9ad4974cb94a00a43495d93fedacc3eadeee7ce7d6e4c1fd2b38e0f90e51a85449399ee5d15d52c1eac7f00db32cd26a2f062b5827223ad3693"


