# This was autogenerated! Do not modify
SUMMARY = "Linux support headers for userspace development"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "linux"
HOMEPAGE = "https://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/linux/linux-libc-dev_6.12.95-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "566dc00c0f705b1560ddd9b030179d26"
SRC_URI[deb0.sha1sum] = "2b8a574bdef5602b79b122706db435ecdc96b0d4"
SRC_URI[deb0.sha256sum] = "c62d1f64927f3b0340133aa7e5587f65f607d2ad4d96be9c61d2cd85a397c931"
SRC_URI[deb0.sha512sum] = "82a01b5102cdfb37e585fd8291293997ace5d5382b4cff4f397ef7a0c037326e0e5c226f0e06eebbcebaef7bec8297810faaceae421a16f2181522fb2826d2b1"


