# This was autogenerated! Do not modify
SUMMARY = "Linux support headers for userspace development"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "linux"
HOMEPAGE = "https://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/linux/linux-libc-dev_6.12.100-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "31553c08db4808af9fc8930f8ec72b85"
SRC_URI[deb0.sha1sum] = "5df355a302df39759cc3b8a862877ecac88a8536"
SRC_URI[deb0.sha256sum] = "81663fd32e2657a9c714c8982936234c9afcfc0ba90c92a45587c359e8592799"
SRC_URI[deb0.sha512sum] = "1a145eab33bd2cf7cb54bba64ee649bfba48d284396c029df7591153a2bd300d3268b663d61c42ed9dae392201c5bee33ec31fcdd8a85dd1ae939c4ccf73b86f"


