# This was autogenerated! Do not modify
SUMMARY = "Linux support headers for userspace development"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "linux"
HOMEPAGE = "https://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/linux/linux-libc-dev_6.12.101-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e851b9696c20422a1e9ea4a669f6e44c"
SRC_URI[deb0.sha1sum] = "9fbcc5a5c1443b718e5d5021be917391fff1410b"
SRC_URI[deb0.sha256sum] = "e776ef48b89af0409c6bcd2e8a7e14a3d75d0842b9fd3dc767b7822a0b0950e2"
SRC_URI[deb0.sha512sum] = "7e987f14e7fe24ba2236d066f1bcec271806a91c9932736a7b599cd0b2f0b91c46feea70ca28fb0fe7987021648bde922c055ad21251bbc863b3886c1527a9bb"


