# This was autogenerated! Do not modify
SUMMARY = "GNU C preprocessor for aarch64-linux-gnu"
DESCRIPTION = ""
SECTION = "interpreters"
SOURCE_PACKAGE = "gcc-14"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/cpp-14-aarch64-linux-gnu_14.2.0-19_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0e0940c80c4579647693022c828029b1"
SRC_URI[deb0.sha1sum] = "442a7499f60ee6aa5a6b68735c391f76e256a3f8"
SRC_URI[deb0.sha256sum] = "8e588ac3efe06f7784b08feac584c70e6965b74c045bae7e4e80bb42938f7dbe"
SRC_URI[deb0.sha512sum] = "823e59779cc64473d9816dfe85a40d99d27b15968fa14244406eab6669abb128c138653f957d1cfc508f869169a33a9681b470c8d59b7c122fd83f1fa448b786"

RDEPENDS = " \
    gcc-14-base \
    libc6 \
    libgmp10 \
    libisl23 \
    libmpc3 \
    libmpfr6 \
    libzstd1 \
    zlib1g \
"

