# This was autogenerated! Do not modify
SUMMARY = "library for parsing and generating CBOR (RFC 7049)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libcbor"
HOMEPAGE = "https://github.com/PJK/libcbor"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libc/libcbor/libcbor0.10_0.10.2-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libc/libcbor/libcbor0.10_0.10.2-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8c72ad716141e2fdba061602b2dfd038"
SRC_URI[deb0.sha1sum] = "58dbdc2c2308f485943db0cb8d9f172474a2c8e2"
SRC_URI[deb0.sha256sum] = "2457686e375dcb7567ba01da6638a0711e2a55725d084d65de44dd11bb1f52e2"
SRC_URI[deb0.sha512sum] = "790fa6d97024a1bcce2e7cf941de791c52845d731c56241e384701bb24e2e02b4c06d97e594fa05d61b83341db520f52af1c408b0e13163f541ee07457222c47"
SRC_URI[deb1.md5sum] = "6c1f586c305bd298cb80d37177570a3e"
SRC_URI[deb1.sha1sum] = "b6fc2eed791c948b334e765a9fcad32e7a116c62"
SRC_URI[deb1.sha256sum] = "5e129095192ff766884e5ed13260644e510d20ed6b4facc47809bf2cb630117d"
SRC_URI[deb1.sha512sum] = "3b813cbdf953c55f6f7e8f041b9119a76ab68a39d9166bfe9c1c4013c9f5c3e3bb735844b854b8df702c0bf02abc46efc6fe105bf67a91cade67a8ae32f90c02"

RDEPENDS = " \
    libc6 \
"

