# This was autogenerated! Do not modify
SUMMARY = "Perl module for error/exception handling in an OO-ish way"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "liberror-perl"
HOMEPAGE = "https://metacpan.org/release/Error"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libe/liberror-perl/liberror-perl_0.17030-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e599394d36d69ce1ec7717eb9d32a1a3"
SRC_URI[deb0.sha1sum] = "9f646aad98eb57c1cc329dec6813b96e53287c2d"
SRC_URI[deb0.sha256sum] = "06110a972bdc52f6c6d6615dddbe97f836c61d0e36c685ef4107c2eaa81f871f"
SRC_URI[deb0.sha512sum] = "1e944282bc82bee1efc4489d7035aa8eba065db8980f15e61fabc37d4d28acdb74a58d8c29d3448065aeb0091fe697933f3f516a16aedf0d91d9f27bb72021fb"

RDEPENDS = " \
    perl \
"

