# This was autogenerated! Do not modify
SUMMARY = "Python3 bindings for the Cairo vector graphics library"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "pycairo"
HOMEPAGE = "https://cairographics.org/pycairo/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/pycairo/python3-cairo_1.27.0-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/pycairo/python3-cairo_1.27.0-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8e33a24e785af668f94c85efc1b1f5df"
SRC_URI[deb0.sha1sum] = "adc2e2b9499901c53e921779f43ccb3f0a892589"
SRC_URI[deb0.sha256sum] = "d6e5d25b82d2cd0de18cfe8ee0bc4d3f9d0e33ee27ec1d4347e391fc3e3bf996"
SRC_URI[deb0.sha512sum] = "58f83d793331640906988ad3eb10fd0c8d4b645648934f4a96d9ed034cf30121838f8506a8c2f6d7ed34809853464f39aa2e90180db950b82e5c215e6d171fee"
SRC_URI[deb1.md5sum] = "79f9353bb02365633a4d7c2d91535400"
SRC_URI[deb1.sha1sum] = "3b6258ba50f6d0a7465c739fd62c326146f53c88"
SRC_URI[deb1.sha256sum] = "bbcec3d07448914ea81df1d2c74b25a54e3707f0452a3326f93a47a0ed7e05a5"
SRC_URI[deb1.sha512sum] = "5d7d7b5d0196e157250eb3e615fa1d61b813e462409f4b5c0690282d9e1db2dbce132a721c251a0b25ee98f9d00c799eb5d95d61243727ec1c9fd7ce8412ee39"

RDEPENDS = " \
    libc6 \
    libcairo2 \
    python3 \
"

