# This was autogenerated! Do not modify
SUMMARY = "open an HTML file with automatic charset detection"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libio-html-perl"
HOMEPAGE = "https://metacpan.org/release/IO-HTML"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libi/libio-html-perl/libio-html-perl_1.004-3_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "1d06eb95ac10f5b5cac4b2a228247243"
SRC_URI[deb0.sha1sum] = "548991cb0fdffc7be38693f9a164113d0f3dde07"
SRC_URI[deb0.sha256sum] = "66c87e3e92460b9dcf56257fd6a48cc7fd1283790acb365a111ecb9d74e9ea43"
SRC_URI[deb0.sha512sum] = "7f4c9b874dce3283a856cce68c1a810609dc6b785f2de9b79a4ba1c023a59aeffb0148e9f1621229fe3404604d5f3299b911dec94b73d9acb10cb6ad5694f312"

RDEPENDS = " \
    perl \
"

