# This was autogenerated! Do not modify
SUMMARY = "free implementation of the OpenGL API -- DRI modules"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "mesa"
HOMEPAGE = "https://mesa3d.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/mesa/libgl1-mesa-dri_25.0.7-2+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/mesa/libgl1-mesa-dri_25.0.7-2+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "6d88ad70feebab7182f9202b5d1f50f0"
SRC_URI[deb0.sha1sum] = "6c0f6692cacadf0fa97d0ac1f1aadf113ee17bfd"
SRC_URI[deb0.sha256sum] = "722fad9944bdfd29eb6421576331a2697f83bc4b3551d693edb7aefdde6bb198"
SRC_URI[deb0.sha512sum] = "b43907d05ce987c60c21ee400a005c8480a6388b33e7b85484ac8dbfa0f89df2de532ea5bb5fda125b81b3449cf7af4a86987fe4d868c7f9fe21972b2200549b"
SRC_URI[deb1.md5sum] = "a7a5465ab86922af548c462e86e3b298"
SRC_URI[deb1.sha1sum] = "358b80022483e1128bdba11d14911654584cb1a3"
SRC_URI[deb1.sha256sum] = "628245ff9d8e4f11edb66c0854915018402853e0eb588343d472111f6c4fb582"
SRC_URI[deb1.sha512sum] = "ef5463e41107aebdab702acab2cf35ecde56adda4d11f8b44073bee9f971af14d387158cd953f69de07ae99e8b6ee8fcc5f17a668a600542bc08552be29e802f"

RDEPENDS = " \
    libc6 \
    libgbm1 \
    libvulkan1 \
"

