# This was autogenerated! Do not modify
SUMMARY = "Linux kernel debugging symbols for 6.12.94-cip26-ebclfsa"
DESCRIPTION = "This package will come in handy if you need to debug the kernel. It provides \
all the necessary debug symbols for the kernel and its modules."
SECTION = "debug"
SOURCE_PACKAGE = "linux-cip"
HOMEPAGE = "http://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC}/pool/main/l/linux-cip/linux-image-cip-dbg_6.12.94-cip26-ebclfsa1+r0_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "cc80b8ab2d2c451069aa02fd8195a33e"
SRC_URI[deb0.sha1sum] = "94ba05246a1c3af9cb459bdd53ba7db8f727001e"
SRC_URI[deb0.sha256sum] = "3e62f0cac5db88d750f6de80a57fe22c71e68c968a57c40b2a7854eb319a7cbb"


