# Copyright 2026 Elektrobit. All rights reserved.

require conf/distro/debian-trixie.conf

# Unset all DISTRO_SOURCES variants and overrides to avoid any external
# repositories being used in the build and image creation process.
unset DISTRO_APT_SOURCES
unset HOST_DISTRO_APT_SOURCES

ISAR_USE_ISAR_APT_TO_BOOTSTRAP = "1"

# Remove any base packages
IMAGE_PREINSTALL = ""

EBCL_PLATFORM ??= "unsupported"

KERNEL_IMAGE_PKG ??= "linux-image-generic"

# The following configuration options are for two-VM setups

# Name of the device to use for the LI rootfs
EBCLFSA_LIVM_DEV ??= "vda2"
# Name of the device to use for the HI rootfs with vio-filed
EBCLFSA_LIVM_HI_ROOT_DEV ??= "vda5"
# Name of the device to use for the HI persistent data with vio-filed
EBCLFSA_LIVM_HI_DATA_DEV ??= "vda6"

# Default kernel modules to load in the initrd for use with the Debian Trixie kernel.
# Only applies to the LIVM initrd in the default configuration in two-VM setups.
KERNEL_MODULES ?= " \
    bridge \
    failover \
    llc \
    net_failover \
    stp \
    virtio_blk \
    virtio_net \
"

# Use a class-specific variable for setting the kernel package to allow it to be
# overriden for each class in a machine configuration.
EBCLFSA_LIVM_KERNEL_PKG ?= "linux-image-cip-livm-kernel"
EBCLFSA_HIVM_KERNEL_PKG ?= "linux-image-lisa-frink"
EBCLFSA_FASTDEV_KERNEL_PKG ?= "linux-image-cip"

# Distro features which can control which additional packages and features are
# installed and enabled in the images.
EBCLFSA_DISTRO_FEATURES ??= "profiling"
