# This was autogenerated! Do not modify
SUMMARY = "Fast LZ compression algorithm library - runtime"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "lz4"
HOMEPAGE = "https://github.com/lz4/lz4"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lz4/liblz4-1_1.10.0-4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lz4/liblz4-1_1.10.0-4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "51b7605581fe76fa57b450f5890aca91"
SRC_URI[deb0.sha1sum] = "366df9ca4cd9a1009c147a612e6526be145a4732"
SRC_URI[deb0.sha256sum] = "c31ec4c7c82755a38b2f3fe066fc0c5518cc91a601a268fbcd19bdacb1f22e1e"
SRC_URI[deb0.sha512sum] = "e86c27b17c601ef22a5809a649e783d533d15537c6d9391444564b1176f6474f3616e88635eb39534a25c50b3f818ddb9dac773c618ee33b6bac25e9cd8a4579"
SRC_URI[deb1.md5sum] = "1dfdb4f42dba7cf8cbac006f382e51bb"
SRC_URI[deb1.sha1sum] = "17a2d97282dee1826d56496d8772a447f71f95cb"
SRC_URI[deb1.sha256sum] = "f86fa7f8112d56b74f99c4a8baade57a9962d187d7c8e319428e171b2a34d223"
SRC_URI[deb1.sha512sum] = "e8fa61e69bdb5c4b3648ce0774aca88365ae84d5b304e868e3b83ed10f9fb91954d1e5b2d1f5adfacf1c8bea38a112a25be87563a6dcfdeba1482414b912f01f"

RDEPENDS = " \
    libc6 \
    libxxhash0 \
"

