# This was autogenerated! Do not modify
SUMMARY = "Free Remote Desktop Protocol library (core library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "freerdp3"
HOMEPAGE = "https://www.freerdp.com/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/freerdp3/libfreerdp3-3_3.15.0+dfsg-2.1+deb13u3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/freerdp3/libfreerdp3-3_3.15.0+dfsg-2.1+deb13u3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "111b9c79a68336a856be1d73456298a7"
SRC_URI[deb0.sha1sum] = "ffbaece17fda1e044d263a2aa5f5fe5693981964"
SRC_URI[deb0.sha256sum] = "ef5bb23c1ee7d7c62e52c5adef9429f23205bc0defef65a0730c17c570841d6a"
SRC_URI[deb0.sha512sum] = "8ff1d1220de53ef54631ee96b1a203bf6b1b44b20835af8e19b6131505a51e885ec738863259fd548b06954d152f116c0410bf8241159283bbee361bfe9f4053"
SRC_URI[deb1.md5sum] = "d31a5d37a57e48c323bda7898683a18b"
SRC_URI[deb1.sha1sum] = "ba60c2c159b390a8b8306be53d7741d6ebcf23e2"
SRC_URI[deb1.sha256sum] = "9d7d3c47b0e3b781e2e1c743fdb7786746fa8604b092190fb6a8c3e3f5889028"
SRC_URI[deb1.sha512sum] = "ac7fb100638ef960f5f43b682f752db4c25f106e350f0ff8ccf04224a39dc415d54a7438f3b81303b56f786713b65fe38f0e4a00796d8f0f31ad83ca355493b1"

RDEPENDS = " \
    libavcodec61 \
    libavutil59 \
    libc6 \
    libssl3t64 \
    libswresample5 \
    libswscale8 \
    libwinpr3-3 \
    libwinpr3-partial-api-3-17 \
    libx11-6 \
    libxkbfile1 \
    zlib1g \
"

RPROVIDES = " \
    libfreerdp3-partial-api-3-21 \
"
