# This was autogenerated! Do not modify
SUMMARY = "pixel-manipulation library for X and cairo"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "pixman"
HOMEPAGE = "http://pixman.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/pixman/libpixman-1-0_0.44.0-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/pixman/libpixman-1-0_0.44.0-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "7e728eb855d27c47d9b26600f8d9fc7c"
SRC_URI[deb0.sha1sum] = "d7440d194dd1142be8833d6167253ed019abd015"
SRC_URI[deb0.sha256sum] = "3862c87596f6b4b60fc916395fd69aa10af28a875a8e5c081a8cf30ddd120bd6"
SRC_URI[deb0.sha512sum] = "95daec7e6d429d7960b6a345401e675ac34e490abadb2016b409cfb8a4e2438c586fcc93c6c1b1b36b0f7ac18a69097eeaec2654f5fa70b0b2532d0278130bab"
SRC_URI[deb1.md5sum] = "7694a06b92c4735c0a1b49c07978cafa"
SRC_URI[deb1.sha1sum] = "27ea3a1ea6b1e8a07714747bb0a984f1bf72e478"
SRC_URI[deb1.sha256sum] = "b502cd8b1ece222f42b44c42c33a300d84152c20089660167b9422ad2ebb6132"
SRC_URI[deb1.sha512sum] = "0c4373d3998efe9bba360f2d833c61f2583b5d7727c0246b3fb610d221e72e5f81909adb48beaf2b51ef9e16c96463d25c3452b1337aeec449d99dd594597023"

RDEPENDS = " \
    libc6 \
"

