# This was autogenerated! Do not modify
SUMMARY = "message digest functions from BSD systems - shared library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libmd"
HOMEPAGE = "https://www.hadrons.org/software/libmd/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libm/libmd/libmd0_1.1.0-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libm/libmd/libmd0_1.1.0-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b19d4b4209fcbc0a387d8563f7b50e27"
SRC_URI[deb0.sha1sum] = "b74e47ea74c82c695f1d18c5473851e1882392ce"
SRC_URI[deb0.sha256sum] = "7244ec3839b61fac0c1884fe08aaa040f26e8f1f35f1f5d3482eacefd30d1b44"
SRC_URI[deb0.sha512sum] = "1bca99d6e63a750da1a61d98de3b90273541c3509744985cc45a7ceb6040df87795bca01ac07bf5266bba2ccca9bb9f1d86ef355a0c11ea4a6898565d69919f1"
SRC_URI[deb1.md5sum] = "dff2532846e38b6debcf9b0d6927c826"
SRC_URI[deb1.sha1sum] = "8116ea5ad4527d00e5555b62a35aae2869ebd51c"
SRC_URI[deb1.sha256sum] = "772e86842fd3fa1816a0cfee4833a73996aaa550461491543b886b9c8f999052"
SRC_URI[deb1.sha512sum] = "e2d69fa6752d4511ff409438f73c72cd3a79620273a69bf8155d92673f82c626d949a33348f0799b9a9d7046ced6371ccbc271dc15435fb8c7f904102f0b0573"

RDEPENDS = " \
    libc6 \
"

