# This was autogenerated! Do not modify
SUMMARY = "Linux kernel debugging symbols for 5.15.193"
DESCRIPTION = "This package will come in handy if you need to debug the kernel. It provides \
all the necessary debug symbols for the kernel and its modules."
SECTION = "debug"
SOURCE_PACKAGE = "linux-lisa-frink"
HOMEPAGE = "http://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC_BINARY}/pool/main/l/linux-lisa-frink/linux-image-lisa-frink-dbg_5.15.193-499b5599+r0_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a670baca36eea69acb23a6a79118f54b"
SRC_URI[deb0.sha1sum] = "a854fda647c4c7d17affdc99962e73dda7a57552"
SRC_URI[deb0.sha256sum] = "e110aac1f3fe40d1eb1e5c81f8e0a214913dac847805cb169a9dcd7f9bed33f4"


