# This was autogenerated! Do not modify
SUMMARY = "Utilities for sensible alternative selection"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "sensible-utils"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sensible-utils/sensible-utils_0.0.25_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "1bc74983fca8bf2f6df6f871bca29d13"
SRC_URI[deb0.sha1sum] = "5eb1f900f46b7787fee2082e3bcb32ed09ccaba6"
SRC_URI[deb0.sha256sum] = "873a9b73c3478cc3148cdbf5cc2084949a0a8e4fa16131d1cbc895d2f1f3470e"
SRC_URI[deb0.sha512sum] = "fbfbf1bd021ba485dfadb11f1c7289be77cb001e3956120cbbeb5d89ee78f0e5720c7c8f1d6d604ea0363b2f1857cefd505684a513f86069bf2e88a3855c1b20"


