# This was autogenerated! Do not modify
SUMMARY = "SGML infrastructure and SGML catalog file support"
DESCRIPTION = ""
SECTION = "text"
SOURCE_PACKAGE = "sgml-base"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sgml-base/sgml-base_1.31+nmu1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "43ae9a3314ef701a7a983512435ea60c"
SRC_URI[deb0.sha1sum] = "1913c061c4bda862c5798c6290b2064939061b29"
SRC_URI[deb0.sha256sum] = "a355b832d9f0f4dc9eca1a661080db5dc118e6c435f107a5c4dd201d7af59ba8"
SRC_URI[deb0.sha512sum] = "065ea11c8c4555dc684af78205ac7c69ad9c17f64b6996ef07e3fd6ab8d5a59a46f47332b8ab02eac3e7b1201e3e7c8ba5d9b49a7e569ea004d3be4201b4706e"


