# This was autogenerated! Do not modify
SUMMARY = "XZ-format compression utilities"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "xz-utils"
HOMEPAGE = "https://tukaani.org/xz/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/x/xz-utils/xz-utils_5.8.1-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/x/xz-utils/xz-utils_5.8.1-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "f1d86e1ebee20b0616f055aed01a9ebc"
SRC_URI[deb0.sha1sum] = "4979f0e9421eff39878d78d09c701f082e3a4685"
SRC_URI[deb0.sha256sum] = "9e0a39d95373afdaad3c9dfaab3c8b0beb9a2c4654e6be10b4bcf458509a3217"
SRC_URI[deb0.sha512sum] = "bd39d3a2aff04c820d0a3a6dcbbad83b03c0bdd47ea8dc38816992caa184627f2033def49c316c1f2bb84edea39734bf568e686e96d2bccd409cd63e52af6805"
SRC_URI[deb1.md5sum] = "95ea7560fbeda3859daf75eb6a10526d"
SRC_URI[deb1.sha1sum] = "4b8104754f6cf5a526a276994683f56202b6fdea"
SRC_URI[deb1.sha256sum] = "07b6145c6c934d744c712c252b293ce506d427ea127c7f77b711c518aead54b3"
SRC_URI[deb1.sha512sum] = "7a30f7656ba58a91177dfbcd16d1e1a44dc05bb831c6562a65ab7d36ee2f19144bf4bf28a3e925e1f8d877db01e0d3f70eedf8438f6f5f49ee45db9404e45d5e"

RDEPENDS = " \
    libc6 \
    liblzma5 \
"

RPROVIDES = " \
    lzma \
"
