# This was autogenerated! Do not modify
SUMMARY = "Update Configuration File(s): preserve user changes to config files"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "ucf"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/ucf/ucf_3.0052_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "8d0a4645c9d089fbe2cb5fd9c6d8e14c"
SRC_URI[deb0.sha1sum] = "3655146d2b430eabab297c7149114650353d2a54"
SRC_URI[deb0.sha256sum] = "ab5a6d5a621ad07034ce29d0c2587e6e267ecd2975458b2c8a7d0ada77dcb95b"
SRC_URI[deb0.sha512sum] = "c180172ed4c03bd65a0e0e81ac2a9273f02f0a304dc182655dde9285e92fceb36929f9273e02ee7c003d2918486f225a8ce329112545f46a2f7c73ad70513c08"

RDEPENDS = " \
    debconf \
    libtext-wrapi18n-perl \
    procps \
    sensible-utils \
"

