# This was autogenerated! Do not modify
SUMMARY = "Foreign Function Interface library (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "libffi"
HOMEPAGE = "https://sourceware.org/libffi/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libf/libffi/libffi-dev_3.4.8-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libf/libffi/libffi-dev_3.4.8-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "abd1dc842f9eb03483905e458d481f12"
SRC_URI[deb0.sha1sum] = "8f438f832d31cd74325bf32f8fa00b64e06322ce"
SRC_URI[deb0.sha256sum] = "76b2b80193a656733e1408ebec5371334be5fd48eb5f50ab99d6baf6081d0f1b"
SRC_URI[deb0.sha512sum] = "0e10272b921db31cc9344f1c89b5762d91c2279fdee1258e90c7e5bf9a8325c743b9ab597b881955b372a046d893823a3c4eae4ca8d7fc18275b40f77803bc03"
SRC_URI[deb1.md5sum] = "9faf84424702b5423729deef141d1cb5"
SRC_URI[deb1.sha1sum] = "29050f133f12cd42e68264240cb4c4215c948ec5"
SRC_URI[deb1.sha256sum] = "55f6d389cc954407cdba6e4ba5e7039dd2042d2ca8929d6f5eb49d6b97ba92de"
SRC_URI[deb1.sha512sum] = "2a41ccb860bd8fbbd08cf704033cf1b2cacfb3d729b337dcabfc61a90890a92ef17d16274a29a0ac963f27db88eb1bf4103803e5d0805cd2a7c3922fb627b496"

RDEPENDS = " \
    libffi8 \
"

