# This was autogenerated! Do not modify
SUMMARY = "Cyrus SASL - pluggable authentication modules (DB)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "cyrus-sasl2"
HOMEPAGE = "https://www.cyrusimap.org/sasl/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cyrus-sasl2/libsasl2-modules-db_2.1.28+dfsg1-9_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cyrus-sasl2/libsasl2-modules-db_2.1.28+dfsg1-9_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "697b55318a5683646f3f4c637576f3f3"
SRC_URI[deb0.sha1sum] = "8c66ab6412351683261d50959984811c0480087b"
SRC_URI[deb0.sha256sum] = "a5c38659fbd62c33c6d9bfa2be43e75a572d1818531aad32dd74d0a58cc4bd19"
SRC_URI[deb0.sha512sum] = "b1df5c98383444950246a66876eb43d3ea41d504fd42d325393da19e6ebd639e06bf7539c0ad7946decfc891dd75452a10ac5b08ce4469f63217143d83030022"
SRC_URI[deb1.md5sum] = "e6efb0e483f0783e75a13f3a0a85b370"
SRC_URI[deb1.sha1sum] = "eba6d1c1b8d1d526a51a8bc40b09337f3f4db988"
SRC_URI[deb1.sha256sum] = "ed6eb05f8ded71ab16a0369845805b373fc8a71c0e7d33f73fa2fb11e83a1977"
SRC_URI[deb1.sha512sum] = "4b39d728094256d270c5124911459ebaccda2d2ad70984d6e7ceda1a18ce6b8491097687a1928648b0d4e727b4194610fa88958caa598f5e23958b55b57690a8"

RDEPENDS = " \
    libc6 \
    libdb5.3t64 \
"

