# This was autogenerated! Do not modify
SUMMARY = "utility to find python versions on your system"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "findpython"
HOMEPAGE = "https://github.com/frostming/findpython"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/findpython/python3-findpython_0.6.2-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a58d0d5bd2796ec13fbba9f99c0d11d6"
SRC_URI[deb0.sha1sum] = "fa8063826ab2d1076b2f9b1c340fc16b0c44411a"
SRC_URI[deb0.sha256sum] = "03a75523a1113e9a6ad139395c5604d264b5ab8e6734ca16e8363e7e354d1071"
SRC_URI[deb0.sha512sum] = "d24f255bb8c7b5eac960a8b15dfddde791512a9e618b893303f21eaefbede028dbdce636c6de1a36ae515293b483abd688d902ef07e870c0d3401d4d9d6d6073"

RDEPENDS = " \
    python3 \
    python3-packaging \
"

