# This was autogenerated! Do not modify
SUMMARY = "tools for reading manual pages"
DESCRIPTION = ""
SECTION = "doc"
SOURCE_PACKAGE = "man-db"
HOMEPAGE = "https://man-db.gitlab.io/man-db/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/man-db/man-db_2.13.1-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/man-db/man-db_2.13.1-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "6615aca5c1b21030e543b03143bc02a3"
SRC_URI[deb0.sha1sum] = "01b888083208011eba6ff90581cef9e8dbc8e722"
SRC_URI[deb0.sha256sum] = "d5a407221a0d59845484b5343a37ec6374102e949353e4b158eaa2cbaf27aa5a"
SRC_URI[deb0.sha512sum] = "5a26b867356edb533ecce3dcf9931c5aa87d265d269461bde36204ced14ea535c8e182c8dd4fc62fd590bf5d5da896ec439621ad1c28dd30d74774f674a56bfc"
SRC_URI[deb1.md5sum] = "3c4a857b037574a544f59f1b5f5f69bf"
SRC_URI[deb1.sha1sum] = "872c4b61e85af929c896c55d71083b98b06d923d"
SRC_URI[deb1.sha256sum] = "edf05f2008bd010d576b473db058892f027ef1d097b7d9bc26fe00534d154ef3"
SRC_URI[deb1.sha512sum] = "dd6b28ffbc9d3d0501a5a7cc7e9d0fb409e3af8248223a4286cdc4c7a10f67e514f79230b28dec318b664d07596b5e989f75955bd833128994630016a5d64d48"

RDEPENDS = " \
    bsdextrautils \
    debconf \
    groff-base \
    libc6 \
    libgdbm6t64 \
    libpipeline1 \
    libseccomp2 \
    zlib1g \
"

RPROVIDES = " \
    man \
    man-browser \
"
