# Copyright 2025 Elektrobit Automotive GmbH
# All rights reserved

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend ${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "meta-appdev"
BBFILE_PATTERN_meta-appdev = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-appdev = "6"

LAYERDEPENDS_meta-appdev = "core"
LAYERSERIES_COMPAT_meta-appdev = "v0.6"
