# This was autogenerated! Do not modify
SUMMARY = "Linux Key Management Utilities (library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "keyutils"
HOMEPAGE = "https://git.kernel.org/pub/scm/linux/kernel/git/dhowells/keyutils.git"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/keyutils/libkeyutils1_1.6.3-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/keyutils/libkeyutils1_1.6.3-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d94a241f2f7ab7edf5b6fb049fde8380"
SRC_URI[deb0.sha1sum] = "510fbc305d8dc86f0279c13f77fa06c4c1a6c75f"
SRC_URI[deb0.sha256sum] = "0b11ad17be0300b63ad4eeb4c6450fed24d34b7b740f23e5363dcb29ee6d5eba"
SRC_URI[deb0.sha512sum] = "1bfaf38274414e206f2a373c3d4401c7a230af394ef45286de19c0066a590366bf2444fda9840a7c16ecfaaa1f1f5be0ffdc196c26a3f950f89fa636e8c62154"
SRC_URI[deb1.md5sum] = "99c1055d83f9c4aeb81adf8007bcdf04"
SRC_URI[deb1.sha1sum] = "bcb2ef3b92a9a8dd5652b73efa8b1beeb5e07d0a"
SRC_URI[deb1.sha256sum] = "5e680f317a6613161986417fb3ed63007c9228343f5ac2348551b103cc7fd7b4"
SRC_URI[deb1.sha512sum] = "45c964314f58c01b629c556b8ddc3feba911f7beec07f7f21f585d1853b649faff5ac9e44d8ee6e6433ad5334a17bf1cd9766347851936373fae5a5fb6b061ed"

RDEPENDS = " \
    libc6 \
"

