# This was autogenerated! Do not modify
SUMMARY = "QEMU user mode binfmt registration for qemu-user"
DESCRIPTION = ""
SECTION = "otherosfs"
SOURCE_PACKAGE = "qemu"
HOMEPAGE = "http://www.qemu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qemu/qemu-user-binfmt_10.0.2+ds-2+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qemu/qemu-user-binfmt_10.0.2+ds-2+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "62f5615be5c3f8feb690e15b4bd32aa4"
SRC_URI[deb0.sha1sum] = "9198cda8dcfb46028c6397b3ac9a5fda3d34d43e"
SRC_URI[deb0.sha256sum] = "3d03c957889dace6adfbab57ef5345750732a6f9f365fb468b0c1b5fc2724abe"
SRC_URI[deb0.sha512sum] = "1eb432261a1bd0c46747b4bbcf5798beff35c8c89a2eb602562e92d3490633e66a33fd8217a336ff4561eee7b9f49a170f55c4cdd474620fa58e2f05692e3900"
SRC_URI[deb1.md5sum] = "7ac1de4248ab8d44dc74288685ac37f8"
SRC_URI[deb1.sha1sum] = "70b11fd6e46e8fd41294c397e15df78468c9c72c"
SRC_URI[deb1.sha256sum] = "51514908711e46de3d5150bd4be2a2d2bd505ad2a4066d8a38961ca750ca952c"
SRC_URI[deb1.sha512sum] = "0812ab921ba0f1eb07c4851d044a9c62c28220e980b7220b1c163fdc2ffe5d1a936561380e20512791b6d6c82aed21cb68a0cf3d8bddb18fd0626153b052167a"

RDEPENDS = " \
    qemu-user \
"

