# This was autogenerated! Do not modify
SUMMARY = "QEMU user mode binfmt registration for qemu-user"
DESCRIPTION = ""
SECTION = "otherosfs"
SOURCE_PACKAGE = "qemu"
HOMEPAGE = "http://www.qemu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qemu/qemu-user-binfmt_10.0.11+ds-0+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qemu/qemu-user-binfmt_10.0.11+ds-0+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d5cc706e23de8663d59eeaa4e129757f"
SRC_URI[deb0.sha1sum] = "28b7014d32566ccc276f93ece2908dcd5c0a6e2a"
SRC_URI[deb0.sha256sum] = "ed5178fc4435cc38dbe01c39e23a5a361c984415aec79a137d34324680044ed7"
SRC_URI[deb0.sha512sum] = "3ee67db95e02cd5cfc63d0abe4a930f37fa5b00c083e671ee9263c276591745ba2d9bd7c19a56d8621342f051abdf38a7bb64bbed7cc1909377df10bbbbd6edd"
SRC_URI[deb1.md5sum] = "fa9ee567abf23e2ab07800ff014123a8"
SRC_URI[deb1.sha1sum] = "ae088e33f33af2607441004e1cd33d03dcfdf73d"
SRC_URI[deb1.sha256sum] = "42870ea1469d2ae5b7b8440c27066a3a9a7baf3a11c2909a2177956ef3b0e4f1"
SRC_URI[deb1.sha512sum] = "4d5853b5cece2cd03e43b3bbb882fc5c73907472e932f132d09abdb4b4f6ab68d03b992d52e0289c1a4bec6d8d714c92d0653263bbc8c80e1ef24d95af4efe1e"

RDEPENDS = " \
    qemu-user \
"

