# This was autogenerated! Do not modify
SUMMARY = "MIT Kerberos runtime libraries - GSS enabled ONCRPC"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "krb5"
HOMEPAGE = "https://web.mit.edu/kerberos/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/krb5/libgssrpc4t64_1.21.3-5+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/krb5/libgssrpc4t64_1.21.3-5+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "ff9f1d93cd79961eabcb1c4334177412"
SRC_URI[deb0.sha1sum] = "3e0610e3b6f6d57539344d7a1f95da1ed442fd48"
SRC_URI[deb0.sha256sum] = "ff88e52a6b6599851f3d44f7223f15123d9e5a0b02ed9a308c05c31fa88f7d73"
SRC_URI[deb0.sha512sum] = "4296255178eee4aa00b53ba67eda80ce8bd953240a3156e1cbedbe62160151eec22e55a98573800cb4a3eb15968cfc5c2506acd8c526b2d2142e91acb933bafd"
SRC_URI[deb1.md5sum] = "acc9dc8bd8a40e4bca2cb13fbed3c26b"
SRC_URI[deb1.sha1sum] = "a96d6c076a0fad79f0ce2a4bb92ace20eca7b469"
SRC_URI[deb1.sha256sum] = "a25bfe3625a9f238d86945d12eca58c6e5201ff7cde596aac700dd12ac208bec"
SRC_URI[deb1.sha512sum] = "abdd8ab78c5710ae67431875b88962dcdfbae2f1ef677540f5ebc3053c093a03cbb1636c0a9cde6c14c93f842170e3ec7c6d846d51ebd4d31e493446ff6e2c0d"

RDEPENDS = " \
    libc6 \
    libgssapi-krb5-2 \
"

RPROVIDES = " \
    libgssrpc4 \
"
