# This was autogenerated! Do not modify
SUMMARY = "MIT Kerberos runtime libraries - Crypto Library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "krb5"
HOMEPAGE = "https://web.mit.edu/kerberos/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/krb5/libk5crypto3_1.21.3-5+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/krb5/libk5crypto3_1.21.3-5+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "96cdff8aed6de85e2ac31dc1513207ba"
SRC_URI[deb0.sha1sum] = "59b80ae0af88c085973d19dd8e321815455e70e6"
SRC_URI[deb0.sha256sum] = "7da07ee674b47f1f0be7cc89317c25310086a1f1761217d0f72e6ae2c5a69b84"
SRC_URI[deb0.sha512sum] = "0ef735985c6955a67becb785f8cf4e89acc6128910a9e92764c9ec89e2425eb1a68195e96572d948b12a16d0fe8cbe7be48b053829033e95b148deba18c8729e"
SRC_URI[deb1.md5sum] = "c8bf0efa3716f167a27d7abebf37ed1e"
SRC_URI[deb1.sha1sum] = "d747ad6e5b95660c1ca90228b55886aa814a51db"
SRC_URI[deb1.sha256sum] = "2453e8d4fa3b91b868d5bc10e84a15ad9c7bc4e4cb49379cb1f560bdce50db4a"
SRC_URI[deb1.sha512sum] = "22d1c5b1d2809fccfcfbf3152321ab4e68dd088ab190f09feb978e055cc74c008c36182d7953ebf21a9ee3345dc485b8dbdd128c196e83acb14a723cbf1d962e"

RDEPENDS = " \
    libc6 \
    libkrb5support0 \
"

