# This was autogenerated! Do not modify
SUMMARY = "small library implementing a boolean algebra"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-boolean.py"
HOMEPAGE = "https://github.com/bastikr/boolean.py"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-boolean.py/python3-boolean_4.0-4_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "9fae1a7d135559c25ee839bddea41391"
SRC_URI[deb0.sha1sum] = "2ab4a8c881585ab9ab9ccf5b8abcae2ebd9b46ff"
SRC_URI[deb0.sha256sum] = "92a614a3e26aa2927e1b71e2778ba6a34df02395bc076af92105c6618e6282b3"
SRC_URI[deb0.sha512sum] = "ebfeb4e07d1965b0babad445bd23ded789eba1b59c194683396f41af787f48824908f2c33bd4a0d51a97194a2271625fe39bd3efb27356431e4bb009a58063e5"

RDEPENDS = " \
    python3 \
"

