# This was autogenerated! Do not modify
SUMMARY = "Debian Configuration Management System (C-implementation library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "cdebconf"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cdebconf/libdebconfclient0_0.280_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cdebconf/libdebconfclient0_0.280_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "0eec698fd18895d578b63d64216aeb3e"
SRC_URI[deb0.sha1sum] = "219dec5cd95ea5be91161ab1d30dc3f19efb6e01"
SRC_URI[deb0.sha256sum] = "25acadc8b394bc86d05df16e70975e523f8f839a7d8d6d5e22c1cafdcef741aa"
SRC_URI[deb0.sha512sum] = "edd7c34017817a081817a9ef08399ff1da21602b565ed9bc957d6def20eafe8b0406082cc18d78cb94909e96385d11a478c8b97fd5cacce27b9bfc412963df17"
SRC_URI[deb1.md5sum] = "c650e0f0d50d2cf4dc6e70212efa1cc1"
SRC_URI[deb1.sha1sum] = "755770723753e267a6bd5a58ad81a3848256ce9e"
SRC_URI[deb1.sha256sum] = "8c2976dc62d0f5133018ea62636105335f9b17da77adce7fed1ffb24e2533dba"
SRC_URI[deb1.sha512sum] = "06cbfbf26a987b64ce0fd1f139faf2beae3e6f25d5097d80f091d7360e8bec4a01746eb5e55494f7f23e670826cf5af912b367dffdd71fd465b519cb640b5d31"

RDEPENDS = " \
    libc6 \
"

