# Copyright 2026 Elektrobit. All rights reserved.

# Rebuild a package from its Debian source package (.dsc + .tar.gz).
#
# Usage in a recipe:
#   inherit dsc-rebuild
#   require recipes-<section>/<package>/<package>_<version>.src.inc
#   S = "${WORKDIR}/<unpacked-source-directory>"
#
# Optionally add patches via SRC_URI:
#   SRC_URI += "file://my-change.patch"

inherit dpkg

# dpkg-source -x sets .pc/.quilt_patches=debian/patches, but BitBake puts
# patches in patches/, so quilt push silently does nothing.  Use patch(1)
# for quilt-format packages.
PATCHTOOL = "${@'patch' if d.getVar('DEBIAN_SOURCE_FORMAT') == '3.0 (quilt)' else 'quilt'}"

# The .src.inc uses the autogenerated name; the actual recipe is "debhelper"
DEPENDS:remove = "debhelper-compat"
DEPENDS:append = " debhelper"

# Let dpkg-source -b auto-commit uncommitted changes into debian/patches/
DPKG_SOURCE_EXTRA_ARGS:append = " --auto-commit"

# For 3.0 (quilt) packages, BitBake's default unpack extracts the orig and
# debian tarballs as siblings, leaving debian/ outside S.  Re-extract with
# dpkg-source -x so that debian/ is properly merged into the source tree
# and the upstream quilt patches are applied.
dsc_rebuild_quilt_reextract() {
    rm -rf "${S}" "${WORKDIR}/debian"

    dsc=$(find "${WORKDIR}" -maxdepth 1 -name "*.dsc" | head -1)
    if [ -z "${dsc}" ]; then
        bbfatal "No .dsc file found in ${WORKDIR}"
    fi

    # Link source archives from the download dir next to the .dsc
    sed -n '/^Checksums-Sha256:/,/^[^ ]/p' "${dsc}" | \
        awk '/^ /{print $NF}' | while read -r fname; do
        [ -e "${WORKDIR}/${fname}" ] && continue
        [ -e "${DL_DIR}/${fname}" ] && ln -s "${DL_DIR}/${fname}" "${WORKDIR}/${fname}"
    done

    dpkg-source --no-check -x "${dsc}" "${S}"

    # Save quilt state so it can be restored after BitBake's do_patch
    cp -a "${S}/.pc" "${WORKDIR}/.pc-debian"
}

python do_unpack:append() {
    fmt = d.getVar('DEBIAN_SOURCE_FORMAT') or ''
    if fmt == '3.0 (quilt)':
        bb.build.exec_func('dsc_rebuild_quilt_reextract', d)
}

# Replace BitBake's quilt state with the debian quilt state so dpkg-source -b
# knows which patches are already applied and only auto-commits our changes.
do_prepare_build:append() {
    rm -rf "${S}/patches" "${S}/.pc"
    if [ -d "${WORKDIR}/.pc-debian" ]; then
        cp -a "${WORKDIR}/.pc-debian" "${S}/.pc"
    fi
}
