# This was autogenerated! Do not modify
SUMMARY = "time zone and daylight-saving time data"
DESCRIPTION = ""
SECTION = "localization"
SOURCE_PACKAGE = "tzdata"
HOMEPAGE = "https://www.iana.org/time-zones"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tzdata/tzdata_2026b-0+deb13u1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "2508a8ecb1e7638d5723f3c1b2194243"
SRC_URI[deb0.sha1sum] = "47cec4da0609fa1ba1b38b6705c07b8578027cb6"
SRC_URI[deb0.sha256sum] = "306013b77311e875620e89f43c447765a6c72b7b398e0baa8e5721bcbbdf66cf"
SRC_URI[deb0.sha512sum] = "9ea0cf8634c79a4adf1b53364d73f64ab5a057856e97f56e57b91297975cdd61ce26eee05e87198d69ad41429819ab344f65f92d4216cd0c21e5806e1ef9abd1"

RDEPENDS = " \
    debconf \
"

RPROVIDES = " \
    tzdata-trixie \
"
