# This was autogenerated! Do not modify
SUMMARY = "NEWT module for Python3"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "newt"
HOMEPAGE = "https://pagure.io/newt"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/newt/python3-newt_0.52.25-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/newt/python3-newt_0.52.25-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8011fcb019b957dde88e704d29f8e8be"
SRC_URI[deb0.sha1sum] = "6fbe7ca6a1e91ef5f263f62c5580e569e5cc3933"
SRC_URI[deb0.sha256sum] = "94b2f216110fd62c369304e6e77ec786b0d89e4c2ecb5e968565c7cc93f04b08"
SRC_URI[deb0.sha512sum] = "4294e2f614a9a1c6207bc0365fa2a8167173aabb48a665e73dda7a627370149658e4fb8b1dbdf7ae42c7044bf36b0b36b010962cd1fdc3018f3f2b9ce833f0fb"
SRC_URI[deb1.md5sum] = "e26316d8dd5dc2bc60f35ece5d1f720e"
SRC_URI[deb1.sha1sum] = "c78d5ba47c9abc94726b2cd787ab86a5e717596f"
SRC_URI[deb1.sha256sum] = "6ec370fc72488813b836b3cd3d1a957a8a297fbf3439e33b42fa08ae30c9a292"
SRC_URI[deb1.sha512sum] = "6ce002d80731202aa6a6eb53c892eeaa41df54a40ed99d5b2b5e7ffe2254a1de7ac0e5796de6bb3439c3f37dd7e58433fca7ebad018d4a46517b692f7913c271"

RDEPENDS = " \
    libc6 \
    libnewt0.52 \
    python3 \
"

