# This was autogenerated! Do not modify
SUMMARY = "pure Python D-Bus interface"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "jeepney"
HOMEPAGE = "https://gitlab.com/takluyver/jeepney"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/j/jeepney/python3-jeepney_0.9.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "42f10a9f93ddc31c309feb3380d4c5b0"
SRC_URI[deb0.sha1sum] = "dfaca1cfd1cc0704cf4c6dd28bb76c9fed1b0e0e"
SRC_URI[deb0.sha256sum] = "d6ba39f138043cdb6600bff39e0cbaa0e7f9f47927d08e34cd42935221ef770c"
SRC_URI[deb0.sha512sum] = "d9ce1878efb3b8d31b1a38320e0b10db9bf0834b5a9ec73a9e421c97be3388298032666bc6a1e1d7fb47cd23e684f388a3149c1388196f1169cbe545bf8de555"

RDEPENDS = " \
    python3 \
"

