# This was autogenerated! Do not modify
SUMMARY = "theorem prover from Microsoft Research - development files"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "z3"
HOMEPAGE = "https://github.com/Z3Prover/z3"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/z/z3/libz3-dev_4.13.3-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/z/z3/libz3-dev_4.13.3-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "2a44f34c370b5e3d622b4a06d96d3fb2"
SRC_URI[deb0.sha1sum] = "3078f2493b7fb7e0242c7f608220db8e64482651"
SRC_URI[deb0.sha256sum] = "df63eae0c0b2a4d59577b2f36fe2521cb11aa2955e6fb242441603e5ae1cf757"
SRC_URI[deb0.sha512sum] = "c8db4af4354b4aee4252ba86c7bd547247d008228356ad5c759cc8a6f67eae3f690d6c7538db3823f0966cb005337301f73d687aa87bcc18cf86e385f2cbef6a"
SRC_URI[deb1.md5sum] = "b252dd38c2e8dcd9f1a5ab754d1ba021"
SRC_URI[deb1.sha1sum] = "acf11564200118350181ef63833a02541adf57af"
SRC_URI[deb1.sha256sum] = "e35389f0b02e020d6714c5ef349eef4a1f514d0293c05fd28bb90c1fe4f3f2b7"
SRC_URI[deb1.sha512sum] = "fa2c1fa0c98c159cf5ba2ff0070cf9d8325d624fb7120515ca364e96afb96770036cd9b65361de6ebee14282031be68cb3eb8459505229b8ccd9fb9ab5532d46"

RDEPENDS = " \
    libz3-4 \
"

