# This was autogenerated! Do not modify
SUMMARY = "GCC support library (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "gcc-14"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libgcc-14-dev_14.2.0-19_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libgcc-14-dev_14.2.0-19_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "39f291b5a853a4ef843359d007960016"
SRC_URI[deb0.sha1sum] = "9581fae9cbf1bb9b8e9c59405f71259c5bb8524f"
SRC_URI[deb0.sha256sum] = "ca6f2d36d96b19b3eb71405b0b80134d8c89380b02204a2512e5c58ceb090628"
SRC_URI[deb0.sha512sum] = "a4d75a46ebe3d767003a1dd43db7282a5ff8977ddd727329dc1633685a61d778548e95e095dc94aaac89cb2fa5c53baf092d5ec36989e6af96d1a6e4408d68c0"
SRC_URI[deb1.md5sum] = "987f4f6107a082bf9f860d485ff4e727"
SRC_URI[deb1.sha1sum] = "281cc6541ccd92caca0dfc9c5532620d3adf4af9"
SRC_URI[deb1.sha256sum] = "64b8ebc7182a69aa9525df6eab5e7eb849b947e350d821549f8a8a3e9b19e5ba"
SRC_URI[deb1.sha512sum] = "e7dd614f0ad220b300fd870875891b33ce5fd7f63490933e60964696e66ac325c4311d2ce2d1966910c46bd2b392749494e00e2a9e2bc5318c40e95b1792ab3c"

RDEPENDS = " \
    gcc-14-base \
    libasan8 \
    libatomic1 \
    libgcc-s1 \
    libgomp1 \
    libhwasan0 \
    libitm1 \
    liblsan0 \
    libtsan2 \
    libubsan1 \
"
RDEPENDS:append:amd64 = " \
    libquadmath0 \
"

