# This was autogenerated! Do not modify
SUMMARY = "Runtime library for GNU Objective-C applications (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "gcc-14"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libobjc-14-dev_14.2.0-19_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libobjc-14-dev_14.2.0-19_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "bb028c0bd4e50bb5b3d13b58425d07f7"
SRC_URI[deb0.sha1sum] = "85e077f0bcf3e59be037d918fac16e0b0347f36e"
SRC_URI[deb0.sha256sum] = "60f8a34f94d46b0ae8d48335525bfaae3daef93c56d6b8bce0e76118e44a9136"
SRC_URI[deb0.sha512sum] = "877d224087c0b67fe18885bc1772870f9392086e93fc55be97900fcc824d9581ce21adee6dbf56a11cf93c24eb15ee2b3a3ca6c9062f0cc147a426b3239cc9e0"
SRC_URI[deb1.md5sum] = "e79abfb6e454b32eb41e7b66dc411c38"
SRC_URI[deb1.sha1sum] = "44b7299299fae0756987fe08ae827a376858ef60"
SRC_URI[deb1.sha256sum] = "b248dc482ad75e0dbe64e70a468ce61b2c167fe63420185290dd441b28cd1357"
SRC_URI[deb1.sha512sum] = "57e7d10566c18e1ef5a2757c403ec83aebb3134bb76f06d74bc474b7e0b492297a1fc166673883cba6230fd0d525acb8c931ecbfbd3b37af4eb4d8a6a840cc0e"

RDEPENDS = " \
    gcc-14-base \
    libgcc-14-dev \
    libobjc4 \
"

