# This was autogenerated! Do not modify
SUMMARY = "Tiny scripting language with ECMA script syntax"
DESCRIPTION = "Ucode is a tiny script language featuring ECMA script syntax, builtin JSON \
support and templating using Jinja inspired markup. The ucode VM is provided \
as shared library with a C API allowing embedding into host applications and \
interchanging data between ucode and C programs. The ucode VM can also be \
used as stand-alone multi purpose scripting language through the provided \
ucode cli interpreter. \
 \
This package contains the ucode command line interpreter, which is required \
to develop, debug and precompile ucode scripts."
SECTION = "interpreters"
SOURCE_PACKAGE = "ucode"
HOMEPAGE = "https://github.com/jow-/ucode"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/u/ucode/ucode_0.0.20220322_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a9f19a80383a8e5ed8cda9d05406ca18"
SRC_URI[deb0.sha1sum] = "c5c497d038650685eceaebee065c7c1cb45df39c"
SRC_URI[deb0.sha256sum] = "735d6bf7d15381ee114667531a9d9bf3ffe0771b22cf954317f4eff290b0b650"

RDEPENDS = " \
    libc6 \
    libjson-c5 \
    libucode \
"

