# This was autogenerated! Do not modify
SUMMARY = "GNU C compiler for the aarch64-linux-gnu architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-13-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "amd64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13-cross/gcc-13-aarch64-linux-gnu_13.3.0-16cross1_amd64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a078c9a4f65c6668945b87291ff06379"
SRC_URI[deb0.sha1sum] = "16862a704740342e8417c86244a4f78f86dc2997"
SRC_URI[deb0.sha256sum] = "ee5d98b1c34ab6f5b751490b42da4bb07672a2f7afc15a3beb2b96ed93b6a768"
SRC_URI[deb0.sha512sum] = "0812238e5a295c604d28b6445f3b3e9c206bd126b97484b322764de61fbbc7d80760cc9cd495eda819de173a863ed777c9449b40ed1437de778523954e2b93be"

RDEPENDS = " \
    binutils-aarch64-linux-gnu \
    cpp-13-aarch64-linux-gnu \
    gcc-13-aarch64-linux-gnu-base \
    libc6 \
    libcc1-0 \
    libgcc-13-dev-arm64-cross \
    libgcc-s1 \
    libgmp10 \
    libisl23 \
    libmpc3 \
    libmpfr6 \
    libstdc++6 \
    libzstd1 \
    zlib1g \
"

RPROVIDES = " \
    c-compiler-aarch64-linux-gnu \
"
