# This was autogenerated! Do not modify
SUMMARY = "GNU Standard C++ Library v3 (development files) (arm64)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-13-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13-cross/libstdc++-13-dev-arm64-cross_13.3.0-16cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "230a3ffa7152830f5f667a9a077cded0"
SRC_URI[deb0.sha1sum] = "b1b6c10533b1ceea45d4974aa74d2fa4a21971fa"
SRC_URI[deb0.sha256sum] = "5538d558020cb9f9ab43e1d14197baa9c2b4d9ce63ec44f6bc60c9a24cab4d88"
SRC_URI[deb0.sha512sum] = "ac4d6097cdffff299c41ae7fad2645b3cb16ac5950d21a2caac329e9ca283278a68071a8e9c9fcea2a946f1a10257a8a4f508c63529e2eaa34b5db8017ca27ab"

RDEPENDS = " \
    gcc-13-cross-base \
    libc6-dev-arm64-cross \
    libgcc-13-dev-arm64-cross \
    libstdc++6-arm64-cross \
"

RPROVIDES = " \
    libstdc++-dev-arm64-cross \
    libstdc++-dev-arm64-dcv1 \
"
