# This was autogenerated! Do not modify
SUMMARY = "development files and documentation for libcurl (OpenSSL flavour)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "curl"
HOMEPAGE = "https://curl.se/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/curl/libcurl4-openssl-dev_8.14.1-2+deb13u4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/curl/libcurl4-openssl-dev_8.14.1-2+deb13u4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "31c4457ec225daa74963972bf3fbe245"
SRC_URI[deb0.sha1sum] = "7fb48083fc82bdfea301c14b82655f7bac55d6fd"
SRC_URI[deb0.sha256sum] = "8dd19979f8bccf67ddbf4baffeb6c01a2c12089d950ae4e2b593017c00c32836"
SRC_URI[deb0.sha512sum] = "92a8bfb6cd349d83f28d5774fd3fb928e574b303f05f6a0b2e0208e8e3f40b77e017df114cf462c0f695de264b3781a94f63dff02785ffe63ca0eeb8a66f4c23"
SRC_URI[deb1.md5sum] = "56d3ef72abd073dbde06465dd7e819fb"
SRC_URI[deb1.sha1sum] = "22542bfe28185bbde64bd01182b46dbf436119dd"
SRC_URI[deb1.sha256sum] = "054fa85e1491b9da2638e83112d11d8cc22936a15da2b7d0d151a8a520b92292"
SRC_URI[deb1.sha512sum] = "356b6cc42f28a27023a1ba7461e8b246386a78e80390517099def1f2ccfcbc0baa19a7456829f92958128f2105eea4e71dfdd35a94cd1b613d9a862dbbf1f553"

RDEPENDS = " \
    libbrotli-dev \
    libcurl4t64 \
    libidn2-dev \
    libkrb5-dev \
    libldap-dev \
    libnghttp2-dev \
    libnghttp3-dev \
    libpsl-dev \
    librtmp-dev \
    libssh2-1-dev \
    libssl-dev \
    libzstd-dev \
    zlib1g-dev \
"

RPROVIDES = " \
    libcurl-dev \
    libcurl-ssl-dev \
    libcurl3-dev \
    libcurl3-openssl-dev \
    libcurl4-dev \
"
