# This was autogenerated! Do not modify
SUMMARY = "Simple, correct PEP517 package builder (Python 3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-build"
HOMEPAGE = "https://github.com/pypa/build"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-build/python3-build_1.2.2-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "9e74981ffc86bd3fe73aedf8c0934c6e"
SRC_URI[deb0.sha1sum] = "d7fb785f8475ece03b464b20412f8f28efa33d45"
SRC_URI[deb0.sha256sum] = "398f05b1681a6d36b6e5b16e821a803b80582a6c61d91d52b4b886430cf007cd"
SRC_URI[deb0.sha512sum] = "b2044340f1b1166304b16c6bb2e2512dff297b4ea41d38768b64468aebcdf1041a07e10a71bdfdb02e84187182dccc311940fa5fb3fa621beb62d337a69808d4"

RDEPENDS = " \
    python3 \
    python3-importlib-metadata \
    python3-packaging \
    python3-pyproject-hooks \
    python3-tomli \
    python3-wheel \
"

