# Copyright 2026 Elektrobit. All rights reserved.

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-features-public-yoriito-integration"
BBFILE_PATTERN_meta-features-public-yoriito-integration = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-features-public-yoriito-integration = "6"

LAYERDEPENDS_meta-features-public-yoriito-integration = "core"
LAYERSERIES_COMPAT_yoriito-layer = "v0.6"

LICENSE_PATH += "${LAYERDIR}/licenses"
YORIITO_LICENSE_PATH = "${LAYERDIR}/licenses"

require conf/distro/include/virtual.inc

REPO_YORIITO_DEBIAN_UPSTREAM_APT ??= "https://deb.debian.org/debian"
