# This was autogenerated! Do not modify
SUMMARY = "Perl module for manipulation of ZIP archives"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libarchive-zip-perl"
HOMEPAGE = "https://metacpan.org/release/Archive-Zip"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/liba/libarchive-zip-perl/libarchive-zip-perl_1.68-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "507878c7edce5b9d21ff5e1776d7f503"
SRC_URI[deb0.sha1sum] = "69db96c0518c282551e49d67e29819941fa4f7c4"
SRC_URI[deb0.sha256sum] = "d1006344c2b897e2ffd1a60c5423f60e9d5c15f701e72c3d60b08b684608cff8"
SRC_URI[deb0.sha512sum] = "adac7ebab07aebf26f8de03e11c4ba2c15cf17a4451d43e9323439efe048d5d19c2fce9668823d021dcde1ba856c198b63236c1e3b8652d85f2bf12cb270da8c"

RDEPENDS = " \
    perl \
"

