# This was autogenerated! Do not modify
SUMMARY = "Generic PCI access library for X"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libpciaccess"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libpciaccess/libpciaccess0_0.17-3+b3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libpciaccess/libpciaccess0_0.17-3+b3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "cf5bbdf3fd7e3b6026f6380553ce2c0a"
SRC_URI[deb0.sha1sum] = "e26e5d3c53522d2f2bf9539e121f5f23f338a47c"
SRC_URI[deb0.sha256sum] = "d9a0091071635a84e837051e4813005ac445071731becea28fba4d9806df5252"
SRC_URI[deb0.sha512sum] = "7c30d9a2bdf29289c7eb514422483ab31ccbb62a4967130f4387fa5cc27e10b35dd3d11d64d678a28267555efb687f8c801d4b4e137f133d79bdb0cde2c40f30"
SRC_URI[deb1.md5sum] = "7a6444942da074022102f49c5930ef10"
SRC_URI[deb1.sha1sum] = "ef6872499767b55a7a38301149bd6719dbda72da"
SRC_URI[deb1.sha256sum] = "2d22631116e5eb4f2e49e6b1ec2933c68d72e4e54c07cf7a17b82f8073db40b2"
SRC_URI[deb1.sha512sum] = "fe9cb9128c8bc452ddb7d9a354fcd37e79ebfbf44f795e3191b5adc15c1a487704ee4ef0f94f695647de771ee77abb799c25d1a48ec5e0bb007fe19f7757fac4"

RDEPENDS = " \
    libc6 \
    zlib1g \
"

