# This was autogenerated! Do not modify
SUMMARY = "Library for YUV scaling (shared library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libyuv"
HOMEPAGE = "https://chromium.googlesource.com/libyuv/libyuv/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/liby/libyuv/libyuv0_0.0.1904.20250204-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/liby/libyuv/libyuv0_0.0.1904.20250204-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "aaf4af94f3459bb17f4ee43dbd31a0ea"
SRC_URI[deb0.sha1sum] = "16a374877f31819da9b40cd4056944c8230e9e05"
SRC_URI[deb0.sha256sum] = "1a6827fe94fa5572a032332df7313ed408e9c0ad78f3a1248391bddc6d920ef2"
SRC_URI[deb0.sha512sum] = "eca07301205507a91b9d07eb2f1fd11f70015f7faea89c81f89a4bcc25e7c165020815576e018708c53477c8b9676b686bfda5f15089b0cba8a01a106397d3ab"
SRC_URI[deb1.md5sum] = "751ae6ffc90ec152baecad56622598cb"
SRC_URI[deb1.sha1sum] = "b95fc45a5d48a3c907dd9e244b772e9997abac58"
SRC_URI[deb1.sha256sum] = "46d8d7bf6e333b460aaeac9cec0a410ed8f1988a47cb481c191ddc689c02215a"
SRC_URI[deb1.sha512sum] = "4c2f5f232c500262c0006f230ab94a2e8a7d2787122fa15fe7e2f3658c399537300b0e8c243ce240f552be760596a50468e2bb6a39fb4b3c01ecfefe5e53f0ba"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libjpeg62-turbo \
    libstdc++6 \
"

RPROVIDES = " \
    libyuv \
"
