# This was autogenerated! Do not modify
SUMMARY = "parser for HTTP messages written in C"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "http-parser"
HOMEPAGE = "https://github.com/joyent/http-parser"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/h/http-parser/libhttp-parser2.9_2.9.4-6+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/h/http-parser/libhttp-parser2.9_2.9.4-6+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "a7b92b369bd4b4627fe19dfb356715db"
SRC_URI[deb0.sha1sum] = "8329ef3e17ff31c107b193dab29979cbce14f60b"
SRC_URI[deb0.sha256sum] = "eb226fd47bec216a02ca6282ab348a3515d1832c58edf1d71b2b5e7948ef3d03"
SRC_URI[deb0.sha512sum] = "44251d89cc4658c105f0b65af365b090fd9c129f4ca63eba7f1f9c42c045c10ce38412cf34b0f3d1e2c58515dba8a9d5a93303c7726dc9153a776d19f59dc8af"
SRC_URI[deb1.md5sum] = "87e369d9346adf1e81c5f73bb72c5f8f"
SRC_URI[deb1.sha1sum] = "b15a0d533bbb1942567a0e1f9f2c41ed503be970"
SRC_URI[deb1.sha256sum] = "b83c393474812e969b6eb8847e2d8a6210f0f5708c21f5e9b94971127f0bdae4"
SRC_URI[deb1.sha512sum] = "19337f27810902b867fad6865b8f943a93fb14eb5d0b705dad2d630f8dbdbba39457145c1f4a22eaa1be317bca3da723ffe79b26219eff61d5c67c8f4f5edaa8"

RDEPENDS = " \
    libc6 \
"

