# This was autogenerated! Do not modify
SUMMARY = "tools for managing Linux kernel modules"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "kmod"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/kmod/kmod_34.2-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/kmod/kmod_34.2-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "9edb239465beb5197b67f91415ccbb01"
SRC_URI[deb0.sha1sum] = "6488c70d87c8fc0cb9fb052ce7d2519618889e4a"
SRC_URI[deb0.sha256sum] = "d56f9311beb17cd15447d11d91fd4de94d23a47d4619e8806b1b807b40c72e53"
SRC_URI[deb0.sha512sum] = "752124de729cefdc2236b9c4061fbaaa495579a404293d9e05d482a7ddb6ffe14b0f7e84fb523eb538b26f19cb84cb3c308a1f1d4313d01622f0e4ba0127dda6"
SRC_URI[deb1.md5sum] = "d1df4242c689cfebde9dc332b9404fb9"
SRC_URI[deb1.sha1sum] = "731c719cba0a5d3ed002c1528821c6353007b70d"
SRC_URI[deb1.sha256sum] = "fd7300fcb8b93cc5f77aa439ee539ceb8050f5cf1d22d86e85179d04f7de5b6f"
SRC_URI[deb1.sha512sum] = "82ddc11821a1baf41cfe0db51b7c3605c9d0e59c849fd4e92a8333335fe8aa84e2634136a971e90477d385950dfbe4f449fc66cf921a3d1038ff80e333d3bef1"

RDEPENDS = " \
    libc6 \
    libkmod2 \
    libssl3t64 \
"

