# This was autogenerated! Do not modify
SUMMARY = "root certificates for validating SSL certs and verifying TLS hosts (python3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-certifi"
HOMEPAGE = "https://github.com/certifi/python-certifi"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-certifi/python3-certifi_2025.1.31+ds-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "65928f0c26d8e763f2e00cb706d0fe7e"
SRC_URI[deb0.sha1sum] = "cba83f3d5cf28d705cb2f1877a003367eb7921b0"
SRC_URI[deb0.sha256sum] = "939b1a979218ec23b5f9469e2ad8a809de588f586bbaf3292b4e617d987824bd"
SRC_URI[deb0.sha512sum] = "9a2a08208874b5806331adf82563d8ae89017bec9829ac8ac5589becb5a11cbb72bdbd592378ea74fbbacf65a6c8aa77da80ea58470dcc98e78a250b4d604a80"

RDEPENDS = " \
    ca-certificates \
    python3 \
"

