# This was autogenerated! Do not modify
SUMMARY = "client for setting system time from NTP servers"
DESCRIPTION = ""
SECTION = "net"
SOURCE_PACKAGE = "ntpsec"
HOMEPAGE = "https://www.ntpsec.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/ntpsec/ntpsec-ntpdate_1.2.3+dfsg1-8_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/ntpsec/ntpsec-ntpdate_1.2.3+dfsg1-8_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8053dc72c22cd69839ba70d865491196"
SRC_URI[deb0.sha1sum] = "898be59c292e930a62dc7ea3ca451c3a46dc1bf7"
SRC_URI[deb0.sha256sum] = "8806c77aa6347f14289145e0b323abb6d86c435e7636e3b0f00a354188a1b4cc"
SRC_URI[deb0.sha512sum] = "b4bea2bf0f8d81bb3239de7a53fe3254042323e47372765481c33c594fe9df488c30989ceb9907bc191d69186b827e62b980292964014296360ce2059de473e2"
SRC_URI[deb1.md5sum] = "ec1a22e2bb790e8c0b4267dfb9c1b303"
SRC_URI[deb1.sha1sum] = "19653b3fc65225f73d3ba9cbd870b5b08ab833d5"
SRC_URI[deb1.sha256sum] = "4fe2afb24e395e7cf3bc27ce65fcd621c9d8fdbe91e582352e49d037471fbfb6"
SRC_URI[deb1.sha512sum] = "bc42c20de97df7a18f86ab65b865edadb0a961c7098190161b6068b3a91eac1d60b9879ef4192e9978c98da69b2ecf495b252d313232cc39be81fd96bfb2d9a2"

RDEPENDS = " \
    netbase \
    ntpsec-ntpdig \
"

