# This was autogenerated! Do not modify
SUMMARY = "GNU TLS library - main runtime library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gnutls28"
HOMEPAGE = "https://www.gnutls.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gnutls28/libgnutls30t64_3.8.9-3+deb13u4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gnutls28/libgnutls30t64_3.8.9-3+deb13u4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "ce391a9ff4974eba985481ee3eaf34a5"
SRC_URI[deb0.sha1sum] = "72f4c6cf757e4af0acf000271eec501c06f7a97d"
SRC_URI[deb0.sha256sum] = "18a8bdfd91c7e3bcb01719d55a2b56849c7160b34f1f52b1c4fdfdd41bf1352b"
SRC_URI[deb0.sha512sum] = "7c2ce59b4739620179f860cc8501d82056c47ecc01f0fcd7d4178cb0fb307881d7033bc6568e6ab82c624f3e0e99a85dc954218df7317a161c7026dbd9ce3136"
SRC_URI[deb1.md5sum] = "8ba3742c66fdabbd9344082735b31bab"
SRC_URI[deb1.sha1sum] = "cd179066d4266a1c6c26038dcc8c1133186a9a07"
SRC_URI[deb1.sha256sum] = "337ef41ab360015d051d6a07f85f8aa6706b35712e3dea23157eba9c902196e2"
SRC_URI[deb1.sha512sum] = "ac5b81afc1e171cf155e35a03821b0f3ab992345cc4d8cc8cd8f3c72ecfc315897757bcb220879303f738191f0da9f36b2b909a605d810ab428407a58d0fae04"

RDEPENDS = " \
    libc6 \
    libgmp10 \
    libhogweed6t64 \
    libidn2-0 \
    libnettle8t64 \
    libp11-kit0 \
    libtasn1-6 \
    libunistring5 \
"

RPROVIDES = " \
    libgnutls30 \
"
