# This was autogenerated! Do not modify
SUMMARY = "pure Python implementation of a sliding window memory map manager"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-smmap"
HOMEPAGE = "https://github.com/Byron/smmap"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-smmap/python3-smmap_6.0.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "5f9ae98aeb8385369b328bce372b5fd6"
SRC_URI[deb0.sha1sum] = "e54aa54061cb1bb71a9db0d59935ddc6d4cfbb5f"
SRC_URI[deb0.sha256sum] = "8e4cf6a612c093bd43046e17f51957102c0af46a444d964afa592c54bbea37b2"
SRC_URI[deb0.sha512sum] = "441b78e92fa6829ddb714b81663a1947fb8bd7fc26ca52d5b9f93d5b06af12a2cdf878ed5e2ddc3bdede11e0183f8cf76556792046b3c9b1ac65d7c72ddea884"

RDEPENDS = " \
    python3 \
"

