# This was autogenerated! Do not modify
SUMMARY = "x264 video coding library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "x264"
HOMEPAGE = "https://www.videolan.org/developers/x264.html"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/x/x264/libx264-164_0.164.3108+git31e19f9-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/x/x264/libx264-164_0.164.3108+git31e19f9-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c847c6f125d66999d62a4f0ea906229d"
SRC_URI[deb0.sha1sum] = "660978005e4cfc7f22a19de8ac7edf2a56d13f99"
SRC_URI[deb0.sha256sum] = "325c90dc0888be316c8979b94aee546d223d4edf03b30927d1e9d431f67e33b2"
SRC_URI[deb0.sha512sum] = "2d2ec1376d5f264cf166180c067be7b8eaa130620c4e785492f73048117b260a5f5f797a9f85fc0c57d8b2eb94ee50fe06bd607b06a0bbca182c9a23c4943101"
SRC_URI[deb1.md5sum] = "89e57fc84d0a9b0abd0596d86991a3ae"
SRC_URI[deb1.sha1sum] = "a20e4c990a3a82b2526a2d04b656157e6ed4a173"
SRC_URI[deb1.sha256sum] = "e062e2ed96d60fdc3ebba5714957e4bfc76e1c87ff6cfa7c022cea3052573f94"
SRC_URI[deb1.sha512sum] = "37ae6a695773cb705d5dbd311e821981436669720f1171acbd10946f4f6528d0f8f92cac9a68acd20c390d0e03b198244abc86864bb3bf525f9956f949188ffb"

RDEPENDS = " \
    libc6 \
"

