# This was autogenerated! Do not modify
SUMMARY = "Qt 6 QML Models library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "qt6-declarative"
HOMEPAGE = "https://www.qt.io/developers/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-declarative/libqt6qmlmodels6_6.8.2+dfsg-7_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-declarative/libqt6qmlmodels6_6.8.2+dfsg-7_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "f739fe37aee68314256b5819cc808a9b"
SRC_URI[deb0.sha1sum] = "3dd6a421fd478f9d78daa3c5b8b11ff089b45330"
SRC_URI[deb0.sha256sum] = "1531ec2f4459760b73a6b137fc6e64e933f1160a2976ccc9d6bd84bb598370d0"
SRC_URI[deb0.sha512sum] = "b3dfa4da4aa452ad695e0d18476aabbf43c3d172ed6b4899fbec9eae8bdb245fa3707c72587d03337b7fa544e3bde951cf891ea836583b4df6d7d8eacea1282a"
SRC_URI[deb1.md5sum] = "5e2260322ca9e70db2a0894d77d605f9"
SRC_URI[deb1.sha1sum] = "9570cd83a394a4d13d8938cf7f2729592f4e4475"
SRC_URI[deb1.sha256sum] = "2ab948dc53768affe1290296539a0ac3f701c5201a5e96bdfc4969a4aee11589"
SRC_URI[deb1.sha512sum] = "ca7a4ef57789f3d4fd7c6d03dd745e065f3378728ab60d082335ecff057d6122fb6b0372b980e91e1de4b147ddc8db2873c2dd8504c83085cdc86fc868d65fcf"

RDEPENDS = " \
    libc6 \
    libqt6core6t64 \
    libqt6qml6 \
    libstdc++6 \
    qt6-base-private-abi \
    qt6-declarative-private-abi \
"

