# This was autogenerated! Do not modify
SUMMARY = "Qt 6 QtQml QML module"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "qt6-declarative"
HOMEPAGE = "https://www.qt.io/developers/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-declarative/qml6-module-qtqml_6.8.2+dfsg-7_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-declarative/qml6-module-qtqml_6.8.2+dfsg-7_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "463fefd5691b8dc5d9ce264c6bad5757"
SRC_URI[deb0.sha1sum] = "f6025dbc5729240a3b5a266c21eff97092930282"
SRC_URI[deb0.sha256sum] = "d46a9a1f9ed30cd859133d1c43663af96018ea38b3a29aa050d42274ceb83eae"
SRC_URI[deb0.sha512sum] = "f97ca80944e5025f6973a109bd1bb6db648d2843ade836dfaf163463638c3ee631187b03eea2893d56550ce66ee735eca3f1e30b28558c9a53af467f53087d5e"
SRC_URI[deb1.md5sum] = "a4bae6fa60a3f0723844734abfe00401"
SRC_URI[deb1.sha1sum] = "070df0c5c885a35cf453fc94dc2cdb01c16a4776"
SRC_URI[deb1.sha256sum] = "52e7eaeb9b857039309dc6652e90a5d1ecd581382ba1fb7548a61d6cd783c4aa"
SRC_URI[deb1.sha512sum] = "71797d7f03b32583b6a4e3c0b1d28654bc67541e7569feb9d05963fd5407284ba81dcbe7c0b591ec51bf582ed6e81123ecf228e974db6c4b9d107c01bce2f674"

RDEPENDS = " \
    libc6 \
    libqt6core6t64 \
    libqt6qml6 \
    libqt6qmlmeta6 \
    libstdc++6 \
    qml6-module-qtqml-models \
    qml6-module-qtqml-workerscript \
"

