# This was autogenerated! Do not modify
SUMMARY = "Qt 6 QtQml Models QML module"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "qt6-declarative"
HOMEPAGE = "https://www.qt.io/developers/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-declarative/qml6-module-qtqml-models_6.8.2+dfsg-7_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-declarative/qml6-module-qtqml-models_6.8.2+dfsg-7_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1dd582217e5419a9076113db3106ed49"
SRC_URI[deb0.sha1sum] = "90e50df4e1aec910775bf0835ab72b26d8281f5a"
SRC_URI[deb0.sha256sum] = "1e8fa7f5f97804ec60e2e56c62b016eafffccc18cc8595b91e78c9f3bdfd6e2b"
SRC_URI[deb0.sha512sum] = "0fee1097d37d056ae12e92631fb730e696c68598a17efceb8a2e5ae524b1df71c438874686dc9a307a1ee58031723aee5214f5fc8c57201dd9cd193956a4f74d"
SRC_URI[deb1.md5sum] = "3c2e507ca069c49b8475196249b60160"
SRC_URI[deb1.sha1sum] = "262aa6772d6e1aacdd9d80c203b213adac7b9cba"
SRC_URI[deb1.sha256sum] = "e0f9f0fef8169eaf2005055bd0e6d04b4cc93cf05e548629d5ccc180a973142a"
SRC_URI[deb1.sha512sum] = "ebbfc2297c284735c94017380159cc6c614d525198a3cd2c43e9a5b961a2525e993062c5a57287010ae7116f6faf3a93ee30383b0cdf9a6a462772d7e48ea0cd"

RDEPENDS = " \
    libc6 \
    libqt6core6t64 \
    libqt6qml6 \
    libqt6qmlmodels6 \
    libstdc++6 \
"

