# This was autogenerated! Do not modify
SUMMARY = "high performance general RPC framework (development)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "grpc"
HOMEPAGE = "https://www.grpc.io/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/grpc/libgrpc-dev_1.51.1-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/grpc/libgrpc-dev_1.51.1-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d8f246202dae480a1cd319e1a703cf47"
SRC_URI[deb0.sha1sum] = "bcf4b727098f391d7d981133aa6cfb1242ea1990"
SRC_URI[deb0.sha256sum] = "be63b48e48b693a2660aa1ff89ddc92396b662b600054b8bc7e57849c0289b65"
SRC_URI[deb0.sha512sum] = "68351078c3cec6945c0d20dd8ead58ce819057e41da19fb8926fc289a6341ed143e6dea92400ee1a15705cc26cacc9bf4b3149301c60c93d43cc879198cecbfe"
SRC_URI[deb1.md5sum] = "c8381f00e775e48f6c88d8bf4162954d"
SRC_URI[deb1.sha1sum] = "95891a280d1d2214b45667101809e07e60291af5"
SRC_URI[deb1.sha256sum] = "e3adb248466cff9df6cf7246d8ed0ca9546b4e39bce0c7575cccecc82374d3e3"
SRC_URI[deb1.sha512sum] = "6e32af661529b41c41e92a0f30e0765d0ad7f2dd1d5c65a421fc396f375cb8e048f8115159ed6406e43659494ac17710767d9b1a1794b33c0d2b32dc2b53fb49"

RDEPENDS = " \
    libabsl-dev \
    libc-ares-dev \
    libgrpc29t64 \
    libre2-dev \
    libssl-dev \
    pkgconf \
    zlib1g-dev \
"

