# This was autogenerated! Do not modify
SUMMARY = "rich set of graph drawing tools - cdt library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "graphviz"
HOMEPAGE = "https://www.graphviz.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/graphviz/libcdt5_2.42.4-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/graphviz/libcdt5_2.42.4-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "81547d6c27bfcd1071cb2c0c2d02121a"
SRC_URI[deb0.sha1sum] = "c18e3ce9ec456c9b422e24dd47d343a01edb9d58"
SRC_URI[deb0.sha256sum] = "5da7f9faa69262ef270b9db22e27773e5928d4066a7fc12171296952efbf6c27"
SRC_URI[deb0.sha512sum] = "540c8801549d4f92ec4e405be1f8a449076141ec8950eab0d7e568032e8133a0a7cd3ef541cc0e797ae6d59e1b2c6a6eaf59d0472bd71b1e523a71431cf26b63"
SRC_URI[deb1.md5sum] = "9fb882a62ea896679559dd919891bbab"
SRC_URI[deb1.sha1sum] = "ac7d57d7703b020fd03ef8953295bfcb3a8de673"
SRC_URI[deb1.sha256sum] = "76be8603ccbdbad3c6794a1af76e1a1cff4a8b12d5e120cba6381bf944a9ce3c"
SRC_URI[deb1.sha512sum] = "511b7ae3ef7c9f541f4065459cac3bad9e15cd0ccd20a84e0625b32985e0a8c7e823bc680058ecbadb6282b21dd7e48d45cf1d5648f2a92a9abf047f954cb235"

RDEPENDS = " \
    libc6 \
"

