# This was autogenerated! Do not modify
SUMMARY = "rich set of graph drawing tools - gvc library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "graphviz"
HOMEPAGE = "https://www.graphviz.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/graphviz/libgvc6_2.42.4-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/graphviz/libgvc6_2.42.4-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "5e1154da3963b562b6ad25cb8eb45a03"
SRC_URI[deb0.sha1sum] = "5bad202c980c83d6c94df50e54c66a19e772eaee"
SRC_URI[deb0.sha256sum] = "a6f5311fdfe1e8260edef8d1bccfbe80a436a7803699925d9c478d6a72a29f31"
SRC_URI[deb0.sha512sum] = "9fc16d90336b77094c6cbcb1dd911b75f6c049e488dfd2747beb584f956a6471e0ea7b9813c9c4f6686213bc5026b08fb70e921ed66c1772d1f01c4958ff0bda"
SRC_URI[deb1.md5sum] = "cd0cc8e1989af574bb949fde7c1956eb"
SRC_URI[deb1.sha1sum] = "08ecbd5480e0f243856d15fc989d26ef9f6a5691"
SRC_URI[deb1.sha256sum] = "7c5da672e5c76bc1aaf2cdbcf38a707e5806cc499d97dbc1415ce022aa8cbdf9"
SRC_URI[deb1.sha512sum] = "3cb0ae9e5d047f6a3f9876244a73dbf44865e206400e87ddd63d4a9042f43ceb76ff8353d17c1bec1910f08204019ada6294c056bb281f6a436496ba981449e5"

RDEPENDS = " \
    libc6 \
    libcairo2 \
    libcdt5 \
    libcgraph6 \
    libexpat1 \
    libgcc-s1 \
    libgd3 \
    libglib2.0-0t64 \
    libgts-0.7-5t64 \
    libltdl7 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpangoft2-1.0-0 \
    libpathplan4 \
    libstdc++6 \
    libwebp7 \
    libx11-6 \
    zlib1g \
"

