# This was autogenerated! Do not modify
SUMMARY = "networking and traffic control tools"
DESCRIPTION = ""
SECTION = "net"
SOURCE_PACKAGE = "iproute2"
HOMEPAGE = "https://wiki.linuxfoundation.org/networking/iproute2"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iproute2/iproute2_6.15.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iproute2/iproute2_6.15.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "76785a4d79f3b56d81988aef77ee6035"
SRC_URI[deb0.sha1sum] = "a1cd30144cc86fe22948a5d1798cf83df1482822"
SRC_URI[deb0.sha256sum] = "7b2dcade4a83ded723fcab21c5a53c47f29352c9c5e1661a089a1e481b3fb48a"
SRC_URI[deb0.sha512sum] = "2319f248637abe0d1dda41965ddbdf98498c10d97af63c5d78dfa2c4f102bebc4a640fafa2095c95d6a8d6b5d47ba005ae70b4d72b0c7364fd1b9bb6d81a74d1"
SRC_URI[deb1.md5sum] = "bebc7292a873ded6c0838cd9e8d27cac"
SRC_URI[deb1.sha1sum] = "4d5a28869b76d8b049658bbd2862b97b9e06988e"
SRC_URI[deb1.sha256sum] = "6750637e683afeef92690c7a136bace6c277066d644aa0da0adc08e2d6785af6"
SRC_URI[deb1.sha512sum] = "5d86e563aadd11f895b6e09d612e2b16e0a366cf0071ea7a51ffd1b7cbf392becc7db5d9ffcad59645981df362c1e92a2726f4e8689a2fd3dbe000b82db3a371"

RDEPENDS = " \
    debconf \
    libbpf1 \
    libc6 \
    libcap2 \
    libcap2-bin \
    libdb5.3t64 \
    libelf1t64 \
    libmnl0 \
    libselinux1 \
    libtirpc3t64 \
    libxtables12 \
"

RPROVIDES = " \
    arpd \
"
