# This was autogenerated! Do not modify
SUMMARY = "Initramfs tool to verify and mount the real rootfs from storage"
DESCRIPTION = "The resulting binary (cominit) expects to be run as the system init process \
out of an initramfs. Its purpose is to mount the rootfs partition, switch the \
root and start the rootfs init. The rootfs filesystem may be read-only or \
read-write using any filesystem supported by the Kernel in use. Continuous \
integrity checking is supported through dm-verity for read-only and \
dm-integrity for writable variants. \
 \
If successful, cominit will clean up after itself and exec into the rootfs \
init ([rootfs]/sbin/init). On any fatal error, cominit will try to exec into \
a rescue shell. This will be either [initramfs]/bin/sh if the error occurred \
before switching the root or [rootfs]/bin/sh if it occurred after."
SECTION = "admin"
SOURCE_PACKAGE = "cominit"
HOMEPAGE = "https://github.com/Elektrobit/cominit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/cominit/cominit_0.12.2_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "2ba8cc8c1e91cfac07810015f549f5e7"
SRC_URI[deb0.sha1sum] = "f43d4121f1e531dad456218a848a1673634da196"
SRC_URI[deb0.sha256sum] = "71161ecf577341b8f38c5a76888d952c1c05f0a2e263287ca07fb08d685f154c"

RDEPENDS = " \
    libc6 \
"

