# This was autogenerated! Do not modify
SUMMARY = "Tests for cominit"
DESCRIPTION = "The resulting binary (cominit) expects to be run as the system init process \
out of an initramfs. Its purpose is to mount the rootfs partition, switch the \
root and start the rootfs init. The rootfs filesystem may be read-only or \
read-write using any filesystem supported by the Kernel in use. Continuous \
integrity checking is supported through dm-verity for read-only and \
dm-integrity for writable variants. \
 \
If successful, cominit will clean up after itself and exec into the rootfs \
init ([rootfs]/sbin/init). On any fatal error, cominit will try to exec into \
a rescue shell. This will be either [initramfs]/bin/sh if the error occurred \
before switching the root or [rootfs]/bin/sh if it occurred after. \
 \
Test utility package."
SECTION = "admin"
SOURCE_PACKAGE = "cominit"
HOMEPAGE = "https://github.com/Elektrobit/cominit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/cominit/cominit-tests_0.12.2_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "23dd234710895c4920c0a5abf553f581"
SRC_URI[deb0.sha1sum] = "74d0e7cf533173f7dae85ee8360aef2d14c2c388"
SRC_URI[deb0.sha256sum] = "90e41ad8be0f8d5b76ec9afda4c12fcbb5dd33c3c89ab36f44a3f4a782744102"


