# This was autogenerated! Do not modify
SUMMARY = "Tests for cominit"
DESCRIPTION = "The resulting binary (cominit) expects to be run as the system init process \
out of an initramfs. Its purpose is to mount the rootfs partition, switch the \
root and start the rootfs init. The rootfs filesystem may be read-only or \
read-write using any filesystem supported by the Kernel in use. Continuous \
integrity checking is supported through dm-verity for read-only and \
dm-integrity for writable variants. \
 \
If successful, cominit will clean up after itself and exec into the rootfs \
init ([rootfs]/sbin/init). On any fatal error, cominit will try to exec into \
a rescue shell. This will be either [initramfs]/bin/sh if the error occurred \
before switching the root or [rootfs]/bin/sh if it occurred after. \
 \
Test utility package."
SECTION = "admin"
SOURCE_PACKAGE = "cominit"
HOMEPAGE = "https://github.com/Elektrobit/cominit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/cominit/cominit-tests_0.12.2_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "90bf1f490c145bd39eb0a984ebf8833a"
SRC_URI[deb0.sha1sum] = "540035ddb619d09ab01d9092347dfd193e06d283"
SRC_URI[deb0.sha256sum] = "3f8b38b71f1afc678556799311ff565812f5e6e224324aff6c9de55a7fc50ae3"


