# This was autogenerated! Do not modify
SUMMARY = "multidict implementation (Python library)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-multidict"
HOMEPAGE = "https://github.com/aio-libs/multidict/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-multidict/python3-multidict_6.4.3-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-multidict/python3-multidict_6.4.3-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "df51a01e3f79630effe46448acb534ac"
SRC_URI[deb0.sha1sum] = "beba31633bc22163fa173f021bb9f7ea1562bd26"
SRC_URI[deb0.sha256sum] = "8bc102844ac2f648b74d7ca758b97ec6984f306255324dfd4ad149694ab20c5e"
SRC_URI[deb0.sha512sum] = "b723c2c1fffbbff1eedc896d9baf241e3e4378c55391141c59d43388d3d93c345d18c1bce292289de28b2d62f4a41245dba5d7c3b0addd85e83b9969021694be"
SRC_URI[deb1.md5sum] = "02a7255a5f79cc07651029ccd70d3288"
SRC_URI[deb1.sha1sum] = "c6f333c3384642604822fc9782f6a80c30ac7553"
SRC_URI[deb1.sha256sum] = "724d117deb76efa7d9446a9355c0ba80b37ee3d62657a38cb88e562874f1c540"
SRC_URI[deb1.sha512sum] = "913d4a8a02cf429cc59eb79056a0521bf4fb395dbff9aa1b4fe8bd75a9d3f21485819fb2c31855d29c26807bfbf9a7e5d3602170eef3655911d39dbdb1c9c83d"

RDEPENDS = " \
    libc6 \
    python3 \
    python3-typing-extensions \
"

