# This was autogenerated! Do not modify
SUMMARY = "Tcl (the Tool Command Language) v8.6 - shell"
DESCRIPTION = ""
SECTION = "interpreters"
SOURCE_PACKAGE = "tcl8.6"
HOMEPAGE = "http://www.tcl.tk/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tcl8.6/tcl8.6_8.6.16+dfsg-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tcl8.6/tcl8.6_8.6.16+dfsg-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b4f6e7a67042c98c39dcd0c28b666a99"
SRC_URI[deb0.sha1sum] = "9e6c0e3e601eb9df47951f4d513c58dbf8f02b16"
SRC_URI[deb0.sha256sum] = "3b8d5f3ade3b2365c1dd78e7d5b42183d73f0e67893729bd0624b043cdd2b627"
SRC_URI[deb0.sha512sum] = "5cbe1042c5795f4de1f149bae5d2889481ec211ec28714de7dce19d9d8dff955d1f93b4f7fcfba1bf8e6adb710f1e8d30c4d9a92e666b1414dde4a73a39625a6"
SRC_URI[deb1.md5sum] = "0802a8e204b8dc1423dc742ad6939cdb"
SRC_URI[deb1.sha1sum] = "19a0ba8cdafedbee746687a00a65b7a7fd84d827"
SRC_URI[deb1.sha256sum] = "1cd867d99819b5464af416967558a54358f71770fabafcc737baab854caa4e44"
SRC_URI[deb1.sha512sum] = "1e65db57f8a35a93601b6c70a9dfedccad5da7a9f502c38148bb9dc543caeb68fed283c910c62df77ffc44c515e36137aadeba6881b330ea729ff73bad24d864"

RDEPENDS = " \
    libc6 \
    libtcl8.6 \
"

