# This was autogenerated! Do not modify
SUMMARY = "Netfilter nftables high level userspace API library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "nftables"
HOMEPAGE = "https://www.netfilter.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nftables/libnftables1_1.1.3-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nftables/libnftables1_1.1.3-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "de65a21d1b4c7ffde5afd5ca6364e4a3"
SRC_URI[deb0.sha1sum] = "4db1c5622a1010bb315eb437b45c4178cd121164"
SRC_URI[deb0.sha256sum] = "c7cbee3dce8452ae5c3c4269f6f52e96b896d36a46ea3c490e0e11e8ff359896"
SRC_URI[deb0.sha512sum] = "d4af1a38b79a6d9775e8dfe90f56f3c7c0eb056ff616535fb7554d5b93e1da2e3e4e5885e266898b2410f438f6f69cb2d115be5523e584fd93126ba7051292d4"
SRC_URI[deb1.md5sum] = "f11d76e85566e7d032acfa6f18dd4031"
SRC_URI[deb1.sha1sum] = "e3581e998573605518256560dbd1a774367417c0"
SRC_URI[deb1.sha256sum] = "260b0790a8f567ef27d293e15c722d867de113d579c330be17d13354cd61c356"
SRC_URI[deb1.sha512sum] = "c1db506d9e6e7aae8ebe3652f83c926f5f5b10a81000c067cb0565f219cac22c7ef2b4d13ae59c0eb91f0ddff164194f7c1aec6f51efae569c9a000333250a5d"

RDEPENDS = " \
    libc6 \
    libgmp10 \
    libjansson4 \
    libmnl0 \
    libnftnl11 \
    libxtables12 \
"

