# This was autogenerated! Do not modify
SUMMARY = "TurboJPEG runtime library - SIMD optimized"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libjpeg-turbo"
HOMEPAGE = "https://www.libjpeg-turbo.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libj/libjpeg-turbo/libturbojpeg0_2.1.5-4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libj/libjpeg-turbo/libturbojpeg0_2.1.5-4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "2bb269b6bd304a7e8ba10af66467c8f5"
SRC_URI[deb0.sha1sum] = "4225320d3436fb5803ac4013b5d2d0d018fd1efb"
SRC_URI[deb0.sha256sum] = "41e47391d822b61b7ca70002c793c1aa003bce6e31d30a28edda432e2b842a80"
SRC_URI[deb0.sha512sum] = "9c332578320219dfc200e7af2093f2e4e5b7f69935b2afc5846e149034b2870465ba5a75a9fd54b3ebbe93810ae553b03fbe8d9d73320781eda2d7684d9da48e"
SRC_URI[deb1.md5sum] = "597422a6205d21a8301439e74a73f8d9"
SRC_URI[deb1.sha1sum] = "d9ecbd145d20bcb5136a5b3a2fb872ef6b392612"
SRC_URI[deb1.sha256sum] = "bfce9b617b7de2e313b701de3ad3611b764613820d690592e3e96f3a62f02cdf"
SRC_URI[deb1.sha512sum] = "57d0107fdc941ae280a4205cebec998868a97b5ef7ec929540e42a719d0be4ea901a12e1c62f3d11bbac61ea26e00936fe889fb62fb0226c1fc5dcfb97042eed"

RDEPENDS = " \
    libc6 \
"

