# This was autogenerated! Do not modify
SUMMARY = "python3 interface to the libmagic file type identification library"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-magic"
HOMEPAGE = "https://github.com/ahupp/python-magic/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-magic/python3-magic_0.4.27-3_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "d1b0a20497a6e53dab937185f560c568"
SRC_URI[deb0.sha1sum] = "f4b209e7e0f611a549300f3871c08a4a7a8f65d4"
SRC_URI[deb0.sha256sum] = "6cffe27f4381ff4d4e56113f72a7c6b79ddd8b2bc92958d5b2051fb788def236"
SRC_URI[deb0.sha512sum] = "c2612659e440b43126cb2acb298f6949c970ed6681b0a2c50bd8e58b189b48f7219735c6a110cfa2537947c79f7f4e733ce514fd164777327a27a52c09f019e3"

RDEPENDS = " \
    libmagic1t64 \
    python3 \
"

