# This was autogenerated! Do not modify
SUMMARY = "Linux Kernel Device Mapper userspace library"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "lvm2"
HOMEPAGE = "https://sourceware.org/lvm2/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lvm2/dmsetup_1.02.205-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lvm2/dmsetup_1.02.205-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1097404ddbb3b6147fffe884f634746c"
SRC_URI[deb0.sha1sum] = "7cb0ff0558fc03261898a63a7a3c869a775d26d5"
SRC_URI[deb0.sha256sum] = "4771f7ab0a907a8e5d02a6358ff016ae7cb49124906bada02fa882e141b615a0"
SRC_URI[deb0.sha512sum] = "c643bc96d704bd896cdcc738da59b36cd48aba134f897afc5b578adfc5148c3bac9948d6bad6f1f1bf521520976f7a37e828a54aa4b82efef18640944237ffd4"
SRC_URI[deb1.md5sum] = "33675e46c9d872171df644b1e4971065"
SRC_URI[deb1.sha1sum] = "63ec630316cf70c5d1ed3dd5e3ba92de92b6b3f4"
SRC_URI[deb1.sha256sum] = "f802c1ec2d6f45a6544f09c5da72f9688e06208d12bb76ac9b25f2cfa8033306"
SRC_URI[deb1.sha512sum] = "1c144a136e01cefc239c87d58402575b2e3955dc4e7738ce28ea2697f7bf06d03b0e8927e0e037c33fc4ab7fc5da2eebe3fe2e2944a00e5e25735007b6c2c5a0"

RDEPENDS = " \
    libc6 \
    libdevmapper1.02.1 \
"

