# This was autogenerated! Do not modify
SUMMARY = "efficient, principled regular expression library, development kit"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "re2"
HOMEPAGE = "https://github.com/google/re2"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/re2/libre2-dev_20240702-3+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/re2/libre2-dev_20240702-3+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4bd64fc6470aab42fbb8056f75eb296a"
SRC_URI[deb0.sha1sum] = "04aec8f7ccf6d2d20fc3c8f773eb09ce2ffe0276"
SRC_URI[deb0.sha256sum] = "feaa00a81f873c0121b16d910903ff0604889dbf8c8f7a4cc2482c72e6c9e0f6"
SRC_URI[deb0.sha512sum] = "218972bc1de54041459124996e293e2b79d3eaabf0d4e8070478a9f08e2b1dda1be5b8575c1c9bde6c131688315712af032244b69db42839facd40180bdf851b"
SRC_URI[deb1.md5sum] = "35f9253bb3f2daa496e82c2cbcd53f8a"
SRC_URI[deb1.sha1sum] = "3bac8ff5932cb32d8adcbccb2ac2587e62f68288"
SRC_URI[deb1.sha256sum] = "0ada6dc934c590d513ffe1d7d0da3355d95a76c8d2f4761616f88f81f74754ad"
SRC_URI[deb1.sha512sum] = "e401efb534652fe47d586cf1d1428197a6dfdb2b479632a1fee108682aaaa55875921f93f5d28035d6e781894213a77634fd96b6ff221e64b55f0e2260209985"

RDEPENDS = " \
    libabsl-dev \
    libre2-11 \
"

