# This was autogenerated! Do not modify
SUMMARY = "Open Container Images manipulation tool"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "umoci"
HOMEPAGE = "https://umo.ci"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/umoci/umoci_0.4.7+ds-4+b10_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/umoci/umoci_0.4.7+ds-4+b10_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "bcd645961cc1ca73790f87a24bda2d93"
SRC_URI[deb0.sha1sum] = "e429f1bfa6626c136583ade5f3dcb6962f71c628"
SRC_URI[deb0.sha256sum] = "d6c837c39304a646e3cd3ee1ec329a5ab936bbe1e22538edc950b72e32eca9cc"
SRC_URI[deb0.sha512sum] = "ffcfdbe190a4315f291e6e186aae057c1d6e4511ed52f0a8350d9d21d52df4580e2ebc66a5aff12daf765a1a11d82784a6bd53b930ead63f8c12f963e2446154"
SRC_URI[deb1.md5sum] = "4c681c7476b337600ce54cec45b5d9cb"
SRC_URI[deb1.sha1sum] = "e34e0c744e494622a355cedf02f507dffa0d766c"
SRC_URI[deb1.sha256sum] = "07f94acfbd96cb56dbcf86d7cf3ed8d6b54ee1e8c140665911a172360781a5d6"
SRC_URI[deb1.sha512sum] = "bcd8821d00ab3b84da1219ebb32dbb065afd03dea875c43035f34addbb9037e2084026fb7ea0da8950dd10bf6b6239de6bec77746333410a7ab8d73bba36f2dd"

RDEPENDS = " \
    libc6 \
"

