# This was autogenerated! Do not modify
SUMMARY = "low level cryptographic library (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "nettle"
HOMEPAGE = "https://www.lysator.liu.se/~nisse/nettle/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nettle/nettle-dev_3.10.1-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nettle/nettle-dev_3.10.1-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "fc11347d878857ec40d131e3ff840c7a"
SRC_URI[deb0.sha1sum] = "c976bcf43970427f2b1dbd9c4b7162a307596634"
SRC_URI[deb0.sha256sum] = "686dc13aaa2804161dbc7c916a664bf37fb7bb9a8128b6e025fa45ab06804e3a"
SRC_URI[deb0.sha512sum] = "9f003b191cc25c333bf8500568f8bb704fe44576fdc4b8aeabd04da21e533444552f66961a90fc01d8bf15f9ad4eb8f42720a1ace5e809638b92ced7f1e002ad"
SRC_URI[deb1.md5sum] = "cd4d83eb7778bfd44ea1b60b16d297a3"
SRC_URI[deb1.sha1sum] = "41d4669cab0dc8670b3772e8919f0f326b0dbde4"
SRC_URI[deb1.sha256sum] = "4786f95ed545c9e69ad54268f41e0c4c57524f2ef6c0df9c39041d7efe4899f7"
SRC_URI[deb1.sha512sum] = "145c49e294e071d51549366e80eeeb8808a3dfa924360f8d5f6e7bdd77b48207a0ff4b76b60ae4c854b1c66c1ea4c400368ee1c9fcf97e865e028ff03cac33db"

RDEPENDS = " \
    libgmp-dev \
    libhogweed6t64 \
    libnettle8t64 \
"

