# This was autogenerated! Do not modify
SUMMARY = "Basic TCP/IP networking system"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "netbase"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/netbase/netbase_6.5_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "fd96ad393ce05e5bb055165dd214150d"
SRC_URI[deb0.sha1sum] = "13c4d9e65ee7d35f60f8b3347e2b732f7498abdf"
SRC_URI[deb0.sha256sum] = "76bafa92947ebd37b0a6f9ec6570412041f56edebc1c66d323731216d318471e"
SRC_URI[deb0.sha512sum] = "b0d289d0aa33390a9f47e547af6aeb87cc2a4d9f8a636591c148c835ee4fc3a6312360ae92a6469cd3914b00ac5d37903821e8b7c441f3398498dc195cd642d3"


