# This was autogenerated! Do not modify
SUMMARY = "Development package for libelos - common headers"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Development package with common headers."
SECTION = "libdevel"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/libelos-common-dev_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "46e573306fbdfa685383400b8b183ccc"
SRC_URI[deb0.sha1sum] = "ae91f950921101e51ba39b46da1081a30d043e15"
SRC_URI[deb0.sha256sum] = "b961b4a3fe0db62ff090d37a9d3ec4d67875306b4de1066fdc7c73371d90d34a"


