# This was autogenerated! Do not modify
SUMMARY = "Development package for libelos-cpp"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Development package for libelos-cpp."
SECTION = "libdevel"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/libelos-cpp-dev_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0ac17088b31baf567f5ef1e294a36ef4"
SRC_URI[deb0.sha1sum] = "fc89da13701a55eb4a1375b937ca441880fede95"
SRC_URI[deb0.sha256sum] = "ac7be5ee6b6cdd83efeae5cb8503108e8a53d4a17ff5c9bfc71aff8e11e50d6d"

RDEPENDS = " \
    libelos-cpp1 \
"

