# This was autogenerated! Do not modify
SUMMARY = "Development package for libelosplugin"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Development package for libelosplugin."
SECTION = "libdevel"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/libelosplugin-dev_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "cca2e63c4905ebe2e8e436991e97b729"
SRC_URI[deb0.sha1sum] = "88ddae47e743af331e20df6fc3a6822648cc356a"
SRC_URI[deb0.sha256sum] = "37459598c995ebe9614e645e634a37f88dd4e745584654f638c896b488c2ed66"

RDEPENDS = " \
    libelos-common-dev \
    libelosplugin1 \
"

