# This was autogenerated! Do not modify
SUMMARY = "sorted container types: SortedList, SortedDict, and SortedSet (Python 3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "sortedcontainers"
HOMEPAGE = "http://www.grantjenks.com/docs/sortedcontainers/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sortedcontainers/python3-sortedcontainers_2.4.0-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "c39ed65cb135c385897175065b5feefc"
SRC_URI[deb0.sha1sum] = "343a944b3ec5c1dbd8de6ae079ab8745dcdf5afc"
SRC_URI[deb0.sha256sum] = "b00fd22e4fd50d8ba44442607fc3c737186082b16648d3995b2e4fca642f53e1"
SRC_URI[deb0.sha512sum] = "18945c6456de34493d28b5aeaba2c320808795c0edeb91365cb3e7daa8162df6018a48a040ab5a3789748bd1cb50d7b3f01267ed521b8efab839967e31513e31"

RDEPENDS = " \
    python3 \
"

