# This was autogenerated! Do not modify
SUMMARY = "Library of common utility API's used in elos and samconf (mocks)"
DESCRIPTION = "Library of common utility API's used in elos and samconf. \
 \
Mock library package."
SECTION = "libs"
SOURCE_PACKAGE = "safu"
HOMEPAGE = "https://github.com/Elektrobit/safu"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/safu/libmock-safu0_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "70569007eb81d7dfbd848e8e4e8b4fee"
SRC_URI[deb0.sha1sum] = "4c7c04f14c813e3e9b29c80a5d40300c75583db2"
SRC_URI[deb0.sha256sum] = "109e501374fb68933306eed5d731eda716c67cd1a1ceb86468f9fbaa6d6739a2"

RDEPENDS = " \
    libc6 \
    libcmocka0 \
    libjson-c5 \
    libsafu0 \
"

