# This was autogenerated! Do not modify
SUMMARY = "Library of common utility API's used in elos and samconf (mocks)"
DESCRIPTION = "Library of common utility API's used in elos and samconf. \
 \
Mock library package."
SECTION = "libs"
SOURCE_PACKAGE = "safu"
HOMEPAGE = "https://github.com/Elektrobit/safu"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/safu/libmock-safu0_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "20c912866640baaf90e585d4dbc2d74f"
SRC_URI[deb0.sha1sum] = "5b8684fd1d1e15e04dd050e5adce884f3b59336e"
SRC_URI[deb0.sha256sum] = "bd6d427e342ee0f0bc71f6c41d31b4dca1b892f8f5b2c4c9072ece69c3fa56af"

RDEPENDS = " \
    libc6 \
    libcmocka0 \
    libjson-c5 \
    libsafu0 \
"

