# This was autogenerated! Do not modify
SUMMARY = "lint tool for shell scripts"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "shellcheck"
HOMEPAGE = "https://www.shellcheck.net/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/shellcheck/shellcheck_0.10.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/shellcheck/shellcheck_0.10.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "02d4a11d469beb04101c927888fdab89"
SRC_URI[deb0.sha1sum] = "33cbebe93d9ba084ac011afb26d99f281a832be8"
SRC_URI[deb0.sha256sum] = "8b207f7d4421a46cec9e377c74d450e1717092b58ae3e7151cd5f85f639065cd"
SRC_URI[deb0.sha512sum] = "407e89b72d8aca6be853df8ef37c124741e81c4d0a240acd83ed4160ad98621847a4d95e7579b85f7f01a9a7fbcedde23f85de004ff3dd45de9d6466dc435aa2"
SRC_URI[deb1.md5sum] = "d973d7fd81763ab837cb85cf049aca68"
SRC_URI[deb1.sha1sum] = "fc845aa55c276e552a7161b45eb28d49364e8f73"
SRC_URI[deb1.sha256sum] = "35bffb007a2873c76258647b23110bd7ca8032e168918491e0ce37e8c54365d4"
SRC_URI[deb1.sha512sum] = "17fe16ef1fe0f8a9afb412820f2507534c264bddae180c98b25adf41fc62e9579ff3c49da5a762bf39b32fcef97340642356e86232c54a32aaa90d5f62351e95"

RDEPENDS = " \
    libc6 \
    libffi8 \
    libgmp10 \
"

