# This was autogenerated! Do not modify
SUMMARY = "debhelper add-on to call autoreconf and clean up after the build"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "dh-autoreconf"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/dh-autoreconf/dh-autoreconf_20_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "4e651de0bd2d70c7d57d47b01bb8af4d"
SRC_URI[deb0.sha1sum] = "58218d5fd111e985646c0d8d109cf64162796716"
SRC_URI[deb0.sha256sum] = "9527d06ee13195c48718a2580d7262883344a5ecc7a77b48c3b7aa70086a0125"
SRC_URI[deb0.sha512sum] = "046283432e1f6de1a14b32ef5bf057cf3279d52fb9c6ed5b3c227e08176662ef589063ace906c225a8f2c93373527498e905574ca7b191569d9ecffa9ca411b3"

RDEPENDS = " \
    autoconf \
    automake \
    autopoint \
    libdebhelper-perl \
    libtool \
    perl \
"

