# This was autogenerated! Do not modify
SUMMARY = "Interactive high-level object-oriented language (version 3.13)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python3.13"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python3.13/python3.13_3.13.5-2+deb13u3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python3.13/python3.13_3.13.5-2+deb13u3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "bf0e2c79a2c4e41f2a363ed8cd049bcf"
SRC_URI[deb0.sha1sum] = "587cc4df1ef23e1998374d6438c66a992330ecb8"
SRC_URI[deb0.sha256sum] = "669335986fd641d6f6c538f558fc752a20c1d8168856f90b7e34a7615484dcd2"
SRC_URI[deb0.sha512sum] = "f7144af2edc79f15a8e9dd08238f21a56682e06d9d91723e5579878bcb463fcc91c00aa5daed762f1329ed512b1c6d60665c630995c8d09d44bfb676fecf14cd"
SRC_URI[deb1.md5sum] = "6e2db8482f310188083f01f95c139d39"
SRC_URI[deb1.sha1sum] = "1577f0a317b1cfcf174c2605681982b0f04d3f67"
SRC_URI[deb1.sha256sum] = "47af7a6a254dfe18365f680b2a0dabec9188d054c81d6d3f8caaa55e53e0871a"
SRC_URI[deb1.sha512sum] = "e444270c5ee0297e1bb80e713e1342a3207e300fcc081d80a3323825c0ef369b69576420a004725fcec4767ef452847f2e6f7d64f53be0f1d9f82783fd68a145"

RDEPENDS = " \
    libpython3.13-stdlib \
    media-types \
    python3.13-minimal \
    tzdata \
"

