# This was autogenerated! Do not modify
SUMMARY = "library for reading and writing JSON for C++"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libjsoncpp"
HOMEPAGE = "https://github.com/open-source-parsers/jsoncpp"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libj/libjsoncpp/libjsoncpp26_1.9.6-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libj/libjsoncpp/libjsoncpp26_1.9.6-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "39e78c5b99ab282f4d1c36d8424f4ff6"
SRC_URI[deb0.sha1sum] = "6ad049c35173d62b6d4d57915c8ffcbeb1cc30a4"
SRC_URI[deb0.sha256sum] = "fd0b75839fe7b1a08df49e4203b1fb042df4f7d982db8d91c1fd7bdbcd4b1460"
SRC_URI[deb0.sha512sum] = "f1b2189087f7cc20da13fcdb9cb4802f931565ee1423e74fa5206447a4b37eecbbbaf9dcecd21c557fd6ac8069c459696db6d5ee569b6fad233a3d1672adf2b0"
SRC_URI[deb1.md5sum] = "1002ebe844cb28e7c34cf78bfe00d2f2"
SRC_URI[deb1.sha1sum] = "7b6ae79ced09174c36c6aabad563c6c052947977"
SRC_URI[deb1.sha256sum] = "346da1614a66ae07549243f2abf1dc5fdcc590a4ccb408458b5ea7ef7997477d"
SRC_URI[deb1.sha512sum] = "41d9985d9d049e79af13f299a76138477b567301a5247f198ba0ee4adfeefa7c2b8bc3239f45279217d1a2ed2df654ccff9391ade41d5a8c87d267c172374508"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
"

