# This was autogenerated! Do not modify
SUMMARY = "GNU Privacy Guard -- minimalist public key operations"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "gnupg2"
HOMEPAGE = "https://www.gnupg.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gnupg2/gpg_2.4.7-21+deb13u1+b4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gnupg2/gpg_2.4.7-21+deb13u1+b4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "f9532e44838c7a9b020a170889e48e98"
SRC_URI[deb0.sha1sum] = "0957927cf2752594b157801d242ad82452480251"
SRC_URI[deb0.sha256sum] = "58e8cda09c8b848c6c2208587426027829fb3f9f9464cd5f1f0506720816f537"
SRC_URI[deb0.sha512sum] = "db8c321be36d411e3d6e1c559406af10ae848cecc47323373523863363f8b7e0d9b3cf808a03fa2f8ae5c5a7de8581bd718f4e2a01d4f8d2618d61378ad08bee"
SRC_URI[deb1.md5sum] = "23274324c3aace3d9c3b1e724c6e8548"
SRC_URI[deb1.sha1sum] = "c279c5435aeaa1ba8ddf880cf81cc477944b5748"
SRC_URI[deb1.sha256sum] = "840abc3e9178b9578fbc9c9674ebb2f3b983790f713ffd2b6a0371d8670dc8e7"
SRC_URI[deb1.sha512sum] = "dce0fa8eae0982d1c4190de7d017f8ece827f39088e792ff9fcaa48214536b66519814f01921520bf9b6e3f8ada86ac59e3684105c50efad6696d4607d8d0df0"

RDEPENDS = " \
    gpgconf \
    init-system-helpers \
    libassuan9 \
    libbz2-1.0 \
    libc6 \
    libgcrypt20 \
    libgpg-error0 \
    libksba8 \
    libnpth0t64 \
    libreadline8t64 \
    libsqlite3-0 \
    zlib1g \
"

RPROVIDES = " \
    keyboxd \
"
