# This was autogenerated! Do not modify
SUMMARY = "administration tools for packet filtering and NAT"
DESCRIPTION = ""
SECTION = "net"
SOURCE_PACKAGE = "iptables"
HOMEPAGE = "https://www.netfilter.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iptables/iptables_1.8.11-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iptables/iptables_1.8.11-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "16e74aac945c7b5f01ce48de9dcc1ac0"
SRC_URI[deb0.sha1sum] = "d43e1c03d0968518eb54f4dc49edb10b1e97672e"
SRC_URI[deb0.sha256sum] = "95ba166bb68a76ca1513196dd59d91e3c33b2096884c6de80406f302b18a030e"
SRC_URI[deb0.sha512sum] = "31bb23de45cb7f9fa04685a6769cb6393c85fb7a80d7cec228e90f7fc12f5642f9b704ae428a177565c921fd6957cf211912258ca623dfb431bdebd9f9150b92"
SRC_URI[deb1.md5sum] = "36b682be5e5555a5ad6662e7d21c4386"
SRC_URI[deb1.sha1sum] = "72498801bbed2013d9ec17e32159b205aea39f9a"
SRC_URI[deb1.sha256sum] = "441a3c4b202f83cb1c2609c9eff768229ce991c2f49bea37416168028bc23e95"
SRC_URI[deb1.sha512sum] = "73e93344ccdf941706fd2cb2b943e89c3ed0634c7ed0b5f20f70957f58270ea020d9a755df223f2fa6b88c764ef9e411ba9804ec13776e7ca2cbe748828e3dc4"

RDEPENDS = " \
    libc6 \
    libip4tc2 \
    libip6tc2 \
    libmnl0 \
    libnetfilter-conntrack3 \
    libnfnetlink0 \
    libnftnl11 \
    libxtables12 \
    netbase \
"

