# This was autogenerated! Do not modify
SUMMARY = "disk encryption support - startup scripts"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "cryptsetup"
HOMEPAGE = "https://gitlab.com/cryptsetup/cryptsetup"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cryptsetup/cryptsetup_2.7.5-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cryptsetup/cryptsetup_2.7.5-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "7efc305a0f6f57dd71867baa5e90979c"
SRC_URI[deb0.sha1sum] = "1ba6ce22bb22547805cdedfa844f2348efb8147f"
SRC_URI[deb0.sha256sum] = "916ff5b1336f67dbaf763039529c3a0e10d2b839ef11463cde13a405ba49bcd4"
SRC_URI[deb0.sha512sum] = "9a907435cb13d89a3b0b2fa5267a33194fd9db779132c1fa1cccd5602c07171f0eebd5a2fc8bf8a054c8560fd35cc5439f40ef158c86dba7fbd9c71e5f9893ca"
SRC_URI[deb1.md5sum] = "f52b579ed0dbd13722d1eb5084a4fbd8"
SRC_URI[deb1.sha1sum] = "fd4646aa020d4f880b65cc94511b487e17f454c9"
SRC_URI[deb1.sha256sum] = "098a83767a860e7cbee86bd1b0a9195db7f38bf8f97f00fc94c3d818eb750665"
SRC_URI[deb1.sha512sum] = "d8d0ca505d042e51676dd4fef0638a48c52c45d578f1619ea007e0c8f6f793d48a41a1684bd8ac5bc03721abfbe718ef2f90adad08837125ceed0d9c0d469ea6"

RDEPENDS = " \
    cryptsetup-bin \
    debconf \
    dmsetup \
    libc6 \
"

