# This was autogenerated! Do not modify
SUMMARY = "Make ssh v2 connections (Python 3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "paramiko"
HOMEPAGE = "https://github.com/paramiko/paramiko/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/paramiko/python3-paramiko_3.5.1-3_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "dc8d4e4b594a55cef3a5a43d8b0307c5"
SRC_URI[deb0.sha1sum] = "5ff312e0a341cf410a289441a2ea5aa86b77ef84"
SRC_URI[deb0.sha256sum] = "1fb1e8bcf27d6c8de1860ee97ea2d0ee8dbea99e4efc201e74adc3e9713431bc"
SRC_URI[deb0.sha512sum] = "d108ca57421782944a5631ffffa2e9a18f2f3d5614d45f46d4c20bd63724d386b5296e3465d3addd2cf3a719deaf8f57ddbd04ff1aa867c955ed6d9135a727ff"

RDEPENDS = " \
    python3 \
    python3-bcrypt \
    python3-cryptography \
    python3-nacl \
"

