# This was autogenerated! Do not modify
SUMMARY = "Font rendering engine for Complex Scripts -- library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "graphite2"
HOMEPAGE = "https://graphite.sil.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/graphite2/libgraphite2-3_1.3.14-2+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/graphite2/libgraphite2-3_1.3.14-2+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "88afc62ee0e94eedec7c371d167f596a"
SRC_URI[deb0.sha1sum] = "da1c7c76394d6f24c807d689752490c41b853dfc"
SRC_URI[deb0.sha256sum] = "1769ba3ed3c1fc75b7fbe02678e32aa24391205813eceef4e1e3500015d12ee3"
SRC_URI[deb0.sha512sum] = "3f7395bf9fe2ce03caed88900d68965a57ac687f7a32a8fa3d76aa78b4a85522ef1a2ce9b52ec243f691bd20fbe5671c9d85f4d4d2555d8a0ea8193e24e4c003"
SRC_URI[deb1.md5sum] = "d2e9d48234759bdd69c03b0839485163"
SRC_URI[deb1.sha1sum] = "eac497eeb31c895ce4c509da482bda2c8ac81e3b"
SRC_URI[deb1.sha256sum] = "b0c3414b113de62be1dc28fa2c899ac0856256e2f094d92c36c3275a5053311a"
SRC_URI[deb1.sha512sum] = "78a7637ed2b0c19aa8e506d3deec763dd8d7d3c31bce6a3da4bd09a8288ab3d4150a387d37639b76cdb0310a4778782df1158eff2a667f9a1eaecb066f827c3a"

RDEPENDS = " \
    libc6 \
"

RPROVIDES = " \
    libgraphite2-2.0.0 \
"
