# This was autogenerated! Do not modify
SUMMARY = "GNU C++ compiler for aarch64-linux-gnu architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "amd64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/g++-14-aarch64-linux-gnu_14.2.0-19cross1_amd64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "2712eff8bc94b36f2843be66d028f3d2"
SRC_URI[deb0.sha1sum] = "67e3bc14f1751d52b5971e4357390e83bcb6a450"
SRC_URI[deb0.sha256sum] = "edbb7ab8e432a4a5b2ca2b7cce97bb643bd6fb1ae75e65bb0e889bae1c6d40eb"
SRC_URI[deb0.sha512sum] = "4c7f38de65a66ad0e4e80aa1611ebc2ee00fd573a2a8aee3c21b2692063d05379864281527d0078d4ef88f08ccb7900255d18ce846429a8342d676db96e4aa8a"

RDEPENDS = " \
    gcc-14-aarch64-linux-gnu \
    gcc-14-aarch64-linux-gnu-base \
    libc6 \
    libgmp10 \
    libisl23 \
    libmpc3 \
    libmpfr6 \
    libstdc++-14-dev-arm64-cross \
    libzstd1 \
    zlib1g \
"

RPROVIDES = " \
    c++-compiler-aarch64-linux-gnu \
"
