# This was autogenerated! Do not modify
SUMMARY = "GCC, the GNU Compiler Collection (base package)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/gcc-14-x86-64-linux-gnu-base_14.2.0-19cross1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0ee15af5939543b72a5758aaed948b0c"
SRC_URI[deb0.sha1sum] = "754f1053729bc3a2998db867ed9844f7a9d6eb43"
SRC_URI[deb0.sha256sum] = "e39695bfd2eaf3ce59d6ffc60f2db3bc1eb3c9806c7612c8d36383e363dc312a"
SRC_URI[deb0.sha512sum] = "2c5fad0d2919a5eea88c1adb6356a1949edc81b6e4e8822d523723719da2d9f53c4ef30a6d647c2564cf054d4b70fa8c742cc978c5c16d329ad4ed4fb9872872"


