# This was autogenerated! Do not modify
SUMMARY = "GCC, the GNU Compiler Collection (library base package)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/gcc-14-cross-base_14.2.0-19cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "96f8a0dac418f9fa92bdd475d15b2c66"
SRC_URI[deb0.sha1sum] = "82a947e4b214f251876ac9b3df2f3f878d038f90"
SRC_URI[deb0.sha256sum] = "a6c277ad0961c1e69bebd2509151733961ea49bb53ff64aa1dac72b5929babf0"
SRC_URI[deb0.sha512sum] = "5344f7e50ad203f5698f5ace91fd9d4017c599fd78b86df454002c0109afb287b81e8e96b362ad4cb773ed1936755dbed5a221f1257ba7530bc39edd70e26d6e"


