# This was autogenerated! Do not modify
SUMMARY = "GCC OpenMP (GOMP) support library"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/libgomp1-arm64-cross_14.2.0-19cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "4738d2ba144d678fa7ecbe3494e4ee18"
SRC_URI[deb0.sha1sum] = "53760621d9b4a19d61bcd8943e8825096d78fe97"
SRC_URI[deb0.sha256sum] = "6ef2c0825f2edd319d333fe6db721e1efa79bd595a5149c9f5a17af04dd40978"
SRC_URI[deb0.sha512sum] = "9b055baed3f1c31f9700ee3d9d1d4524d968e4dc70e3f4c74b341623e42393ba85d3ab274c61a549f0cf095c2ef800de95a5b51aadbc91d06cd0f3fa799b54d6"

RDEPENDS = " \
    gcc-14-cross-base \
    libc6-arm64-cross \
"

