# This was autogenerated! Do not modify
SUMMARY = "GCC Quad-Precision Math Library"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/libquadmath0-amd64-cross_14.2.0-19cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "5bc089047012f0d6d5637ab3bd386b98"
SRC_URI[deb0.sha1sum] = "ac464a7d326406117840a3e7d4aa19471e81f6de"
SRC_URI[deb0.sha256sum] = "daf07a61d4cc3c72107b80a43bbc373da3b73165fc0047bda224bf164746ddcd"
SRC_URI[deb0.sha512sum] = "21329f370343e486bc858f493047d740fffaaf9982130bd71a6e56a6c69361e66724bc310400c8093c34f16ac33580abcd8dd863a5be8a183260c9fa66943fa2"

RDEPENDS = " \
    gcc-14-cross-base \
    libc6 \
"

