# This was autogenerated! Do not modify
SUMMARY = "ThreadSanitizer -- a Valgrind-based detector of data races (runtime)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/libtsan2-arm64-cross_14.2.0-19cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "23c39dbb2c65abb8e58aef7cd778acb4"
SRC_URI[deb0.sha1sum] = "a7797880524830cbbbeaf1ad1739207be05bd8a9"
SRC_URI[deb0.sha256sum] = "a93d548f6a34d1afb6f1dda193fe841c0d6225363af55e6106f333986c906169"
SRC_URI[deb0.sha512sum] = "e33f19d477048367f8823b20d46b0a5ac8cf1ac7564f43cb4412129f7e655e2b6a8001514798b44eb18f1388aa9f822adce09ac0cc5cf7a366abd896aa28efb8"

RDEPENDS = " \
    gcc-14-cross-base \
    libc6-arm64-cross \
    libgcc-s1-arm64-cross \
"

