# This was autogenerated! Do not modify
SUMMARY = "UBSan -- undefined behaviour sanitizer (runtime)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/libubsan1-arm64-cross_14.2.0-19cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "7fa1858dc796ab3efd46854c775e752a"
SRC_URI[deb0.sha1sum] = "5f2bd0c6e54ac47b396718c56387a1ddfa1e598a"
SRC_URI[deb0.sha256sum] = "c9f76887373bf39380605cdbbbe2942f4a2ba434eb4aefdf3a573d9bed930ffb"
SRC_URI[deb0.sha512sum] = "b0c3ee949363df5b35cd94fbbfbc439e88a3b94a890cacbf4af2a4bccf53dff88d5493b3c615316b7da5c11f8d78917fa1ecc15933e5ef5c8af8951e9a34be15"

RDEPENDS = " \
    gcc-14-cross-base \
    libc6-arm64-cross \
    libgcc-s1-arm64-cross \
    libstdc++6-arm64-cross \
"

