# This was autogenerated! Do not modify
SUMMARY = "Library for serializing and deserializing Python Objects to and from JSON and XML."
DESCRIPTION = ""
SECTION = "misc"
SOURCE_PACKAGE = "python3-cyclonedx-lib"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/p/python3-cyclonedx-lib/python3-cyclonedx-lib_9.1.0_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "6fff213ba954c77c557ec8d48e9be762"
SRC_URI[deb0.sha1sum] = "ef9dcdfdf360d08d436790afd29726ffee60286f"
SRC_URI[deb0.sha256sum] = "7a58070ae493b731d87e64f8d98921d0d9c308453fd6b78050290f7be645c90d"

RDEPENDS = " \
    python3 \
    python3-license-expression \
    python3-packageurl \
    python3-py-serializable \
    python3-sortedcontainers \
"

