# This was autogenerated! Do not modify
SUMMARY = "Library of common utility API's used in elos and samconf (development)"
DESCRIPTION = "Library of common utility API's used in elos and samconf. \
 \
Development package."
SECTION = "libdevel"
SOURCE_PACKAGE = "safu"
HOMEPAGE = "https://github.com/Elektrobit/safu"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/safu/libsafu-dev_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "d6ac14c5a2885eff5dfe55dda5ccada2"
SRC_URI[deb0.sha1sum] = "8b3a05cac2a45d04e0071838084ce098d97a9189"
SRC_URI[deb0.sha256sum] = "69981b5a66b45edc5410d8a6ec369aa7ccbe36467c561bd22bcef8b42ad5af83"

RDEPENDS = " \
    libcmocka-mocks-dev \
    libmock-safu0 \
    libsafu0 \
"

