# This was autogenerated! Do not modify
SUMMARY = "Asynchronous event notification library (core)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libevent"
HOMEPAGE = "https://libevent.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libe/libevent/libevent-core-2.1-7t64_2.1.12-stable-10+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libe/libevent/libevent-core-2.1-7t64_2.1.12-stable-10+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "001733a6f373fb3187dc993916fb35ca"
SRC_URI[deb0.sha1sum] = "cadf2653bdcdd055754e7c0ff0d4130c81b382d2"
SRC_URI[deb0.sha256sum] = "1bc17a28932ce24d863ae39dfc1a975c5c83760bb67655d9e4dd3807c9b768e0"
SRC_URI[deb0.sha512sum] = "08b92525f0a86d802f57779ac3152f7e6604f6d543eadc25e5319af1dde830ee9632a755656efd5d2e0a94bad5f1bcf1081fd11a19708f09080c2a92c23b7842"
SRC_URI[deb1.md5sum] = "179dd142c1d750d48d89dbf9e884efd2"
SRC_URI[deb1.sha1sum] = "c4abdd42ccb8190c44861b2fc071c261a680758a"
SRC_URI[deb1.sha256sum] = "84a27a752d520df78bab24a499f66db21d5274803eb9a2e4d7f88554210f7dea"
SRC_URI[deb1.sha512sum] = "24e2f4fe6251da87f83a54b04baa93137b9f51d69beb6581cfb8308fa9acd4390512915f72470a5439ff1a7f26791f9ea8166d4457ff1a89e2348d28ddb97c18"

RDEPENDS = " \
    libc6 \
"

RPROVIDES = " \
    libevent-core-2.1-7 \
"
