# This was autogenerated! Do not modify
SUMMARY = "simple interprocess messaging system (library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "dbus"
HOMEPAGE = "https://dbus.freedesktop.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/dbus/libdbus-1-3_1.16.2-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/dbus/libdbus-1-3_1.16.2-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "686cab55ea673c13d19531883c4860eb"
SRC_URI[deb0.sha1sum] = "f3ec83ea1cd58fb9396676003591fa59708de382"
SRC_URI[deb0.sha256sum] = "bbcb711daff7e104b5f80f9b05475b6142674bfe65518a36a56e96a91068a3f5"
SRC_URI[deb0.sha512sum] = "0b2874c57c3223d9e9c4899d322a821a0b81485c71fa7abe929c4a9a10bf72db1770a74387136e2161efff907e6b4e9789b68c25da23f7d9576ab784c536de45"
SRC_URI[deb1.md5sum] = "8ed5572bfeb5703d6b118efd985a26c1"
SRC_URI[deb1.sha1sum] = "2c7bb2d71c41cf3b903b518058bd46a3a27f4263"
SRC_URI[deb1.sha256sum] = "ca6bb5f2047ad58d274cb7d14216035a07d8e5aae6f6a0122c4f6293c9c39515"
SRC_URI[deb1.sha512sum] = "acf896eba2bd4c446d30fa7c82fd0013336cc55dbf56d15e034b12c2f7e801ea7679093312d290015991dc8c47eed7fb1afdbc9ec6e70a4e6f1245a7098e0cc9"

RDEPENDS = " \
    libc6 \
    libsystemd0 \
"

