# This was autogenerated! Do not modify
SUMMARY = "high-productivity build system"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "meson"
HOMEPAGE = "https://mesonbuild.com"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/meson/meson_1.7.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "81cd12db2cf60f3906a0b8aed40d5d55"
SRC_URI[deb0.sha1sum] = "1c19891e27425581abe233e7a062270058b3856c"
SRC_URI[deb0.sha256sum] = "e92d04e60e784336883d537755d09b7dcb856809fa318a0931df3898e84ded95"
SRC_URI[deb0.sha512sum] = "ad4cd002cdb60ad0c5524fe3962ff3ee9a2f54882dfcc5ab2bbfa1012f26f4ec1b527bdc797041ddd83e0d3a4e8eabe260c7594e113914803049a28c4eabb2c8"

RDEPENDS = " \
    ninja-build \
    python3 \
    python3-setuptools \
"

