# This was autogenerated! Do not modify
SUMMARY = "Google's C++ test framework sources"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "googletest"
HOMEPAGE = "https://github.com/google/googletest"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/googletest/googletest_1.16.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "91d2a14dd3595762bd8264f03e87da77"
SRC_URI[deb0.sha1sum] = "308e32b8cdc9962375877df8878b7a7520a77c1e"
SRC_URI[deb0.sha256sum] = "61fa1c7592dd93ec88ba0e574ef4ca5bc33c4908ad4545ef4b987ead120fc847"
SRC_URI[deb0.sha512sum] = "b2d8a0c5ef0dda949641bc23a28bde3be11bb59ad1f9ea63f00fea1bc8390dc5640ecf0366817f1f9706c1e582bfffcd5e2d0eb96093f852e194a3c2f708b5f7"


