# This was autogenerated! Do not modify
SUMMARY = "Python package installer (pip wheel)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-pip"
HOMEPAGE = "https://pip.pypa.io/en/stable/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-pip/python3-pip-whl_25.1.1+dfsg-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "d83373bc7f86434172e785b4037bff8c"
SRC_URI[deb0.sha1sum] = "8cd5a0ebc9a7cb880ada1896d321192eca96e62f"
SRC_URI[deb0.sha256sum] = "e65351935aa4af2b10ae2abb5744f5059e9abad51aea6cd0cb825702010763f7"
SRC_URI[deb0.sha512sum] = "6bd4e97e4c3ce523878da8b68db0a4b9ea87c72b4b4442dfc6c379466bd1c5da019dc91b16f74f5b59b12fdaef4373ee3dcc75653e2a2505ec120751c310e5b1"

RDEPENDS = " \
    ca-certificates \
"

