# This was autogenerated! Do not modify
SUMMARY = "A purl aka. Package URL parser and builder"
DESCRIPTION = ""
SECTION = "misc"
SOURCE_PACKAGE = "python3-packageurl"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/p/python3-packageurl/python3-packageurl_0.16.0_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e0759876c7facea4c805cf2494bd76ea"
SRC_URI[deb0.sha1sum] = "c27de4778e84c91ed075354f35aee0bc7760b495"
SRC_URI[deb0.sha256sum] = "a4c5b9ef7e5fa7f0e8d7903efe527dd5b2d3d14f8267c45c278d015c6b114b7c"

RDEPENDS = " \
    python3 \
"

