# This was autogenerated! Do not modify
SUMMARY = "timeout context manager for asyncio programs in Python"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-async-timeout"
HOMEPAGE = "https://github.com/aio-libs/async_timeout/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-async-timeout/python3-async-timeout_5.0.1-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "85ca22cf6250fa95e28c99255a5d0e8c"
SRC_URI[deb0.sha1sum] = "14dd538dec5d65ed61b2af29018be8133cd555f2"
SRC_URI[deb0.sha256sum] = "502ded6fbff18c66ef1e5a8dff69b8e1dc8e61b4df9b496e396f20bb8928b6df"
SRC_URI[deb0.sha512sum] = "9cde72e243f09801c07d4e4be6d0ba08c1f3635e0617ba63a6bf3bf2aaa3ac6900d63c220e2c647e7fdac4ca7d242c62a72cae3a50f7d66c4be8cd4f9da84c7f"

RDEPENDS = " \
    python3 \
"

