# This was autogenerated! Do not modify
SUMMARY = "utility to set/show the host name or domain name"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "hostname"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/h/hostname/hostname_3.25_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/h/hostname/hostname_3.25_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "0a4d5601fc0b60d1654562db9bd4e08c"
SRC_URI[deb0.sha1sum] = "537c47a3d6cda3b7d09e534a3304b4c7501893c3"
SRC_URI[deb0.sha256sum] = "9c2a27e5d4d87137211fe46631b05b2ee8892ec76aae926304e4485ba02e1015"
SRC_URI[deb0.sha512sum] = "dadc6569db169e4b44eed2de6222684060002ff5eb743d37bba1f00866deabc9ee7f5a103c907de363438d5d7e52e31587d28c93bdb7065481e6c23db3e4efc9"
SRC_URI[deb1.md5sum] = "9db3ae22f641523145dfeee081f4698b"
SRC_URI[deb1.sha1sum] = "1ca9a8cc106f8b2e488655a2e5c741b92bf689f1"
SRC_URI[deb1.sha256sum] = "04d1ff24cb605788b59ed30d0052c1039c8bce2fb44c01c3c4b0c6edd4ea7ccc"
SRC_URI[deb1.sha512sum] = "812f25aedaf15112cbd28d1e0b5b18c755b257c011e6f142d9450cf4d91edc64a534279c3525a3eaeed0925e0ed7dc9b75f7ba9e60f3041cab94a739e5b3dd17"

RDEPENDS = " \
    libc6 \
"

