# This was autogenerated! Do not modify
SUMMARY = "Module to obtain filesystem disk space information"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libfilesys-df-perl"
HOMEPAGE = "https://metacpan.org/release/Filesys-Df"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libf/libfilesys-df-perl/libfilesys-df-perl_0.92-7+b4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libf/libfilesys-df-perl/libfilesys-df-perl_0.92-7+b4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "032f92d598e80e91930b3321a646be3c"
SRC_URI[deb0.sha1sum] = "2a8c37535f7ece25454c51e9359adc962fcea23e"
SRC_URI[deb0.sha256sum] = "9090a48bafa583628386eb8f36c9f1e3ad5fa14e96c1f4f104c1c7515887112e"
SRC_URI[deb0.sha512sum] = "693ac396eb4ae1067acb95dd248132ad3f1ed5c99bea5a90ef63a73abddb262596261be73ec8f34448c73f7d851c4cbf5fed4c49477055905f872e8a1a0c61ba"
SRC_URI[deb1.md5sum] = "6ca80d2ba9042e103113a156ee88b81e"
SRC_URI[deb1.sha1sum] = "0301848d12b18af2cf1dd5926bd1a14d7ce774eb"
SRC_URI[deb1.sha256sum] = "b05e736b64d24fa4184f18efde46f8a04c1847c5713f9e962fcdb0cfa87c255c"
SRC_URI[deb1.sha512sum] = "c6f44176aa62975777883e51bfdefa49a67b7dd534fd9efeb7a7ea2d1e4e051fe1be2808f69f1df147dae380ce76bcd2724e8d8c74d1d09c2905c39bfa915985"

RDEPENDS = " \
    libc6 \
    perl \
    perlapi-5.40.0 \
"

