# This was autogenerated! Do not modify
SUMMARY = "lightweight and flexible command-line JSON processor"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "jq"
HOMEPAGE = "https://jqlang.github.io/jq"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/j/jq/jq_1.7.1-6+deb13u2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/j/jq/jq_1.7.1-6+deb13u2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "44a3b34a3d1e34b941e347bf7c63bcc7"
SRC_URI[deb0.sha1sum] = "5556211154d1adb33a69780c9b9385f7cf79fda9"
SRC_URI[deb0.sha256sum] = "c6464bdc20086222fa9295481367e9a52f3fb78120a14089bae5f0d36f1b8a74"
SRC_URI[deb0.sha512sum] = "d518c9a5038e8ce2eed5aedb4e0bb7938cddafd5d6864bbd384d8fa81c5beb687f093b6fd2cbde52a6b9085f7801dcec42737bbe5706c14c2fcbe5bdb2d2da90"
SRC_URI[deb1.md5sum] = "2a927c0c2a7b730e9e80db000fc04f85"
SRC_URI[deb1.sha1sum] = "b323ed28cf6f1f1e1e1324108f154c419ee8d9ed"
SRC_URI[deb1.sha256sum] = "4b64a93ec70ec5639709843dbb3a8721849f84a22eb3b01dde42aec26c93e03b"
SRC_URI[deb1.sha512sum] = "8f6ff1baef380130f3d4144ca0e66a020bd445cfd4468043845d517e0b3627c9420081c063cb0389ca98e82f1fda8725345292f4b48d7ce15900eb4bed64664b"

RDEPENDS = " \
    libc6 \
    libjq1 \
"

