# This was autogenerated! Do not modify
SUMMARY = "TPM2 Software stack library - TSS and TCTI libraries"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "tpm2-tss"
HOMEPAGE = "https://github.com/tpm2-software/tpm2-tss"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tpm2-tss/libtss2-tcti-libtpms0t64_4.1.3-1.2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tpm2-tss/libtss2-tcti-libtpms0t64_4.1.3-1.2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "de2fbc377c25eb2427faab9eebda4440"
SRC_URI[deb0.sha1sum] = "94b0dbca527436d53cb920c7d92411f1f72d7c7a"
SRC_URI[deb0.sha256sum] = "f120a59a8850c187cc9183b239fa3c4c1f17d34150fbe52ce7403be9865ea232"
SRC_URI[deb0.sha512sum] = "46123b8b22268dcfb80e82c0a52d0bf4433fb4bc39f20e953d609b0219e92598377bcea3f5eb7e405da90d7a832732188b869932f01addc9b7cceeb3e2be4f63"
SRC_URI[deb1.md5sum] = "3373dcf227ee9ccf7a2b20cd82647f04"
SRC_URI[deb1.sha1sum] = "77ebdaa1939c3daf927fd12b9273232935e2e310"
SRC_URI[deb1.sha256sum] = "a1c749263eea62be38ec24f7791c6bc8aa26b0a061089651d52604011e2b297b"
SRC_URI[deb1.sha512sum] = "b800aa70a6695a3d14020f5bebbaefbc4a70a6b9dfc927701d41685a036234c4af9fc490ddf90a1823a7c7fd4fe2fd1bba8a9eb1127cef548ed3c376b11437fa"

RDEPENDS = " \
    libc6 \
    libtss2-mu-4.0.1-0t64 \
"

RPROVIDES = " \
    libtss2-tcti-libtpms0 \
"
