# This was autogenerated! Do not modify
SUMMARY = "TPM2 Software stack library - TSS and TCTI libraries"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "tpm2-tss"
HOMEPAGE = "https://github.com/tpm2-software/tpm2-tss"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tpm2-tss/libtss2-sys1t64_4.1.3-1.2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tpm2-tss/libtss2-sys1t64_4.1.3-1.2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b2ced39ee076c6a2031f95cc432e573c"
SRC_URI[deb0.sha1sum] = "8c2c2c57012a57bb9cab60138bcc4a3e04bab408"
SRC_URI[deb0.sha256sum] = "ffd806325106fb22cf479e65c6c74ef6c5db598a943dfd3b6a38b1edbdd55e99"
SRC_URI[deb0.sha512sum] = "5f340e3c42a533cced4c83de38be2645ed628aacfda1e1c05e021e0911dcd6b49619d388869f738b32ff1bdddb4929d5cd0695aa295fe5cb9241d3f17e708a6d"
SRC_URI[deb1.md5sum] = "682a4986c5078f54a8f5be646dc1feb6"
SRC_URI[deb1.sha1sum] = "3be3ee843220f318fc7c8372493d2732c202b85c"
SRC_URI[deb1.sha256sum] = "3a16f52bd797c577b96d9b9ffa2e4a004ae8f426cd14c1709b66d3ee282b1d50"
SRC_URI[deb1.sha512sum] = "e0d740a12eeb2294d6cb8d9c2fc86a474585e8f99e00c93c923dd91ac7b26f7f7efb768fc113110f85de7325482c4ad05ba06cdf076e96cdb11eeebcfab20a7d"

RDEPENDS = " \
    libc6 \
    libtss2-mu-4.0.1-0t64 \
    tpm-udev \
"

RPROVIDES = " \
    libtss2-sys1 \
"
