# This was autogenerated! Do not modify
SUMMARY = "device mounting library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "util-linux"
HOMEPAGE = "https://github.com/util-linux/util-linux"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/libmount1_2.41-5_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/libmount1_2.41-5_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d72fc0f5a34f1310c5faf55441cec855"
SRC_URI[deb0.sha1sum] = "a82622f9dbedc5d438d8791f4e3a59f6f9976d88"
SRC_URI[deb0.sha256sum] = "cd9efc7addd2556062f6d148b502e38a64e08c0ab220806219cfffd865f0f6f6"
SRC_URI[deb0.sha512sum] = "32d94931eaa0afff2d0a37837782d06fc232a5aa4ee9a2f85335d9b13add16335071ebf926e9729303a534d450213e3a483106f5742ca4cacd37576bac0d7641"
SRC_URI[deb1.md5sum] = "aea7b6f86e8b7e3a6c474b0e40b85d36"
SRC_URI[deb1.sha1sum] = "81aee071e0a7fff9504c0ec2cbf6acf665ebf0bb"
SRC_URI[deb1.sha256sum] = "2e791f8faf7bbbc94d354cf7b6c3728dc303b7aa327dfe7a2aa6954320977c8f"
SRC_URI[deb1.sha512sum] = "2f0f54e90a10b0e7428a0e7e6911618c17549d137609b4eccefd4c4c92cbe1cd7a362ea787f201bd97f2903f446d19a75a80cd350f7d79c77e60faad0b5539ad"

RDEPENDS = " \
    libblkid1 \
    libc6 \
    libselinux1 \
"

