# This was autogenerated! Do not modify
SUMMARY = "library that provides access to the DWARF debug information"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "elfutils"
HOMEPAGE = "https://sourceware.org/elfutils/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/elfutils/libdw1t64_0.192-4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/elfutils/libdw1t64_0.192-4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "dce1fbf1b92ecebdc46875e417966356"
SRC_URI[deb0.sha1sum] = "987981dc49c6d3e1747b0a66389277495221cc4c"
SRC_URI[deb0.sha256sum] = "6b41d3895b40eff429dd8013f0c13b6e26371a26491f414dbf66ba86c4c2c3f1"
SRC_URI[deb0.sha512sum] = "d98cc79d97177cd2745822e0e1fcccf5d31ce30fd585438729c6a57a09cf58d83ba7ea21c72f4d13a5437ee616f0453adeaf8aac41b0d5109ef44080b05ddf36"
SRC_URI[deb1.md5sum] = "806bdf3cab84b1ac63bc178b679fb249"
SRC_URI[deb1.sha1sum] = "a5479f1aaf123dc0861d769ad90a0f1cc3fdf62d"
SRC_URI[deb1.sha256sum] = "67efcbd99255a3468f6612a7719083ea1bed967d0bfae39863b5f0e190e0c5ec"
SRC_URI[deb1.sha512sum] = "7bcccb4152b267a1e6be43f137e57f31d401578bbb8ced758917a50d42df1450344e46e63d03b93bc6e2ea31b36262bb430dabdaf116295f7792c591a0b30ed5"

RDEPENDS = " \
    libbz2-1.0 \
    libc6 \
    libelf1t64 \
    liblzma5 \
    libzstd1 \
    zlib1g \
"

RPROVIDES = " \
    libdw1 \
"
