# This was autogenerated! Do not modify
SUMMARY = "jaraco contextlib extensions"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "jaraco.context"
HOMEPAGE = "https://github.com/jaraco/jaraco.context"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/j/jaraco.context/python3-jaraco.context_6.0.1-1+deb13u1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "68810a9349c09b93bbb6c5248800bf22"
SRC_URI[deb0.sha1sum] = "a3771cff5246256367688a76ca1defc0f55d226d"
SRC_URI[deb0.sha256sum] = "f909ec7b00dd96a1905322acba7cdd2df09747ceddeef6e426a97b33ab227f80"
SRC_URI[deb0.sha512sum] = "16b2a05c2dbe149ec1b7ee68b915599a060973387f733d3ede2aa31a296098c4e84fce7dd44c01d390715047c5f2a7b286b232691745b17e1b814c474b0990a9"

RDEPENDS = " \
    python3 \
    python3-setuptools \
"

