# This was autogenerated! Do not modify
SUMMARY = "FreeDesktop.org shared MIME database and spec"
DESCRIPTION = ""
SECTION = "misc"
SOURCE_PACKAGE = "shared-mime-info"
HOMEPAGE = "https://freedesktop.org/wiki/Software/shared-mime-info"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/shared-mime-info/shared-mime-info_2.4-5+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/shared-mime-info/shared-mime-info_2.4-5+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "eb14bdac3ec58b10fe4c8138deb484f2"
SRC_URI[deb0.sha1sum] = "ba07bd4663ae920f445c1f3d146a0756c293af02"
SRC_URI[deb0.sha256sum] = "d7d061df29326b0ca6b273ac9332168659ff1562659f0a33609657a143dd7881"
SRC_URI[deb0.sha512sum] = "011958e4cd90391f11d4957acef34b8edee71659ca2e79e540f7097454f20c3d9d179d540f5693461b7f09470e6388592c7a71bfe4ded14396ca5f943ea79551"
SRC_URI[deb1.md5sum] = "460cd921bf615715144741803f3c10ee"
SRC_URI[deb1.sha1sum] = "812cd7a2f5f17a321d513fc26af8dabe9469018a"
SRC_URI[deb1.sha256sum] = "a68086d0fdffc32fa05b1768f67b83d06344b026a855e29daa7ff02d64deec59"
SRC_URI[deb1.sha512sum] = "ab10922a63a285073fff7835e04403aee4d373c0338d39945d64c2c1cd0263d36711438dd73a697615dc50ea461518eef4fd7e7298db131dd6294569a44cf9fc"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libglib2.0-0t64 \
    libstdc++6 \
    libxml2 \
"

