# This was autogenerated! Do not modify
SUMMARY = "debug symbols for crinit"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/crinit-dbgsym_0.25.3_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "48693ab92077387fdf692fd73a9e92e6"
SRC_URI[deb0.sha1sum] = "da010aad68f08fd1fdc346e124cfaceb33bcc054"
SRC_URI[deb0.sha256sum] = "ef44621438a2ad22f5de6a93401d736c2cb608dc8f63d0afc21a02be41beb72f"

RDEPENDS = " \
    crinit \
"

