# This was autogenerated! Do not modify
SUMMARY = "utilities that use the proc file system"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "psmisc"
HOMEPAGE = "http://psmisc.sf.net/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/psmisc/psmisc_23.7-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/psmisc/psmisc_23.7-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8d4af9904d81c58b04deb9421f8a5a26"
SRC_URI[deb0.sha1sum] = "e3503756e8f55e59f66efde77227bb508aef4905"
SRC_URI[deb0.sha256sum] = "19e772bca5ad0b28620229fe4f91383044c5c6322c7c50ae46da1c60d73d9960"
SRC_URI[deb0.sha512sum] = "73c56e23e43c1180e86d81a2a9df5f0ac20ac4ade96aeffa2ad987a9fbf9f3cdf2c9e3d7ee3aa7145f2b45cb6b36bb8be89e9f796e7732b30d230cac50b7e585"
SRC_URI[deb1.md5sum] = "85d69a6f8b8bfa9aebb1308de34d8da6"
SRC_URI[deb1.sha1sum] = "f4f9ed44290e345f79be3e6250576d58944da89d"
SRC_URI[deb1.sha256sum] = "9ebae564434a8fb5f23b770b5810e9e9c887cde32c23498f340db353a629c993"
SRC_URI[deb1.sha512sum] = "fca380b1e160bd49eb98bb7618adfeef96ec713179c5f676a82045e3c62a2c2b7739119ef5e834a7482111d4017d697352f50a79e5cff680da50c3e177a58852"

RDEPENDS = " \
    libc6 \
    libtinfo6 \
"

