# This was autogenerated! Do not modify
SUMMARY = "code coverage tool for Python 3"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-coverage"
HOMEPAGE = "https://coverage.readthedocs.io/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-coverage/python3-coverage_7.6.0+dfsg1-2+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-coverage/python3-coverage_7.6.0+dfsg1-2+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "aabab670cfea08b468ace219772427fe"
SRC_URI[deb0.sha1sum] = "200a08d1576ccf395cce0aec16d60f6f593f4ade"
SRC_URI[deb0.sha256sum] = "f23328ab99e3694d0df5ceb38fa5957bb0f694fb4e6ea92772ae7fdb7c3894f7"
SRC_URI[deb0.sha512sum] = "eb70bbe6ad0b08cabffcdd8705edd579b0a6ed8010b488f6728a2e052fb93c2f56e98feeacfbf4994e1d8eccf005a1c5db1f58e3e57483709ce6e9ff430c37a2"
SRC_URI[deb1.md5sum] = "96cdfba0358ccdf7416fe990b42526b7"
SRC_URI[deb1.sha1sum] = "48b344ef1b23a019f4bf6efbb28e44e764fa9844"
SRC_URI[deb1.sha256sum] = "3cae30865e19523b45613882ceb6649bd97299427e648029c49d16226d13869e"
SRC_URI[deb1.sha512sum] = "7c4ebd82d27b43e2b7aafc88495d7d9b9eb16f53928784695d4d630b1d46289976cb0a3968a3c346861001395282b00b46d7a0082b6c3de4457e518ae62f03f3"

RDEPENDS = " \
    libc6 \
    python3 \
    python3.13 \
"

