# This was autogenerated! Do not modify
SUMMARY = "Data-Driven/Decorated Tests - Python 3.x"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-ddt"
HOMEPAGE = "https://pypi.python.org/pypi/ddt"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-ddt/python3-ddt_1.7.2-4_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "4b565d994795716bdfd6c9c67ebfc94a"
SRC_URI[deb0.sha1sum] = "3d68b5bc667d415c592c316e0fb7d806b2800187"
SRC_URI[deb0.sha256sum] = "ea1118f67af3b66ce29cc555f691af5b0c4272a950d65a279278f1e814e9c955"
SRC_URI[deb0.sha512sum] = "6645b737c1fa0ee637d47edc590b268d5eef3d0838fe969d19d8496237e0d6234ee1edacedb611a3ba89517985c5dbf5216c773b955d49c1f518a3eae1d550a3"

RDEPENDS = " \
    python3 \
"

