# This was autogenerated! Do not modify
SUMMARY = "Secure Sockets Layer toolkit - development files"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "openssl"
HOMEPAGE = "https://openssl-library.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/openssl/libssl-dev_3.5.6-1~deb13u2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/openssl/libssl-dev_3.5.6-1~deb13u2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "30860ae7f82b46b682b6e6f32d08a3ce"
SRC_URI[deb0.sha1sum] = "ed4549f189f5faa3929d51268c16419c2ee87616"
SRC_URI[deb0.sha256sum] = "04250d9e51fc87ef6d539f36cf0b66668dd34beec101af56dc35198ea99cef00"
SRC_URI[deb0.sha512sum] = "86af9b4fabb728cb3f9e47c1dabcf76074ef5fdd395ac2d6ffd822db69120a0f7d92bab0568e563e9b16edb3d5f236b233341b35918ab73ac88cea190a2f2100"
SRC_URI[deb1.md5sum] = "b7d53047e53ec91d88bbe36910657e60"
SRC_URI[deb1.sha1sum] = "e00e42b454c6acfd3a11622bc8aca25e8b4a232b"
SRC_URI[deb1.sha256sum] = "afdd9c57261502a3a434ba606ddfd1e8fd0f288c663f2dc4f7570ce927867651"
SRC_URI[deb1.sha512sum] = "4f0e2d5075333d582a87672e9565c0b9cd310d44fe7bb2db89fceaa290ab648619d95a98059cd22a58d32d75aa43557ca13c2fa8de3327ed8962fed776a11b53"

RDEPENDS = " \
    libssl3t64 \
"

