# This was autogenerated! Do not modify
SUMMARY = "C version of reader, parser and emitter for ruamel.yaml"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "ruamel.yaml.clib"
HOMEPAGE = "https://sourceforge.net/p/ruamel-yaml-clib"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/ruamel.yaml.clib/python3-ruamel.yaml.clib_0.2.12+ds-1+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/ruamel.yaml.clib/python3-ruamel.yaml.clib_0.2.12+ds-1+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "01e1b45de38d87d86a677767465a7b5e"
SRC_URI[deb0.sha1sum] = "5914bab1735e184c28d2e9f49ac625bb02f34b5a"
SRC_URI[deb0.sha256sum] = "f7a0eac4734f4f4f5d6aa3f3986831171abbcc0dffe3b623e6a39bd09675768f"
SRC_URI[deb0.sha512sum] = "61fb7fd74936d71bfcf9dc79551afe4d0c7db93138113575509c2104a8170dd39bddb7266c4df21e16ba18424790f17df04af062bad6ce47c904351332d50018"
SRC_URI[deb1.md5sum] = "e293a89612247011a2ba0c25cd98eaa0"
SRC_URI[deb1.sha1sum] = "7557c4d02903388a640122c788c4922e91669a75"
SRC_URI[deb1.sha256sum] = "0263c166304ec575210ec641b9a080898ccc1cdb422299cf481d6c17e84576de"
SRC_URI[deb1.sha512sum] = "f2e03d96230bcd39578d26fc2cd8b778d19abac4e2820e6c2b40022d77e7ca38c493c57e78724609f34bb729367109913a5a949b42df4da754f10a0415ee2120"

RDEPENDS = " \
    libc6 \
    python3 \
"

