# This was autogenerated! Do not modify
SUMMARY = "OpenJade group's SGML parsing tools"
DESCRIPTION = ""
SECTION = "text"
SOURCE_PACKAGE = "opensp"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/opensp/opensp_1.5.2-15.2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/opensp/opensp_1.5.2-15.2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e0dd9467c81b02fc6ff1979260e757af"
SRC_URI[deb0.sha1sum] = "4d5cb82c6c10b849074e29b3b3e01ac4378de32b"
SRC_URI[deb0.sha256sum] = "28a70c12674090082a0c7e59d3548e531bfbb69deac9c566c5e170f8116d587e"
SRC_URI[deb0.sha512sum] = "310721129b48f84573455a30e88bf113d14fb7cef4e3a2bcb76f6a0f4b6999519b682790b7d05999cb546b6682a877b7dfce5e384359ea565f6af10672ae635b"
SRC_URI[deb1.md5sum] = "41618b52fa23e630e197a0ce936bf1b5"
SRC_URI[deb1.sha1sum] = "104ee0840c923f42186f8d3d0b3fa922a02ed1a6"
SRC_URI[deb1.sha256sum] = "a732d0c2e44a6570ec40acda7774563b4535feae192c4e8857fe3bcb9848fb80"
SRC_URI[deb1.sha512sum] = "812d619c6c2edfa8ef03c38430bef1e10558c1b371b994f5bf1bdd9543a692832dc6e39dffb21b112eb238f5b46fe74485ecd3024dd5a12c2b0f5da4d422fc94"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libosp5 \
    libstdc++6 \
    sgml-base \
"

