# This was autogenerated! Do not modify
SUMMARY = "fast lexical analyzer generator"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "flex"
HOMEPAGE = "https://github.com/westes/flex"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/flex/flex_2.6.4-8.2+b4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/flex/flex_2.6.4-8.2+b4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "52853b92287366809b8783ea43ce45d0"
SRC_URI[deb0.sha1sum] = "1c4cd7a846dc581c994a12572e1c121f742faae4"
SRC_URI[deb0.sha256sum] = "75f963765232c356d0a2fb70e780dfa9de2425aca036ec60eefb7fc98a2c905b"
SRC_URI[deb0.sha512sum] = "15c1071dc4159502a38e9babe3468cb9b5b293e83d5cd7b12b6ca2824c9d98b58d62774a914c1df46c6259a23ba6bf300ceae694b6775096b0b9e6c1b50f9b1c"
SRC_URI[deb1.md5sum] = "1a95d6945b72d6b84aed43399a3318ff"
SRC_URI[deb1.sha1sum] = "3b24c420882a0647d044c50a0e787fd69a8cc619"
SRC_URI[deb1.sha256sum] = "2b5f5aa509bc12ef82cc42b854704ff538efabea9824b49ed53418f1eba43d51"
SRC_URI[deb1.sha512sum] = "b8b5438621b501183b7d9b248069579491cf681580063ce28d482e40bbfd773f2e83ea320c3f8aed983886b69e061dfeee1ee97897d5e1c882986eb997b18e45"

RDEPENDS = " \
    debconf \
    libc6 \
    m4 \
"

