# This was autogenerated! Do not modify
SUMMARY = "easy-to-use client-side URL transfer library (OpenSSL flavour)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "curl"
HOMEPAGE = "https://curl.se/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/curl/libcurl4t64_8.14.1-2+deb13u4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/curl/libcurl4t64_8.14.1-2+deb13u4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1ce441ba039d03e1f68100922946691b"
SRC_URI[deb0.sha1sum] = "4a4f00f2bb5053fd158d5e3f2866d12c46079ced"
SRC_URI[deb0.sha256sum] = "9a28a1f9cd78e2ff07c436e78a76bc114d491404dbe3a836a83e385d496ab4f2"
SRC_URI[deb0.sha512sum] = "2bfea79880500c2518f01dc0c016b64a6ddc8b9d870731e53425e52c34b00936456ef4100f67abcbe022260f12458771e6604a35fcdefcdb598b8c186d882c74"
SRC_URI[deb1.md5sum] = "fee169d2a02b583a845195c9b0cf5715"
SRC_URI[deb1.sha1sum] = "783fb234e1cd9c53d1cf5f04774b20ed89b7ab8c"
SRC_URI[deb1.sha256sum] = "2723a9f4fa2569439d3d0734054b027414eeb2291c7ed001362f8b5e42035083"
SRC_URI[deb1.sha512sum] = "c82185e137209a44ea3421d3a2104287f2826413bcc1a754796326dbfbdfe2b9c0badd22e00ec01ef7ef99fc0237a60391f302bc833f88ab309f4f11063301de"

RDEPENDS = " \
    libbrotli1 \
    libc6 \
    libgssapi-krb5-2 \
    libidn2-0 \
    libldap2 \
    libnghttp2-14 \
    libnghttp3-9 \
    libpsl5t64 \
    librtmp1 \
    libssh2-1t64 \
    libssl3t64 \
    libzstd1 \
    zlib1g \
"

RPROVIDES = " \
    libcurl4 \
"
