# This was autogenerated! Do not modify
SUMMARY = "Git Large File Support"
DESCRIPTION = ""
SECTION = "vcs"
SOURCE_PACKAGE = "git-lfs"
HOMEPAGE = "https://git-lfs.github.com/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/git-lfs/git-lfs_3.6.1-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/git-lfs/git-lfs_3.6.1-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "099fd158521c19ef6878b59ad5411d59"
SRC_URI[deb0.sha1sum] = "9336dcdeab14d160ff3579f18d52cebdda204c84"
SRC_URI[deb0.sha256sum] = "fcb3e7a6c042e70fc541d05b163c88fffd3364d509c961e83dec881e7cda5bca"
SRC_URI[deb0.sha512sum] = "d105e47a06d6e4297278b0f8483b397be54bf49ff096ce5a9182b27ab64709ccca82efaef1eef7cbab5984c7ae79e199f836f45c30ea775332de40a14d1742e4"
SRC_URI[deb1.md5sum] = "e1b138454ad97ac3495cf8586b19c627"
SRC_URI[deb1.sha1sum] = "b6dd0410641e61b175f0bd0dedc0a228be38d688"
SRC_URI[deb1.sha256sum] = "22f42a579bb7f17354b8b7f0361953a2f9d742e50cb7c5b9e8badddbaaeaee2d"
SRC_URI[deb1.sha512sum] = "ce71f02eae990aa622f78ab73476fa1b714c203081c4f1a27b6d8c2e2946b450eb1a660b1abc59b9cfc077ff02bf96047e3d2b4074e0886e2e0cfc20fa157896"

RDEPENDS = " \
    git \
    libc6 \
"

