# This was autogenerated! Do not modify
SUMMARY = "version compatibility baseline for Perl OpenSSL packages"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "perl-openssl-defaults"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/perl-openssl-defaults/perl-openssl-defaults_7+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/perl-openssl-defaults/perl-openssl-defaults_7+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "2caef042ae1130238f60a1a6eee2d9b8"
SRC_URI[deb0.sha1sum] = "7b1b69fd9946da11979384ca1d75fbf28206c8a0"
SRC_URI[deb0.sha256sum] = "e1d601fe96d5465a90042b49921b2086347a2e2111705972ba415ce9f9f3a871"
SRC_URI[deb0.sha512sum] = "41fe7b4c03562a540ad23ce9c81122e451a92e567a2fdb2a3444f171e63b94479e02ce787ae18eac3cef620f55486635aa130263c7bf25bec54c575ba75c430c"
SRC_URI[deb1.md5sum] = "bf7421e520dc5183678fd9e22d78536a"
SRC_URI[deb1.sha1sum] = "fd31303c5abd1b9a072aaf8be8f2302e0e651133"
SRC_URI[deb1.sha256sum] = "1fa2d99f1f7d32147cd5935eb2700ac49b366c086fea21c963c73e6dc62d62b1"
SRC_URI[deb1.sha512sum] = "43586bfd2a546633016b2a8e5eb5decbd60bb59a0432036d5cf90591f37e4e1ba5341b97828c8a25b0a535824a64eb8d7c0a8a82ef6eb6dfd6dab3ddde2f7785"

RDEPENDS = " \
    libc6 \
    libssl3t64 \
"

RPROVIDES = " \
    dh-sequence-perl-openssl \
    perl-openssl-abi-3 \
"
