# This was autogenerated! Do not modify
SUMMARY = "Perl module for argument type classification"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libparams-classify-perl"
HOMEPAGE = "https://metacpan.org/release/Params-Classify"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libparams-classify-perl/libparams-classify-perl_0.015-2+b4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libparams-classify-perl/libparams-classify-perl_0.015-2+b4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "40234920b9b05b7533da1f7c024aae71"
SRC_URI[deb0.sha1sum] = "42f47726ca619498a48aa3e67699637a75ef02aa"
SRC_URI[deb0.sha256sum] = "81e4cd06ca1d23b5f22778feb90a6de03aa98c6ba66e752c74c290a08dfddbb6"
SRC_URI[deb0.sha512sum] = "cbe52d4c0c1631dc937d9e7376425059c578a576680d1c488d4316611d67a934f2ecccbe9068646ac1cef303a25e026ca4c40d3b3eed6f5bd1e123ebf3f36612"
SRC_URI[deb1.md5sum] = "cacdaa9002648a705f488fed1e6a8e31"
SRC_URI[deb1.sha1sum] = "18d2c7aab0fdaabe39643e43cbc92c32ad1f6f85"
SRC_URI[deb1.sha256sum] = "68e3c7db369ab4837dafee937a6e6309c6faeb09c943a349100fee243570a87e"
SRC_URI[deb1.sha512sum] = "f097c207fb166668cb673c61d8b160b1cda3e828823915b645eece8b44b728fab371e47d42aab685ebd9d4e9a88c7426f4bc96f0d87ab9dcdb4af0d0465ab4d2"

RDEPENDS = " \
    libc6 \
    libdevel-callchecker-perl \
    perl \
    perlapi-5.40.0 \
"

