# This was autogenerated! Do not modify
SUMMARY = "terminal-related programs and man pages"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "ncurses"
HOMEPAGE = "https://invisible-island.net/ncurses/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/ncurses/ncurses-bin_6.5+20250216-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/ncurses/ncurses-bin_6.5+20250216-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "abb1cdc444e16d7a575bac5a9f57caeb"
SRC_URI[deb0.sha1sum] = "c448da94739cdf78f6c3b52184d844d1985dbf71"
SRC_URI[deb0.sha256sum] = "40a525f4761e9ed4b8adcd1783cb9a6467ff8008215ae99b3597825bdefc61e4"
SRC_URI[deb0.sha512sum] = "7247a97f613225def0812674ca9e3ed9f6cd6ca5022d094a83bc4bbd149ad950752e1c78f99d109aafed03336ed1ddf5c8a9d1a357bf4f989fc0b711f9671f13"
SRC_URI[deb1.md5sum] = "32a9f31177ee494de787f37e365056bc"
SRC_URI[deb1.sha1sum] = "1e8ab4cecbf17ba57e7b8ba82ae9f07f466bdb6c"
SRC_URI[deb1.sha256sum] = "7ac6919efb0effc9004caae758811bfe85bb486a057262822468e90d73d38458"
SRC_URI[deb1.sha512sum] = "eace724e798a760903c25461543afa55409a0be5a7dc176bebf08bd87383c0fa6dfb1d5bbed17768bc9eed8b50d81b42b8a29e1b9443254f84882f771b48762e"

RDEPENDS = " \
    libc6 \
    libtinfo6 \
"

