# This was autogenerated! Do not modify
SUMMARY = "module that allows you to declare real exception classes in Perl"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libexception-class-perl"
HOMEPAGE = "https://metacpan.org/release/Exception-Class"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libe/libexception-class-perl/libexception-class-perl_1.45-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "09a590234f461170a7e9aa338fef70fc"
SRC_URI[deb0.sha1sum] = "fbb4c081c5fead4d8850662c72d3086b0ac930b9"
SRC_URI[deb0.sha256sum] = "2a334645983bfadc0522651c6d86999ebb9b37cf10588ef5b6631c40e045bd1c"
SRC_URI[deb0.sha512sum] = "938165cc722eca8fd5cd0cb9db0f36fe08bc704de76b24ade5026b33dfb194ba7c2bca6fb9181b2e9cc44fd93fdd573422620a71c58dd2c6a3dcd6aff5fb2add"

RDEPENDS = " \
    libclass-data-inheritable-perl \
    libdevel-stacktrace-perl \
    perl \
"

