# This was autogenerated! Do not modify
SUMMARY = "SAX-based renderer library for SVG files (runtime)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "librsvg"
HOMEPAGE = "https://wiki.gnome.org/Projects/LibRsvg"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libr/librsvg/librsvg2-2_2.60.0+dfsg-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libr/librsvg/librsvg2-2_2.60.0+dfsg-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "dd667b7425a84c7d85de4ffe995232bf"
SRC_URI[deb0.sha1sum] = "59a7cfc1624ac57bf5a722b259523cbedc492ba1"
SRC_URI[deb0.sha256sum] = "81fd7a825f06e344dc42fb7af92577ec242b6d24237b8a0bf79ea203a7f377c9"
SRC_URI[deb0.sha512sum] = "37e60f09fc95141651637386aedcb0d3b46008f7dddae550f0fbc9273410b580d749c6652f37305f96b6768520f8133a2dcf65c32447715a2c57fa4ecf5cd1e4"
SRC_URI[deb1.md5sum] = "fa2f7b0599ff177bf76ab0008683c64a"
SRC_URI[deb1.sha1sum] = "117fa35e37b9707d0d6d9b8786400eee15cf0b88"
SRC_URI[deb1.sha256sum] = "901ba3daba9f7d634680b02e6359e2218fb9929b6eb216ca592efd7cb2b43f06"
SRC_URI[deb1.sha512sum] = "676aad9ff22e2810aeb68a80c4daeb343dce199cc16f33c74d9924fcf686eddc28c92d06cbe543ce64b58e3664bfd3a858075ce44a6b2ff3a36f680c5a550d85"

RDEPENDS = " \
    libc6 \
    libcairo-gobject2 \
    libcairo2 \
    libdav1d7 \
    libgcc-s1 \
    libgdk-pixbuf-2.0-0 \
    libglib2.0-0t64 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libxml2 \
"

