# This was autogenerated! Do not modify
SUMMARY = "GNU C++ compiler for x86_64-linux-gnu architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-14"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "amd64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/g++-14-x86-64-linux-gnu_14.2.0-19_amd64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "1c4594673a37b71eef6efd8d0875a27c"
SRC_URI[deb0.sha1sum] = "9a5f16d514fa20032b674b0e0fb2a55e5b077603"
SRC_URI[deb0.sha256sum] = "c66b009fedd340520279d1af2f91d0668e9f64f0c08fe62179ca1c75e556be58"
SRC_URI[deb0.sha512sum] = "0e8ce85fa09a18430f292c86f898ecf8c113d793d6058cf0c35b6d079aaaa2bef003c7e51f5fc4815de9efe931ba7f60da2d8dec2b5cca95a2f829a58afb67cb"

RDEPENDS = " \
    gcc-14-base \
    gcc-14-x86-64-linux-gnu \
    libc6 \
    libgmp10 \
    libisl23 \
    libmpc3 \
    libmpfr6 \
    libstdc++-14-dev \
    libzstd1 \
    zlib1g \
"

RPROVIDES = " \
    c++-compiler-x86-64-linux-gnu \
"
