# This was autogenerated! Do not modify
SUMMARY = "OpenWrt micro bus architecture"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "ubus"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/u/ubus/ubus_20250807_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e00057133284d25d145342e7f15485a4"
SRC_URI[deb0.sha1sum] = "4916bfb20d20941217fb851a39e0e3497ada61d2"
SRC_URI[deb0.sha256sum] = "823f0ed163523bf50097dd42a99c401c9031c105d70729b43dc030fac44a74f8"

RDEPENDS = " \
    libblobmsg-json1 \
    libc6 \
    libubox1 \
    libubus1 \
"

