# This was autogenerated! Do not modify
SUMMARY = "set of advanced DWARF utilities - transitional package"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "dwarves"
HOMEPAGE = "https://git.kernel.org/pub/scm/devel/pahole/pahole.git"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/dwarves/dwarves_1.30-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "3c3d182acc1118f494d581292d130362"
SRC_URI[deb0.sha1sum] = "8be5c28c0259e5f70bff0ec91da7918a7cd9bdee"
SRC_URI[deb0.sha256sum] = "638cbdb560d3d07c6e1335a0441dd1c38ef02f77658603ad18324b2ccb50f53a"
SRC_URI[deb0.sha512sum] = "148afb8d8fa6cc10a300762fc5fc043d6dd4d18ba09a478a5f7953f4376350dd64ad83983509dc15113128c0178909e5d60a4af92439d1f3b67e9fc245fdc0af"

RDEPENDS = " \
    pahole \
"

