# This was autogenerated! Do not modify
SUMMARY = "system interface for user-level packet capture"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libpcap"
HOMEPAGE = "https://www.tcpdump.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libpcap/libpcap0.8t64_1.10.5-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libpcap/libpcap0.8t64_1.10.5-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "be1a228c5222c9352f4decaf726b5ac8"
SRC_URI[deb0.sha1sum] = "ed8292cf5eac639b41964374e2554e85d087b88d"
SRC_URI[deb0.sha256sum] = "6a756d536a5b0cd3ef92f19ff9f22ed80c66baadbc0fe55d599f4aa0c27d3f86"
SRC_URI[deb0.sha512sum] = "3c0f3c8c2353391d6751698e809844dbd137f21c70f38039f2516f3d7bb672d8b9980ca281a7c4108007d8cca7085526c784efdd994bf721d673198ec7131228"
SRC_URI[deb1.md5sum] = "fd2b28d3a7d339036429bc4fb7f0fe92"
SRC_URI[deb1.sha1sum] = "055b2516b47585e4ee9cf2d9dc24e66fbaa791cc"
SRC_URI[deb1.sha256sum] = "9db27b0ebf0333ea8524feac225d39db283235bb408eee90cb59d426d5a422a5"
SRC_URI[deb1.sha512sum] = "7cdc6216e07165196b1d2f8a9f1d6fcc0140ca2a8adcedd90eb57991960d66182ef75849c84e80429953a7664f197d2d5e9f0eadd2553d111c9d621e5bcaab56"

RDEPENDS = " \
    libc6 \
    libdbus-1-3 \
"

RPROVIDES = " \
    libpcap0.8 \
"
