# This was autogenerated! Do not modify
SUMMARY = "FFmpeg library containing media filters - runtime files"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "ffmpeg"
HOMEPAGE = "https://ffmpeg.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/ffmpeg/libavfilter10_7.1.5-0+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/ffmpeg/libavfilter10_7.1.5-0+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4c24b396fcf176243bbc8f38da6b46f5"
SRC_URI[deb0.sha1sum] = "ec55b7ed08a0fb908e8736d89e75542bb36b5748"
SRC_URI[deb0.sha256sum] = "55015c70802ac95c8e14d7cba5f6051c649bd8d2dd4971312b754378edff5867"
SRC_URI[deb0.sha512sum] = "7ad031d87b25d228b92e5b78fbee83636a2138a816e0aaed4c75bebda7e15d9f938612950a677f48ca293e6fe21dcff401adff622e88dc28df83fd5433be19f4"
SRC_URI[deb1.md5sum] = "ebfabcd1fa1bd7b94d8bfe51ba672dc2"
SRC_URI[deb1.sha1sum] = "39c77629b8de85765aa2dae86051002fbe6d36f0"
SRC_URI[deb1.sha256sum] = "42d9544cf6082b231906a3bd0d5f9dc5c3b0bdc049b61a219b659319c66ed2e3"
SRC_URI[deb1.sha512sum] = "1d488465967d62fa5045d89ad65c21439e5727d728be2f8545dc30398d808519771770529adac3b9d3141171084f8e71b8949b4988c562d1221d098b60c3787c"

RDEPENDS = " \
    libass9 \
    libavcodec61 \
    libavformat61 \
    libavutil59 \
    libbs2b0 \
    libc6 \
    libflite1 \
    libfontconfig1 \
    libfreetype6 \
    libfribidi0 \
    libharfbuzz0b \
    liblilv-0-0 \
    libmysofa1 \
    libplacebo349 \
    libpocketsphinx3 \
    libpostproc58 \
    librubberband2 \
    libsphinxbase3t64 \
    libstdc++6 \
    libswresample5 \
    libswscale8 \
    libva2 \
    libvidstab1.1 \
    libzimg2 \
    libzmq5 \
    ocl-icd-libopencl1 \
    zlib1g \
"
RDEPENDS:append:amd64 = " \
    libvpl2 \
"

