# This was autogenerated! Do not modify
SUMMARY = "FFmpeg library with de/encoders for audio/video codecs - runtime files"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "ffmpeg"
HOMEPAGE = "https://ffmpeg.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/ffmpeg/libavcodec61_7.1.5-0+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/ffmpeg/libavcodec61_7.1.5-0+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "f7c9dfe5730e4990ab2d25f562c5f751"
SRC_URI[deb0.sha1sum] = "92c9861814a154ba603666a0143bb86cceb8f6ad"
SRC_URI[deb0.sha256sum] = "6c07da16b276827973463bdd22607721df1c2877641c753d2418cf6bf49a0f2e"
SRC_URI[deb0.sha512sum] = "c92c0a1abf493cc65af8df56cad06b7463722f17010060531f2924c30f127657b14267297518ba545070d60ed3d4ef66509ce337cafe87faffcf634b34fdceb0"
SRC_URI[deb1.md5sum] = "bb526d34f2ad5727561067fa98ddd9c0"
SRC_URI[deb1.sha1sum] = "a4c5aac95f6033fc1084e8e5660314d8ffa4c98c"
SRC_URI[deb1.sha256sum] = "dca58c157a2a0434b4c371b14b52f7922625147453b3d3cc165a2bb08157b31d"
SRC_URI[deb1.sha512sum] = "201f4202da2e4984e67076d0273e91d78bafda1e3653a8a0c6b980fe19511667f7d3210e747a937ce6323cde109009d88ac5d70fba4bc2809cd6253fca34f258"

RDEPENDS = " \
    libaom3 \
    libavutil59 \
    libc6 \
    libcairo2 \
    libcodec2-1.2 \
    libdav1d7 \
    libglib2.0-0t64 \
    libgsm1 \
    libjxl0.11 \
    liblzma5 \
    libmp3lame0 \
    libopenjp2-7 \
    libopus0 \
    librav1e0.7 \
    librsvg2-2 \
    libshine3 \
    libsnappy1v5 \
    libspeex1 \
    libsvtav1enc2 \
    libswresample5 \
    libtheoradec1 \
    libtheoraenc1 \
    libtwolame0 \
    libva2 \
    libvorbis0a \
    libvorbisenc2 \
    libvpx9 \
    libwebp7 \
    libwebpmux3 \
    libx264-164 \
    libx265-215 \
    libxvidcore4 \
    libzvbi0t64 \
    zlib1g \
"
RDEPENDS:append:amd64 = " \
    libvpl2 \
"

