# This was autogenerated! Do not modify
SUMMARY = "FFmpeg library for audio resampling, rematrixing etc. - runtime files"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "ffmpeg"
HOMEPAGE = "https://ffmpeg.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/ffmpeg/libswresample5_7.1.5-0+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/ffmpeg/libswresample5_7.1.5-0+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "11ad22ef87bc735f03c40762733622b6"
SRC_URI[deb0.sha1sum] = "3d083929ba664cbe6423d0a8268346db1be2247c"
SRC_URI[deb0.sha256sum] = "abe0f2f6a27db64a0d2d344e333880be997b2ec5431fc187a100078075680d94"
SRC_URI[deb0.sha512sum] = "c7cf2be9921434ee51dfebdd6a1925c724ea54da509a4f98defdf48b1abde2e9b3716cec29210ed94f9a92267758811067b98ee9a7a1b446ed7ae3e33ad641c7"
SRC_URI[deb1.md5sum] = "990f394cb028eda8297b93d264506fdc"
SRC_URI[deb1.sha1sum] = "35fd66f9a0731478b6200f32a502c5108d913ae8"
SRC_URI[deb1.sha256sum] = "ab19f630592925e70e9f8d6e12fc53d756d292d28d4f6154f1c3e393c3a87aa3"
SRC_URI[deb1.sha512sum] = "1946e32ceafe2171476521feb05b97c867e3ceda93c2fbdae0621142a28a7de244933563338edad277f9011dcd0623bdaa58a5045f1f9c50a7a5edff4bb3156e"

RDEPENDS = " \
    libavutil59 \
    libc6 \
    libsoxr0 \
"

