# This was autogenerated! Do not modify
SUMMARY = "A library used by many OpenWrt projects"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libubox"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/libu/libubox/libjson-script1_20250807_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a5f6a3aff3ebd41ea8ae791a8a5fa8dc"
SRC_URI[deb0.sha1sum] = "87e087df04bb7ffa56a5f5296473b168557a369f"
SRC_URI[deb0.sha256sum] = "c5c17929cd95114ee9323b08000812a3ecf8e42d47ebedb30190196ee2dd39c0"

RDEPENDS = " \
    libc6 \
    libubox1 \
"

