# This was autogenerated! Do not modify
SUMMARY = "asynchronous name resolver"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "c-ares"
HOMEPAGE = "https://c-ares.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/c-ares/libcares2_1.34.5-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/c-ares/libcares2_1.34.5-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8903a84cac9be97a92a558c84ea54067"
SRC_URI[deb0.sha1sum] = "82c30b2adc94d31141729fd7aa7a86d6f72218dd"
SRC_URI[deb0.sha256sum] = "5034a2c34ea4730797df1a5f6a0ec142d7d09ce6923c06e167f08ad2e69a4218"
SRC_URI[deb0.sha512sum] = "d2a823051e8dc24f8c7fd1d8164eff74b4cd07737ed83c6e850c387f109d03fc348804689706588d628b8777298ecced511476aa120ff826612b7cdb061762a4"
SRC_URI[deb1.md5sum] = "efdd5d599c130728c3e5ede0b7613b24"
SRC_URI[deb1.sha1sum] = "9036c93525155b41b8c5e9266a643a9af9fedb57"
SRC_URI[deb1.sha256sum] = "138f3224f7ee18555bdcd20424b7d9de723095f8eca8379e6722ad070c4dd089"
SRC_URI[deb1.sha512sum] = "6e564a11730fd0441b8c3c075527f01ab0520f51cacc0cc1b1d22eb81e3c205573f27e46a5de375e84294b39295c4640097d86ec5f1e85c623ee46940e87dc3b"

RDEPENDS = " \
    libc6 \
"

RPROVIDES = " \
    libc-ares2 \
"
