# This was autogenerated! Do not modify
SUMMARY = "SELinux runtime shared libraries"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libselinux"
HOMEPAGE = "https://github.com/SELinuxProject"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libselinux/libselinux1_3.8.1-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libselinux/libselinux1_3.8.1-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "6f70ae12d588cad7039e43c24449cc13"
SRC_URI[deb0.sha1sum] = "44b247687c034c8a4142204f0827f7286614b354"
SRC_URI[deb0.sha256sum] = "68bb8d32bd8d6d7d2f5952a169db03d1484b46ae1e52abccdec42a19dccea5d5"
SRC_URI[deb0.sha512sum] = "73e2967dbd16a8fd65b553345bed2c618854baaeada2042363595ab1028936d363c8243f4e3497283d813ba83c6432801aa95e2f4600c049b6ed28a9776f2855"
SRC_URI[deb1.md5sum] = "1d49e99295c51fafc01829ddb97b433b"
SRC_URI[deb1.sha1sum] = "fb4a4673feba6e9418143e9bf3f43743f94bb494"
SRC_URI[deb1.sha256sum] = "fc13da4c7783b8f4361d92ef1045931f298d1b0ac78ed1a85c2232615f49fc6f"
SRC_URI[deb1.sha512sum] = "6d293368cee662c456663895e8b2f5648749c804f5ae53c3329934f783adfd4acb8006c6ca814e1aef465439fb36aca14a052f82fb808a048dac6323418d005b"

RDEPENDS = " \
    libc6 \
    libpcre2-8-0 \
"

