# This was autogenerated! Do not modify
SUMMARY = "Compiler cache for fast recompilation of C/C++ code"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "ccache"
HOMEPAGE = "https://ccache.dev"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/ccache/ccache_4.11.2-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/ccache/ccache_4.11.2-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "a41bd779dd12810158cfdae7a38c88cf"
SRC_URI[deb0.sha1sum] = "27fb6df6373f318425fde156a6f75dd81c564175"
SRC_URI[deb0.sha256sum] = "08a3f49741c54a78325a85bfdce125e30026d697874b1bb37328916c47106506"
SRC_URI[deb0.sha512sum] = "57493103fb1c5698c1fe8944168e10b72fabefd2d00aa74cba74ee6cba5423484d955599c152fb70943cfc54841b86c936f90690397f5c483b47bda686cc5e89"
SRC_URI[deb1.md5sum] = "9280bce02f82a5697e50e0f336a494ae"
SRC_URI[deb1.sha1sum] = "64274df3b729280f48dc2cb9278fa85d46cfd731"
SRC_URI[deb1.sha256sum] = "668adcf17218750ebebe6e6ce071a660628f5a6a60fcf86900bec9424f17a8a8"
SRC_URI[deb1.sha512sum] = "ded22f1108d6f2897542f017445d60d5da7010ca7278245868ee01fbee4288bd685875b867aa60f34a18b524060037d4f450046cdc43f9db9bbb89adfde9250f"

RDEPENDS = " \
    libc6 \
    libfmt10 \
    libgcc-s1 \
    libhiredis1.1.0 \
    libstdc++6 \
    libxxhash0 \
    libzstd1 \
"

