# This was autogenerated! Do not modify
SUMMARY = "AddressSanitizer -- a fast memory error detector"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gcc-14"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libasan8_14.2.0-19_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libasan8_14.2.0-19_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "562d7783317980e9c8e8390e848635f0"
SRC_URI[deb0.sha1sum] = "859f439847b6c17ded21ad8499c8e5e45d0a4f52"
SRC_URI[deb0.sha256sum] = "771899ade7310fe31aa538a509354c33d62bbe4e408b4e5fc1e513988dc42645"
SRC_URI[deb0.sha512sum] = "1bb0e692dc86e9d92464cf23efe6fc867736ddc4a51c14bd782a7b91b7abe68f978ec087a245205d0f282b272394f8af3eceada440096fb68b34b7121e192781"
SRC_URI[deb1.md5sum] = "4e8000e70b521893dd64e07945c547c7"
SRC_URI[deb1.sha1sum] = "6534a610e7eafec20b3e63681fd92e5ac490e689"
SRC_URI[deb1.sha256sum] = "5621bd583a3390b45726a8eebe23601f7fad86a25193e5349976cbf17e2bc9ad"
SRC_URI[deb1.sha512sum] = "52e3fe90410ed89ddac08cdc94982201becf5b7c3aaad22bc719ae49ea24ef2ed875cde54ae591f52affce4d0b9de7538957cda3afb13e375c4fa9236d51e9b0"

RDEPENDS = " \
    gcc-14-base \
    libc6 \
    libgcc-s1 \
"

