# This was autogenerated! Do not modify
SUMMARY = "GCC cc1 plugin for GDB"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gcc-14"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libcc1-0_14.2.0-19_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libcc1-0_14.2.0-19_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4ebf8aac056b24e0843b48b1afa96e96"
SRC_URI[deb0.sha1sum] = "1b039a35c6e9d3202f2226ecafd4ba19cce90b4e"
SRC_URI[deb0.sha256sum] = "2d587e3bfba4aec701946b7ba0c1640b97b6d8dd0a34ba1c70ae85261ecedefa"
SRC_URI[deb0.sha512sum] = "fd4fc1548d871d42a8f8d6f3fcd25e0fd2071c41b3d97c14500df63649cc8729b27919471594b7f5891515bee3a933de58a36e51c7a7eb66bb02e0acdcaa27d7"
SRC_URI[deb1.md5sum] = "4a19fcb29672f0e41ca88df80d9fb9af"
SRC_URI[deb1.sha1sum] = "4553c914ec8aad388c71cc4310baacbe7ba7c871"
SRC_URI[deb1.sha256sum] = "f5e390b5fd65432b820afa403a61ab4d6286948fc07ca3aacb4d230a81f5c9a5"
SRC_URI[deb1.sha512sum] = "f6b2c54d7eeede587c689b033a7a397eba3441d12c1eec4610478ecb8d27885ac7ff1bc822653433bd165af938f0b946363a547624b87c630a56a764417dadf6"

RDEPENDS = " \
    gcc-14-base \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
"

