# This was autogenerated! Do not modify
SUMMARY = "ThreadSanitizer -- a Valgrind-based detector of data races (runtime)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gcc-14"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libtsan2_14.2.0-19_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14/libtsan2_14.2.0-19_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1d0da369861896521af8a6844d0eaa64"
SRC_URI[deb0.sha1sum] = "519e4ffbb01aeefa404f227fcf2577e1185d80aa"
SRC_URI[deb0.sha256sum] = "529d7f68227d16975076c5f842e8b687faea1b5df8e0dcf62e436d5402844ca5"
SRC_URI[deb0.sha512sum] = "9a02f270207669ccac62e1d4a50cf5878b47e1d57c67dd652ad7f337701c6bb1af64fefc9404aa72cb959d4b6ded965706cc258d21cadb0acf271f478b4cc03d"
SRC_URI[deb1.md5sum] = "f70ade74245a6673ed51533a5923bca3"
SRC_URI[deb1.sha1sum] = "1a8825162faa757c6c786376bdf827ba908b8a77"
SRC_URI[deb1.sha256sum] = "c767c05f3dade13b5780478366029f2ff32e44bea852c6a4d7a1f93f1363d3e3"
SRC_URI[deb1.sha512sum] = "0c15942a8eb3eb6e555f9db4d7c49552281cfb46b6d2467937e0148701840f4d4446916d6aaa345373ced1e9ada3f027913699a40078336df72e84ecd2ac6e51"

RDEPENDS = " \
    gcc-14-base \
    libc6 \
    libgcc-s1 \
"

