# This was autogenerated! Do not modify
SUMMARY = "X.509 and CMS support library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libksba"
HOMEPAGE = "https://www.gnupg.org/related_software/libksba/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libk/libksba/libksba8_1.6.7-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libk/libksba/libksba8_1.6.7-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c3c403d168dc06715353eea1d3604f0c"
SRC_URI[deb0.sha1sum] = "fb91920ae8646fcd3a27eb871f624280d6d344d9"
SRC_URI[deb0.sha256sum] = "45bc1bfaf41a5e1136b1c1f58c495a950888da33a617de24202f3568e45b9572"
SRC_URI[deb0.sha512sum] = "39424f6085daa954c5fa571fe3cfc34b00f47a69666d1740d3f8d913b38f27e3ecd587763fe659ae3d12d0239e94bffb8ebf25a6c1c4bd9659d2dd04b0595d13"
SRC_URI[deb1.md5sum] = "0d4af5bfbe38f0e3def309f7eb8f2f17"
SRC_URI[deb1.sha1sum] = "03c27be1fc71dcf82e617a31de1dbc70f09ae2d1"
SRC_URI[deb1.sha256sum] = "ee001c93cf2a5e495e1885fac2d7ec1474bd619539f0f33a0b326ac511e04297"
SRC_URI[deb1.sha512sum] = "1f06ff8d5e07176fa6538131b1df4ce1da4be6ffea4778057a7bae39316fc38bb82c2b003dbfe18a344ac691ddb40609762425e39de53c4b99a4bf9762ba03c2"

RDEPENDS = " \
    libc6 \
    libgpg-error0 \
"

