# This was autogenerated! Do not modify
SUMMARY = "Markdown for C"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "md4c"
HOMEPAGE = "https://github.com/mity/md4c"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/md4c/libmd4c0_0.5.2-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/md4c/libmd4c0_0.5.2-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "caeae92239c7bf29f11944557c6eb5f2"
SRC_URI[deb0.sha1sum] = "903f7a4603c22b7d8f8bd65ccde91c09a73eef6e"
SRC_URI[deb0.sha256sum] = "0bd88d7ce2bda0626836267c02beb1ddf89e99eae26bd5c717ce5601faa075a9"
SRC_URI[deb0.sha512sum] = "57ef2a083d2122abce062381a9f699c107ebc3f1d7f3630c521b5825069f95d69d389ec2e804319d102730ae1a9153f7f674f2750182bd610a6ef75e22a00418"
SRC_URI[deb1.md5sum] = "4915dcd3c932b7dc3fe9357b277c73d2"
SRC_URI[deb1.sha1sum] = "8c859f981994dbd233310ddec359cf9d9ca6d44c"
SRC_URI[deb1.sha256sum] = "fbeaf1abceacb4b081355e16deb7c41e23df719754b10525c35320d808050bda"
SRC_URI[deb1.sha512sum] = "a72602df1008adc9f60dac016086ac9d03b5605d9a7d8f35ff93c2c7dcc175714a9fcfb0c9c2e588d1d3875b8fc77cab8a4df3c5f54a34386473f377ae3936c1"

RDEPENDS = " \
    libc6 \
"

