# This was autogenerated! Do not modify
SUMMARY = "Python 3.x module to query metadata from packages"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-pkginfo"
HOMEPAGE = "https://pythonhosted.org/pkginfo/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-pkginfo/python3-pkginfo_1.12.1.2-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f7e917353e3425e903fe22793c1dd740"
SRC_URI[deb0.sha1sum] = "e5972abe0f52c6158f74938b7e96790e20ec21ca"
SRC_URI[deb0.sha256sum] = "3038bee57c0b753d7f754c83c9e9661fc9b211c6bb547ab17bdb577ff4e442e5"
SRC_URI[deb0.sha512sum] = "8a731c2c0e6898852b686612320749ebee342945f7a9ad2ee2b338c7f28288f6da056c41b74ef0c3536f41f56b50c9caa3a6cb351846771296d0dcc861574fbb"

RDEPENDS = " \
    python3 \
"

