# This was autogenerated! Do not modify
SUMMARY = "produces graph of changes introduced by a diff file"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "diffstat"
HOMEPAGE = "https://invisible-island.net/diffstat/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/diffstat/diffstat_1.67-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/diffstat/diffstat_1.67-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1643d7c9cc30db4a4fc387eed198484f"
SRC_URI[deb0.sha1sum] = "090893eb7bcdc067d6f1685ee8490535e300281a"
SRC_URI[deb0.sha256sum] = "3512554268a33d370768e6c3ca91ddff7b5d96efc706192f330eb749d30257a9"
SRC_URI[deb0.sha512sum] = "ee1b72aaba43a3f7238caf3b7f44fd92bebc34dd446b2a36e441cbafa22063a66f85bb7218e82f8ebffcfe1ea2d012d0927c185db8e69cf97ff1118063ffa183"
SRC_URI[deb1.md5sum] = "5a36d4994834e4fab4aae5812bcb80bb"
SRC_URI[deb1.sha1sum] = "ea2b8e0ed1685864f5132d6e91ddc0285b6399bb"
SRC_URI[deb1.sha256sum] = "2c82754fe9a75d5f332d0cb581cb48ed723d83430e4c6b2fd0524e923cbcd2e7"
SRC_URI[deb1.sha512sum] = "3d8469eeb6b9cbcb89f7460c9cd29a792208a007bcc54bb8b7a9c835f68f18f224133358299b517d88424295b5bac6a87fadb70429d87bfe1451a28dc890e2c4"

RDEPENDS = " \
    libc6 \
"

