# This was autogenerated! Do not modify
SUMMARY = "List of standard media types and their usual file extension"
DESCRIPTION = ""
SECTION = "net"
SOURCE_PACKAGE = "media-types"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/media-types/media-types_13.0.0_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "3d78beccf2775d0b95c2fbd174ab20d8"
SRC_URI[deb0.sha1sum] = "ede2c5c9f1526d5a0f1d05b438bf9cdc942d2711"
SRC_URI[deb0.sha256sum] = "0788e4b0b72db1bcf74a19cb24c3511e7770ad0b341f0f30e361701c3072f53e"
SRC_URI[deb0.sha512sum] = "e39868afa648dc3483f970222ef6b9b3d2fc94ebb73b9091581cc06c4107f088a7066eb1d6db6a610003e196768d7781c8188c47631594764b7839f50779935b"


