# This was autogenerated! Do not modify
SUMMARY = "Python binding for SELinux Policy Analyses"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "selinux-python"
HOMEPAGE = "https://selinuxproject.org"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/selinux-python/python3-sepolicy_3.8.1-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "37d51611f0a054eb9a88b617deaceca3"
SRC_URI[deb0.sha1sum] = "fbf6514a569a93f0cd6d08b9db150256556b87d6"
SRC_URI[deb0.sha256sum] = "05ed0cccd1856d6dbfa00c4812bd493a92b66239e090163401ce475f6c94093c"
SRC_URI[deb0.sha512sum] = "01e08df023087c160669fa2310d5c04ef362bcd669952139f07c367b2e582c16588d1b1810148e470ebda04b20268704874617ae07411f2ba7d07d6912bf459e"

RDEPENDS = " \
    python3 \
    python3-selinux \
    python3-sepolgen \
    python3-setools \
"

