# This was autogenerated! Do not modify
SUMMARY = "library for SSA/ASS subtitles rendering"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libass"
HOMEPAGE = "https://github.com/libass/libass"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/liba/libass/libass9_0.17.3-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/liba/libass/libass9_0.17.3-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "35161f9ec04b85ef2ce795f9b5f90910"
SRC_URI[deb0.sha1sum] = "239ef17d1815d19dbd61ab3214b081d4c0f1fb99"
SRC_URI[deb0.sha256sum] = "000faddfaa19c7c1631f2d71a9cd1982cd3a88611967debe631440a1c64617b4"
SRC_URI[deb0.sha512sum] = "258a2d762722f8741b656641c9929bf02a868f3b87351c061288e4cfbdc01b9db98c788ecbcebf4369878d68675cfd17ec76a8550784ec6e7738dc4f2d29c35d"
SRC_URI[deb1.md5sum] = "3f5c568b0a183f45008da07f309b930c"
SRC_URI[deb1.sha1sum] = "fd7c00bf808de37d4aa84d6aecd6e9c590791919"
SRC_URI[deb1.sha256sum] = "849fbb86d5fa8b3cac38b80ff577ff3d1f85e6fdcb95313db4639593069843e2"
SRC_URI[deb1.sha512sum] = "f6958aee23aa0107a4eae765e12b20fab087f0d8d16cd7ed0254ed19019b5d7452dd3c29e8755937cdbeaba3d91948b2a5b01f61cb5ff72b22aa4c15ab711b87"

RDEPENDS = " \
    libc6 \
    libfontconfig1 \
    libfreetype6 \
    libfribidi0 \
    libharfbuzz0b \
    libunibreak6 \
"

