# This was autogenerated! Do not modify
SUMMARY = "LLVM OpenMP runtime - Documentation"
DESCRIPTION = "The runtime is the part of the OpenMP implementation that your code is \
linked against, and that manages the multiple threads in an OpenMP program \
while it is executing. \
 \
This package contains the documentation of this package."
SECTION = "doc"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libomp-20-doc_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a7695f435b878df6fccf9203993df24d"
SRC_URI[deb0.sha1sum] = "b20c9337e8cf5107586cc391cd535893b1b0c15e"
SRC_URI[deb0.sha256sum] = "474c4e3b903db3982fbf399ef619fb63251c857ff1a804f86238a10b68d9ac97"
SRC_URI[deb0.sha512sum] = "9d568f89bc313635a4498806cd0c9635bd7721b073d5715d0fed12e461ce8f17582b4bf52329b4b56e1faedb4a4abba4e372bcd5fc825489ec321e86e2297a77"

RDEPENDS = " \
    libjs-jquery \
"

