# This was autogenerated! Do not modify
SUMMARY = "X11 font rasterisation library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxfont"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxfont/libxfont2_2.0.6-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxfont/libxfont2_2.0.6-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b140ed254ea5551d8fb5765c2de66900"
SRC_URI[deb0.sha1sum] = "49ffbfdd4dc45ec83dd6619cb23632060fdaf7fb"
SRC_URI[deb0.sha256sum] = "79a7f56e4a0c7b1defa706c7b1f3076f7d80aaeea9de253b2a87406253319681"
SRC_URI[deb0.sha512sum] = "ff26bf98699e7bf62d188d3d0ace8b668668d416f9555d0cdaae8c113d8bf301b5bdf81dfa14c4b47189202aff4327bde4a96c2f339556b1d283fabe2c38b0e7"
SRC_URI[deb1.md5sum] = "1c2d88d85985386bf6d7999afdef9502"
SRC_URI[deb1.sha1sum] = "e34e80066bb64196cc614d0fe652fa75f48138ae"
SRC_URI[deb1.sha256sum] = "bd15438e61e968518e26f5f4a2523329f16e066652395db915d8b941bf71b5ba"
SRC_URI[deb1.sha512sum] = "6d4525d4724418d5f03257e8f42c0656fb8f96012903dad6905c4a0a66cbfe0f1b77f617368c1fe6ddf27437e0b4be8191704d4c6eb109a67b4207990a01ee9f"

RDEPENDS = " \
    libbz2-1.0 \
    libc6 \
    libfontenc1 \
    libfreetype6 \
    zlib1g \
"

