# This was autogenerated! Do not modify
SUMMARY = "X11 Inter-Client Exchange library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libice"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libi/libice/libice6_1.1.1-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libi/libice/libice6_1.1.1-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4505f32fea598b20a8cb5adadd0c49f3"
SRC_URI[deb0.sha1sum] = "c3e3ab098862b22a80f4bf418660ec448e0085dd"
SRC_URI[deb0.sha256sum] = "38185997162793b5dfb768644badc57852879784a2f9d83c6c4e47efa5e36698"
SRC_URI[deb0.sha512sum] = "e2c70c57570955cc87bbe20dd3ae83b00aa81b862bd5bd35048110badd861baf31d3c6a23ecc8923358e5dd84f96b7013eb7f4864a46277584da8ec61bcce33a"
SRC_URI[deb1.md5sum] = "67af7e4607f27e926359a9a347785cc1"
SRC_URI[deb1.sha1sum] = "2c32ba01093f5bd889f96d3a0902566b6c033bfb"
SRC_URI[deb1.sha256sum] = "048874f2296660a5e925844635f4d050cb054e7d3459cb15b4c30afb113fbecb"
SRC_URI[deb1.sha512sum] = "3e7ec44f9650be63c4b7c023ffab71fb76b441b28f445659a3a8fae6157eac03770c0f13eba0391c9403126aaf52a01ef5b7d7fc87bff3338d1fdd4b064a54ab"

RDEPENDS = " \
    libc6 \
    x11-common \
"

