# This was autogenerated! Do not modify
SUMMARY = "GNU dbm database routines (runtime version) "
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gdbm"
HOMEPAGE = "https://gnu.org/software/gdbm"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gdbm/libgdbm6t64_1.24-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gdbm/libgdbm6t64_1.24-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "0159295388a840d6859ad88d119872ad"
SRC_URI[deb0.sha1sum] = "8212065c80c91a05839e26821dc65088f4ffe67d"
SRC_URI[deb0.sha256sum] = "e7b42c68c391e278733adb3c1efdacd24d660862bd7bac0efbc10a91e5696dfc"
SRC_URI[deb0.sha512sum] = "bd244d4550bddac57d96dbad1099b01206101d32b02302d38000b3f676d6af8fdee02051f5d2072f44b4c7c1c8b0f2950e0bede793f006031a5ad10203ea6c97"
SRC_URI[deb1.md5sum] = "e56de47bb1f185f41a1894cb53085aae"
SRC_URI[deb1.sha1sum] = "1d369e7e2a3081183ce152aff0a703ab06f2b3cd"
SRC_URI[deb1.sha256sum] = "329efe726e24a413b9933e298ce24d255973ec111eea0ca721157968fd24156a"
SRC_URI[deb1.sha512sum] = "a65f84ebd08ca28224b442dcc70c51ec6e761378f2a7e73e010d0b5df62c71d89a4c6f414bc65b2bcc29bd17c5ef94ce9cfddc5394158f73c0d62aeefdfb45cd"

RDEPENDS = " \
    libc6 \
"

RPROVIDES = " \
    libgdbm6 \
"
