# This was autogenerated! Do not modify
SUMMARY = "GNU dbm database routines (legacy support runtime version) "
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gdbm"
HOMEPAGE = "https://gnu.org/software/gdbm"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gdbm/libgdbm-compat4t64_1.24-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gdbm/libgdbm-compat4t64_1.24-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "cc53af617261680fa9ed2d4931697837"
SRC_URI[deb0.sha1sum] = "99eade0456a55035ce891d7f85cb620b0dcd7871"
SRC_URI[deb0.sha256sum] = "2cbd43cf2dfbf57ff48188b5d79d29cf7ea8f0dedaa61ab0bcc02eceff50ea01"
SRC_URI[deb0.sha512sum] = "055e8bbb9f73c9d7856e4ab567137944337b5bd13fa0a0acd70181a2effd91868699cce7518cdac660dcfcc3097753278b91af1a95f18929c8835a095f94810c"
SRC_URI[deb1.md5sum] = "fe7bfb01f23565b679a60eb42bedbe40"
SRC_URI[deb1.sha1sum] = "39c76c3aa584fb3475cef7b78c982a0617cc53a8"
SRC_URI[deb1.sha256sum] = "266b9a9e8d1ecc4393ebd29bec7e7c0fe1505b1d8755033af9e15df161316627"
SRC_URI[deb1.sha512sum] = "abeee43018de150be72e321fd47ff70be0942612141426bd4a5cf9b0ab66ede6252773d7546321f25c1486efde0c34b3144ec38cc19a98125bd0cf60a2f0cebf"

RDEPENDS = " \
    libc6 \
    libgdbm6t64 \
"

RPROVIDES = " \
    libgdbm-compat4 \
"
