# This was autogenerated! Do not modify
SUMMARY = "Perl module to create accessors to class data"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libclass-data-inheritable-perl"
HOMEPAGE = "https://metacpan.org/release/Class-Data-Inheritable"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libc/libclass-data-inheritable-perl/libclass-data-inheritable-perl_0.10-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "db156304da2a9d15ed8a5e69fe1a5ca1"
SRC_URI[deb0.sha1sum] = "2124154a44a429b14b8c63896588531a2806a028"
SRC_URI[deb0.sha256sum] = "363776352e02e2a4423997d1f03a815194bf69c391fb5d460e3327f244d0b635"
SRC_URI[deb0.sha512sum] = "bd17f27099d02d1ebda939609227fbc7ddecbffddf93e680e888823770c4d8ad0b1860a4d0c13f1133ba9551326f666c0b7c3f93cc9b7d235717d2fe439161dc"

RDEPENDS = " \
    perl \
"

