# This was autogenerated! Do not modify
SUMMARY = "debug symbols for elos-plugin-backend-dlt"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "elos"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elos-plugin-backend-dlt-dbgsym_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "22e7d85d693da18ff4cee1e242e1d7e0"
SRC_URI[deb0.sha1sum] = "2f68e830d51e4460c0b456cecff5174965681be2"
SRC_URI[deb0.sha256sum] = "4a119aafc69c29e75e660b6583ffa0f81d92c792c9b82b82268fb4d0988ea58f"

RDEPENDS = " \
    elos-plugin-backend-dlt \
"

