# This was autogenerated! Do not modify
SUMMARY = "debug symbols for elos-plugin-client-dummy"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "elos"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elos-plugin-client-dummy-dbgsym_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0bb2e406cae644f09c08f8f7910a46f4"
SRC_URI[deb0.sha1sum] = "a646239443de8b0c79e52a6ec6b61cfd76c186d3"
SRC_URI[deb0.sha256sum] = "5129bc2c2a3cf1f3afe4c214ec3c62751d18f01b78f659d6832ff26d536227f7"

RDEPENDS = " \
    elos-plugin-client-dummy \
"

