# This was autogenerated! Do not modify
SUMMARY = "debug symbols for elosc"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "elos"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elosc-dbgsym_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "fd3c9d9acdffa7236d8cdc63bda76b21"
SRC_URI[deb0.sha1sum] = "75679491e5141a64ab940d26f43adc1154526135"
SRC_URI[deb0.sha256sum] = "a0b4044027719b7874bef96321e8860fd38e4c16ab50030822fb3b0309bfba3e"

RDEPENDS = " \
    elosc \
"

