# This was autogenerated! Do not modify
SUMMARY = "debug symbols for libelosplugin1"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "elos"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/libelosplugin1-dbgsym_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "1be96bca81f826bdbb50c95c7a755517"
SRC_URI[deb0.sha1sum] = "43025154d6be3e8000a0a09e5b7768cb93f67f87"
SRC_URI[deb0.sha256sum] = "b25368a163324be5766795a3c7fea6fa03841793dbcbe22c89e1d74960155df2"

RDEPENDS = " \
    libelosplugin1 \
"

