# Copyright 2026 Elektrobit. All rights reserved.

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ebclfsa-public-images"
BBFILE_PATTERN_meta-ebclfsa-public-images = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ebclfsa-public-images = "7"

LAYERDEPENDS_meta-ebclfsa-public-images = "meta-ebclfsa-public"
LAYERSERIES_COMPAT_meta-ebclfsa-public-images = "v0.6"

# Additional feature content
EBCLFSA_FASTDEV_FEATURES_CONTENT ?= ""
EBCLFSA_LIVM_FEATURES_CONTENT ?= ""
EBCLFSA_HIVM_FEATURES_CONTENT ?= ""
EBCLFSA_FASTDEV_FEATURE_SDK_CONTENT ?= ""
EBCLFSA_LIVM_FEATURE_SDK_CONTENT ?= ""
EBCLFSA_HIVM_FEATURE_SDK_CONTENT ?= ""

# Partition growth settings for different rootfs types in Megabytes
EBCLFSA_FASTDEV_FEATURES_ROOTFS_PARTITION_GROWTH_MB ?= ""
EBCLFSA_FASTDEV_FEATURES_DATA_PARTITION_GROWTH_MB ?= ""
EBCLFSA_LIVM_FEATURES_ROOTFS_PARTITION_GROWTH_MB ?= ""
EBCLFSA_LIVM_FEATURES_DATA_PARTITION_GROWTH_MB ?= ""
EBCLFSA_HIVM_FEATURES_ROOTFS_PARTITION_GROWTH_MB ?= ""
EBCLFSA_HIVM_FEATURES_DATA_PARTITION_GROWTH_MB ?= ""

# Baseline rootfs sizes for different rootfs types in Megabytes
EBCLFSA_FASTDEV_BASELINE_ROOTFS_SIZE_MB ??= "2048"
EBCLFSA_FASTDEV_BASELINE_DATA_PARTITION_SIZE_MB ??= "100"
EBCLFSA_LIVM_BASELINE_ROOTFS_SIZE_MB ??= "756"
EBCLFSA_LIVM_BASELINE_DATA_PARTITION_SIZE_MB ??= "100"
EBCLFSA_HIVM_BASELINE_ROOTFS_SIZE_MB ??= "756"
EBCLFSA_HIVM_BASELINE_DATA_PARTITION_SIZE_MB ??= "100"

# The following expressions will get evaluated, once EBCLFSA_*_*_PARTITION_SIZE_MB are needed.
# This ensures that the rootfs/data partition size is calculated dynamically based on the baseline size and any additional growth specified.
# The used ebclfsa_partition_size function is defined as part of the ebclfsa_image class.
EBCLFSA_FASTDEV_ROOTFS_PARTITION_SIZE_MB ??= "${@ebclfsa_partition_size(d.getVar('EBCLFSA_FASTDEV_BASELINE_ROOTFS_SIZE_MB'), d.getVar('EBCLFSA_FASTDEV_FEATURES_ROOTFS_PARTITION_GROWTH_MB'))}"
EBCLFSA_FASTDEV_DATA_PARTITION_SIZE_MB ??= "${@ebclfsa_partition_size(d.getVar('EBCLFSA_FASTDEV_BASELINE_DATA_PARTITION_SIZE_MB'), d.getVar('EBCLFSA_FASTDEV_FEATURES_DATA_PARTITION_GROWTH_MB'))}"
EBCLFSA_LIVM_ROOTFS_PARTITION_SIZE_MB ??= "${@ebclfsa_partition_size(d.getVar('EBCLFSA_LIVM_BASELINE_ROOTFS_SIZE_MB'), d.getVar('EBCLFSA_LIVM_FEATURES_ROOTFS_PARTITION_GROWTH_MB'))}"
EBCLFSA_LIVM_DATA_PARTITION_SIZE_MB ??= "${@ebclfsa_partition_size(d.getVar('EBCLFSA_LIVM_BASELINE_DATA_PARTITION_SIZE_MB'), d.getVar('EBCLFSA_LIVM_FEATURES_DATA_PARTITION_GROWTH_MB'))}"
EBCLFSA_HIVM_ROOTFS_PARTITION_SIZE_MB ??= "${@ebclfsa_partition_size(d.getVar('EBCLFSA_HIVM_BASELINE_ROOTFS_SIZE_MB'), d.getVar('EBCLFSA_HIVM_FEATURES_ROOTFS_PARTITION_GROWTH_MB'))}"
EBCLFSA_HIVM_DATA_PARTITION_SIZE_MB ??= "${@ebclfsa_partition_size(d.getVar('EBCLFSA_HIVM_BASELINE_DATA_PARTITION_SIZE_MB'), d.getVar('EBCLFSA_HIVM_FEATURES_DATA_PARTITION_GROWTH_MB'))}"
