# This was autogenerated! Do not modify
SUMMARY = "Cairo 2D vector graphics library (GObject library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "cairo"
HOMEPAGE = "https://cairographics.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cairo/libcairo-gobject2_1.18.4-1+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cairo/libcairo-gobject2_1.18.4-1+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "3940f873974dfcad021f31442a80f9b2"
SRC_URI[deb0.sha1sum] = "36c3a8310926123fe4f0ba6a597d508033894c48"
SRC_URI[deb0.sha256sum] = "4fcd432ebe8f93599bd05426f304e2f70409aad271fc6b4b3a2c6243c99c377c"
SRC_URI[deb0.sha512sum] = "20d709e96dc8d2f2bf268b6810a694d16b4b1551fcefe75adf0f5d7bad2e79478f2700f5be8cff6826324ef1dfe0af3e15a15bd4cf6e5dcfa2adf29e16b519c6"
SRC_URI[deb1.md5sum] = "00d6e035deb0b900ee8cd2b9b6d3a9e0"
SRC_URI[deb1.sha1sum] = "faf948b97717d318c22d441c5a22c465f0fab65b"
SRC_URI[deb1.sha256sum] = "470185fcc3aa8e3fea4e0108bc842ce9179918da44d4d0cf7d67598d3470fd1a"
SRC_URI[deb1.sha512sum] = "aa53747992b576d97db8ab65f3bffe58e4916188b157686dd673b7c99aac45bdbef467d17d85bcbf6326cd6ea1826f739bea7581c5c6f09772c1f05515005428"

RDEPENDS = " \
    libcairo2 \
    libglib2.0-0t64 \
"

