# This was autogenerated! Do not modify
SUMMARY = "cip Linux kernel headers for 6.12.94-cip26-ebclfsa"
DESCRIPTION = "This package provides kernel header files for 6.12.94-cip26-ebclfsa on arm64 \
 \
This is useful for people who need to build external modules"
SECTION = "kernel"
SOURCE_PACKAGE = "linux-cip"
HOMEPAGE = "http://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC}/pool/main/l/linux-cip/linux-headers-cip_6.12.94-cip26-ebclfsa1+r0_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "2e21247f0e59dd9e36271c97344870eb"
SRC_URI[deb0.sha1sum] = "5dad1ae99c05bcbd348ab7ce04bf42bfdb99397b"
SRC_URI[deb0.sha256sum] = "463bb637d272d2235cfe335d1de809c93f80ab506052650d280e5571b60edaf4"

RDEPENDS = " \
    linux-kbuild-cip \
    perl \
"

