# This was autogenerated! Do not modify
SUMMARY = "Linux Kernel Device Mapper userspace library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "lvm2"
HOMEPAGE = "https://sourceware.org/lvm2/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lvm2/libdevmapper1.02.1_1.02.205-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lvm2/libdevmapper1.02.1_1.02.205-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "6f016efa31b9b8b92d02e07c67d65e0b"
SRC_URI[deb0.sha1sum] = "c660548e2994bf30be72c7dbbfbef6648e9440a1"
SRC_URI[deb0.sha256sum] = "e924e0df8823987f271b7d3a375dc2f8adcd76db66f09d0273043c885edb0af0"
SRC_URI[deb0.sha512sum] = "bbd48f7c94342cee15d9c6eb768bbf8489fdea7570e020cf575545ccbc6fce94881206c379f12fe9bc678e738775c6fd3e1cc2cba05aed98cbfed4a5c7ee2643"
SRC_URI[deb1.md5sum] = "1b45a7c4ce44e5867717a14259705a5c"
SRC_URI[deb1.sha1sum] = "dc1478f8e44f4dc3e464dab29bd7431a82286752"
SRC_URI[deb1.sha256sum] = "4d783b235eb9857ec96fabd0f161a84426706d079ec82ef5a91cbbf9dd644904"
SRC_URI[deb1.sha512sum] = "6ca216af5035fb4249b0360381b5d8f35ea2c42729134fdedad6f2f2f8f95008b3a6c30def73234eeb48161e24d33d0492677a37a89827ac9e2e83d415f34d29"

RDEPENDS = " \
    dmsetup \
    libc6 \
    libselinux1 \
    libudev1 \
"

