# This was autogenerated! Do not modify
SUMMARY = "high-quality block-sorting file compressor library - runtime"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "bzip2"
HOMEPAGE = "https://sourceware.org/bzip2/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/bzip2/libbz2-1.0_1.0.8-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/bzip2/libbz2-1.0_1.0.8-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "9b894973cee72ed70062492ef177bb5e"
SRC_URI[deb0.sha1sum] = "d7cc66c713ee3a13713f3dffaec4e2b9fa43ffe2"
SRC_URI[deb0.sha256sum] = "cba4cda04244b5e481bb15524bc3c983a7d1b6f330013b9b381706a2fcb65310"
SRC_URI[deb0.sha512sum] = "5765ec82be20460494f991ab3f3ea676199905b4165f9f00b62b7d8d5a37cf4a800a43582601f32f31e59d8e1c10842d8d906ca1825a3492b09da6f927982e52"
SRC_URI[deb1.md5sum] = "86ba0d08aa1c87b5ee5dc455b72b5c8d"
SRC_URI[deb1.sha1sum] = "776bcf9f762ce2e2a1af4b72a697817058c9ece4"
SRC_URI[deb1.sha256sum] = "3537fe4fc577a60c8a9568873cd577db7ebc135eb8bb1825f18caf8972d9d2f2"
SRC_URI[deb1.sha512sum] = "88909bde379d2e814382107690af38e3a20282c7ada3f429d5f0d524a6f72a072fb6dcdec718a4d50679214841f10ee76426e14f052590c923f360fbf06b8591"

RDEPENDS = " \
    libc6 \
"

