# This was autogenerated! Do not modify
SUMMARY = "Network Security Service libraries"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "nss"
HOMEPAGE = "https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nss/libnss3_3.110-1+deb13u3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nss/libnss3_3.110-1+deb13u3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4b63b2494e8e2e644b0c58d2ad409b07"
SRC_URI[deb0.sha1sum] = "0df640065d6e263fc0d58e676e65d65aced112b3"
SRC_URI[deb0.sha256sum] = "9f4fb2f6bc2530529dd3e79c411566de696fae1ddeb8d585756cc92543bbcb6b"
SRC_URI[deb0.sha512sum] = "d6f49575ddc6361cfde9de3020e06bd68325b899a3b3f4d2c4264e2d0e80284e66665806ff1b475b7205c4b058635adcb319723c2dc8df718dda983174f87a9c"
SRC_URI[deb1.md5sum] = "ec9ad024c87b0302c808fe226d69e9c0"
SRC_URI[deb1.sha1sum] = "fde8b2d02b3696ec05a8e9b5946300c88d95de89"
SRC_URI[deb1.sha256sum] = "d8ecf0195b57c097d2ff1f1d83efbd492b782f657c036cc76495fc7d916ed7e7"
SRC_URI[deb1.sha512sum] = "485089e2b494b32cdd4409c73c3a353cc25328d31e59152f172d0158fa3e9155da6fc501f875a7c5bd990566f1f08f837fb00cd1381a0195843ad4bfe654da22"

RDEPENDS = " \
    libc6 \
    libnspr4 \
    libsqlite3-0 \
"

