# This was autogenerated! Do not modify
SUMMARY = "Perl module for minimalist role composition"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "librole-tiny-perl"
HOMEPAGE = "https://metacpan.org/release/Role-Tiny"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libr/librole-tiny-perl/librole-tiny-perl_2.002004-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "ff588d7b06827c5df2ea1810cdd18dfd"
SRC_URI[deb0.sha1sum] = "01f7ea58bca1d0b5d06b93eddb7d06749d7b0c67"
SRC_URI[deb0.sha256sum] = "ba2e4028236ada61e5d59d0a05503dc88301cd276091b8a42dd177598a8ebcc6"
SRC_URI[deb0.sha512sum] = "7261efe1c1702f9ca272aec03e451e487a07033625f5c0556383113bdab76c327726018de408d2e8b5f304ab77362e8cc6158d8f75b60b9e1f85f51d6114c9e9"

RDEPENDS = " \
    libclass-method-modifiers-perl \
    perl \
"

