# This was autogenerated! Do not modify
SUMMARY = "fast compression/decompression library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "snappy"
HOMEPAGE = "https://google.github.io/snappy/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/snappy/libsnappy1v5_1.2.2-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/snappy/libsnappy1v5_1.2.2-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "5e2457205f23689a487168e17d9d4b7e"
SRC_URI[deb0.sha1sum] = "2bd7f7bd78b8ee7573af8995bab358ff1830e2ff"
SRC_URI[deb0.sha256sum] = "53ec5f1050d64375a63cd1c30ee4a6d21ef0cfd485f9999aa0b70dd424ca3465"
SRC_URI[deb0.sha512sum] = "be47e1b4d7cd8cf6766271d2507397ee6937dec5c076657295f9e22dfeaed787414fa77aeee62848a72d31af83a1fe92b8c6ecebe94b93722dc0e3b0803623e4"
SRC_URI[deb1.md5sum] = "62d6705bab295b56b1657e66b1bd0c99"
SRC_URI[deb1.sha1sum] = "fd53b1e3ddbfa0d05cf27c2fd23d432f167837a6"
SRC_URI[deb1.sha256sum] = "b307da3076ad257cd8adec2faa5ad051fa9bd54edc1f473ecaf69b1456fdebd2"
SRC_URI[deb1.sha512sum] = "fbd71d5e136d6f9e2f06ea7e08a206ffbd78560c6b73fed004ac1dc91dcc95a95caa84814bfac9017d331a50c9aa7b276ad90b8b77ffb15d92ee21d7c96cbd9c"

RDEPENDS = " \
    libc6 \
    libstdc++6 \
"

