# This was autogenerated! Do not modify
SUMMARY = "sans-serif typeface family font"
DESCRIPTION = ""
SECTION = "fonts"
SOURCE_PACKAGE = "fonts-lato"
HOMEPAGE = "http://www.latofonts.com"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/fonts-lato/fonts-lato_2.015-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0586731524b9b1f7a38dd4655994c37f"
SRC_URI[deb0.sha1sum] = "399e818baf775f8463252c1f0e1025cf0b21660e"
SRC_URI[deb0.sha256sum] = "0bd1c095d4646f51ce3e5c002df3cd322c0fbabf13c76a694a0360e1191221e8"
SRC_URI[deb0.sha512sum] = "1862d17e304a44544dde1c357ba55e4423cf7b5febd83dcaf805917be9938202a13a7b60485409f27fe3434cfb9c6cbce6c82c7ac27b63c5044c1f9e1afd91ec"

RDEPENDS = " \
    dpkg \
"

