# This was autogenerated! Do not modify
SUMMARY = "ext2/ext3/ext4 file system libraries"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "e2fsprogs"
HOMEPAGE = "http://e2fsprogs.sourceforge.net"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/e2fsprogs/libext2fs2t64_1.47.2-3+b11_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/e2fsprogs/libext2fs2t64_1.47.2-3+b11_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c931916a20480c6a8a28f0d22cec1cb9"
SRC_URI[deb0.sha1sum] = "30bd90557229da3e99aeab2c3acbc3a2868a2183"
SRC_URI[deb0.sha256sum] = "0aa71547d523226775d3d6ac38dea6d6d8ea184c615592b05b9275a71d418f01"
SRC_URI[deb0.sha512sum] = "821df096a972e90c7896f70f364bfdc27265b89eafc024c36b21460266ae0559b34ce1a27c1afb17bd2373fc7e4ea8e703ada67c90c401f0013c8dda1a9475f7"
SRC_URI[deb1.md5sum] = "b55131ba64ef49e73fe2254df364aa04"
SRC_URI[deb1.sha1sum] = "899584338013baf1118737ee7257177002bec517"
SRC_URI[deb1.sha256sum] = "d065ff9b61dc2c15ae0d78465fc5108d6006a8b42ad8d85893d57a8475324279"
SRC_URI[deb1.sha512sum] = "4967b5cef4dd68307bd0119bdcdea2ab94cf5186e3bb6c9c5aba1d78489ea37d0d6770b4224d6ddfebec65e7e7dc28a39415881a5634b5f5e1f8884ae2ed5033"

RDEPENDS = " \
    libc6 \
"

RPROVIDES = " \
    e2fslibs \
    libext2fs2 \
"
