# This was autogenerated! Do not modify
SUMMARY = "Configurable Rootfs Init control utility package"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary. \
 \
Control utility package."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/crinit-ctl_0.25.3_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "ae1b581331ffdb519f74379eecb0be30"
SRC_URI[deb0.sha1sum] = "06919ab5c1fdcf97a0638adb2fbccb84e2e4d7e6"
SRC_URI[deb0.sha256sum] = "0651d84ed8dda30db60934a98d34d7bc16c2aae30f9685882c894841291e8a4c"

RDEPENDS = " \
    crinit \
    libc6 \
    libcrinit-client0 \
"

