# This was autogenerated! Do not modify
SUMMARY = "Documentation for Configurable Rootfs Init"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary. \
 \
Documentation package."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/crinit-doc_0.25.0_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a9ff24378ebeaafe7c5f3f94e51228bd"
SRC_URI[deb0.sha1sum] = "3e217d8a225a3d0af3ec861a988a67d4c6747a89"
SRC_URI[deb0.sha256sum] = "5e3bd89b7bfc6d540d768064453ea6f8e0f2ffa8eb8db4911d612aa23f1e3aea"


