# This was autogenerated! Do not modify
SUMMARY = "Configurable Rootfs Init tests"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary. \
 \
Test utility package."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/crinit-tests_0.25.3_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e4d967cca6974cc7c681067fbab5e449"
SRC_URI[deb0.sha1sum] = "11169f51a9570e4984181c6d61ca82dff2a872c4"
SRC_URI[deb0.sha256sum] = "587e00ec5d46d1d6d829b442f07137fc26acc83fa6056b5115c26cfd7e78d7ad"


