# This was autogenerated! Do not modify
SUMMARY = "Configurable Rootfs Init tests"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary. \
 \
Package to demonstrate crinit features."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/crinit-demos_0.25.0_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "82e194248e2180c664dca23434fcb30b"
SRC_URI[deb0.sha1sum] = "c174fa38b7edf1306cee4a72475741933d422124"
SRC_URI[deb0.sha256sum] = "c345ce2e31b4e7bb641d4f95b50b44a380dae22dfdb3d72c625783cd5fefdfb9"

RDEPENDS = " \
    libc6 \
"

