# This was autogenerated! Do not modify
SUMMARY = "Configurable Rootfs Init"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/crinit_0.25.3_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e414285d3e9835ee98e5b321c00a44c2"
SRC_URI[deb0.sha1sum] = "487784f6a61673cf1e97ccf6479bd28772826a2f"
SRC_URI[deb0.sha256sum] = "543e258efe7bf69793a3821888ad5b432bfc492ed6d1204cab516df82ffb08e0"

RDEPENDS = " \
    libc6 \
    libcap2 \
    libmbedcrypto16 \
    libsafu0 \
"

