# This was autogenerated! Do not modify
SUMMARY = "Configurable Rootfs Init client library development package"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary. \
 \
Client library development package."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/libcrinit-client-dev_0.25.3_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f94e08d436892760c8892b61b12b0e30"
SRC_URI[deb0.sha1sum] = "b76790fa466168a097e4ce4d17985bb7e0c6765a"
SRC_URI[deb0.sha256sum] = "0f952042a6b6e04064ac883696eac3e0f288bb6b05d43528a08b5d8463fc4c19"

RDEPENDS = " \
    libcrinit-client0 \
"

