# This was autogenerated! Do not modify
SUMMARY = "Configurable Rootfs Init client library"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary. \
 \
Client library package."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/libcrinit-client0_0.25.3_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a6d5fca4004c9aa9915f566796c52bc8"
SRC_URI[deb0.sha1sum] = "38108d4098bd6316e80a8e923e243e9a6f9c3604"
SRC_URI[deb0.sha256sum] = "693a3a5fff0bd4fae2ae19b9627ea0ae5d59a47d6ba5dbba32a46c4bf653544b"

RDEPENDS = " \
    libc6 \
"

