# This was autogenerated! Do not modify
SUMMARY = "Configurable Rootfs Init client library"
DESCRIPTION = "Crinit is an init daemon executed as PID 1 by the Linux Kernel. It reads a \
global configuration ("series"-file) either specified on the command line or \
from /etc/crinit/default.series. The series file in turn may reference further \
configuration files or a whole directory from which all configs shall be \
loaded. Each one defines a task potentially containing a set of commands and \
dependencies on other tasks. \
 \
The specified tasks are then started with as much parallelism as dependencies \
allow, i.e. tasks without any dependencies are spawned as soon as possible \
after Crinit has been started. Once a task is spawned, finished, or has \
failed, its dependent tasks are updated and spawned as necessary. \
 \
Client library package."
SECTION = "admin"
SOURCE_PACKAGE = "crinit"
HOMEPAGE = "https://github.com/Elektrobit/crinit"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/crinit/libcrinit-client0_0.25.0_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "b995f96cfb1c2895576463011cbe3a80"
SRC_URI[deb0.sha1sum] = "db89caf85e616f88283f3212b4adb44ff3deeb3c"
SRC_URI[deb0.sha256sum] = "87f3904f442cd1bea3b521d8a940d31e63fed10de08e06e82e68feefba8b09c2"

RDEPENDS = " \
    libc6 \
"

