# This was autogenerated! Do not modify
SUMMARY = "package management related utility programs"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "apt"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/apt/apt-utils_3.0.3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/apt/apt-utils_3.0.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "60215af405d98f5bcc4f174ead680a2d"
SRC_URI[deb0.sha1sum] = "6d3e28c0a239de32dd4bb6140fd5786e566c394f"
SRC_URI[deb0.sha256sum] = "679daae89a4f3a514e17de6efb7a6125fd727eb4999cdbaeacd8bab118b8ee69"
SRC_URI[deb0.sha512sum] = "bdc19472ba523c5223f4679c7f14dea231c6965ee426eaca525f7133448fb1a10410c999502e42ecca8a7bd4d8b10d55b5d3f895899287913d93a6165843e655"
SRC_URI[deb1.md5sum] = "c34920c73b5665ba4209d14a2d48bc08"
SRC_URI[deb1.sha1sum] = "453d7febc638c98b1ea8664f58d39b3b8a6a3f0a"
SRC_URI[deb1.sha256sum] = "d3541017d1f189cdc34538260e0edb90cfbe07f9a4691f250f155d6962eefc16"
SRC_URI[deb1.sha512sum] = "dad38d1c885820dde34b21b0efa7b5b74b13aef458038f43f5857a2ac0595fa9178ae7233aecde11078c60dd6e5243f84ca89162391f618c07719ea6a464f623"

RDEPENDS = " \
    apt \
    libapt-pkg7.0 \
    libc6 \
    libdb5.3t64 \
    libgcc-s1 \
    libstdc++6 \
"

