# This was autogenerated! Do not modify
SUMMARY = "GNU awk, a pattern scanning and processing language"
DESCRIPTION = ""
SECTION = "interpreters"
SOURCE_PACKAGE = "gawk"
HOMEPAGE = "http://www.gnu.org/software/gawk/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gawk/gawk_5.2.1-2+b2_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "319d966a07ced7573c106705619eadcf"
SRC_URI[deb0.sha1sum] = "2d2b2ecc3bdbe2adb7cca97811914443d4dddee6"
SRC_URI[deb0.sha256sum] = "0c040f686b0dd34387c0aa69848dd9f29741043821a843b480c38a1cf5956142"
SRC_URI[deb0.sha512sum] = "a5bc28b0f4232147a07cfec94423cd3cf415b3e8a5dd92102079ae8a30cd4d40136df17c5810dd6568094571190b909b2f2065d40c1ecdcc892f26f774f86739"

RDEPENDS = " \
    libc6 \
    libgmp10 \
    libmpfr6 \
    libreadline8t64 \
    libsigsegv2 \
"

RPROVIDES = " \
    awk \
"
