# This was autogenerated! Do not modify
SUMMARY = "generic font configuration library - support binaries"
DESCRIPTION = ""
SECTION = "fonts"
SOURCE_PACKAGE = "fontconfig"
HOMEPAGE = "https://www.freedesktop.org/wiki/Software/fontconfig/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/fontconfig/fontconfig_2.15.0-2.3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/fontconfig/fontconfig_2.15.0-2.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c186e7685a219328fd50e7370038d2c5"
SRC_URI[deb0.sha1sum] = "5ab99fde8b6c1bb93fe4df598eec4eedde72b6da"
SRC_URI[deb0.sha256sum] = "09794b188e042c90b4a89fcb5afeb276bc231b74ddf8a3efbbc7dfb6f0eac4cb"
SRC_URI[deb0.sha512sum] = "0de67b672946a4c5ff3ddee0ea298334b51536bfe962fde87d7d0574cd928853bb3fb84851ce9375b3415b699a87b7fa03edfb4e88243d7322e61b6e03f672b1"
SRC_URI[deb1.md5sum] = "3b13d58c43a7ea36b565fedc7d458830"
SRC_URI[deb1.sha1sum] = "d993b70200df178b4763dc53c7d1fa708bf91517"
SRC_URI[deb1.sha256sum] = "f899e800435bc3bd3ecc6139bfcb2b45b3dbd2ffa59c4b9b3cc246e9661052af"
SRC_URI[deb1.sha512sum] = "49ed4532ef993632d74f6072a736575ffcfa9a15432c604a663879003e5666268cdbcb0ec5cc0ed30ef1d1e3224a39955d6a661d8fdbe4e2460e195bed5870b5"

RDEPENDS = " \
    fontconfig-config \
    libc6 \
    libfontconfig1 \
    libfreetype6 \
"

