# This was autogenerated! Do not modify
SUMMARY = "low-level interface to bzip2 compression library"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libcompress-raw-bzip2-perl"
HOMEPAGE = "https://metacpan.org/release/Compress-Raw-Bzip2"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libc/libcompress-raw-bzip2-perl/libcompress-raw-bzip2-perl_2.213-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libc/libcompress-raw-bzip2-perl/libcompress-raw-bzip2-perl_2.213-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "21363b6b5ec936195ce69128ec6e6f0e"
SRC_URI[deb0.sha1sum] = "792ef4dff3e1c2acc70e30ce9a3114803a841f5e"
SRC_URI[deb0.sha256sum] = "48368324989f83e30173bdc1cf011d6e723e8fbf9516fbb9762194e116b1d454"
SRC_URI[deb0.sha512sum] = "f83c1eb29ea2ccdb2381a664363dd1a2097412ce0ed1c22f560da42d60185bd2a5906b068e75e7009cd4a26fbe39c00d71dbcd760015f189cf4bd81c8a900633"
SRC_URI[deb1.md5sum] = "1198d5e8f7838954827f3df619743c32"
SRC_URI[deb1.sha1sum] = "6fe3b20f1deef9bdcaf078e686a2f7c68c785feb"
SRC_URI[deb1.sha256sum] = "c92f51205f43898a299c30fe9a2b46a2041e13b0534f2ea9fd50a971c0f3f6b8"
SRC_URI[deb1.sha512sum] = "3b701d40091d898fb05461dab38d280d1b7169a7523954045c22fcc05b2bff5d80736dee6834f929db2ef56d837715c9bf86ec5b5ad0613ee716a95045c6fade"

RDEPENDS = " \
    libbz2-1.0 \
    libc6 \
    perl \
    perlapi-5.40.1 \
"

