# This was autogenerated! Do not modify
SUMMARY = "Dynamic library for security auditing"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "audit"
HOMEPAGE = "https://people.redhat.com/sgrubb/audit/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/audit/libaudit1_4.0.2-2+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/audit/libaudit1_4.0.2-2+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "bd58445b6e91a8a892a5042f08b6d697"
SRC_URI[deb0.sha1sum] = "e1817234df69c35e66a256e911ba0a81eebdb111"
SRC_URI[deb0.sha256sum] = "e5c200c6f9db0d0e5766c5cad66a686f46c7649868435fba966cdb0be59b42f2"
SRC_URI[deb0.sha512sum] = "dafdba82e8b06420911d93373cfa1fc17d3e4e0032395db63d82f36f5784928f57ba119317128c7d5dab0a170ab1986aec6f562a09857f209057eb0fc7f68e9c"
SRC_URI[deb1.md5sum] = "3b768977c80eac2c14276fa395844e9b"
SRC_URI[deb1.sha1sum] = "62b13b7215da6ed26a8832caeaf1b85f2c1e8bf4"
SRC_URI[deb1.sha256sum] = "a1124818a702c584ee139948c20596f6bb464d8110a14bc2dc748646ae461cab"
SRC_URI[deb1.sha512sum] = "b1c65fbf862b171fa1bc5d54df1c9caa18d90475dc8251441547f56bd34652fb9864aa5151e3fa6b163f2bbd16cb3b33012d6df12a6de743ba435c6a87758b89"

RDEPENDS = " \
    libaudit-common \
    libc6 \
    libcap-ng0 \
"

