# This was autogenerated! Do not modify
SUMMARY = "miscellaneous system utilities"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "util-linux"
HOMEPAGE = "https://github.com/util-linux/util-linux"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/util-linux_2.41-5_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/util-linux_2.41-5_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e6f4aad164cd75a2b566ca651a032493"
SRC_URI[deb0.sha1sum] = "e5f9f61a9715391d797852bb431d7400c3a04629"
SRC_URI[deb0.sha256sum] = "47fc393fed410642889c86164928219c039e5b43d823aa32e1dbb341eef1d9c5"
SRC_URI[deb0.sha512sum] = "2ccbcfd208b46fb11c666f8def276b06fbc978e763989c053a5f40a2a54d471b2da4d2cb07c2c5eb1b16da50b01527357f04ef6c06e5d25f1849f1ec259f5dea"
SRC_URI[deb1.md5sum] = "20fffec1635d1604b9fd118e47643aa5"
SRC_URI[deb1.sha1sum] = "e76be3e653327f16f37ab2c460e45d19b04e79dd"
SRC_URI[deb1.sha256sum] = "d336901e4c1aedf268837d41a4e1004faa9b7ad4f1e6763f01711b487a4c18ce"
SRC_URI[deb1.sha512sum] = "d3f43ffe513fa1e960623835179164c4b44b7909c99b1c649138ac75912fe059e4dc92008592110ead3e9911f69a21ca8ac5da0a81c61e9901eef74ff3c02b0e"

RDEPENDS = " \
    libblkid1 \
    libc6 \
    libcap-ng0 \
    libcrypt1 \
    liblastlog2-2 \
    libmount1 \
    libpam-modules \
    libpam-runtime \
    libpam0g \
    libselinux1 \
    libsmartcols1 \
    libsystemd0 \
    libtinfo6 \
    libudev1 \
    libuuid1 \
"

RPROVIDES = " \
    hardlink \
"
