# This was autogenerated! Do not modify
SUMMARY = "AV1 decoder developed by Google -- runtime library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libgav1"
HOMEPAGE = "https://chromium.googlesource.com/codecs/libgav1/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libg/libgav1/libgav1-1_0.19.0-3+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libg/libgav1/libgav1-1_0.19.0-3+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e93049581b24b0e191dd28725918bcac"
SRC_URI[deb0.sha1sum] = "c08b320e5cd9f5d863c049290a08abb4230c3422"
SRC_URI[deb0.sha256sum] = "94010041e59c7a8d2d3d1f5e62afd523f002b7b1caa3189419160b66d71c0195"
SRC_URI[deb0.sha512sum] = "067493788556f48927be20c786c303fc6752173cef983fc6e432f0b7677a9b5e5e1af4fcc058d3a931f45b23c89892734430c0882acd65f9e671e1245d538159"
SRC_URI[deb1.md5sum] = "ab9161f668aad2f039e71c61d16de5d1"
SRC_URI[deb1.sha1sum] = "418e457ffa79e726f99df426e57b3bb28b66c243"
SRC_URI[deb1.sha256sum] = "441bdfa9e19df94067968de72aafa71d7b09877fa14153f456f828e140f8e3ff"
SRC_URI[deb1.sha512sum] = "32cc6a520e900be1725b5b10e8076e52a3318fd8542f621157ab99667f067eb1b9bc9025b6c4c5074dfc33225b5fb0e46aeddbbd55f48d7aefc83de8bbfc96eb"

RDEPENDS = " \
    libabsl20240722 \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
"

