# This was autogenerated! Do not modify
SUMMARY = "converter from DocBook SGML into roff man macros"
DESCRIPTION = ""
SECTION = "text"
SOURCE_PACKAGE = "docbook-to-man"
HOMEPAGE = "https://www.oasis-open.org/docbook/tools/dtm/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/docbook-to-man/docbook-to-man_2.0.0-48_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/docbook-to-man/docbook-to-man_2.0.0-48_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "114e46b48da0443e9e14cc65c6317e31"
SRC_URI[deb0.sha1sum] = "aa31848a2f9482541c11592d40c18d941b48eaa9"
SRC_URI[deb0.sha256sum] = "3d1244ad793222aa6a806ec2bcf2eb7983e5c2899714ca79ec7394fcd37fb652"
SRC_URI[deb0.sha512sum] = "d66a3a66a87ce9e7b625b0526817e7a6f8c237894c25a1266fa0b277fd420fdc75c5745b80e374d4801c7e53a925064022698b7d78e30a02a6f0a21f988214b2"
SRC_URI[deb1.md5sum] = "94fafba406470242551a794e0869b590"
SRC_URI[deb1.sha1sum] = "026fcd7205802ade3aa5682a3d9a45d585d1f0ad"
SRC_URI[deb1.sha256sum] = "dfd81d6f74282fb8d40afb7b4b7645d5df99210b239868ce4df251ce1880a8ea"
SRC_URI[deb1.sha512sum] = "b97b6fa1c99a1c4772e071b47f2a849e7f82a0cc0446670f8892824f5e2013ac6d0b092eebd6864eae407a53ee1b0e745dbb9824df9216689d9da21d76f6b4f2"

RDEPENDS = " \
    docbook \
    libc6 \
    opensp \
"

