# This was autogenerated! Do not modify
SUMMARY = "netfilter libip4tc library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "iptables"
HOMEPAGE = "https://www.netfilter.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iptables/libip4tc2_1.8.11-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iptables/libip4tc2_1.8.11-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "426458393ed6c82e3edecf715ba050e2"
SRC_URI[deb0.sha1sum] = "9c611eacced34f52cfb2daf0970cf91762e5d63c"
SRC_URI[deb0.sha256sum] = "762e4d9c7f86b3fdaefee2baf61ce40073d46d7602651433f2cb7a5eabfb47b4"
SRC_URI[deb0.sha512sum] = "2cf5766c28360d2f7e91adb4e6e428296be26a31b3bc9f4cabfe46b4653838ca004c4b5e4a241b97126a154f148e9fa08b58aa9d46191e1d841b73f5c76a68a4"
SRC_URI[deb1.md5sum] = "086cd52db395e59d295cfcaf03783848"
SRC_URI[deb1.sha1sum] = "37a4a4e02d1bc3c2a6c7bebdeffdd2bad952fdee"
SRC_URI[deb1.sha256sum] = "e2d86b0b1b5d06b529cf60f3876970b02c1ae1147555bfcf1c5b17bfdae992ca"
SRC_URI[deb1.sha512sum] = "36e3bfe40aa2fb892d322ce43979404368beb9863f6326d921bf85ccf73d3ee538d8638ddf5a6eac4589ff8ba98bb74d2223da5b2e5577980596b038c4227fb1"

RDEPENDS = " \
    libc6 \
"

