# This was autogenerated! Do not modify
SUMMARY = "netfilter xtables library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "iptables"
HOMEPAGE = "https://www.netfilter.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iptables/libxtables12_1.8.11-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iptables/libxtables12_1.8.11-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "148ab3e9d626eb9ee6bdf956d48bf77a"
SRC_URI[deb0.sha1sum] = "8f531c4de3a77c8d0501ea62f853c0a0212d5f78"
SRC_URI[deb0.sha256sum] = "4de5aa59faef5e98d6ba9f5f521a915be5641f224f597862f8d29e8319e8db16"
SRC_URI[deb0.sha512sum] = "501c3f7aeced91d6bc0b037b4c30bc4a85a8fbbd5e78b7435f98b09ee7f20d1e44cedf3a37995a4301d2675eb77e6dbe8ad40aa8b545a52859a3fc44f68ff4f3"
SRC_URI[deb1.md5sum] = "01330d52881256fe711a915fb3ba1334"
SRC_URI[deb1.sha1sum] = "a7f2d13ef75ba9398b44d5635b2670a2523e644b"
SRC_URI[deb1.sha256sum] = "b200a559a4ae1b4ebcee4fb0fcaef6a16ef01abbe3da8887de15e800b1a6440d"
SRC_URI[deb1.sha512sum] = "d3d4e880b9107fd3eb23d4e478d2bc656ad3f6ae0f8354c1965861f8244c01d22b700e2a314e51f9bc873d21760d7f00b32abfea850251d890595c51beb99377"

RDEPENDS = " \
    libc6 \
"

