# This was autogenerated! Do not modify
SUMMARY = "Non-interactive ssh password authentication"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "sshpass"
HOMEPAGE = "https://sourceforge.net/projects/sshpass"

inherit dpkg-prebuilt

DPKG_ARCH = "amd64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sshpass/sshpass_1.10-0.1_amd64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "6a555c0ad208b4156eb017fc84ce78c4"
SRC_URI[deb0.sha1sum] = "0fb6907fe22edd25085190c1abbdc9edf9767079"
SRC_URI[deb0.sha256sum] = "55f11ea67b8a7393865eae8ea426585feacdccb6e33431fc5e873d0b1b4391c5"
SRC_URI[deb0.sha512sum] = "da7b7385e777721bd0da56c5eed5edaafd80a3757c6b713f1c234af90bbc7bbc7e1d1b0f8c88f79917706de18428938555e58b3776d9e701fe15882c67c8e5a8"

RDEPENDS = " \
    libc6 \
"

