# This was autogenerated! Do not modify
SUMMARY = "system login tools"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "util-linux"
HOMEPAGE = "https://github.com/util-linux/util-linux"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/login_4.16.0-2+really2.41-5_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/login_4.16.0-2+really2.41-5_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "284768ac02d2af9ce13dad67ae0a601d"
SRC_URI[deb0.sha1sum] = "fa502d98a2dc4a84841a54d15df707dfa203f032"
SRC_URI[deb0.sha256sum] = "6286d52eb6829e6253a8bd93bf8686fb1ceeccb03f9b461bb25ab35c67396c35"
SRC_URI[deb0.sha512sum] = "aa1ff8366e6b1622a8e1336083ed562002a96674e55545e96941af139e746dbf18cbca1b2599c250546cf0c7e36d38dd522290c70320c151fca9913aa89639cf"
SRC_URI[deb1.md5sum] = "184e0752ec4f3f64e37dbdc794fba78b"
SRC_URI[deb1.sha1sum] = "e9484135630af1305e002d2babbd20ac1a576acc"
SRC_URI[deb1.sha256sum] = "c58d89c3e776ec356d75f33bbf5d24a797050691edaee4d97d31da9e6e47b2ec"
SRC_URI[deb1.sha512sum] = "b035ca003f42f6cf106c0ae65985e03a35150e8e55a2688298fc29b9e2ba8f1a88828db433e0f1d4836922e79a84a9188b93d6f98273eb7265dacc48a7143e49"

RDEPENDS = " \
    libaudit1 \
    libc6 \
    libcrypt1 \
    libpam-modules \
    libpam-runtime \
    libpam0g \
    login.defs \
"

