# This was autogenerated! Do not modify
SUMMARY = "tools for mounting and manipulating filesystems"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "util-linux"
HOMEPAGE = "https://github.com/util-linux/util-linux"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/mount_2.41-5_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/u/util-linux/mount_2.41-5_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "433f0a11367c86bf0b8d41337227cdbe"
SRC_URI[deb0.sha1sum] = "7b6699cddac83b36088d96cdbce795341ec9f79d"
SRC_URI[deb0.sha256sum] = "2ca8aceb0e76d50d8d8415e718cd9f1f8c17358bbbe9c5622177e6965439c256"
SRC_URI[deb0.sha512sum] = "9b6e8d66882ab75e5c3a48ecbbcf408f403a6eaafc2d9060a20faf78a297d37bf8c02fa5304d7b032b5a1a87db37667cc7a1ccaa20d88bd06c9e9b12895bc4c0"
SRC_URI[deb1.md5sum] = "1a977dd1e9e38bc2b91ee65435c4d7bc"
SRC_URI[deb1.sha1sum] = "4d6294a277eeaf7ea69bdf39c0230d7de9869d5f"
SRC_URI[deb1.sha256sum] = "62fd64b4fc9bac520d37eb7b2bee0fa310bbecf66d83d5ef5989092ecd0669b6"
SRC_URI[deb1.sha512sum] = "f19d52694fe283dd3aff97681abc1517db2a778b27a624488e4fc511089acd4957ed69c00b6d25053743d12608bd662c5a9225733deea9c66e4afb44103740f1"

RDEPENDS = " \
    libblkid1 \
    libc6 \
    libmount1 \
    libselinux1 \
    libsmartcols1 \
"

