# This was autogenerated! Do not modify
SUMMARY = "Python decorator for old classes, functions or methods"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-deprecated"
HOMEPAGE = "https://github.com/tantale/deprecated"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-deprecated/python3-deprecated_1.2.18-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "baac30f694a2c10c90c2e35401c641c3"
SRC_URI[deb0.sha1sum] = "ea8b3e7ff1e936c3000fa63bdb0be27ec2a4114f"
SRC_URI[deb0.sha256sum] = "57646d92e1e60c64a8f384fe8fc556c97c8aa84746032377b0b355cbe35ee9b6"
SRC_URI[deb0.sha512sum] = "11bfb4eef7387e099221887bb9bb2a09a39b017d0b80d8cd26b45e48eab4033337ed7d4f308016a5ad557cbf49ff3fceccff7a148057c509d249d3aaaacb57bf"

RDEPENDS = " \
    python3 \
    python3-wrapt \
"

