# This was autogenerated! Do not modify
SUMMARY = "brain-dead simple parsing of ini files"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-iniconfig"
HOMEPAGE = "https://github.com/RonnyPfannschmidt/iniconfig"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-iniconfig/python3-iniconfig_1.1.1-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "4e83be70306cc7ae98058ac32979bae0"
SRC_URI[deb0.sha1sum] = "a82ccbdead75b9fc25cce3ecf9acab968d000a66"
SRC_URI[deb0.sha256sum] = "c9226a32a78fa93f9e993a4ed77fcb3ceb23c21b9d75d7ea4dc77cb016ed0d83"
SRC_URI[deb0.sha512sum] = "6c75c1faeeaf0b2bedc5e8b164c851fd21628adadaff00ed843601909564d4dd74bd0cb621ccfd44b7bd0ecfaed38588fff111395d9a447be5663ce171fbe415"

RDEPENDS = " \
    python3 \
"

