# This was autogenerated! Do not modify
SUMMARY = "Theora Video Compression Codec (shared library - libtheoradec)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libtheora"
HOMEPAGE = "https://www.theora.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libt/libtheora/libtheoradec1_1.2.0~alpha1+dfsg-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libt/libtheora/libtheoradec1_1.2.0~alpha1+dfsg-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "6c2bfc6641b8564cae1d29a04dee0dd8"
SRC_URI[deb0.sha1sum] = "ae9cd2f9b54fa22302ff6ec6a838677b2bef12e7"
SRC_URI[deb0.sha256sum] = "31c566d16b0a30f2c100d685d09b831d10d756bd043107ec6594c082274c0c74"
SRC_URI[deb0.sha512sum] = "e5691a50254d37d95638fbada37cc89ee8d15d30dad79b20fc16cc92402cae66efb22c9d40706bab6638ba23264664a9a48357aa79120b5d31198585c6a932df"
SRC_URI[deb1.md5sum] = "ab534115ee12d72e013a79b170b897bb"
SRC_URI[deb1.sha1sum] = "1ebc8e41464b58bb77445e1b1109e9b2c424f0a1"
SRC_URI[deb1.sha256sum] = "e233aa1a1d345e6db838040f0ced479c5cda3fcc04d6637468275c398f585924"
SRC_URI[deb1.sha512sum] = "8a9c3503d8c185f76fc57021f4c17398f34c89a00b785fab667809accd6942f36749fc23244b8849ae8596ccf835a4e457b649df843ee4814bc59412ed284ff8"

RDEPENDS = " \
    libc6 \
    libcairo2 \
"

