# This was autogenerated! Do not modify
SUMMARY = "Theora Video Compression Codec (shared library - libtheoraenc)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libtheora"
HOMEPAGE = "https://www.theora.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libt/libtheora/libtheoraenc1_1.2.0~alpha1+dfsg-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libt/libtheora/libtheoraenc1_1.2.0~alpha1+dfsg-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "eed038470e8d94241810066bb32de38b"
SRC_URI[deb0.sha1sum] = "6cd3d61a5c5afd400f1bc71203cb6ed212f7be1e"
SRC_URI[deb0.sha256sum] = "ce795eba6cdb510a52cd158dee7930a23667ffb4bdf07fbc44d4590edbf6f503"
SRC_URI[deb0.sha512sum] = "c2fde8e9791949cee1cfa5fd8787bdd819463ad49593958dc960d3e93031abe4d8d9912d58f43cfb6d10a9ae08cf40199fd8073acfa28f2efe49cfcd5832dbee"
SRC_URI[deb1.md5sum] = "3d1dffe55e89f8e2e20ba13aaf1eefed"
SRC_URI[deb1.sha1sum] = "082c4f83abbdff51fb0a2734b050558e235bb655"
SRC_URI[deb1.sha256sum] = "b09a5ad17f11b0f90b7d0f0262dc363b6ec59625a9b55d1cdc2a6feb7c7f349e"
SRC_URI[deb1.sha512sum] = "c09693eedabd4d5507faf78621e956ca53b1602c857c6676f3d367bdfee951289c096c0d21ebf499b22d67194fb7e3c714209cc5e07a3bb029089a1aa70d3f44"

RDEPENDS = " \
    libc6 \
    libogg0 \
"

