# This was autogenerated! Do not modify
SUMMARY = "Yet Another JSON Library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "yajl"
HOMEPAGE = "https://lloyd.github.io/yajl/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/y/yajl/libyajl2_2.1.0-5+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/y/yajl/libyajl2_2.1.0-5+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "673d40591d089485358604ae174ef5d2"
SRC_URI[deb0.sha1sum] = "26b344e88a5203ec9d8d83796a8639ece65ff93a"
SRC_URI[deb0.sha256sum] = "98497e30d6672298111b74e59890b3232b947abe4ecf04e39f480413b755e4f5"
SRC_URI[deb0.sha512sum] = "c7d214a40e4d139a6fc2430603948f11a68e009a4670616f021dda102cc9e03cb9b9bdeb7322b5fb1e662e09baca04b0524539bc50cc1370a264ce9fbfe82ddd"
SRC_URI[deb1.md5sum] = "29e017404999ac8db61715b695f1f4f1"
SRC_URI[deb1.sha1sum] = "f322f8e67fc99488957aadf57357bc56bd6e1dbc"
SRC_URI[deb1.sha256sum] = "24fa6da12564ea776c508641fe63a8b6a3b3a3a22b671013539cae8f6748cf80"
SRC_URI[deb1.sha512sum] = "26637a9ed40f355f106c554da546a7d51461d9df9d0a6d746a3784dbae82ee3ca0838c122be28c5a90ccff839334b022bfaeedce6c39846c46b8c21e5516796a"

RDEPENDS = " \
    libc6 \
"

