# This was autogenerated! Do not modify
SUMMARY = "Vendor neutral GL dispatch library -- OpenGL support"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libglvnd"
HOMEPAGE = "https://gitlab.freedesktop.org/glvnd/libglvnd"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libg/libglvnd/libopengl0_1.7.0-1+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libg/libglvnd/libopengl0_1.7.0-1+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d08caccc9be72f1c0632f9e5df0aa1c0"
SRC_URI[deb0.sha1sum] = "1a03fa48e855af83b10a03cee8e29628f41df00e"
SRC_URI[deb0.sha256sum] = "50ea65a1141cbf6b02e41492963656ad0ba71d257cc4066ee9756bca7a6c1ac3"
SRC_URI[deb0.sha512sum] = "d8d3511d011439167accbde521c2902bb99f36dd6f68a2d2d2b32764adb932e7deb7f2737830ea62ec9ff21ca17c8ec6d7c16b1e39e032ac56fd207ff8370d1c"
SRC_URI[deb1.md5sum] = "a891ec303acaa955f7c64727346b4611"
SRC_URI[deb1.sha1sum] = "47aa24c2df209a25d8c985f4729f57252765f7dc"
SRC_URI[deb1.sha256sum] = "1880bc8e29a9dfd2823fc0b88f514eb65699d961ec967d2ed2ba692c241fa09a"
SRC_URI[deb1.sha512sum] = "b75377a8c358ef44bbca662d58bf8a41cf8eb4bed6fcefe50d085ba33e7f79602730bf70c2ccd08f7e4c837f646f8b2d5ac1da54e93cff6ad687e51125d9c8a3"

RDEPENDS = " \
    libc6 \
    libglvnd0 \
"

