# This was autogenerated! Do not modify
SUMMARY = "extensions to the C++ standard library (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "abseil"
HOMEPAGE = "https://abseil.io/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/abseil/libabsl-dev_20240722.0-4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/abseil/libabsl-dev_20240722.0-4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8b0b0db17d1e210a3d851ea093734ddd"
SRC_URI[deb0.sha1sum] = "3004411469ec7796fb1037d7f3d1ba1169b3df6e"
SRC_URI[deb0.sha256sum] = "5036eacaaa092524fa2fdb2ae6ce0db188ee2c6a742dc3d6986151ab2dfc8a92"
SRC_URI[deb0.sha512sum] = "4b00fbb2106260a40b636eec7e183a500fe714e9beb4d23f0f7ff7a00c0156e42e5e10fab7cd867849f587576cf3a1b55db202579c149fa726099a67cea26d40"
SRC_URI[deb1.md5sum] = "6be76742713f02ba008f54b11e721dc8"
SRC_URI[deb1.sha1sum] = "817973b0d0749ee62b6ac138c2bc0cf83bd26cea"
SRC_URI[deb1.sha256sum] = "221d6c0d8b5589cffb9bb4f4a9a46629a930f67617d5b2d0f2a6d3038508a150"
SRC_URI[deb1.sha512sum] = "748074650893bdd321e26e28b64c3e7c650f6930dbd14f0f3b73b43b80619ab13b0e04a5b49f119dce649eceba0b97ac0097642ac97b9f32f5bef2d87d70a8cf"

RDEPENDS = " \
    libabsl20240722 \
"

