# This was autogenerated! Do not modify
SUMMARY = "style-preserving TOML library for Python"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-tomlkit"
HOMEPAGE = "https://github.com/sdispater/tomlkit"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-tomlkit/python3-tomlkit_0.13.2-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "919a627a2e8ddc9f95d4e097bf4a3f99"
SRC_URI[deb0.sha1sum] = "549651fce68651fc8c751cfcb1e2beac2eba07e4"
SRC_URI[deb0.sha256sum] = "eb63552797125eeb2c5eee60da580f7514f6df0d24c915d9621b4f192f5b53de"
SRC_URI[deb0.sha512sum] = "7516937701391ce2b60c18299bb56c946f03766367fc4ae527cab9e95480f4ffb6ee1015f99c26754b8237a54f6c244b142ea2e6ca95b16ba2c6d9ce907ddac3"

RDEPENDS = " \
    python3 \
"

