# This was autogenerated! Do not modify
SUMMARY = "Unified Configuration Interface"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "uci"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/u/uci/libuci1_20250206_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "06909642d3b20efa6b3e4e3f5def9488"
SRC_URI[deb0.sha1sum] = "8cedf97c89673d4a3be9b21375f03aa174d96daf"
SRC_URI[deb0.sha256sum] = "9a72f99aabc21b2fa8c817ee4cd6570fee90bc43bf18c6bc8f1e78c13cc02085"

RDEPENDS = " \
    libc6 \
    libubox1 \
"

