# This was autogenerated! Do not modify
SUMMARY = "Secure Sockets Layer toolkit - cryptographic utility"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "openssl"
HOMEPAGE = "https://openssl-library.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/openssl/openssl-provider-legacy_3.5.6-1~deb13u2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/openssl/openssl-provider-legacy_3.5.6-1~deb13u2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "276e8f78023167ca2ad52fa8e767b0ae"
SRC_URI[deb0.sha1sum] = "3b5367f36e8989c6021e165214a9afe7a2110121"
SRC_URI[deb0.sha256sum] = "feac35e2e79f70ca54abe3ffe3d7eeb51af5e56789d3b668df1ea4e6644db0a4"
SRC_URI[deb0.sha512sum] = "31548e4bddd82afaf3e539546dcc1b101555450f931a0bbbfdcf5cceb9c887169ee8a937498bbd0918db6166f8fdbe5b0fb8930bb93fe0121fa3d8132eb31458"
SRC_URI[deb1.md5sum] = "21c0d10775611ac1a50b79ddcb215e64"
SRC_URI[deb1.sha1sum] = "d5a41e70f8551fb076606ed0b1c0dab7fa9bc32d"
SRC_URI[deb1.sha256sum] = "b099729f6a38d7d57f7f442f0f836c862673b9bb0ee65d757da6e3cdebbfd2a4"
SRC_URI[deb1.sha512sum] = "c4fce450e1d98d51e9b7d2caa003b08a9107357d16982b1ebd6cba314b595092b8813f212b5bcfa197f418d23bdc6bbe16025ce1fc4e8b832adfb0bd846d1097"

RDEPENDS = " \
    libc6 \
    libssl3t64 \
"

