# This was autogenerated! Do not modify
SUMMARY = "XML parsing C library - development kit"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "expat"
HOMEPAGE = "https://libexpat.github.io/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/expat/libexpat1-dev_2.8.2-1~deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/expat/libexpat1-dev_2.8.2-1~deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "db456d1618ee4892cc66fddbe74c50ef"
SRC_URI[deb0.sha1sum] = "32838d916b53e41b138eae329a776463599ac0a1"
SRC_URI[deb0.sha256sum] = "9b78603ddfb844fe3379f67da14ee856bf5aa63fa543ca760985b1abb583c7c2"
SRC_URI[deb0.sha512sum] = "82c273683912cf96b848309be7a09f699c00bdf76e5dc5e2293fddcbd2214df69bbea41f708e623ed3f358df22d221a75821397a37a8caf46b14da1ce550921b"
SRC_URI[deb1.md5sum] = "de4d365e0e94d6a3d66047005c7ad182"
SRC_URI[deb1.sha1sum] = "3969b6c528243a41a82a8e2b2a3b0342a993dce7"
SRC_URI[deb1.sha256sum] = "098445a0b4dd4b7d03b1b90cb4ca98c221ac95c596fc45052a3d75260669e9fd"
SRC_URI[deb1.sha512sum] = "ab93d969566a8bdfeb5da85649056f57ceb75528e732af3c89b4835b5f0e63c9bd87f383d98b5c8442085967db8ec3c55f5b3cb3f3b464204a32dcdd5903e421"

RDEPENDS = " \
    libc6-dev \
    libexpat1 \
"

RPROVIDES = " \
    libexpat-dev \
"
