# This was autogenerated! Do not modify
SUMMARY = "File type determination library using "magic" numbers (compiled magic file)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "file"
HOMEPAGE = "https://www.darwinsys.com/file/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/file/libmagic-mgc_5.46-5_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/file/libmagic-mgc_5.46-5_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8da55a327bbd532ce7b78c1aeacd1ec9"
SRC_URI[deb0.sha1sum] = "893ce13de17a5f241dff5ac9fd79a5a92e41ced1"
SRC_URI[deb0.sha256sum] = "1368da7c4c7dd10fb2f9ee3ed8a70801650c0c1d249a4076af15e2ddfbb14b46"
SRC_URI[deb0.sha512sum] = "887b6ff4f3a7e17e7fd9171a9b54e983cc043d0098bb0b6c798766ce35285176bd55bd3803bcc46b690f503d501dc4f4e4df3bc1a966602f7089ef5d7c1f3c3f"
SRC_URI[deb1.md5sum] = "de7f8d76cc1365f660cab3e3f490b01f"
SRC_URI[deb1.sha1sum] = "b97b2f6bb2f8024ec7b8ac96a3099969833f0a1e"
SRC_URI[deb1.sha256sum] = "3b09b5391373b137ea8c881fafdf708d621816c27cd546edaaf559204490ab5d"
SRC_URI[deb1.sha512sum] = "548a2ec861783646fdbad529c34fee5b04cbb0162259a1dff52fe29a9fb682d35c7c74bbf5cf3227a2d04e9eef04ab930f65d0f204818386adf16fe7e0d7bba5"


