# This was autogenerated! Do not modify
SUMMARY = "Recognize the type of data in a file using "magic" numbers - library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "file"
HOMEPAGE = "https://www.darwinsys.com/file/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/file/libmagic1t64_5.46-5_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/file/libmagic1t64_5.46-5_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "83a3a06a0d2d58dce689b3fc03fed596"
SRC_URI[deb0.sha1sum] = "9cc6a691e8acacc7ab1f6ebeac2e9da3545659a4"
SRC_URI[deb0.sha256sum] = "53f653873216b135570b42c423ea93825c008ac464780b4578e80ee424237a4e"
SRC_URI[deb0.sha512sum] = "54d2eadcfe85943893e7de1cd2ebcf8fe795176b952f3dfb2bd59da9ce47215e59dea50ae6cb2be09d3ff2a2d2cea0a86c7127041e67c7e5493a844f3b073f00"
SRC_URI[deb1.md5sum] = "d589749269660e1fa04723cd6134018d"
SRC_URI[deb1.sha1sum] = "436e4a22b6db7c220a7713f3f6c645015c1e6387"
SRC_URI[deb1.sha256sum] = "c37244e188d63139b0e7d175a1d8e81253a6b505dac7b5c14e2fd9142f1f5672"
SRC_URI[deb1.sha512sum] = "0d50186bb4e2df5be0074d9ca00820a3a795210e1370748da9eea7c0b65f1799ac1b3c15837791430f2ffb6441841a06823ee7e0055821d568947a447ace0080"

RDEPENDS = " \
    libbz2-1.0 \
    libc6 \
    liblzma5 \
    libmagic-mgc \
    zlib1g \
"

RPROVIDES = " \
    libmagic1 \
"
