# This was autogenerated! Do not modify
SUMMARY = "Library for computing Fast Fourier Transforms - Single precision"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "fftw3"
HOMEPAGE = "https://fftw.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/fftw3/libfftw3-single3_3.3.10-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/fftw3/libfftw3-single3_3.3.10-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "7afa52e7eea2200f6d783db7aa71b1cf"
SRC_URI[deb0.sha1sum] = "9dbcbd4a58ba39447358c845f7d5cbefbaba8459"
SRC_URI[deb0.sha256sum] = "cb1910b561a4c475a8005ae1b604d1f5fd9d22114292f45e258ce4a160300e01"
SRC_URI[deb0.sha512sum] = "58c7d096a40aaa6e045d36b7cc366b25a91403738403582b475ce582913fcdfd95865bf5239dc7ee18c373942a5fc5e9d04f1a519006170cf2b97a5a9c5f605b"
SRC_URI[deb1.md5sum] = "92698e9137a08168340a8983ab890b8d"
SRC_URI[deb1.sha1sum] = "90040b72c8f0309ff7409723bc6d6fd478c143ea"
SRC_URI[deb1.sha256sum] = "874b10ccab6219bcae210cc9ff9298389e266ad7308be086956c859ae1aa8ba5"
SRC_URI[deb1.sha512sum] = "c035de4c2467fc9b646976c5899d78afcc45b0c7d6d661a6aace1c9f2d38a40b5239dd2ae6c1bb1571e7da61066d107c6a69207b02cf2b0661eb3f8a1d59753b"

RDEPENDS = " \
    libc6 \
    libgomp1 \
"

