# This was autogenerated! Do not modify
SUMMARY = "Reliable Internet Stream Transport -- shared library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "librist"
HOMEPAGE = "https://code.videolan.org/rist/librist"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libr/librist/librist4_0.2.11+dfsg-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libr/librist/librist4_0.2.11+dfsg-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "fbeb76d92596a0f71b1c71f7c90a57b1"
SRC_URI[deb0.sha1sum] = "6ee503b6f0bc26900c882e6fd47813827b293313"
SRC_URI[deb0.sha256sum] = "a3f66bd87fdd95561ec41894a782ca9e2e9272ed72c925be8a44da95e41a03b2"
SRC_URI[deb0.sha512sum] = "18d9b23e40fb6124ebf6dbad7f97c378f7c5f90dab1575c84dd834fa8a16f16af2155924138beb9e577b427f8291df2a0fcf3c4d8dc6b07ec06728c771d98936"
SRC_URI[deb1.md5sum] = "2a3477eccb19076292a95cc0b04e3608"
SRC_URI[deb1.sha1sum] = "4dfade3a19bc892c2dcbb05eec6ba54a1c520040"
SRC_URI[deb1.sha256sum] = "c0614f5e8696430801e201d958bc00d442008e9bd58915313a314cac475b295c"
SRC_URI[deb1.sha512sum] = "6bb57b287e690bf7cc0a020618f779f77935efe4ad41b17db4f85b0d17c500efd2e16da9c108bcbd8002f08a0fb51ef4696d572f5f46436f4a7fe081b0caa0ca"

RDEPENDS = " \
    libc6 \
    libcjson1 \
    libmbedcrypto16 \
"

