# This was autogenerated! Do not modify
SUMMARY = "minimal Perl system"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "perl"
HOMEPAGE = "https://dev.perl.org/perl5/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/perl/perl-base_5.40.1-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/perl/perl-base_5.40.1-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "7b6368cab00c867c1f1978a2717abc78"
SRC_URI[deb0.sha1sum] = "170febe68b6846ec3f9341fd618179c79d4f7804"
SRC_URI[deb0.sha256sum] = "94f1060613a666dc569026a8344bee202ba3b29ec124dc6ef30bfc72e735c78b"
SRC_URI[deb0.sha512sum] = "eb0ae9655117652a1d1128f5179184247576b9f07027bbc78364796e8dbbe6b5e052c5a3217539fdb58acded6c5ae52096b727c44e190b8d68b928f799ded83e"
SRC_URI[deb1.md5sum] = "d7724d307a4a6a612059767fc3f4b3ef"
SRC_URI[deb1.sha1sum] = "118feee7a1d3456ca143a8c510a48d66ad4af3bd"
SRC_URI[deb1.sha256sum] = "65eef1a545207309b9ce87139be81be9dd12f24b0bd12be935cb36e51bdb6f2d"
SRC_URI[deb1.sha512sum] = "be768ba00fdb29c0662a94b63d2ad6498c9e2df6405ab19d4b07f97c3abe2e71267b2b8f9dc32233e049de6e4fba9ff3e5ccb9006f6b30f9a5dd67d1d63a0c70"

RDEPENDS = " \
    libc6 \
    libcrypt1 \
"

RPROVIDES = " \
    libfile-path-perl \
    libfile-temp-perl \
    libio-socket-ip-perl \
    libscalar-list-utils-perl \
    libsocket-perl \
    libxsloader-perl \
    perlapi-5.40.0 \
    perlapi-5.40.1 \
"
