# This was autogenerated! Do not modify
SUMMARY = "interactive high-level object-oriented language (default python3 version)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python3-defaults"
HOMEPAGE = "https://www.python.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python3-defaults/libpython3-stdlib_3.13.5-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python3-defaults/libpython3-stdlib_3.13.5-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1a62d5a7546d4924a3de7de3dfbfa323"
SRC_URI[deb0.sha1sum] = "ee2d3c4d8cec0f62aff45a3414d1d4eda120b3c4"
SRC_URI[deb0.sha256sum] = "7e142ed64a81ccdd39714f213467bd365736ef341adb2be11be981f638b9175f"
SRC_URI[deb0.sha512sum] = "7ebf084c346d57963eb2386f21f8d5c955763b105983f37530e43525cd854ba78a8d400d48b36e2ac8d897dfa6ddce1b074249fdcf42443aa862f93f1bfff3d3"
SRC_URI[deb1.md5sum] = "37bda3e635c0316f2ab6826013f45c41"
SRC_URI[deb1.sha1sum] = "0997df5c848fffd424f0968d71ee6140146dd5a6"
SRC_URI[deb1.sha256sum] = "0e5b09b3c90f34399a357c32e1be08a3f31b39d3c615464f00354b309f82e732"
SRC_URI[deb1.sha512sum] = "3a854f737b6d102094270a4d49c234c71a5398b899e507f20a6bfbf6028d36aa23d73885f3f682b1ab64d6c1f72715d419fe7aec83eef7d35675d581a89b54e1"

RDEPENDS = " \
    libpython3.13-stdlib \
"

