# This was autogenerated! Do not modify
SUMMARY = "HTTP/3 library with QUIC and QPACK (development)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "nghttp3"
HOMEPAGE = "https://github.com/ngtcp2/nghttp3"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nghttp3/libnghttp3-dev_1.8.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nghttp3/libnghttp3-dev_1.8.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "3505b5209628de32b30ae395287ca082"
SRC_URI[deb0.sha1sum] = "14688d9f20699ae6db8b53ddd5c06302b0f38cad"
SRC_URI[deb0.sha256sum] = "47089a3bfde3562ea4524ceb768186045398012a466499268b8a5fb115b81a4e"
SRC_URI[deb0.sha512sum] = "193eb7fea5ffddadc59db33d5a8602f6256f9c3d82e9ae8f075ab132f43f393e57ad2c478ab963aebe33a61f5002c3092f795af465b392bb3c646914663704c5"
SRC_URI[deb1.md5sum] = "b2b31c459516aaca951ae8f3d8a1866e"
SRC_URI[deb1.sha1sum] = "71962b9607a4b1b79c350c62d4c2d4d62de73ec7"
SRC_URI[deb1.sha256sum] = "d8a0f1398d67279edb181485ac7e6c9ef67871cdf4585338846e1c8bbde1e91c"
SRC_URI[deb1.sha512sum] = "6a4973e51581cd997a9464df2f2c8f293d021359b292d3b069d6661cdb38f8ed7b732338009395687ee75af9c2c712b96eb466145b329bd1ead725567ab42679"

RDEPENDS = " \
    libnghttp3-9 \
"

