# This was autogenerated! Do not modify
SUMMARY = "subordinate id handling library -- shared library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "shadow"
HOMEPAGE = "https://github.com/shadow-maint/shadow"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/shadow/libsubid5_4.17.4-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/shadow/libsubid5_4.17.4-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "cfecdd3c987d4142ac2ecd3b597785e1"
SRC_URI[deb0.sha1sum] = "115bd4ec8a55ebf97fb8c987e96fbc199e21ae23"
SRC_URI[deb0.sha256sum] = "4d4faef8143c117a055a9041a7e99f8ba014c420a9b6e2fef5c693482581a204"
SRC_URI[deb0.sha512sum] = "6d140d10e55e4761dc10acd85d3c95736302f844b63bc66b2f4472bbd84703709889bd8cd3e3b11a8c9aad6d30140ddd3f2c056edee1377dbe866a2770c8a63b"
SRC_URI[deb1.md5sum] = "9c86f6891d9d6205ca1e170a25b1f527"
SRC_URI[deb1.sha1sum] = "9336ae364f30506d66156f1dfe51133bcdb0dc4d"
SRC_URI[deb1.sha256sum] = "0cbd234e3e1afad8195cf12d87c7eb820a3e55b252e48da930cd9f0df3e787c1"
SRC_URI[deb1.sha512sum] = "8b55e21666c427a2234839f91b6c7d4331b4d6c11727e5919187eba29af0c4794c76b89aee7063466315306e8173daf8cf4714e98671937e15de969642a21239"

RDEPENDS = " \
    libacl1 \
    libattr1 \
    libaudit1 \
    libbsd0 \
    libc6 \
    libcrypt1 \
    libpam0g \
    libselinux1 \
    libsemanage2 \
"

