# This was autogenerated! Do not modify
SUMMARY = "braille display access via BRLTTY - shared library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "brltty"
HOMEPAGE = "https://brltty.com"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/brltty/libbrlapi0.8_6.7-3.1+deb13u3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/brltty/libbrlapi0.8_6.7-3.1+deb13u3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b6c027232a966affeb7680cd7e20b32d"
SRC_URI[deb0.sha1sum] = "698f4ebd819d609a03c67e99e7e68fff0c12a024"
SRC_URI[deb0.sha256sum] = "d8767805735bfae0edbe793fc8b6f6266ac9e55bec88c3d36b567c41b6438ca2"
SRC_URI[deb0.sha512sum] = "aa62fd5202f614cdaeb63637f194451726b590d596d4a9cd1c9378296b4e5b2726ff8591be8f6f91a65659a9b2319b02770ab5c2e62831cfc51f69294cdb5dfb"
SRC_URI[deb1.md5sum] = "b8169fa59f53b1469f122682eef84b76"
SRC_URI[deb1.sha1sum] = "c7fc849cf21303eb07cadc2689a48d6b4f654bb4"
SRC_URI[deb1.sha256sum] = "87baeae48d35a00805dcc15d6e3a73272890c4db1a1a755a132d170aa17bb208"
SRC_URI[deb1.sha512sum] = "10b7bfb9baed82b2f0caf8cf621635adcb90a3fbc3321d47ecbdbcf8c7fd9b255a2b12b0e6283b9895c6bfc3c7f45c14d1ac362027522a2b10dfeead500327c2"

RDEPENDS = " \
    libc6 \
    libsystemd0 \
"

