# This was autogenerated! Do not modify
SUMMARY = "tiny C SSH library (OpenSSL flavor)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libssh"
HOMEPAGE = "https://www.libssh.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libssh/libssh-4_0.11.2-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libssh/libssh-4_0.11.2-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "dd8c6b63d74dcc72deb5ad08fc9ecc1c"
SRC_URI[deb0.sha1sum] = "32d0d272c64b56aa299d19895f5bf0b66c17864b"
SRC_URI[deb0.sha256sum] = "6b0f7d26c69bf9b18ebed6b77b4cbc57835f7ba956abb8ae00ef866372296ae2"
SRC_URI[deb0.sha512sum] = "a00dbb14a6550f57880b9e6f54c6ad4bd7b11430d940686bb9dfa68966d7e4a97124773b357edb02e852e65877746e46abca06e9da70e25667610c6b8b540e29"
SRC_URI[deb1.md5sum] = "581602513e1445986c682f39aa1e6ad0"
SRC_URI[deb1.sha1sum] = "2719048979ef313897eb5197b07773e6ddba3a55"
SRC_URI[deb1.sha256sum] = "580f894dd44593ee5f89783530ff3708dde83ff3443a2bf8e441ae29aad81226"
SRC_URI[deb1.sha512sum] = "997742a4662b14ad914a885f7b19fb9ba64768e49b6f03d5768ae6dc51bda49d6a63c026bd1dcce84ca0b42d7f3fbb53445a643ef072d258faa8977e16e7949a"

RDEPENDS = " \
    libc6 \
    libgssapi-krb5-2 \
    libssl3t64 \
    zlib1g \
"

