# This was autogenerated! Do not modify
SUMMARY = "X11 pixmap library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxpm"
HOMEPAGE = "https://www.x.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxpm/libxpm4_3.5.17-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxpm/libxpm4_3.5.17-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "7466c0184f89f5ea9ae405e44c138182"
SRC_URI[deb0.sha1sum] = "18f306c1b41053db8a630b7f5480ff8b2221fd91"
SRC_URI[deb0.sha256sum] = "d2f8933b552e7a282bbc32bc7545628195c4a3692a20ad0e232cc5fee9130790"
SRC_URI[deb0.sha512sum] = "bb44e44c508bb7976a2572beb1b14772358f1658de456b3a8c2322688061b7c50db9c94dc9373f49fddffb5d901a5f3f0cd82a5bebedde8ed5507dc267eabc36"
SRC_URI[deb1.md5sum] = "74e7456470aae8e01dc846129dcc6af1"
SRC_URI[deb1.sha1sum] = "5d4bf77d10b9254a69f0921429d33ca2df851fc4"
SRC_URI[deb1.sha256sum] = "7af00645e130ee865951795dee7b504e82f59e871ec1c6e255904edcb8ed266f"
SRC_URI[deb1.sha512sum] = "a4626b72fb1e83102ab67b4b09dc2743677701f1d419c9cbcea99b0cf651598242637c6f24d9afc37199c9853e530e41cb4c4cdf5f7bf76c9f377eaa8d2dd636"

RDEPENDS = " \
    libc6 \
    libx11-6 \
"

