# This was autogenerated! Do not modify
SUMMARY = "Modular compiler and toolchain technologies, runtime library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "llvm-toolchain-19"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-19/libllvm19_19.1.7-3+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-19/libllvm19_19.1.7-3+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "46d9b011e2daeb518da6dd49e8d81170"
SRC_URI[deb0.sha1sum] = "1815a811f2dcc3c2b27c41f015af2223eb3a5d74"
SRC_URI[deb0.sha256sum] = "db0d614d61345ca710fb73e75105f1ec6e38898fa7b3aa99fa7eb7d8b0a11d57"
SRC_URI[deb0.sha512sum] = "fe0086fd0c710cf856a1803cf640a23a0586db9c07a833734fd768c8097639e50e561ea0f808e3ceab1854728d53043f1d56668db34c5114e51848923b80f692"
SRC_URI[deb1.md5sum] = "7559baa773117c7b713d8104645662c1"
SRC_URI[deb1.sha1sum] = "6747341239003915b31ca6077d96bed559f73c1b"
SRC_URI[deb1.sha256sum] = "8a48e1a49f7fcc3be74e697767d72902f4b03041401d1529bcfad1849df39148"
SRC_URI[deb1.sha512sum] = "c7d7731420718f3aa6c12d1cdf0da9ac524242f47c5fb944b0cb69d00cf8ff4605bfc007bbf4f26a4e91d5e9cf6c8ec1439e653e570b354d5c6654bde882de65"

RDEPENDS = " \
    libc6 \
    libedit2 \
    libffi8 \
    libgcc-s1 \
    libstdc++6 \
    libxml2 \
    libz3-4 \
    libzstd1 \
    zlib1g \
"

