# This was autogenerated! Do not modify
SUMMARY = "Foreign Function Interface for Python 3 calling C code - runtime"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-cffi"
HOMEPAGE = "https://cffi.readthedocs.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-cffi/python3-cffi-backend_1.17.1-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-cffi/python3-cffi-backend_1.17.1-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "f1d07604d457a4939d658f0a698cc4d1"
SRC_URI[deb0.sha1sum] = "82509aab35933296efba440a16ef68c55f4be13c"
SRC_URI[deb0.sha256sum] = "7cfe53f3eff772127fd22e503876e3dd2b34b4c2a68fe9a524ce214e5bb7927a"
SRC_URI[deb0.sha512sum] = "ef6fc5cb43c2cad45e716ac82dfd71b9fc9ef40c4a69f28970c2768cf848a43b7ada183a0ca9d76a37d58473e38e88217f93cd76ad643fa4e57b1849f80f6a30"
SRC_URI[deb1.md5sum] = "9670d588ed3dcfa62d5fbf08ba96098f"
SRC_URI[deb1.sha1sum] = "05d907eb8bd4463a9d460842fa175069ae4e7aca"
SRC_URI[deb1.sha256sum] = "e11e59b2bd2d17a6ac5a37b63c806518563ee5a436152a91284c5514b94d67af"
SRC_URI[deb1.sha512sum] = "6d685e55ce58bd37c5821edf19a6d12e7dd789ed70f45ac0325ecf0b97be080a524e04a1cba9a4a861e74ac4002d54eb02978959e3c6339165e05843ed7da1eb"

RDEPENDS = " \
    libc6 \
    libffi8 \
    python3 \
"

RPROVIDES = " \
    python3-cffi-backend-api-9729 \
    python3-cffi-backend-api-max \
    python3-cffi-backend-api-min \
"
