# This was autogenerated! Do not modify
SUMMARY = "tool to manage containers and pods"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "podman"
HOMEPAGE = "https://github.com/containers/podman"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/podman/podman_5.4.2+ds1-2+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/podman/podman_5.4.2+ds1-2+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "5066cb9baa248c8dde58e27cefa27245"
SRC_URI[deb0.sha1sum] = "88cf22a55b360b21b46b87364f6fd7533135315c"
SRC_URI[deb0.sha256sum] = "e3987a9d1e6d46cbd4ee11bd067927a5f7f886e41c7a2dbe5b89a436905d44a0"
SRC_URI[deb0.sha512sum] = "d2f4ad3443bf7a8d042bca451d47d7de2f0677cc23f938c36ead5a4eebe4c8dab9c727178246b03fae786e3d3e547695911d8302eab83c33bed994522206f794"
SRC_URI[deb1.md5sum] = "dd235494e189de2444d3d324c360c384"
SRC_URI[deb1.sha1sum] = "8cfa16a8d7a038da13243693542f7d2120b7162f"
SRC_URI[deb1.sha256sum] = "3df3cd889c6d04b8090894cb32dd54911fe774b15373d750fc8c53821d8b7b2a"
SRC_URI[deb1.sha512sum] = "d6be88e941ca0228c6e7d6b90628062d421a6ed5072ae91d734efc7a845630467f93fdd03985e56af61f8b68bed6d04e01683c9d024a0601162f3ec7eecd6ed6"

RDEPENDS = " \
    conmon \
    crun \
    golang-github-containers-common \
    init-system-helpers \
    libc6 \
    libgpgme11t64 \
    libseccomp2 \
    libsqlite3-0 \
    libsubid5 \
    netavark \
"

