# This was autogenerated! Do not modify
SUMMARY = "debug symbols for libmock-safu0"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "safu"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/safu/libmock-safu0-dbgsym_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f6b1f4b0d58f34bf0e2f9b1dd65c3c3c"
SRC_URI[deb0.sha1sum] = "b02c4f17dd33a97a5fea8588cca6e1dc628774de"
SRC_URI[deb0.sha256sum] = "a85cc7df264e112ffe88f496485e7ee5c2f65e1461db70c60a7108ad88950424"

RDEPENDS = " \
    libmock-safu0 \
"

