# This was autogenerated! Do not modify
SUMMARY = "Stateless OpenPGP Verification-only (SOPV) CLI (rpgp and rpgpie)"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "rust-rsop"
HOMEPAGE = "https://codeberg.org/heiko/rsop"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rust-rsop/rsopv_0.6.4-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rust-rsop/rsopv_0.6.4-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8f58d589c22265fc859a0dc041ac3a3a"
SRC_URI[deb0.sha1sum] = "a4ae7549a37c7361fba7c1381ea171ba1744cfad"
SRC_URI[deb0.sha256sum] = "e8027485cbac466161ba61736ff1d581b3478aefd07206f3b0454bedf2e6424d"
SRC_URI[deb0.sha512sum] = "1e749946dd12de509c4699d6800d16b1ed143bd9385431afe67c56bc761db3c769f4ee0321337922a07e3c6c672523da0b94c624787f2420db268e800f5133a0"
SRC_URI[deb1.md5sum] = "75c45f4dffca785196d0f78be8a04c56"
SRC_URI[deb1.sha1sum] = "2bde03ac85498cc79954cb645913fed2a6c937af"
SRC_URI[deb1.sha256sum] = "5fbf6c4b3f1b4316e7603212417e8eafbe21619101a74a487fb809d504a12770"
SRC_URI[deb1.sha512sum] = "73174d5e068e88b6869f8fb7e0eb4bb078e80f1a3580c1f5ff74906c375882982eb00c5dfa5cbfda34321013c20f693168b52de579c86600764266945e9e8522"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
"

RPROVIDES = " \
    sopv \
"
