# This was autogenerated! Do not modify
SUMMARY = "Asynchronous name service query library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libasyncns"
HOMEPAGE = "http://0pointer.de/lennart/projects/libasyncns/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/liba/libasyncns/libasyncns0_0.8-6+b5_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/liba/libasyncns/libasyncns0_0.8-6+b5_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c4868c175574e6ec20cb7af66803aca2"
SRC_URI[deb0.sha1sum] = "5f80e84e0c0354e3980df6fb3963df39f64dc61a"
SRC_URI[deb0.sha256sum] = "e7958777b0e3586349c57ac759a95b68f80d28e5bd1c4225705198b39b436115"
SRC_URI[deb0.sha512sum] = "71451d275a52a22faa71ce0bda3d06128ccef4b02b127331666b5d011cfd724627f550b1e1d4e5bff06fbc5a21c138ba94a3076dc7e692d2e94b3fc7e7354d23"
SRC_URI[deb1.md5sum] = "e07bf8ff4150133029caa3798fbee913"
SRC_URI[deb1.sha1sum] = "835c9618b0ba2ef7c29e43452794decad7e650d8"
SRC_URI[deb1.sha256sum] = "818bbcaa7ada536a1bdd5b1c26b77608606403f5c15557691e83d0b4433b89ef"
SRC_URI[deb1.sha512sum] = "34b7e2cb99fdd626ce74109aab27e6d509a079cbb3729632745f8b5cc0deaa0bd1fcecfaec78f560ddcc7059fb512d6109e722cf9b7950866364905fbcd6b252"

RDEPENDS = " \
    libc6 \
"

