# This was autogenerated! Do not modify
SUMMARY = "OCI container runtime monitor"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "conmon"
HOMEPAGE = "https://github.com/containers/conmon"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/conmon/conmon_2.1.12-4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/conmon/conmon_2.1.12-4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1dba156c56e5f60b81eaa09ad000cf6a"
SRC_URI[deb0.sha1sum] = "d402c0a908f711def0b9c84ddb04877e40918653"
SRC_URI[deb0.sha256sum] = "5de1cc371415dc0a75d988d74b89789a86a6d541de3ccaf2214e548c584d1605"
SRC_URI[deb0.sha512sum] = "289a31042dcc9dbd11dc2bd64ca89fc1d753c35d261037dc7c6e669f17ac4969aa74b05ec62a18b47cdcaa74ebd3685006adddd38f68bc6ba290c9819c1758d5"
SRC_URI[deb1.md5sum] = "6e9921f6192519d8037f1d0e0c334ca1"
SRC_URI[deb1.sha1sum] = "a9765e5fed271f1c2fd6fb71eef6b0ec39be89f2"
SRC_URI[deb1.sha256sum] = "ab363c81d7b775af77ff9dcbdd6fe0ffcdc643b27aba661ba5174f3f2557ea5f"
SRC_URI[deb1.sha512sum] = "8d0161abed6ac19fa6662c7e352b8a11eeec2533d52507167933262f3533d3b70a020f2eb1332b5e07d61bd72284099bd18bbe2c4a867758a2c8e311f7e01a3f"

RDEPENDS = " \
    libc6 \
    libglib2.0-0t64 \
    libsystemd0 \
"

