# This was autogenerated! Do not modify
SUMMARY = "Wietse Venema's TCP wrappers library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "tcp-wrappers"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tcp-wrappers/libwrap0_7.6.q-36_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tcp-wrappers/libwrap0_7.6.q-36_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "0a132e896f6b55940d85795306f3c469"
SRC_URI[deb0.sha1sum] = "f68950b258f62f06af58295d7ae6c141a9a0e47d"
SRC_URI[deb0.sha256sum] = "cde12afa15d6b1556c5e0564d22edf3b99e6b8fa94c59ccd8b8eebbb62dc19ec"
SRC_URI[deb0.sha512sum] = "1af04f9074743a8c566497b223fe114916a5f983987661d389f87c9243c7889e48c2cffad4abfb4aa9cf455ed454503d8d1d57f8c839fae33e0e0d1dd12b7d59"
SRC_URI[deb1.md5sum] = "feb713dd65eb114c6998e2b6ffdfef76"
SRC_URI[deb1.sha1sum] = "2147a199f0eb525d8f88e6dfe925e10f7a627849"
SRC_URI[deb1.sha256sum] = "fd2e54582a07fba9c8a6f78c68dcc6d3c8cf1c70632a68124394bde4dccf52ea"
SRC_URI[deb1.sha512sum] = "ff4ca818a3a5d464213657c9dfacff3b5ed37d539c809619b8eefad8c36e6939298755af51694d2351a4e85d07652931770eadd4e4984df8af6c2fb3e15424d6"

RDEPENDS = " \
    libc6 \
"

