# This was autogenerated! Do not modify
SUMMARY = "scaling, colorspace, depth conversion library (shared library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "zimg"
HOMEPAGE = "https://github.com/sekrit-twc/zimg"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/z/zimg/libzimg2_3.0.5+ds1-1+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/z/zimg/libzimg2_3.0.5+ds1-1+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "16fdd1d8ee417b3b34bab63e6ebe741d"
SRC_URI[deb0.sha1sum] = "8a0f8089a05a9aa1a28cb7bf0e8a7ca4bedc27f9"
SRC_URI[deb0.sha256sum] = "d021b92ec5d647565db6b67e92a7e06e16b35ae6046c0f36d454a0cff88bbd50"
SRC_URI[deb0.sha512sum] = "c358642e0656297d4a0c157e1bfaa5534250a12a1f4ad1b5ad12789585b8891805dd216300809f3fa9e47e9118d9ba1c3396e3d33420e3008333a727a9fa5d73"
SRC_URI[deb1.md5sum] = "a316c0d5426d9cde83008f2533286ee7"
SRC_URI[deb1.sha1sum] = "68e38e96b46e15de2d827e84a1d1a0ea5feeace7"
SRC_URI[deb1.sha256sum] = "5f71dc6a1c7b91df4564a41b299e216b574e94e99afc49ff3f334be3816e3d5a"
SRC_URI[deb1.sha512sum] = "0dc028858ccfd6d4886f85ba838196582f0f9d20d1f1f157b27cbfe48e87c0265f4844ecdcdf80fbd99e0976108dbc5f41705cdfa9f0ed64df0c2b4ec3034ff9"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
"

