# This was autogenerated! Do not modify
SUMMARY = "GNOME XML library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxml2"
HOMEPAGE = "http://xmlsoft.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxml2/libxml2_2.12.7+dfsg+really2.9.14-2.1+deb13u3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxml2/libxml2_2.12.7+dfsg+really2.9.14-2.1+deb13u3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "381b30ad5e8669318c82153f776a0e40"
SRC_URI[deb0.sha1sum] = "1004cd76d8bbb2b8603eaf4ac38670d6b1b79928"
SRC_URI[deb0.sha256sum] = "e0c6b63ce4602a036a526f60fe5e6c1586710688058d98fc1001b9b3147b7efd"
SRC_URI[deb0.sha512sum] = "a47718fe817a02ad82bd338dac451f3c2b1c8404462591b390ffc1e868e88ed3cd10aeab5a997899aee6ae21bec06259eab75a4ba53b1798d13bc972f796d1ec"
SRC_URI[deb1.md5sum] = "a9e8d99406f5d5185074c9cb4523cec9"
SRC_URI[deb1.sha1sum] = "2134e5dafdd15479196fd07e3362c3d3424832da"
SRC_URI[deb1.sha256sum] = "a66b9c960acef8ed9653223cbd00b155a92ebb758ea13a788c41609246c23bc7"
SRC_URI[deb1.sha512sum] = "834700231d131c62577196b55a85d3b0ae8dd758082e8488f9229d238d5d5201acc927a1ea81deffd92104224d1ced9889aba9514c404689fead3b2d0b709830"

RDEPENDS = " \
    libc6 \
    liblzma5 \
    zlib1g \
"

