# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# Uncomment this if recipes are added to this layer
# BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
#             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-generated"
BBFILE_PATTERN_meta-generated = "^${LAYERDIR}/"
# Once this layer provides bb files, the following line can be removed
BBFILE_PATTERN_IGNORE_EMPTY_meta-generated = "1"
BBFILE_PRIORITY_meta-generated = "6"

LAYERDEPENDS_meta-generated = "core"
LAYERSERIES_COMPAT_meta-generated = "v0.6"
