# This was autogenerated! Do not modify
SUMMARY = "Secure Reliable Transport UDP streaming library (GnuTLS flavour)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "srt"
HOMEPAGE = "https://github.com/Haivision/srt"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/srt/libsrt1.5-gnutls_1.5.4-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/srt/libsrt1.5-gnutls_1.5.4-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c81b197031d175921195d1763a28b29a"
SRC_URI[deb0.sha1sum] = "011dd271cfbda9bfffbebf91ed007e2e9d84b401"
SRC_URI[deb0.sha256sum] = "e19a867c9697663183e2904ee8ac86f1579769d346c191bf6904629cb3791071"
SRC_URI[deb0.sha512sum] = "89e567a99929e2ea680531616baf56fe4acd44f098d3bf9d092b5609275fb3ecf47ff66b036b2210623cd1ecd008bd49a31a8fe5e7fefa585588b81b88eca615"
SRC_URI[deb1.md5sum] = "b802abb7b297c103521c537f9e103a0c"
SRC_URI[deb1.sha1sum] = "16d1935eda8d004ed1b60ab478d27e53e19e0067"
SRC_URI[deb1.sha256sum] = "ac6acf94b49232771ccf7e8289bb28e06b17718994a591c2a27e50d6e57a3360"
SRC_URI[deb1.sha512sum] = "ff49d176cd9979d479e7036feede0e4e9dc2d36cb3154704d6dde2e2586aab813c39d36882741b1a34ab295b979656520faf672c9adf85aa69bfa8b23b5be275"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libgnutls30t64 \
    libnettle8t64 \
    libstdc++6 \
"

