# This was autogenerated! Do not modify
SUMMARY = "debsbom generates SBOMs for Debian based distributions."
DESCRIPTION = ""
SECTION = "misc"
SOURCE_PACKAGE = "python3-debsbom"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/p/python3-debsbom/python3-debsbom_0.7.1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "1137585ee78470921e5394a4a82da76e"
SRC_URI[deb0.sha1sum] = "224dfe2563abbb8ed258a7246b211d5f62efaa16"
SRC_URI[deb0.sha256sum] = "9a83eed730743d4c95753e62a701ab9b90e56f57220407399a14dc23dd082f26"

RDEPENDS = " \
    python3 \
    python3-apt \
    python3-debian \
    python3-license-expression \
    python3-packageurl \
"

