# This was autogenerated! Do not modify
SUMMARY = "source highlighting library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "source-highlight"
HOMEPAGE = "http://www.gnu.org/software/src-highlite/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/source-highlight/libsource-highlight4t64_3.1.9-4.3+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/source-highlight/libsource-highlight4t64_3.1.9-4.3+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e9d82a402dd34388e57627083af7d102"
SRC_URI[deb0.sha1sum] = "fd61cb0c4756ff3e6883606f4c0339fdce7eb076"
SRC_URI[deb0.sha256sum] = "6d69c221c44345f33af52cc849c5d39438590d5b2030224a6fdb3e6e660f815a"
SRC_URI[deb0.sha512sum] = "78d730d459960b824b307a621589feebb3ca86fcf78e95f0d4c22a6ea7e72a82403f3aaa7c00c87d493e1e1fbfed6e43115eaa1c17cc156c943621e2b9536922"
SRC_URI[deb1.md5sum] = "ddc237f6020e33296555945add30f520"
SRC_URI[deb1.sha1sum] = "2316cabdb4b0b3ab83257c2b70922725422c89fa"
SRC_URI[deb1.sha256sum] = "bac0141f19cd66546afd4d262d97f2192572793076ad6444f0f7d2a894ce48d4"
SRC_URI[deb1.sha512sum] = "6b16160843363f13fd371c773c8b86c6003120434ffb2221acb8c84dd06730ef14a4ba1185da7dda0d8de7ccf807c1c5953f9e99f83e2cc0c685b0e391a41c4b"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libsource-highlight-common \
    libstdc++6 \
"

RPROVIDES = " \
    libsource-highlight4v5 \
"
