# This was autogenerated! Do not modify
SUMMARY = "debug symbols for samconf-tools"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "samconf"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/samconf/samconf-tools-dbgsym_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e69d8d20f590fecd4aedfa008e08b097"
SRC_URI[deb0.sha1sum] = "5120cb0f38510ab716547159ad669be17cdc941a"
SRC_URI[deb0.sha256sum] = "7fcef0d27f9ee7791992bbf771391f5526eb903a3a778c83551ae1e55b94f43b"

RDEPENDS = " \
    samconf-tools \
"

