# This was autogenerated! Do not modify
SUMMARY = "debug symbols for samconf-tools"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "samconf"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/samconf/samconf-tools-dbgsym_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "076d1af47bec180f498fd5e3c8d3126e"
SRC_URI[deb0.sha1sum] = "1bb6442b71799a2726cdccf25d26baf4ff3e4f96"
SRC_URI[deb0.sha256sum] = "8304730ff10291f480558039126171162b4df0c5a382cf60dd60ee381068af1d"

RDEPENDS = " \
    samconf-tools \
"

