# This was autogenerated! Do not modify
SUMMARY = "fast, versatile, remote (and local) file-copying tool"
DESCRIPTION = ""
SECTION = "net"
SOURCE_PACKAGE = "rsync"
HOMEPAGE = "https://rsync.samba.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rsync/rsync_3.4.1+ds1-5+deb13u4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rsync/rsync_3.4.1+ds1-5+deb13u4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8b6d1d3ae5bccdccf7b1b80339f3b76b"
SRC_URI[deb0.sha1sum] = "797cccca95b53521ac509b235ed402b6aedfe92d"
SRC_URI[deb0.sha256sum] = "8aa122f6ba8d2ff112c72bb9814ee096ee516f0213b36b98bbe79c83c92fb226"
SRC_URI[deb0.sha512sum] = "116d173a55f550f49c7ea780941bcad1df9bc244278ab7f4c3838cda5bf4ea5c65fd51d23124e0101b722088437a3e30c24ef097bd3f6a5bd0521612c8bc728b"
SRC_URI[deb1.md5sum] = "ab1c2ba5198d21016f22015f5e7e88f0"
SRC_URI[deb1.sha1sum] = "6f1b09a41456f66a3c1be88acbf7235d90d36727"
SRC_URI[deb1.sha256sum] = "67eb7ce60a056e23b86c0ac020fc00da62647fdbfbe34453693601f8db1abf29"
SRC_URI[deb1.sha512sum] = "ee4e8eeeb43533411592a6ee124cb04bf03136d19f4630e23f5899c30fa240b57c76430f510c8690cb9698a1eea1a0815f0e2b51416aab508bae7cf9eb521aef"

RDEPENDS = " \
    init-system-helpers \
    libacl1 \
    libc6 \
    liblz4-1 \
    libpopt0 \
    libssl3t64 \
    libxxhash0 \
    libzstd1 \
    zlib1g \
"

