# This was autogenerated! Do not modify
SUMMARY = "X Rendering Extension client library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxrender"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxrender/libxrender1_0.9.12-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxrender/libxrender1_0.9.12-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "ac7b3037243f273fda29a1d78fef7eec"
SRC_URI[deb0.sha1sum] = "07e9c43d74776b99891fd817fccf4ac8c402b695"
SRC_URI[deb0.sha256sum] = "9d042dfd5e613be1e02e6ddd0c5c4adef19c5eb08f6db838c2eba672c496dca4"
SRC_URI[deb0.sha512sum] = "ef24ffe1015af7edbb4cdd168ce4e853447d6dfd7b3c19d802f10d525867bfdb91b49a65198d7821f63deb3638deef482eb360ec5025d94f06aa295e246706a6"
SRC_URI[deb1.md5sum] = "b74b219757a83cd6cc556b4533d6a0f0"
SRC_URI[deb1.sha1sum] = "550f124ce116dca504d2e3894963e5a1350fceed"
SRC_URI[deb1.sha256sum] = "28396c96e460288d5851913121b053609f7ff34f996d78d7a38c1d2b6ab9f006"
SRC_URI[deb1.sha512sum] = "fd65ba4ef854ff65f7379853a76de847170eba4557e325e7c04b24f7378b8083184b531062a47fdb6ca0f3a137e1fb53b8d8074176e6a7f6f490080589768f17"

RDEPENDS = " \
    libc6 \
    libx11-6 \
"

