# This was autogenerated! Do not modify
SUMMARY = "Library to mock common C functions for testing purposes"
DESCRIPTION = "Library to mock common C functions, like libc and jsonc, for testing purposes. \
This collection of ready to use mocks is based on cmocka_extensions. \
 \
Development package."
SECTION = "libdevel"
SOURCE_PACKAGE = "cmocka-mocks"
HOMEPAGE = "https://github.com/Elektrobit/cmocka_mocks"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/cmocka-mocks/libcmocka-mocks-dev_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "be35f8747d98582e16cba56767215471"
SRC_URI[deb0.sha1sum] = "96a57154730a390200d7fbc3a36164c3f432044d"
SRC_URI[deb0.sha256sum] = "7294e1775386167e6e1bce0dfae9b485a5b4bbba40985f4414c6abfade0100ed"

RDEPENDS = " \
    cmocka-extensions-dev \
    libmock-jsonc0 \
    libmock-libc0 \
    libmock-libmnl0 \
    libmock-openssl0 \
"

