# This was autogenerated! Do not modify
SUMMARY = "library of rate-limit wrappers for functions"
DESCRIPTION = ""
SECTION = "javascript"
SOURCE_PACKAGE = "jquery-throttle-debounce"
HOMEPAGE = "http://benalman.com/projects/jquery-throttle-debounce-plugin/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/j/jquery-throttle-debounce/libjs-jquery-throttle-debounce_1.1+dfsg.1-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "977e8b386a1382908972179698f7878b"
SRC_URI[deb0.sha1sum] = "fc57d866d71d5e0d276c8cf0b291bb1d92e65feb"
SRC_URI[deb0.sha256sum] = "41a3f4d4cdf1f58cd21c8501b3c5393ea9094ae993b19e38279fb71cadd7ad6c"
SRC_URI[deb0.sha512sum] = "464c7d5d45556a1987ac8f75d77b86a281287bb61df0e7fcdf122283dd2bdef5ee71683eb2e045c62e6a095289cd71ee3d12921e25771c7f78e7967d2b66f2f2"


