# This was autogenerated! Do not modify
SUMMARY = "Small run-time speech synthesis engine - shared libraries"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "flite"
HOMEPAGE = "http://cmuflite.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/flite/libflite1_2.2-7_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/f/flite/libflite1_2.2-7_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "053e5fe93ee8b112ff1e689b59856c8d"
SRC_URI[deb0.sha1sum] = "d1666bacbc25327ec85f08fc0c6552a52d4b0194"
SRC_URI[deb0.sha256sum] = "5945190970be7d4a1f71fb6f7e3e340ba2675e770605df0754051d617a6c5ee6"
SRC_URI[deb0.sha512sum] = "8d97079a0676dae1953aadcdbb32e40f752b36e5560a33f6612427e88eb6a622cad1b3b71b130461dfca641abb2d99afa379c1baf9efe3f5a0b27c7685f6e851"
SRC_URI[deb1.md5sum] = "29a2c99a06ea805d9994e07e58f0a6dd"
SRC_URI[deb1.sha1sum] = "7f3c9a9709d2eb3cf435c4008a730155fb50dfb0"
SRC_URI[deb1.sha256sum] = "2cfee9289cee3b2b3e3eecd7f37bff2330f9c51f4ae6d0c3a66fc1ef370bd03d"
SRC_URI[deb1.sha512sum] = "a7a823a1cf5896557bb6468636eeaf52441bf3d4a71a0df965e73eccd2d9c89cf87e4553195c310b2a012912b65cac3b1a548a4823c4e9336cf511252be8a450"

RDEPENDS = " \
    libasound2t64 \
    libc6 \
"

