# This was autogenerated! Do not modify
SUMMARY = "library for simple use of LV2 plugins"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "lilv"
HOMEPAGE = "https://drobilla.net/software/lilv.html"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lilv/liblilv-0-0_0.24.26-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lilv/liblilv-0-0_0.24.26-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "11cfd64048acd488802e572c6b777e3c"
SRC_URI[deb0.sha1sum] = "bd4d20fbe966cfa869b6a4cb7bc51c8eb426ed3b"
SRC_URI[deb0.sha256sum] = "71f03560980b7c7f89ada7bd49ac3239166db770b2fa752b13d67abbd98ce8bc"
SRC_URI[deb0.sha512sum] = "8d87799c76400276953db0185bd2c81afa42eac952caa55782cc2d195ed833c3678dae602002fc2fd7e63c58d206ac8cef6fb3aac8de98e448e9595a74d801cf"
SRC_URI[deb1.md5sum] = "9a8e4245ed792eb33277762e9d874e0d"
SRC_URI[deb1.sha1sum] = "8d7240a772ad2b22af0af308bca0e37e899e90ac"
SRC_URI[deb1.sha256sum] = "eb14f680a7c639a9dce34928a2a560468baa25f03a79cb76b6acc9b35226b54e"
SRC_URI[deb1.sha512sum] = "ef38b8597b446520acc9b87f0f0e4822986551eeaf59d3889cb06d043f4fc0a48f0d09c9b097d06151882e16ac758165d78abfc3dbb2b6178b4fa4090a61502b"

RDEPENDS = " \
    libc6 \
    libserd-0-0 \
    libsord-0-0 \
    libsratom-0-0 \
    libzix-0-0 \
"

