# This was autogenerated! Do not modify
SUMMARY = "alternative regular expression module (Python 3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-regex"
HOMEPAGE = "https://github.com/mrabarnett/mrab-regex"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-regex/python3-regex_0.1.20241106-1+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-regex/python3-regex_0.1.20241106-1+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "822a933d6d69dee48c91ee817f9cfc7d"
SRC_URI[deb0.sha1sum] = "8824baffc1a59aa4a0da0a30f018c89aa9e1c071"
SRC_URI[deb0.sha256sum] = "0e11319c649490436b8cb83432edda577cf39c6e634b1a0b3af422c27dcc6be9"
SRC_URI[deb0.sha512sum] = "bbc4affdcc1c827e63368c814510ed59170210482ccf0bc9fd16c125810ae1bbe6d18d39088dc7bb6ed471384790a077636688909e05ee85a1a474eeb456fe77"
SRC_URI[deb1.md5sum] = "ad723c2a035444d9422903a7e5b207c6"
SRC_URI[deb1.sha1sum] = "f34192c3821f22c48cb642d0959a65c5effb678a"
SRC_URI[deb1.sha256sum] = "67cd8ac5c83652a0ea879ecf1162d493c2f4a8e2bf43c637988b384e269efa95"
SRC_URI[deb1.sha512sum] = "9f306a3532cd67150aab1e132195f8905c014a987f2d3f8f95bf18b063272a52331e88fa04ceef0e75dddd14484272681b355b03ec43beddc72abb0814d5cbd5"

RDEPENDS = " \
    libc6 \
    python3 \
"

