# This was autogenerated! Do not modify
SUMMARY = "GNU binary utilities, for x86-64-linux-gnu target"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "binutils"
HOMEPAGE = "https://www.gnu.org/software/binutils/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/binutils/binutils-x86-64-linux-gnu_2.44-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/binutils/binutils-x86-64-linux-gnu_2.44-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "2b5be658d9c5315d3d567fbb577421e8"
SRC_URI[deb0.sha1sum] = "f9458461ce861552a4d173ad8e5b504c957efc68"
SRC_URI[deb0.sha256sum] = "e6741ce95ff0f7a131c8d9faa3528ccbbc453078bbc62a97da81340ed7462c53"
SRC_URI[deb0.sha512sum] = "df558463aeab13d0a04036a5283d4a12c16e9abfc0479a0aabba132049deff1d07dcdb0b80264d5bedf94c35e01b0141d598006250be076b4c9cb8185e44d327"
SRC_URI[deb1.md5sum] = "f641f31c60738c77717053851440de8f"
SRC_URI[deb1.sha1sum] = "cfbdeb54870b16ecd456ac9f3be96668165ec435"
SRC_URI[deb1.sha256sum] = "af80fafe2d2f855736799d403c8668b2272ae479ccc83ed469e98877e44c2b0b"
SRC_URI[deb1.sha512sum] = "b11b58309375c7abc7ab4b7d59ae0008553f585c817d71742cf1f56eca160b0b55817c0051fcd6276b899981ed2bb7b333e6c45ffdbd6f32d22cfedf9401883e"

RDEPENDS = " \
    binutils-common \
    libc6 \
    libjansson4 \
    libsframe1 \
    libzstd1 \
    zlib1g \
"
RDEPENDS:append:amd64 = " \
    libbinutils \
    libctf-nobfd0 \
    libctf0 \
"

