# This was autogenerated! Do not modify
SUMMARY = "GNU Next Generation profiler (runtime library)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "binutils"
HOMEPAGE = "https://www.gnu.org/software/binutils/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/binutils/libgprofng0_2.44-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/binutils/libgprofng0_2.44-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "9c14211adbdf98219ffef25f33fa71a1"
SRC_URI[deb0.sha1sum] = "e2b9ac2d0ea0bb8e1bee2418aba1c592f9c7d5ba"
SRC_URI[deb0.sha256sum] = "0d36d0bde85c467ac6735dded08e19dd30ae1369e3908b9eb48ccc0d6ff66648"
SRC_URI[deb0.sha512sum] = "1a14439a3817f239a92ac5628a8b92483aaf5a02cf2cc2e5cb002e0fcab14c088e39da75398efbd023cf52c213362011c65941c66f0700e7a50beeda8af089f3"
SRC_URI[deb1.md5sum] = "a15237471a9223ee5959e584225626aa"
SRC_URI[deb1.sha1sum] = "304992ad9f6073c46c3f1c5b932412dceeee0f4c"
SRC_URI[deb1.sha256sum] = "4642014c84f3d070d889725900fbd23165189597d45deddc7bdcf9928de9e32e"
SRC_URI[deb1.sha512sum] = "47b90090b5da6b9597ed7aa884b8c7df18fb038846ef266a0920db350d0714095a1bfc55ef1267baa4127febedfc30a6839fc92d026a39064ed4ccecc5e0ed4d"

RDEPENDS = " \
    libbinutils \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
    zlib1g \
"

