# This was autogenerated! Do not modify
SUMMARY = "Library to handle the SFrame format (runtime library)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "binutils"
HOMEPAGE = "https://www.gnu.org/software/binutils/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/binutils/libsframe1_2.44-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/binutils/libsframe1_2.44-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "7438ed05450a8a28f307e973a57bfa72"
SRC_URI[deb0.sha1sum] = "816e8b1e4f5d0845fb01a1743a6f3de33395d0f5"
SRC_URI[deb0.sha256sum] = "38f625dfdc582717029ac3a3e97c51d994ec2e7a0e9b230c6b44e40d1276311f"
SRC_URI[deb0.sha512sum] = "660eb57e097bc875333a4bc3b30a0984d0cebd982b7aea29b548207a0fde63a3a28911930135fe4f24788aa368e0734d3924754f6d23e0c74a541818a942845e"
SRC_URI[deb1.md5sum] = "0dbb2cac39fd6d809b20bea9c1d99eba"
SRC_URI[deb1.sha1sum] = "062dbd16b90b3ce5414bcb59781219458e86e6b4"
SRC_URI[deb1.sha256sum] = "d4a90764fa79858347aaa3197bc4489404f005d9cdbea9b2ec75a607ea5ff518"
SRC_URI[deb1.sha512sum] = "d38365785367ecfd4a7e1f9fd8b78a615df1a79dff7cb6eb87bc907e398afbba9b88350a3281efe1a55c8b664cbf2b9ee00f2e86b56af98393d976037c3e373f"

RDEPENDS = " \
    libc6 \
"

