# This was autogenerated! Do not modify
SUMMARY = "LLVM C++ Standard library (development files)"
DESCRIPTION = "libc++ is another implementation of the C++ standard library \
 \
Features and Goals \
 \
  * Correctness as defined by the C++ standards. \
  * Fast execution. \
  * Minimal memory use. \
  * Fast compile times. \
  * ABI compatibility with gcc's libstdc++ for some low-level features such \
    as exception objects, rtti and memory allocation. \
  * Extensive unit tests."
SECTION = "libdevel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libc++-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libc++-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8c4d5ba1101b227655dbbb9562b59199"
SRC_URI[deb0.sha1sum] = "cdd7ed603a10ecfbb7110e3a678dac0a3ee4bc66"
SRC_URI[deb0.sha256sum] = "bf8028fe02b657a96c2d8ba0b26ff85f8361e1d993e44f68848c9656c6b54603"
SRC_URI[deb0.sha512sum] = "9c767974ac8e06bdd566045abbac83326d4edd4d4397ab6add6865c18d87dbabbb672fb1f792dc3b7514b8827843afa44a44570425b2dec46f97ff93cfdd6891"
SRC_URI[deb1.md5sum] = "ee7b999ff1fbfc81bfeb1d1f75cca4e3"
SRC_URI[deb1.sha1sum] = "47705060f9f917e46f49c3d074017824121d99a0"
SRC_URI[deb1.sha256sum] = "a28bd64b5cfbc7d297d89966d675bc30ed2a5c85592833e1692d788a0507b606"
SRC_URI[deb1.sha512sum] = "d6894dae27604cea3dbdbcd5f01ba1787cca620a8b8412cfa779316f59ddb0a1da5dca1374b520f645d4b8054cc05da2f380a1ae69a085434fd18ec603ecd979"

RDEPENDS = " \
    libc++1 \
    libc++abi-20-dev \
    libunwind-20-dev \
"

RPROVIDES = " \
    libc++-x.y-dev \
"
