# This was autogenerated! Do not modify
SUMMARY = "LLVM low level support for a standard C++ library (WASI)"
DESCRIPTION = "libc++abi is another implementation of low level support for a standard C++ \
library. \
 \
Features and Goals \
 \
  * Correctness as defined by the C++ standards. \
  * Provide a portable sublayer to ease the porting of libc++ \
 \
This package provides a version for the 32-bit WebAssembly System Interface."
SECTION = "libdevel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libc++abi-20-dev-wasm32_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e1835c0389b925668a5bc11da8cd4513"
SRC_URI[deb0.sha1sum] = "7cb20dd9d21918a46325c8e22cd285d879df10c5"
SRC_URI[deb0.sha256sum] = "6608c768e1dc2cab00466e1ec9ff9ea094683c9f46a279233a671d0c9c68af8c"
SRC_URI[deb0.sha512sum] = "3c57d4813163958121197a981fa6018d6945e780b6a7550dee2085c5ebfb5f2fded3cf3bedda9513fb5e22b63db9847764ac8230e3e94a493c0944419923324a"

RDEPENDS = " \
    wasi-libc \
"

RPROVIDES = " \
    libc++abi-x.y-dev-wasm32 \
"
