# This was autogenerated! Do not modify
SUMMARY = "Clang library - Development package"
DESCRIPTION = "Clang project is a C, C++, Objective C and Objective C++ front-end \
based on the LLVM compiler. Its goal is to offer a replacement to the \
GNU Compiler Collection (GCC). \
 \
Clang implements all of the ISO C++ 1998, 11, 14 and 17 standards and also \
provides most of the support of C++20. \
 \
This package contains the Clang headers to develop extensions over \
libclang1-20."
SECTION = "libdevel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libclang-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libclang-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "839673b93d25ed39e7dd7bc879528efd"
SRC_URI[deb0.sha1sum] = "a580e4fe3eeed97c2161d5948a3e07acb550bae4"
SRC_URI[deb0.sha256sum] = "b1659c5749209a49fc09ebd8e1fced553002f59ddf6f12a25da69cb9a1821b37"
SRC_URI[deb0.sha512sum] = "dd94de0211e1b3f4e7893a04e37832d0cd0d4b526973dfdd2b3a8b7e7a2898be5533adcce80a21c457a612c2d4fa75aeec274ffe3fd27205c9ec61b5bd4afcdc"
SRC_URI[deb1.md5sum] = "d28a61b10e1d8132f149ffd172ada6ab"
SRC_URI[deb1.sha1sum] = "1d865d4b1e112a2b770bd57703d7bc3d13c09c92"
SRC_URI[deb1.sha256sum] = "a18f267c9158ab22c842a28f38a5f9cc4613893c5377c726de3876d2e858d556"
SRC_URI[deb1.sha512sum] = "b80c68247873e81d8f6acde397fa4ac53d15af3628916d66a5eb85128e3b96eade3cfd241a89a31f42a661554a81ecfb6f2b8a53c58786be8134fcfa82f48273"

RDEPENDS = " \
    libclang-common-20-dev \
    libclang1-20 \
    libgcc-14-dev \
    libobjc-14-dev \
    libstdc++-14-dev \
"

