# This was autogenerated! Do not modify
SUMMARY = "LLVM low level support for a standard C++ library (development files)"
DESCRIPTION = "libc++abi is another implementation of low level support for a standard C++ \
library. \
 \
Features and Goals \
 \
  * Correctness as defined by the C++ standards. \
  * Provide a portable sublayer to ease the porting of libc++"
SECTION = "libdevel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libc++abi-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libc++abi-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d5f0ba043a3081d2f57b111991230cab"
SRC_URI[deb0.sha1sum] = "31cdc9c020cf62423838d59dcd74ad9283b2290e"
SRC_URI[deb0.sha256sum] = "3c65b121efd71a45e133d4a6c175dd9963aebf197ab8ac941ca4fa8fa5722bbe"
SRC_URI[deb0.sha512sum] = "3a273740ba1a9de94bdad384f7e6cdab4f4b8f0e129a547ffa8da12cd70b3a82f99b180f855ff127d831b93bc893bdd0ed6897a72ccc7ad17af8106b9d423604"
SRC_URI[deb1.md5sum] = "500218e3ae989cef32a7e3599f1fed50"
SRC_URI[deb1.sha1sum] = "a036fd976153e301d13997aae01493834a5a8c63"
SRC_URI[deb1.sha256sum] = "a7f2332ec21bafe0565a696bb751e60f5654cc63d89c72c4760c6f3d2bd50c10"
SRC_URI[deb1.sha512sum] = "a09747f1f97927c880715d7975439cbdf3d8758ba0739bb78ebc50725b004a2e3830963ea58a1c4b77ca0c7e484c6fb3e6ab820d5cc319975e2ad004d7686345"

RDEPENDS = " \
    libc++abi1 \
"

RPROVIDES = " \
    libc++abi-x.y-dev \
"
