# This was autogenerated! Do not modify
SUMMARY = "Next generation, high-performance debugger, header files"
DESCRIPTION = "LLDB is a next generation, high-performance debugger. It is built as a set of \
reusable components which highly leverage existing libraries in the larger LLVM \
Project, such as the Clang expression parser and LLVM disassembler. \
 \
This package provides the header files to build extension over lldb."
SECTION = "libdevel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/liblldb-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/liblldb-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "962553cd7fa78614f0bf660236309677"
SRC_URI[deb0.sha1sum] = "867295b95d734342434934cc08972fc77fa059f6"
SRC_URI[deb0.sha256sum] = "494c5f6206102b66b9fd42950cc0a816ca6fc12c5c94a90a9b4b03f50fae97da"
SRC_URI[deb0.sha512sum] = "ed8bffce0dbeb16e742d6a88b402e92f527be59550e83b36fa563ca3a8fa529caf746e26b4fd7629e4dbe4293a463c7c91e30e22d3ee0f074d5c6ce78c2163a3"
SRC_URI[deb1.md5sum] = "0ca7b994ef478661462cbc0fa4680ee6"
SRC_URI[deb1.sha1sum] = "7c62adcb9e34843cc8640b47f1e122ee1d36e21e"
SRC_URI[deb1.sha256sum] = "8b6449a87199be1cf5823d66c215bb6c1d5c6019d781fdca638ae7c2c8689822"
SRC_URI[deb1.sha512sum] = "f8f34792fe70b2bf530e9271c0174fba600fd3a0643befdd6fc2777666d7a0b229bf4be12414d260f8029cb43b784525b34136768f26d03817a869dea4969574"

RDEPENDS = " \
    lldb-20 \
"

