# This was autogenerated! Do not modify
SUMMARY = "Multi-Level Intermediate Representation library"
DESCRIPTION = "Novel approach to building reusable and extensible compiler infrastructure. \
MLIR aims to address software fragmentation, improve compilation for \
heterogeneous hardware, significantly reduce the cost of building domain \
specific compilers, and aid in connecting existing compilers together."
SECTION = "libdevel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libmlir-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libmlir-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "89c7a74b58685ad19e7bdf2bc7d1a218"
SRC_URI[deb0.sha1sum] = "9cb4900359a1d0b288e2a7bef2593c653adb764b"
SRC_URI[deb0.sha256sum] = "f791ddad55e6073fd5b2f29b29a6cf74fc97e6ce98bb1ebfde37bef7835f15d4"
SRC_URI[deb0.sha512sum] = "6a256728e6c90f28b4898fc41ef84c7253614aa6bc648c58c4f7451b27c7b7faf24c516c107c982bba33f78ba776109e5055e1d650f8560e67846ed83f881d17"
SRC_URI[deb1.md5sum] = "8eacd48dfbf42b7cb1a1be86691507b1"
SRC_URI[deb1.sha1sum] = "fa3dbd20925038970d2607cc39bff69168f28b09"
SRC_URI[deb1.sha256sum] = "108c01099252edf6bacbaef7962f70f09a6758ce53d4dfdc3f3529222ebe775c"
SRC_URI[deb1.sha512sum] = "56f7d0c7ff6e4af9fb42bc493ee25f51b59cfff68176d94f26377487d8b7a7e5536a0e34d7eeef2d898a9c68bc3ccc45b878aaaef50086896b081dfa57a21281"

RDEPENDS = " \
    libmlir-20 \
"

RPROVIDES = " \
    libmlir-x.y-dev \
"
