# This was autogenerated! Do not modify
SUMMARY = "production-quality unwinder"
DESCRIPTION = "libunwind is a production-quality unwinder, with platform support for DWARF \
unwind info, SjLj, and ARM EHABI. \
 \
The low level libunwind API was designed to work either in-process (aka local) \
or to operate on another process (aka remote), but only the local path has \
been implemented. Remote unwinding remains as future work."
SECTION = "libdevel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libunwind-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libunwind-20-dev_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "0c228d8ebf23bd14c52af8a4ec09bc33"
SRC_URI[deb0.sha1sum] = "cc24e9f17d555b3b60ce1e901ad328bb4070734e"
SRC_URI[deb0.sha256sum] = "3eacacf81ab2207558fdf806ebd1772a99ae2c67efe08e6087d80679354468ae"
SRC_URI[deb0.sha512sum] = "95250deca127b5868ffa282ed3ea2ffa216ca9aef9915fc2037ad97f1300a57a533fb57355ee244faeea44f8ac91ad9e507d97d60521cc96411361896def5364"
SRC_URI[deb1.md5sum] = "ab2b6cfc70dad00373692ecaffdec175"
SRC_URI[deb1.sha1sum] = "d616d4d08cd413373ca33a0683d679876acadac5"
SRC_URI[deb1.sha256sum] = "f4f0642e3c48aaff8f8b4935d4b15acbf6a0fdd4a91ae42fad7c12de5886542b"
SRC_URI[deb1.sha512sum] = "bbc6cedce255f89aac3f141b3c2b882a5b58e28827b504bbb3f2525daf023fc1addb0800694c3731b0e15a9295b754fc5f58b07950de6bf1e0852d0610a966ec"

RDEPENDS = " \
    libunwind \
"

RPROVIDES = " \
    libunwind-x.y-dev \
"
