# This was autogenerated! Do not modify
SUMMARY = "development files for MIT Kerberos without Heimdal conflict"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "krb5"
HOMEPAGE = "https://web.mit.edu/kerberos/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/krb5/krb5-multidev_1.21.3-5+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/krb5/krb5-multidev_1.21.3-5+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "390f08a1f90c7ef0cd749015647f7ff8"
SRC_URI[deb0.sha1sum] = "55302201411fe60b24a9760f699dbf05fedb8754"
SRC_URI[deb0.sha256sum] = "8f8735ab56020070d8d448c13d214f6d6ba5a2c1d4661b24fa3ba63491cb3f80"
SRC_URI[deb0.sha512sum] = "d5f157b717daf885a7321533a3aad994bbd5e1f8167f5c8f34dfd0ce4a63c158b09f7963f33c804a9dd936b2507e1cb911da82ae79ef2df02aef5a9fc8728342"
SRC_URI[deb1.md5sum] = "4d17d9bcba7b6e4289ddcddf59e3bac4"
SRC_URI[deb1.sha1sum] = "a7f775b5c78d9d5e769349d980b05b9f13e891d2"
SRC_URI[deb1.sha256sum] = "9f5d65a069269b0960418f9d5a3110158234a1efbe9a9feb3650c57422fe41ef"
SRC_URI[deb1.sha512sum] = "4bea4640d5e922c28d714547454896a41121c42fd45a0405a1985bb1df16c1cd2e5ea2c626545e95861684501ad8b43b8f460d9201918d12e62cd195e94b561c"

RDEPENDS = " \
    comerr-dev \
    libgssapi-krb5-2 \
    libgssrpc4t64 \
    libk5crypto3 \
    libkadm5clnt-mit12 \
    libkadm5srv-mit12 \
    libkrb5-3 \
"

