# This was autogenerated! Do not modify
SUMMARY = "Attributes without boilerplate (Python 3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-attrs"
HOMEPAGE = "https://attrs.readthedocs.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-attrs/python3-attr_25.3.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "5308bd5d6bdb97d8dadd82dca9fe9c58"
SRC_URI[deb0.sha1sum] = "08dd5bdb9cedc77ec9a050b7ab5c3ea44f33cddd"
SRC_URI[deb0.sha256sum] = "72cee7fff9e57e8410956e3071ffe910d9de14ddedf14d598a616319428b369c"
SRC_URI[deb0.sha512sum] = "27e3a1378462747d62261dac0ba89b7013bef5c437d992446d94415ab1754ad864c35bb91dc55531a10c11ad0995ab4af70e26c1c488d5181da20ffe06f29e00"

RDEPENDS = " \
    python3 \
"

