# This was autogenerated! Do not modify
SUMMARY = "module to format a header and rows into a table"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libterm-table-perl"
HOMEPAGE = "https://metacpan.org/release/Term-Table"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libt/libterm-table-perl/libterm-table-perl_0.024-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "c5ba46731fa6d66141f111279033b726"
SRC_URI[deb0.sha1sum] = "2392013bbd526631b4c00501758736f348be2597"
SRC_URI[deb0.sha256sum] = "bf8158e63d82882ee203ee1f20f45324509566fe7806e327d52215b23f55a5eb"
SRC_URI[deb0.sha512sum] = "5c9ba0b8284e961431eaf8f8ab9a7f4ed5f73950d66ab4dec61088da66a0fcbe91857aa103a1448f67a9bd21eb8dba1092eea19dd12d1688306c8f11ff6e82be"

RDEPENDS = " \
    perl \
"

