#
# Copyright 2026 Elektrobit. All rights reserved.
#
# Machine definition for the Raspberry Pi 4B platform.

DISTRO_ARCH ?= "arm64"
MACHINE_SERIAL ?= "serial0"
BAUDRATE_TTY ?= "115200"

EBCL_BOOTLOADER_PACKAGES ?= " \
    bootconfig-rpi4b \
    firmware-rpi \
"

IMAGE_BOOT_FILES ?= "${IMAGE_ROOTFS}/boot/vmlinux*;./ \
                     ${IMAGE_ROOTFS}/boot/uboot*;./ \
                     ${IMAGE_ROOTFS}/boot/System.map*;./ \
                     ${IMAGE_ROOTFS}/boot/cmdline.txt;./ \
                     ${IMAGE_ROOTFS}/boot/config.txt;./ \
                     ${IMAGE_ROOTFS}/usr/lib/rpi-firmware/*.bin;./ \
                     ${IMAGE_ROOTFS}/usr/lib/rpi-firmware/*.dat;./ \
                     ${IMAGE_ROOTFS}/usr/lib/rpi-firmware/*.elf;./ \
                     ${IMAGE_ROOTFS}/usr/lib/rpi-firmware/*.dtb;./ \
                     ${IMAGE_ROOTFS}/usr/lib/rpi-firmware/overlays/*.dtbo;./overlays/"

EBCLFSA_LIVM_DEV = "mmcblk0p2"

EBCL_PLATFORM = "rpi4b"

BSP_LAYERDIR := "${LAYERDIR_meta-ebclfsa-public-bsp-rpi}"
