# This was autogenerated! Do not modify
SUMMARY = "High quality 1D sample-rate conversion library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libsoxr"
HOMEPAGE = "http://sourceforge.net/projects/soxr/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libsoxr/libsoxr0_0.1.3-4+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libsoxr/libsoxr0_0.1.3-4+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "9163ff9483cc8f1cfbae01296ca78020"
SRC_URI[deb0.sha1sum] = "3901d1f5655850aec8ee7204de7738d34eec91c4"
SRC_URI[deb0.sha256sum] = "384caa47b6cfe780f30d33c5dfb1c18f6579aed9f3bdbf7f8cd0395ab2d537b7"
SRC_URI[deb0.sha512sum] = "94deb1a1fde7f35da4129f5b864f3147fd7625246ba106c3a4940b31a9586c4abb7fd8591144b5ad45ccbc6f1b357a6d43d6444e30536c5139522cc8f9be69e7"
SRC_URI[deb1.md5sum] = "48db810d3f1ec763aa5f88106df6707f"
SRC_URI[deb1.sha1sum] = "c27fd13bce512359c61145f1fc3fed5346d4a40a"
SRC_URI[deb1.sha256sum] = "1dc754a7d84c5a79d9cdd04c85760e735e2fe7cec7535f9991251a5a8ab851a1"
SRC_URI[deb1.sha512sum] = "ce0a079a308a0fbb6354ed79ecea3d434a0f176868875079a156ea48c45d1acb33f968dc5752658017ff9275d1da1d0bfecc405dd0ea17cc9d8a9dfe63df30bb"

RDEPENDS = " \
    libc6 \
    libgomp1 \
"

