# This was autogenerated! Do not modify
SUMMARY = "Tiny utilities for small and embedded systems"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "busybox"
HOMEPAGE = "http://www.busybox.net"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/busybox/busybox_1.37.0-6+b8_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/busybox/busybox_1.37.0-6+b8_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "ce43a20d040d0eb8f386b82fd0f81636"
SRC_URI[deb0.sha1sum] = "ee849733171b5cc7cb16d1fcbee35668f2bc2b32"
SRC_URI[deb0.sha256sum] = "bfe8994fbd3d60b82b11819514e78e1537b7e67ac2f4e8eb3d517a3db838cbd8"
SRC_URI[deb0.sha512sum] = "1fab224db03006eb4ecb9d51fb7f680eeb15127fc18457e60fe338d1e2e51ba1e5387790c87617382187b821c8aeb01261f26f6e238a5782695399cde07705b8"
SRC_URI[deb1.md5sum] = "03d6fc38acf1679fc7b35869ffbca990"
SRC_URI[deb1.sha1sum] = "40e57e548058b50b69ced63ef76e502a0e3ed60a"
SRC_URI[deb1.sha256sum] = "962273fe42b118ef23c8aea045e5868da707eca5ca312932a3f68f5fba2e9f48"
SRC_URI[deb1.sha512sum] = "687c7990e080ec8fb8adfe9e262baf753bf689d4df8024116e3c5aa8a6e051ee4197a644a9646a3c178620bfb2a3bb45a31cabebb9773106ed8a2dbdfcac5a09"

RDEPENDS = " \
    libc6 \
"

