# This was autogenerated! Do not modify
SUMMARY = "Library of common utility API's used in elos and samconf (documentation)"
DESCRIPTION = "Library of common utility API's used in elos and samconf. \
 \
Documentation package."
SECTION = "doc"
SOURCE_PACKAGE = "safu"
HOMEPAGE = "https://github.com/Elektrobit/safu"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/safu/safu-doc_0.0.1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "451297ce16877a32966f4d1400563c36"
SRC_URI[deb0.sha1sum] = "aaa6e19c66a4bc8c4f14c84c249b5e1f8e025a0e"
SRC_URI[deb0.sha256sum] = "f535685e883ec19a993ee67220492948d9d91ea3dbf81071677a84f07433f5f9"


