# This was autogenerated! Do not modify
SUMMARY = "Tool to generate BitBake .bb files from Apt repositories"
DESCRIPTION = "Downloads package lists from a collection of Apt repositories defined in a \
configuration file and generates BitBake .bb files which can be used by a \
BitBake project to include them in a build environment."
SECTION = "devel"
SOURCE_PACKAGE = "ebcl-reposync"
HOMEPAGE = "https://gitext.elektrobitautomotive.com/EB-Linux/ebcl-reposync"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC}/pool/main/e/ebcl-reposync/ebcl-reposync_0.2.0_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "5fdc8e23b041d7ecb2cd329daf82d90c"
SRC_URI[deb0.sha1sum] = "58b57a9acbd74ad79f495a89ef61f4cb38209a65"
SRC_URI[deb0.sha256sum] = "5097c3a7073acf52ccd524fa0635c25aeb5adc55059cbc8e7f10a84016905a62"

RDEPENDS = " \
    python3 \
    python3-aiohttp \
    python3-cerberus \
    python3-yaml \
    python3-yarl \
"

