# This was autogenerated! Do not modify
SUMMARY = "Tool to generate BitBake .bb files from Apt repositories"
DESCRIPTION = "Downloads package lists from a collection of Apt repositories defined in a \
configuration file and generates BitBake .bb files which can be used by a \
BitBake project to include them in a build environment."
SECTION = "devel"
SOURCE_PACKAGE = "ebcl-reposync"
HOMEPAGE = "https://gitext.elektrobitautomotive.com/EB-Linux/ebcl-reposync"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC}/pool/main/e/ebcl-reposync/ebcl-reposync_0.2.0_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e78fb35ad4db146746713259b55813d9"
SRC_URI[deb0.sha1sum] = "414f413db692b2ebb456a56aa3836263f14601be"
SRC_URI[deb0.sha256sum] = "4610564a30c2fe8f50bb9659c2b1dfc721c5472263fbb606884eb977fcb20624"

RDEPENDS = " \
    python3 \
    python3-aiohttp \
    python3-cerberus \
    python3-yaml \
    python3-yarl \
"

