# This was autogenerated! Do not modify
SUMMARY = "Userspace interface to intel-specific kernel DRM services -- runtime"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libdrm"
HOMEPAGE = "https://gitlab.freedesktop.org/mesa/drm/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libdrm/libdrm-intel1_2.4.124-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libdrm/libdrm-intel1_2.4.124-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "90e77d96c766f817f511e960788b8b7f"
SRC_URI[deb0.sha1sum] = "dc4d33b5325743e649c9d2aa8a484cff9a9fd665"
SRC_URI[deb0.sha256sum] = "188ab1fd74c838b3c8055d62107351e16a4bb7a25d39c30bbb9aac30ddd37238"
SRC_URI[deb0.sha512sum] = "59427cf09548c6df4ff647132d2e48cdf877a169d3fe54c9f099064c7e941cef770eaf169aef962bc0bb0963965e949a490975c7f9b283220cb64650984959ae"
SRC_URI[deb1.md5sum] = "366918ce934e64a0ca09bae1bcd14cfc"
SRC_URI[deb1.sha1sum] = "40533e10a3f9a8d0439cbc294bf4dd2374dd58eb"
SRC_URI[deb1.sha256sum] = "1712acf07bee1b460b1e2701f3f605a386f306e3cb8fa166119ef854f7ee8ba0"
SRC_URI[deb1.sha512sum] = "c6a6424d61e1216f667fcafd5ce06be1309354c3a0f6ea3102d692983753399f773e344807051b0832546fcbb0692a97d99b4504a2254d90ecd211347cf4b288"

RDEPENDS = " \
    libc6 \
    libdrm2 \
    libpciaccess0 \
"

