# This was autogenerated! Do not modify
SUMMARY = "data tables pertaining to HTML"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libhtml-tagset-perl"
HOMEPAGE = "https://metacpan.org/release/HTML-Tagset"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libh/libhtml-tagset-perl/libhtml-tagset-perl_3.24-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "58e5efec3d33fd025ab94074eac61920"
SRC_URI[deb0.sha1sum] = "09987e27fab4ed6fae85fef3d9f6a54a2b779101"
SRC_URI[deb0.sha256sum] = "5efdaf433e10ce127257176d8093e41eabc642839e71f1961bc17f2e4f6169b0"
SRC_URI[deb0.sha512sum] = "4d3b111e93fb0f49fdaf83c9af72a768644977bf3c907d36945ed5812a1c210a75189718a1291a3f501affb94bc8e5dd9b32babb9d5f45b1bc39d8c7293a2ab7"

RDEPENDS = " \
    perl \
"

