# This was autogenerated! Do not modify
SUMMARY = "Collection of mocking related code extensions for cmocka"
DESCRIPTION = "Mocking related code extensions for cmocka used by elos and other projects."
SECTION = "devel"
SOURCE_PACKAGE = "cmocka-extensions"
HOMEPAGE = "https://github.com/Elektrobit/cmocka_extensions"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/c/cmocka-extensions/cmocka-extensions-dev_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "28cf7029d5831c1a3c3d2d368e0ccb3b"
SRC_URI[deb0.sha1sum] = "406ba31bd0b76680422a14a3496b1520d13b70a1"
SRC_URI[deb0.sha256sum] = "640e69222d694dec53aacef7f66e2148d6fadb19544837b5f185034950f63520"

RDEPENDS = " \
    libcmocka-dev \
"

