# This was autogenerated! Do not modify
SUMMARY = "create a Debian chroot"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "mmdebstrap"
HOMEPAGE = "https://gitlab.mister-muffin.de/josch/mmdebstrap/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/mmdebstrap/mmdebstrap_1.5.7-1+deb13u1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "fa5ca5da8863f1610056b696a5ac69a9"
SRC_URI[deb0.sha1sum] = "0a8ec1b8df2721669da0a925059f3f6b9e56a790"
SRC_URI[deb0.sha256sum] = "df731ee92b0ad40f9618b8b1c98c2e90635224f6b21c0905dab65ca099c8fe14"
SRC_URI[deb0.sha512sum] = "c90592a0a61e4f450398bd9197ebf9ba14df24866787bf63100c13ebbc9a38cff46555180ff34be454a34404ab24f9ebe7a75d951cdda590fc4ebaea832bbec6"

RDEPENDS = " \
    apt \
    perl \
    python3 \
"

