# This was autogenerated! Do not modify
SUMMARY = "SSH2 client-side library (development headers)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "libssh2"
HOMEPAGE = "https://libssh2.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libssh2/libssh2-1-dev_1.11.1-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libssh2/libssh2-1-dev_1.11.1-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "391412956ecaf0387023a69448b746f7"
SRC_URI[deb0.sha1sum] = "baa170facf416ca4169899af650b2df5a869e2b7"
SRC_URI[deb0.sha256sum] = "249a07081f4a1ba075d49aeb0513ebe2c3346e5fd8eaf4701f7e2e99631ca142"
SRC_URI[deb0.sha512sum] = "8809b9b914ab8a1b993d8f0892940860453566bd88d6e80dba2c31239bdf4aecf2d6e8afdb2df819f566c22f758562ab83ef046aec6e5ba95aa5dc28141cd9ea"
SRC_URI[deb1.md5sum] = "f3e7f73eaee5db93fb00793e5059a607"
SRC_URI[deb1.sha1sum] = "ff25a21fe80e6a5d7c3cf70e9f713ff64e594006"
SRC_URI[deb1.sha256sum] = "0f17ffcc4b38816722c1330d96e848f47255d4bde24585966167d4b79d7989ba"
SRC_URI[deb1.sha512sum] = "f17df57be0e696c2537a481cf250a5315724bccbaf7279e9fe87e604e23680e57e4010f4c2bca75389508b871f4b0eb2b9aeca2dd8c26f426c0e16894567e71f"

RDEPENDS = " \
    libssh2-1t64 \
    libssl-dev \
    zlib1g-dev \
"

