# This was autogenerated! Do not modify
SUMMARY = "Perl module containing stack trace and related objects"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libdevel-stacktrace-perl"
HOMEPAGE = "https://metacpan.org/release/Devel-StackTrace"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libdevel-stacktrace-perl/libdevel-stacktrace-perl_2.0500-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "b390c1d8b4e7682c8f8a01d14a953022"
SRC_URI[deb0.sha1sum] = "cf6f984a2e4d5987437db13ecd238955cf66efa9"
SRC_URI[deb0.sha256sum] = "34f9d4bb6f73e4a7d2af533a04ca1ce7de8dfdab4d9af3d201a8d1c552261607"
SRC_URI[deb0.sha512sum] = "dbf514dc4a7b4cab7e4d006c5f9e0d829c4e33ea9ad0b9876192cdcd8974c95c4c02e465e0a4ae3c45df8d282823539d39fc4f0e1eb5f7363bacea3826b48da1"

RDEPENDS = " \
    perl \
"

