# This was autogenerated! Do not modify
SUMMARY = "YACC-compatible parser generator"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "bison"
HOMEPAGE = "https://www.gnu.org/software/bison/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/bison/bison_3.8.2+dfsg-1+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/bison/bison_3.8.2+dfsg-1+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e0cd40c1e934acb8eca3681ee65dcb3d"
SRC_URI[deb0.sha1sum] = "73433940b416eea95481af4e07b2ae6ed826e640"
SRC_URI[deb0.sha256sum] = "ce6eb1f7aad18850e32d223a68f54bcbe756d74f138c8ec5460ad9d220f4d335"
SRC_URI[deb0.sha512sum] = "60217509b2afb6efc8ace990c9898172ebc27b77cf4bf4ca0e420379a6aa00eed7a8aa02dde990212457b5e4cffcdd4f1c7f43ba18ba0a658db9fd2988def0c5"
SRC_URI[deb1.md5sum] = "cc5fbccf5c9c968bc05fc5667e3ecb7d"
SRC_URI[deb1.sha1sum] = "39875f9404aa105f09f11f32bedf8865af74912b"
SRC_URI[deb1.sha256sum] = "36b26ef0700504923089b4920e0bd704ff03de750515c90399cbc69bf43aed6d"
SRC_URI[deb1.sha512sum] = "6b8650dc7f5facb7a0c878f2dd9ab84f3f0417f740aca86564618d21409cc9fcfc2976cbadbb5b9463335885cf3bfe50c7062e2a9f79a6f4d088113a8fa52d9b"

RDEPENDS = " \
    libc6 \
    m4 \
"

