# This was autogenerated! Do not modify
SUMMARY = "helper modules for subroutines"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libsub-quote-perl"
HOMEPAGE = "https://metacpan.org/release/Sub-Quote"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libs/libsub-quote-perl/libsub-quote-perl_2.006008-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "bd7b02d3e8dd0b6d3aee179fde1de57e"
SRC_URI[deb0.sha1sum] = "f0b8b97008102c76ef4bce8dd0fc49b06d202475"
SRC_URI[deb0.sha256sum] = "2b8ede3c2db598324eb2bcf3e2ae146dc031a1ca450d337efeabc4a2186fc02c"
SRC_URI[deb0.sha512sum] = "0e14ea9cde9ce037161795bfa0781abc5f97d9de5e4a1f2bc8623b0e5797c014f462eec72c8bbcc156b4bd0964ba44ae6913c07ea8e4239b17b78707c5feab05"

RDEPENDS = " \
    libscalar-list-utils-perl \
    perl \
"

