# This was autogenerated! Do not modify
SUMMARY = "fast lossless compression algorithm"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libzstd"
HOMEPAGE = "https://github.com/facebook/zstd"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libz/libzstd/libzstd1_1.5.7+dfsg-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libz/libzstd/libzstd1_1.5.7+dfsg-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c004a22e17fc379e9bc602764f20cc8a"
SRC_URI[deb0.sha1sum] = "96dbb7ea8dced3367f661f31964693f4919c0f9a"
SRC_URI[deb0.sha256sum] = "2f6a2aeacfc925eba8b00ac9139bc4bfccf8cacb09eb93de067074b26948eef9"
SRC_URI[deb0.sha512sum] = "1f211445c1aa3a8e9dad19369bfcc3959a50720e386f53b49104a8fe9ff3aaa3a7ee44cce84f426178819f009e368ff0dff44fd79ef7f645a88449c8400a0d88"
SRC_URI[deb1.md5sum] = "439dda611ba0b0d0465d5f2a373c43fe"
SRC_URI[deb1.sha1sum] = "fb2129135f3cc38e40faa0d7cdc7bc0048955075"
SRC_URI[deb1.sha256sum] = "924540bd59fdbfa77a0604360efdaca54411a43daf11c7e002a3c64791b67448"
SRC_URI[deb1.sha512sum] = "7d6f82d9c2294238f8f78083f67ae315e4bb2cb9a6e4e966f20064c4945b28ef6cd56379290b2c99e9595e27ab76bd124ff126680b270e684b78d15adea1a496"

RDEPENDS = " \
    libc6 \
"

