# This was autogenerated! Do not modify
SUMMARY = "Module to generate RFC-2822-valid date strings"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libemail-date-format-perl"
HOMEPAGE = "https://metacpan.org/release/Email-Date-Format"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libe/libemail-date-format-perl/libemail-date-format-perl_1.008-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "d781607a6a96d8e5ae6539f1699878f2"
SRC_URI[deb0.sha1sum] = "73cf36afaf00d6872eb9c4f11068cdffab74fdbc"
SRC_URI[deb0.sha256sum] = "2337200c360f282dd5a973c0f20ac005f3e138510723ed7bfc740abed43f1886"
SRC_URI[deb0.sha512sum] = "6221f2ecdf5462cfe865c09d96f7a06bdffd4a053559992f21d87c3712a2b3c3d79bf260d8523dea5ce9e3d2fccbcbc199ec6ef2ce97d1f5584ba2cecfd08191"

RDEPENDS = " \
    perl \
"

