# This was autogenerated! Do not modify
SUMMARY = "Linux kernel debugging symbols for 6.12.94-cip26"
DESCRIPTION = "This package will come in handy if you need to debug the kernel. It provides \
all the necessary debug symbols for the kernel and its modules."
SECTION = "debug"
SOURCE_PACKAGE = "linux-ebclfsa-fastdev-rpi"
HOMEPAGE = "http://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC}/pool/main/l/linux-ebclfsa-fastdev-rpi/linux-image-ebclfsa-fastdev-rpi-dbg_6.12.94-cip26-ebclfsa1+r0_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0179b5b7f94a00a6c7aaa1634ce38c40"
SRC_URI[deb0.sha1sum] = "936a7d58e97165128b0b754d27ee443a9a66a5f6"
SRC_URI[deb0.sha256sum] = "7f9d2a6d96c4b5b431fc6620dd28698eaaffb2cc4a530fcb7e9c43d02496454f"


