# This was autogenerated! Do not modify
SUMMARY = "GNU C preprocessor for aarch64-linux-gnu"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-13"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13/cpp-13-aarch64-linux-gnu_13.3.0-16_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "1996d93cea6a96986a57f74339e57a46"
SRC_URI[deb0.sha1sum] = "b24f94c4446af7f1213726964b7915e5d5f25205"
SRC_URI[deb0.sha256sum] = "295341f6b5440503cbeee306b9c46fad27403dcd5e5bed0df942cb312a5c4f5b"
SRC_URI[deb0.sha512sum] = "ca9bdf15c38efebffcfb48ac5a389c93efada19710ab5d89428b6bcf42de9fe439dead6306dce552b53720cd86735601efc212afcbdbd1a995ebe244c7b90256"

RDEPENDS = " \
    gcc-13-base \
    libc6 \
    libgmp10 \
    libisl23 \
    libmpc3 \
    libmpfr6 \
    libzstd1 \
    zlib1g \
"

