# This was autogenerated! Do not modify
SUMMARY = "module for generating/analyzing Roman numerals for Python 3"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-roman"
HOMEPAGE = "https://github.com/zopefoundation/roman"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-roman/python3-roman_5.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "9568049049228cdabd2201fa91a74849"
SRC_URI[deb0.sha1sum] = "d33ff9af06f72b9b8d214be7ad909ee70433c02e"
SRC_URI[deb0.sha256sum] = "5da6c00238cca76fbff5a3aee14f8094eb13a10104c7698e89ec8fd89ff481a3"
SRC_URI[deb0.sha512sum] = "aee1e771857415dc0b5c5888def5bda9ab90bebe5e63b8d5d6481d94c346b78ce6ee4cc6c3cad0ccd759700ea1bd82d6170dbc08e20d3453f3d2e02a4f8a51d9"

RDEPENDS = " \
    python3 \
"

