# This was autogenerated! Do not modify
SUMMARY = "detect architectures supported by your machine/kernel"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "arch-test"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/arch-test/arch-test_0.22-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "ffdf7b8abbb37a403639624afaa41232"
SRC_URI[deb0.sha1sum] = "a46f52c28b6b8c54e9212ced90b358adaaa02470"
SRC_URI[deb0.sha256sum] = "9255bbca71a0e76dd9f6166a37ec91b474e03297e4b1976d9b1eb04d6dfc56f3"
SRC_URI[deb0.sha512sum] = "c5e2650248d23fb9e832e37e31eaa3940e4c7081bcddeb9548bc928423a12185713a4b14e1e1ed68ebde8de6e7f8b4132334ec57c40e9ec676e9d63db7f45364"


