# This was autogenerated! Do not modify
SUMMARY = "Qt 6 OpenGL module"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "qt6-base"
HOMEPAGE = "https://www.qt.io/developers/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-base/libqt6opengl6_6.8.2+dfsg-9+deb13u2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-base/libqt6opengl6_6.8.2+dfsg-9+deb13u2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "9b90369fa18434bc327d29a320c6d47b"
SRC_URI[deb0.sha1sum] = "4cd87ccb56cf46d0dab19087993f9e0505518a65"
SRC_URI[deb0.sha256sum] = "0b1fb1147dd6f0af541d541cc2fcc1168214b0973fd63941bf3338f208f9214d"
SRC_URI[deb0.sha512sum] = "df1e0444ca0adc9c14544b214891b26e9b2e72cc71370b2517b29ee4206b4318ffee2bcb70de66f5033b2b4b86ed9f3e3840f7ad6c2405b2a67bfd5c93046544"
SRC_URI[deb1.md5sum] = "1906ad624249e5aa2ddd755ec26157c0"
SRC_URI[deb1.sha1sum] = "89de83205eb3eb6a537ab6bc2d85d47ead3c3142"
SRC_URI[deb1.sha256sum] = "edbc333ff0d23f1e635a4c6c678ddef4c9ff06fb9cc963cebae88f2542d2e8ba"
SRC_URI[deb1.sha512sum] = "b710641b01beff274511d940d7fd1cda8953851fcd96c429579f321634481a3309b267ccc44cdde7e08a176ab8384a62a4874760b7c3884684fd50bd31993403"

RDEPENDS = " \
    libc6 \
    libdrm2 \
    libegl1 \
    libgbm1 \
    libinput10 \
    libmtdev1t64 \
    libopengl0 \
    libqt6core6t64 \
    libqt6gui6 \
    libstdc++6 \
    libts0t64 \
    libudev1 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxkbcommon0 \
    qt6-base-private-abi \
"

