# This was autogenerated! Do not modify
SUMMARY = "Qt 6 test module"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "qt6-base"
HOMEPAGE = "https://www.qt.io/developers/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-base/libqt6test6_6.8.2+dfsg-9+deb13u2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-base/libqt6test6_6.8.2+dfsg-9+deb13u2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "f19f9aebba0c84e05c751f59ad146de4"
SRC_URI[deb0.sha1sum] = "c2cbac318f90a4ec5561929c6b5650e0c072e554"
SRC_URI[deb0.sha256sum] = "4d5f32084e925b9e38ff0dc764088094fd5185e7fa02c5cfa6214334fb62e66d"
SRC_URI[deb0.sha512sum] = "bac154ca81e6780096e752f0809e7ba1da1e56aa9c2a5b9369dce3053fa8e30819191efdb13d41a5e0277d9493a6aab141ee93e0053feb9a6bbb79bc0d70003a"
SRC_URI[deb1.md5sum] = "0bb8cfdc07792a6bc857f29e95ad3f75"
SRC_URI[deb1.sha1sum] = "7e7be66a937fde58060c2e0ed79d3df88c70e02f"
SRC_URI[deb1.sha256sum] = "eef6db1a05dd73bec044fdc8c03a7d8706f8c6bc0df9cd75766ba22724c5d4f9"
SRC_URI[deb1.sha512sum] = "b2925fd1cd780f533c94e9992befddfe7dc6f48ea8df3b24f0cf47a7f77161937b1f34074e7c5a5a33294a6fcc2d7da6ef91ef000fc9c2047f354fef70d85768"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libqt6core6t64 \
    libstdc++6 \
    qt6-base-private-abi \
"

