# This was autogenerated! Do not modify
SUMMARY = "multiple precision complex floating-point library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "mpclib3"
HOMEPAGE = "http://www.multiprecision.org/mpc/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/mpclib3/libmpc3_1.3.1-1+b3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/mpclib3/libmpc3_1.3.1-1+b3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "18e262a6f25f47f8d6f5650fa6d0fa6f"
SRC_URI[deb0.sha1sum] = "270987527962db11968d1d8bf2f50f5c4522b3af"
SRC_URI[deb0.sha256sum] = "2af0a5c128e03694a41c0b011bd8a958b7297436cdb3a15ddad7866dae8c300b"
SRC_URI[deb0.sha512sum] = "099617e36f110acf11e748ea89b100e6df581c6bfc1c1490f521845313d1d03107b32d59beddd2b02a27137f93a5bb4de10f2d9092e2ae60daf99919d6c31c40"
SRC_URI[deb1.md5sum] = "83af87707c4f015f1aba3d1770af9e98"
SRC_URI[deb1.sha1sum] = "fe4dda3421ed33928f7bafd0de0d1909a2d4a979"
SRC_URI[deb1.sha256sum] = "d4cfe026a624e51641c80ef2af77387185714f62f3b5c87035e62d9ed8d9eec1"
SRC_URI[deb1.sha512sum] = "a479ebe0009f310d78e53c7b33cc4323926d4eb558c76df675b30fe6729ee797ac426fcb0e332f67dad51e5c1e87f606765264a84b94240813274ec0dbe5cd75"

RDEPENDS = " \
    libc6 \
    libgmp10 \
    libmpfr6 \
"

