# This was autogenerated! Do not modify
SUMMARY = "ISO language, territory, currency, script codes and their translations"
DESCRIPTION = ""
SECTION = "misc"
SOURCE_PACKAGE = "iso-codes"
HOMEPAGE = "https://salsa.debian.org/iso-codes-team/iso-codes"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/iso-codes/iso-codes_4.18.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "303b4e8d876b70d40710f602784d4fc9"
SRC_URI[deb0.sha1sum] = "dc78e7d1eed29c941621dae06e2db1d9469e0e9e"
SRC_URI[deb0.sha256sum] = "969582afb02fd3f0833a666b2112931a999c4f6b23e7fe514f8051dfd7672a45"
SRC_URI[deb0.sha512sum] = "6c28fe324c7cfa82cdd1d3312d7877cc9bf656cbee58f8bdce0b4e4ad19756092cb6f5fab648b73f570ce1d27aba72327291cc2b9fb85dcc554a0b6a3b236a73"


