# This was autogenerated! Do not modify
SUMMARY = "GCC support library (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "gcc-13"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13/libgcc-13-dev_13.3.0-16_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13/libgcc-13-dev_13.3.0-16_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "367281450af39d24dea2cd7cb841cdc8"
SRC_URI[deb0.sha1sum] = "47d18358f02dc97e32641f6ca542bbcd69c93976"
SRC_URI[deb0.sha256sum] = "0cd4b5bbead6f7908db91846caa7d73533e8ffe26e628e60cd572b8bd363fbdf"
SRC_URI[deb0.sha512sum] = "5a8c4c9470447c782a2bbfca9d18346fa66ad707e305700ffe56c0954f24e63bc31db64c598e1545b7b87ea8d108ac1f5d01d5644ee44486368a1c13dc89971d"
SRC_URI[deb1.md5sum] = "3a72fa0c8cf45b60fdf67537b972354c"
SRC_URI[deb1.sha1sum] = "8245bfe4ae1a5724176df2554fd6266aeafc08f4"
SRC_URI[deb1.sha256sum] = "211f8a091784eb08e3618675fe42ff6670a4e7b3381661593c6defe5bcb623d5"
SRC_URI[deb1.sha512sum] = "3bc60bbe9c39d79cdd070969efcbac6114b3f6b2bba7fc2491d5b6991fa60ef8871cb6ea148e99ccd9c8443ef391131236343540145c55645e9c24ceabd3725a"

RDEPENDS = " \
    gcc-13-base \
    libasan8 \
    libatomic1 \
    libgcc-s1 \
    libgomp1 \
    libhwasan0 \
    libitm1 \
    liblsan0 \
    libtsan2 \
    libubsan1 \
"
RDEPENDS:append:amd64 = " \
    libquadmath0 \
"

