# This was autogenerated! Do not modify
SUMMARY = "GNU Standard C++ Library v3 (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "gcc-13"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13/libstdc++-13-dev_13.3.0-16_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13/libstdc++-13-dev_13.3.0-16_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "6d5d82a7d927a6ed695c3a83a34c1712"
SRC_URI[deb0.sha1sum] = "0788651f5fcdec481710daeb9a3a581a095aa477"
SRC_URI[deb0.sha256sum] = "bc99d71c3aab24f73d8e0359a1a540de3bcaf3030739a2c82ecf62aabfcb1744"
SRC_URI[deb0.sha512sum] = "b52d5edf28eda23b0c7c9b22d16c646f57a9c9561dfa56941cac8fe3f68efe711e61dffc3a64fb7faf6e0ff146d53701f9c1a548c723bdc7037a8825b90c94ff"
SRC_URI[deb1.md5sum] = "8b283d4d9a57d299b70975dfbcaa21db"
SRC_URI[deb1.sha1sum] = "e18d44f08b45b467ae36ec727cd17cf21dbd74ff"
SRC_URI[deb1.sha256sum] = "5db1835e949dc2682ee27f3732af709bc6a80f9a825a70a389dd84f24ed48078"
SRC_URI[deb1.sha512sum] = "582e89d680d790bac81e2b4936fa24e17dcc7f4d115fec02eb852d202b3ba144b60a25591a6c9735e040e6fb8dd6a57233964bb2aa3b7d6c4b15224e18124186"

RDEPENDS = " \
    gcc-13-base \
    libc6-dev \
    libgcc-13-dev \
    libstdc++6 \
"

RPROVIDES = " \
    libstdc++-dev \
"
