# This was autogenerated! Do not modify
SUMMARY = "System call tracer"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "strace"
HOMEPAGE = "https://strace.io"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/strace/strace_6.13+ds-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/strace/strace_6.13+ds-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "57c166a524b9b4752a4830e70a744abb"
SRC_URI[deb0.sha1sum] = "dc6111d87e2f538b17b2028989a572f21e76e2c1"
SRC_URI[deb0.sha256sum] = "cae290b67cf835350a2cde58ca332256fba475784b3e02a9a8677d73eaf47511"
SRC_URI[deb0.sha512sum] = "97b6a3c53f3747b4327cb6ae3572efe095de8aadfe061956d586d7cbd5a79fbbd5df3eaee9253309221c3772d8dfee47c0bf1b83394a6a800638accdbfe999e4"
SRC_URI[deb1.md5sum] = "b4da37caf9ccc91b7284a3023747ed87"
SRC_URI[deb1.sha1sum] = "3154e49499b7c31fab4d473711d01fcadd46299c"
SRC_URI[deb1.sha256sum] = "d793af70a104eb0bd5be466c3043b512f549e7cb27971320a7c9b8f4c6165e55"
SRC_URI[deb1.sha512sum] = "7d2cf32f10643995d70e8c81830c4aae06bab5d892955c0a17f5fd571e7a72e02673a0234755c8851390e12ae58a4c223aa67bbe9cb95c8cb40a73503dc8fa2b"

RDEPENDS = " \
    libc6 \
"
RDEPENDS:append:amd64 = " \
    libunwind8 \
"

