# This was autogenerated! Do not modify
SUMMARY = "File identification library for Python"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "identify"
HOMEPAGE = "https://github.com/chriskuehl/identify"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/i/identify/python3-identify_2.6.10-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "54715433cb1cd4d062e4f474a81c1763"
SRC_URI[deb0.sha1sum] = "74085e5cb1614c1b2723d0fd19a8ff7761e92eee"
SRC_URI[deb0.sha256sum] = "8694da6bf69feebd0b90f4b1bee9840da02f74e1d8d80691bb613e4507465d1b"
SRC_URI[deb0.sha512sum] = "bdeea8ff27786d5e716a7a89cb37383cad608607d4d9300f4051eb65ec9df1df99e4ae5e4a5ea14d02cbf40aea7c6c5d0579cadeacf5de3db7c69ce713bc96ac"

RDEPENDS = " \
    python3 \
"

