# This was autogenerated! Do not modify
SUMMARY = "client-side window decoration library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libdecor-0"
HOMEPAGE = "https://gitlab.freedesktop.org/libdecor/libdecor"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libdecor-0/libdecor-0-0_0.2.2-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libdecor-0/libdecor-0-0_0.2.2-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "3534a0e94c56d5c80f51aa6496713f54"
SRC_URI[deb0.sha1sum] = "ba9f1497c2e26f8fea48bd3de50f5eabfc5a8e84"
SRC_URI[deb0.sha256sum] = "e4f228a9d4a38af23fab00f8e20219790b567e2e1f7804b3a215a26294350f82"
SRC_URI[deb0.sha512sum] = "d35da57b968ac99fbc75fab3ddb8f12e950d592ee9106ff41ef22c96378a241f34cb6167d210beaa5a91852dd766c5e2b08e6f2490436c6062040a422c2c6064"
SRC_URI[deb1.md5sum] = "4a7b0cd2221ff4e6e5c1f1212578f223"
SRC_URI[deb1.sha1sum] = "2b2eb23dcf6063cc69a30171c9ee889c405757be"
SRC_URI[deb1.sha256sum] = "34c0db59390767ef7b1cb5594f78f142b0673a5e7788e068cdd323f9c16f9207"
SRC_URI[deb1.sha512sum] = "0cef1365898b06052838cd1b8ef03ddb49e73796abdc1984559997d91250185ced2b589634668f85ea5f99d0ee374d4bb9024d8029b5ac59e130e82222e1fc07"

RDEPENDS = " \
    libc6 \
    libwayland-client0 \
"

