# This was autogenerated! Do not modify
SUMMARY = "GNU version of the tar archiving utility"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "tar"
HOMEPAGE = "https://www.gnu.org/software/tar/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tar/tar_1.35+dfsg-3.1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tar/tar_1.35+dfsg-3.1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "31ebc19d9c4c1c57b1f337f3618588a9"
SRC_URI[deb0.sha1sum] = "24a3a22da8a3c894ae31e2e72538d2d3d28e7790"
SRC_URI[deb0.sha256sum] = "214c02e1aa291076a3147b8a4c4cae02fadf4c67df629186e3e313726faef1de"
SRC_URI[deb0.sha512sum] = "a11027aacc71b99b909c96ba334c4ea7386f99b3fdc3738bb11abb278826ac02237f4bb3eb147d8c21e12645415d4d34e16858662240cd15d7442e4d23e44e03"
SRC_URI[deb1.md5sum] = "091a5abbd79aa35881226017eb01f545"
SRC_URI[deb1.sha1sum] = "59ad34429ad3bb4f376cb20c1cdec7e57e487cd2"
SRC_URI[deb1.sha256sum] = "c460a8294202ca3802b7c703b0bd70dd8bda1f2fc8785839595cf9d5e060d71b"
SRC_URI[deb1.sha512sum] = "c7ef913c6e6704ca99ad4b5a87f6fb0011974f67f0320a3768c62eec98f24c744769f37bdf1eac8b0c241c3073b659e47412b39cd7253c2f34bbc451b3b67d5a"

RDEPENDS = " \
    libacl1 \
    libc6 \
    libselinux1 \
"

