# This was autogenerated! Do not modify
SUMMARY = "LI demo applications for EBcLfSA"
DESCRIPTION = "Demo applications for demonstrating and testing EBcLfSA functionality. \
 \
Dynamically linked binary for LI environments."
SECTION = "utils"
SOURCE_PACKAGE = "ebcl-userland-utils"
HOMEPAGE = "https://gitext.elektrobitautomotive.com/EB-Linux/ebcl-userland-utils"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC_BINARY}/pool/main/e/ebcl-userland-utils/ebclfsa-li-demo_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "d6278c100fe643585321428708fe24d4"
SRC_URI[deb0.sha1sum] = "5a60b34b48a658bf031b9440e00477674818c269"
SRC_URI[deb0.sha256sum] = "0e5f4229a46ecf9be9d3bd13062369f6420d4694aadbad24d5d11b36af6ab3f0"

RDEPENDS = " \
    libc6 \
    libcomfwdlib-li1 \
"

