# This was autogenerated! Do not modify
SUMMARY = "HI demo applications for EBcLfSA"
DESCRIPTION = "Demo applications for demonstrating and testing EBcLfSA functionality. \
 \
Statically linked binaries for HI environments."
SECTION = "utils"
SOURCE_PACKAGE = "ebcl-userland-utils"
HOMEPAGE = "https://gitext.elektrobitautomotive.com/EB-Linux/ebcl-userland-utils"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC_BINARY}/pool/main/e/ebcl-userland-utils/ebclfsa-hi-demo_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "26455728cc8b957b50f4bce1d8df816c"
SRC_URI[deb0.sha1sum] = "ed1aba9fcf383113ed437109bdfebeca399476d1"
SRC_URI[deb0.sha256sum] = "3cc49ad8d9163be4bc1224f1cd42ea0895a415ed53fc6093dfe9e2526f1bd6dd"

RDEPENDS = " \
    musl \
"

