# This was autogenerated! Do not modify
SUMMARY = "eBPF helper library (shared library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libbpf"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libb/libbpf/libbpf1_1.5.0-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libb/libbpf/libbpf1_1.5.0-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "3478aa891f2f2b051b2df5aee4d54693"
SRC_URI[deb0.sha1sum] = "1892fdadd7b362260b6c6aa238dbd6b9ca528c4f"
SRC_URI[deb0.sha256sum] = "04c96ead3024888d80d08c8d08cc8cf4589f4614627acc69519f87ffb5adc1c2"
SRC_URI[deb0.sha512sum] = "e99cb46d715a061508a503ecb25ac94809d8aaa9d9f23b3e9c73cfdc21e30ce1e3c71d080bb55235010b09cb019e0f1bac84f697dea207d3d784fd7cb4a71e64"
SRC_URI[deb1.md5sum] = "2830324cd94d82b638bc45229c6c0bd7"
SRC_URI[deb1.sha1sum] = "ba658524cb09b86420860a52b5f42a3c54a145f5"
SRC_URI[deb1.sha256sum] = "1ca7f600fb8e723a41d6b8220370a6e441f91a1ac513cd59cfeaf4eb2f5136ec"
SRC_URI[deb1.sha512sum] = "0fc09b0a540c417221a56793b8435bc0c2fd4d2be644498da1ab18d2ec25e1626007895c8f22fbfcf7be6ea26c4d54e630a5d86393365d754019d0b231fc3f3b"

RDEPENDS = " \
    libc6 \
    libelf1t64 \
    zlib1g \
"

