# This was autogenerated! Do not modify
SUMMARY = "debug symbols for ubus"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "ubus"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/u/ubus/ubus-dbgsym_20250807_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "687e5da215d31b33f50f5f8f0436e186"
SRC_URI[deb0.sha1sum] = "42b1a44eec61365cbf182812343ac3755fa822ed"
SRC_URI[deb0.sha256sum] = "4cb3df4f02f1145ebf333f8a7be05f5fc0e2768e2afe84c7b0db48c30c6df84a"

RDEPENDS = " \
    ubus \
"

