# This was autogenerated! Do not modify
SUMMARY = "extension to include jQuery on newer Sphinx releases"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "sphinxcontrib-jquery"
HOMEPAGE = "https://github.com/sphinx-contrib/jquery"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sphinxcontrib-jquery/python3-sphinxcontrib.jquery_4.1-5_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "9de0d1a3d01ed26a6b1098c767f838a8"
SRC_URI[deb0.sha1sum] = "3cfebd5271d0766ffdc2405142b43e1a3fbc1ea5"
SRC_URI[deb0.sha256sum] = "bec8ec04b7c1f03324464ca009fb3a25c37037ae98e41633b1c795cd8ee85ecf"
SRC_URI[deb0.sha512sum] = "14e573e49c71c1a13e19f4a211b735ec1073a194961659ef2122d8eb75399d8eee8e6f8000d6246cb10eff09644363586285b69c0ef6db5e034081c087ee1ef5"

RDEPENDS = " \
    libjs-jquery \
    python3 \
    python3-sphinx \
"

