# This was autogenerated! Do not modify
SUMMARY = "JavaScript support for Sphinx documentation"
DESCRIPTION = ""
SECTION = "javascript"
SOURCE_PACKAGE = "sphinx"
HOMEPAGE = "https://www.sphinx-doc.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sphinx/libjs-sphinxdoc_8.1.3-5_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "223a18d2dd85afe5e6105ce04de5be96"
SRC_URI[deb0.sha1sum] = "e5cdc3313284bc6870a396de4082dfe47c303212"
SRC_URI[deb0.sha256sum] = "ec764abfb43e5e8b86bd78ea0d5a97253131ba373e50c28c7d9c08cd1b8a8e3e"
SRC_URI[deb0.sha512sum] = "5a963c503cd582e716aff4273270d44f331a470b64b4fda32e269e5855f7fb4b1aeb2a996b5832705ff77c9a23b508636a01579492c71c2e956312c1985ed03c"

RDEPENDS = " \
    libjs-jquery \
    libjs-underscore \
"

