# This was autogenerated! Do not modify
SUMMARY = "YAML parser and emitter for C++ - development files"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "yaml-cpp"
HOMEPAGE = "https://github.com/jbeder/yaml-cpp"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/y/yaml-cpp/libyaml-cpp-dev_0.8.0+dfsg-7_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/y/yaml-cpp/libyaml-cpp-dev_0.8.0+dfsg-7_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4c835dea991e86faab10f7c2cea969d4"
SRC_URI[deb0.sha1sum] = "72c2d45cfcccc393826acffc8f324760021144f6"
SRC_URI[deb0.sha256sum] = "0103d77ce1535dea4499ab5ad970ab6a343ef63dd93f2a9fdbbf529249719ce0"
SRC_URI[deb0.sha512sum] = "1db270cee83e8717e25b8e6fe4e149ce82fff04df97e50237f5f683c6fb58969e7237fcc4516337592dff7904f01cec8151ee922d6a8dd2b2e16e693b8c40ad3"
SRC_URI[deb1.md5sum] = "f57cc6f9a4f4d368420b49a0088c6c28"
SRC_URI[deb1.sha1sum] = "1a9eb8779e6e50c178417fde842689518e0c4a55"
SRC_URI[deb1.sha256sum] = "300d343e33d7f629a242270f5404fb99ed1ba8bb9376044a8104c660aea3fad3"
SRC_URI[deb1.sha512sum] = "5823fb39818196263044cfe3625a775d5b098d05abc785363676d982a666eb8c95e9f609b947687a0dc3ba648107326befb8b005fa5d611f45017a35f8b2ace2"

RDEPENDS = " \
    libyaml-cpp0.8 \
"

