# This was autogenerated! Do not modify
SUMMARY = "library implementing HTTP/2 protocol (shared library)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "nghttp2"
HOMEPAGE = "https://nghttp2.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nghttp2/libnghttp2-14_1.64.0-1.1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/nghttp2/libnghttp2-14_1.64.0-1.1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "3650643a734bbd58529afd0493d181b2"
SRC_URI[deb0.sha1sum] = "5e221d7a3f04f19acb50ae187d26aa7bbcf0d924"
SRC_URI[deb0.sha256sum] = "896cb217537c09251fb909b8541349010ac279d802d871e98c06a62a2c67ce2c"
SRC_URI[deb0.sha512sum] = "0b1440188e0bbef3e5cdcacaf8f47b94afda7b69dcaddcc6965f3d08a9c7f314fe6939bcf3c86177292d0ae71ab19a37f5c4d59d2e6c1d8e2357443a4a691b9a"
SRC_URI[deb1.md5sum] = "4a8c3ff02286da3016035bdb03405d41"
SRC_URI[deb1.sha1sum] = "e0b30b461a3e305d3e12453faca5624f9bb19694"
SRC_URI[deb1.sha256sum] = "ca222b98d5bef2193c05a1e736d0619798ba7a8f8e92526f3e1d06edcd0bf751"
SRC_URI[deb1.sha512sum] = "1db685ae7dc1e3b6bceb0d7f84859a022728445e7b6c1787be41db80cba73993679b4e1f878b23be7ddcd403f83c12a0f7ec908a98272951b54fd4cb24d763f6"

RDEPENDS = " \
    libc6 \
"

