# This was autogenerated! Do not modify
SUMMARY = "shared low-level terminfo library for terminal handling"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "ncurses"
HOMEPAGE = "https://invisible-island.net/ncurses/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/ncurses/libtinfo6_6.5+20250216-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/ncurses/libtinfo6_6.5+20250216-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "29b1dca7fda2ed82e943e059bea53fec"
SRC_URI[deb0.sha1sum] = "71f2f41f5570ca3482ffb5db97b34f46c6f42b65"
SRC_URI[deb0.sha256sum] = "8b9f6a7983e9418564e48a627518de4c03917b56efe68d7f3e93bd8fffa1cc10"
SRC_URI[deb0.sha512sum] = "53597edeb8053e169f0aec20a36310156f5fa903105abb23016ee91980bf1889f5d159d976b1d57a354a33186726c2014d2307928c38f4246310de9b604d53bb"
SRC_URI[deb1.md5sum] = "8e8ca4096d7cef688cde8918acef9e2f"
SRC_URI[deb1.sha1sum] = "50dda313e588973a1657f81fce4cbb1d3b000055"
SRC_URI[deb1.sha256sum] = "2a747f7fff3c2347c357387a7133df997410f07ba1b1df1a1461a97bd7fbc2fc"
SRC_URI[deb1.sha512sum] = "36c3771c354a4d735626089e6e7ee5b205a9fda9ddb5587241b0625af6ef9fb7baa2110a62df19b462816b981d8244ae74793303de371822952391c3711a78f7"

RDEPENDS = " \
    libc6 \
"

