# This was autogenerated! Do not modify
SUMMARY = "XSLT 1.0 processing library - runtime library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxslt"
HOMEPAGE = "https://gitlab.gnome.org/GNOME/libxslt/-/wikis/home"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxslt/libxslt1.1_1.1.35-1.2+deb13u2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxslt/libxslt1.1_1.1.35-1.2+deb13u2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e4be2efdf330d90bf3cba9f4f30a1c77"
SRC_URI[deb0.sha1sum] = "6aacb7be9da3ae00362a1c025267f7b91815164e"
SRC_URI[deb0.sha256sum] = "9bc71cdba622881dc1ad97a9854309025623ad10e9b545adeb7587cb26ecafe5"
SRC_URI[deb0.sha512sum] = "c37ced42d93b9aca1a0f3d5a7fc866bb62f9323eec3c1f5a1928960d9b210b86ac4a0ee1c3b494ca5b03690f158988b1a4cf9517fa8683ca3e00e2ead4950f2b"
SRC_URI[deb1.md5sum] = "8378dce6d4ed2b2e702f3381432a5050"
SRC_URI[deb1.sha1sum] = "2d6008ac0b93fbd11d2db06f7ce8763332c9adf2"
SRC_URI[deb1.sha256sum] = "c9d10c07fd569ff89834709eb53bb3caf844b503d43b37042f9ee717c224ea28"
SRC_URI[deb1.sha512sum] = "72065c1bda87ae597a21313bb7ccab7079c334b6938a97f336ee480ea331c36bc658c87f74bc3520e5d10e67ca8d9de90642ca4d64ab2713ed92962332f2dbbe"

RDEPENDS = " \
    libc6 \
    libgcrypt20 \
    libxml2 \
"

