# This was autogenerated! Do not modify
SUMMARY = "XSLT 1.0 processing library - runtime library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxslt"
HOMEPAGE = "https://gitlab.gnome.org/GNOME/libxslt/-/wikis/home"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxslt/libxslt1.1_1.1.35-1.2+deb13u3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxslt/libxslt1.1_1.1.35-1.2+deb13u3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b51d6b912a7c65c7a0d7eda2cffa7881"
SRC_URI[deb0.sha1sum] = "3e4a67ab58d0cc533ccc25c97b7071c8eb543bb0"
SRC_URI[deb0.sha256sum] = "c8e5a745ca3afaa079b01e0c00d80a241101d1ab840407fcd4bb423de3326160"
SRC_URI[deb0.sha512sum] = "e675da61125fd33eb88633a5021c5b39520d7e56905e678728eb159b167a0f56faa9d99c0854f9f0ffd7e18bcbb5374c49450e6b0d50c6008216ab5b79b64266"
SRC_URI[deb1.md5sum] = "54a6c7e3930387d0c201b02250c5c8e6"
SRC_URI[deb1.sha1sum] = "a49066e3efb5a329e5558c5fe3b62d5970257644"
SRC_URI[deb1.sha256sum] = "590a5d177dcfa2bf432f0d7db80b936ac7afadfebdb7f077d0c3305da20d1897"
SRC_URI[deb1.sha512sum] = "a484e9dd816951d9a43049da4adeed14ea276224a8376c2131de547a1fda3b6c9d7cf171a1d3e4342593800b4188947980a5f6d244f4293759512a5f1a0842a6"

RDEPENDS = " \
    libc6 \
    libgcrypt20 \
    libxml2 \
"

