# This was autogenerated! Do not modify
SUMMARY = "asynchronous event notification library - runtime library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libuv1"
HOMEPAGE = "https://github.com/libuv/libuv"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libu/libuv1/libuv1t64_1.50.0-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libu/libuv1/libuv1t64_1.50.0-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d98e814a0b3e998b7536ae92a2c551cd"
SRC_URI[deb0.sha1sum] = "dc02e2fb87ccc4bd0715a2e026026e269382afdf"
SRC_URI[deb0.sha256sum] = "5fec8035002e0c745b64d1c5b3e1dc42790d1a77574315b976cf3e4aab9ddc0a"
SRC_URI[deb0.sha512sum] = "d3929f4bbbf6d947e54c72d4539d599b0e6c3d03fcdb4b23874b11ff043d218df462f9874195507d16cede4f539b43432fbf987c618e3e3ea12d69952befce71"
SRC_URI[deb1.md5sum] = "cf158a6776dd513cb3d2b994a74da033"
SRC_URI[deb1.sha1sum] = "fdd88a50caba126d8ceb1c5731363bf2742980a1"
SRC_URI[deb1.sha256sum] = "a9be0f24d7686ba94a6ef4f3c638079c6b39c4263306860d51046c4125d065f4"
SRC_URI[deb1.sha512sum] = "8d4bee2674c61e7f04706b9c636c47c5f87085c81fd34ce212fb52a3644f69da83e65aa16d8faa992b60747002a23ea57daea4864a354c4b0ed9e0b364c056dc"

RDEPENDS = " \
    libc6 \
"

RPROVIDES = " \
    libuv1 \
"
