# This was autogenerated! Do not modify
SUMMARY = "EB corbos Linux for Safety Applications Muslc Tools for using muslc and clang"
DESCRIPTION = "Tools for building applications using lisa-libc and clang."
SECTION = "devel"
SOURCE_PACKAGE = "lisa-libc"
HOMEPAGE = "https://gitext.elektrobitautomotive.com/EB-Linux/lisa-libc"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC}/pool/main/l/lisa-libc/lisa-libc-tools-clang_1.2.5_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "2c77bd8df7eac167fd60a4bb14a432f1"
SRC_URI[deb0.sha1sum] = "d319445fb1b90fb0aeea2c8cab9cf5825a05c42f"
SRC_URI[deb0.sha256sum] = "a60d1043d15ced5eb0076c2552a09beae6de30761a8e94bd76790fec03292cce"

RDEPENDS = " \
    lisa-libc-dev \
"

