# This was autogenerated! Do not modify
SUMMARY = "documentation generator for Python projects"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "sphinx"
HOMEPAGE = "https://www.sphinx-doc.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sphinx/python3-sphinx_8.1.3-5_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "5982cc5b00f7f479bd861a0224e3beb8"
SRC_URI[deb0.sha1sum] = "efedd06145dccbb1a661a83292f5aeb2f565ce0e"
SRC_URI[deb0.sha256sum] = "a8850fc67a970e75940ed370ae3a2542733d5792f80a54a1ede7d4ebed0825f3"
SRC_URI[deb0.sha512sum] = "fe804d6041a82768f229fb34baac7a9746e03fb0f0d9266666c948b235fb2ab4cb886176c45bb66019dca5656d82474fd56d2e8c7fcc8cc615ce9dbca0262c41"

RDEPENDS = " \
    python3 \
    python3-alabaster \
    python3-babel \
    python3-defusedxml \
    python3-docutils \
    python3-imagesize \
    python3-jinja2 \
    python3-packaging \
    python3-pygments \
    python3-requests \
    python3-snowballstemmer \
    python3-tomli \
    sphinx-common \
"

RPROVIDES = " \
    sphinx \
"
