# This was autogenerated! Do not modify
SUMMARY = "documentation generator for Python projects - common data"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "sphinx"
HOMEPAGE = "https://www.sphinx-doc.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sphinx/sphinx-common_8.1.3-5_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f6d8d4a6d5c8b3fe1f622f8c556a6dd6"
SRC_URI[deb0.sha1sum] = "117f9d6f29de9fd4865d3fe42346712d2ce23a7a"
SRC_URI[deb0.sha256sum] = "609b7421027565a1601c415a1200b99d7a4e2720742146e9e30d714fbccc521f"
SRC_URI[deb0.sha512sum] = "33ec192c375d116407e5fc4cfd72b817f3bb386c580b6f40765b009b666073269f1c41e6c8adb0d19a35c566bbfb7755ae48ca7b0a89908b67ed1933c1781fab"

RDEPENDS = " \
    libjs-sphinxdoc \
    libjson-perl \
    perl \
"

RPROVIDES = " \
    dh-sequence-sphinxdoc \
"
