# This was autogenerated! Do not modify
SUMMARY = "GObject-based wrapper library for libudev"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libgudev"
HOMEPAGE = "https://wiki.gnome.org/Projects/libgudev"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libg/libgudev/libgudev-1.0-0_238-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libg/libgudev/libgudev-1.0-0_238-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8f0d78af7731eb60ed3185620703402f"
SRC_URI[deb0.sha1sum] = "3a7615cf56a4445f05598b18345fed9bfbeaaf3e"
SRC_URI[deb0.sha256sum] = "890a55ea26f52062f377389e6326abeadb72a14741c95ab6a1c5a19c77c3c3d0"
SRC_URI[deb0.sha512sum] = "ef9e937df38aa37c728e1e42b9cd4e5190cb2307861ab1c7136bb57565b97b376adeb0282dc1076826a7e7ed7898036b74e0fd475128d768c3ef4fe120ddd027"
SRC_URI[deb1.md5sum] = "d5337295e234d7a6a3396369c9a4bef6"
SRC_URI[deb1.sha1sum] = "b3e4a18d500d101b965f83f5dc7198e34e002e40"
SRC_URI[deb1.sha256sum] = "f0fec02f1bbc0803c9d044413609d3cd0fde24bfe6a5141a38aabfa86c292b21"
SRC_URI[deb1.sha512sum] = "7f6ed81181d9e6f1f5e42ce0348f4167140077d4f57cbc53ded81750dfbd9015bd0e4d674341ad667f294ea3306c5781edbb418f096cfa297ffcbefc140ab397"

RDEPENDS = " \
    libc6 \
    libglib2.0-0t64 \
    libudev1 \
"

