# Copyright 2026 Elektrobit. All rights reserved.

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ebclfsa-public-bsp-rpi"
BBFILE_PATTERN_meta-ebclfsa-public-bsp-rpi = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ebclfsa-public-bsp-rpi = "7"

LAYERDEPENDS_meta-ebclfsa-public-bsp-rpi = "meta-ebclfsa-public-bsp"
LAYERSERIES_COMPAT_meta-ebclfsa-public-bsp-rpi = "v0.6"

LAYERDIR_meta-ebclfsa-public-bsp-rpi = "${LAYERDIR}"
