# This was autogenerated! Do not modify
SUMMARY = "udev rules for TPM modules"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "tpm-udev"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/t/tpm-udev/tpm-udev_0.6+nmu1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "d34dbd5a315a3a11698779a137545b9b"
SRC_URI[deb0.sha1sum] = "170fbf85aa8d35213f0c5a647c91d0b80de09f7a"
SRC_URI[deb0.sha256sum] = "103aaad530acac082222d8530586041cf2b78098d077ccf1d9418b2866d164af"
SRC_URI[deb0.sha512sum] = "6c0a226c78f3cc7ad643d2a636fcf95ca10d4c22cdef25ce33f726a86fbe9cbed12ab7b2bc810c7c6d6d3d8f5d8cb2705dd5ab977f5b5426f4d47c140bddd809"

RDEPENDS = " \
    adduser \
    udev \
"

