# This was autogenerated! Do not modify
SUMMARY = "Open H.265 video codec implementation"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libde265"
HOMEPAGE = "https://github.com/strukturag/libde265"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libde265/libde265-0_1.0.15-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libde265/libde265-0_1.0.15-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "77cf43d14766f98ddcaef8ddeee1e795"
SRC_URI[deb0.sha1sum] = "ff12c356145022070086f254e89f14a1a03c9ee1"
SRC_URI[deb0.sha256sum] = "29fc53a556f05ae2b65f6e4c927712a7191cbb675f6e02f2001e07b6cf3529da"
SRC_URI[deb0.sha512sum] = "109d38928add17ea35314bbe04702d53e1d181793b6de8c6d62a9bd3c866337b6b60a6d59d85275ce053a486a542c24d02920843fd451163ea703c839f2ea1ea"
SRC_URI[deb1.md5sum] = "40b45768100131f189bcbfe201087ede"
SRC_URI[deb1.sha1sum] = "eaedefcc862e7e8f8db1c5987538f95731a01ec4"
SRC_URI[deb1.sha256sum] = "4264617806a2cf98db884837c6dd9602681f5568aebf3e464589b73a03892b78"
SRC_URI[deb1.sha512sum] = "0f19cfdf2df64ef7333277c01a0ce54e13001c27f5bbf74b22f80f9d2552b64677dc62e6e07e12adeb69c774335dc706b63a1058498e5b93cdc65221e3f29e21"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
"

