# This was autogenerated! Do not modify
SUMMARY = "Example KMS/GBM/EGL application"
DESCRIPTION = ""
SECTION = "graphics"
SOURCE_PACKAGE = "kmscube"
HOMEPAGE = "https://cgit.freedesktop.org/mesa/kmscube/"

inherit dpkg-prebuilt

DPKG_ARCH = "amd64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/k/kmscube/kmscube_0.0.0~git20210103-1+b2_amd64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "afb5ff5ed6e4c9747335403347e4efb9"
SRC_URI[deb0.sha1sum] = "a9b6594dcf34fd0f5467fd70e16ecae962f86a00"
SRC_URI[deb0.sha256sum] = "dfa40a966c06c483786c2f7a1a45d4a7de4c976cb3c211e4f5c0838d8a724d51"
SRC_URI[deb0.sha512sum] = "806dc92bc2735444bb0123cffaff6c9e5e3e0a8eb5d18a32b74f84361f9f93fcda53ab359b66270a20b07186fbe070e85b086121af6d4e84aa441a08577a8228"

RDEPENDS = " \
    libc6 \
    libdrm2 \
    libegl1 \
    libgbm1 \
    libgles2 \
    libglib2.0-0t64 \
    libgstreamer-plugins-base1.0-0 \
    libgstreamer1.0-0 \
    libpng16-16t64 \
"

