# This was autogenerated! Do not modify
SUMMARY = "sphinx theme from readthedocs.org (common files)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "sphinx-rtd-theme"
HOMEPAGE = "https://github.com/readthedocs/sphinx_rtd_theme"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sphinx-rtd-theme/sphinx-rtd-theme-common_3.0.2+dfsg-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "c914cadfcfb3fd84df4b725e939f4882"
SRC_URI[deb0.sha1sum] = "3a760867ea152a14b79c52302ecbfa03c9877269"
SRC_URI[deb0.sha256sum] = "1d6c25da42e948f707ad01df5522a289ce0fb69f18e7012b55d1c80a929d040f"
SRC_URI[deb0.sha512sum] = "4e7f902bb05720bf4cc02c4115ef0a807299ace7c85131c4a576d52fa457d523254bf6e3dd827601faf77e9be03c90d557489fbda67e91862a3cb3c03deb6118"

RDEPENDS = " \
    fonts-font-awesome \
    fonts-lato \
"

