# This was autogenerated! Do not modify
SUMMARY = "GCC support library (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "gcc-14-cross"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-14-cross/libgcc-14-dev-arm64-cross_14.2.0-19cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "5da2cfdb75edf6fc9c31de47266fe373"
SRC_URI[deb0.sha1sum] = "77e1ea409f370a215557cdea9b8ce1fcc2b08a36"
SRC_URI[deb0.sha256sum] = "44d31567993f2f138638e3088cc75240d13c7d8a2ebe69032aafd37bc35c7a6f"
SRC_URI[deb0.sha512sum] = "5ba94159bbe4f13db6b369820e07432d690fb4c7e757bfb2ce20eda11b3450f27cb96ee6db9914301002113d0bc625beb3ed0edc7d84532c7926f68362c1b057"

RDEPENDS = " \
    gcc-14-cross-base \
    libasan8-arm64-cross \
    libatomic1-arm64-cross \
    libgcc-s1-arm64-cross \
    libgomp1-arm64-cross \
    libhwasan0-arm64-cross \
    libitm1-arm64-cross \
    liblsan0-arm64-cross \
    libtsan2-arm64-cross \
    libubsan1-arm64-cross \
"

