# This was autogenerated! Do not modify
SUMMARY = "Approximate Nearest Neighbor Searching library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "ann"
HOMEPAGE = "https://www.cs.umd.edu/~mount/ANN/"

inherit dpkg-prebuilt

DPKG_ARCH = "amd64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/a/ann/libann0_1.1.2+doc-9+b1_amd64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "5c436ca7c771d4de65ee5f7b4523b1e5"
SRC_URI[deb0.sha1sum] = "cde3fe279a6c4fd7cfbde4af69dc8dd69b5b6d38"
SRC_URI[deb0.sha256sum] = "13c419c0daec7733adaa92efeb24b6cf52c9e7722e2cfe81f2b1a9464e4fc94c"
SRC_URI[deb0.sha512sum] = "a30169a47a5e06439fd70d7e3d194e46ef5f0dd38007850041772775efed9c8fd246cd3773e8bdce192f51503697034e361b23f75856a02b827d1a6104ac4e29"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
"

