# This was autogenerated! Do not modify
SUMMARY = "asynchronous name resolver - development files"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "c-ares"
HOMEPAGE = "https://c-ares.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/c-ares/libc-ares-dev_1.34.5-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/c-ares/libc-ares-dev_1.34.5-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "23ceed1d3c4f93e62d39443b36803303"
SRC_URI[deb0.sha1sum] = "df85291570dde99d0e36b489aa0faeda720ec09b"
SRC_URI[deb0.sha256sum] = "0270c69a1229fdb60e198e8ba84c8c38cdfd020009cfefee59ad253bcec26d44"
SRC_URI[deb0.sha512sum] = "e5bf1e228701c38ede0d7500494a97a5b0951cf31f679c2f7685a8730da5bc387aafe8f4dd8236bb0a91ed411604ee90a6a55ae81675b8c3d8d83c7a9d29e916"
SRC_URI[deb1.md5sum] = "acd653834ca140b6302df81b83c765d8"
SRC_URI[deb1.sha1sum] = "109d7800bf370139268bea60e2ea7e2699cc3d48"
SRC_URI[deb1.sha256sum] = "40d2336fb01e4b707ad8a6bfbad522fc7ddff3b057d16ee981237fb7cef5d95c"
SRC_URI[deb1.sha512sum] = "6ea287d3317488c025482441633e915296406f1414d69b2400524178ad7e0ffef94ae5651224331cc67a21d561cd4146ae3c62d92dc1b4527badf6032ee9221d"

RDEPENDS = " \
    libcares2 \
"

