# This was autogenerated! Do not modify
SUMMARY = "JPEG 2000 image compression/decompression library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "openjpeg2"
HOMEPAGE = "https://www.openjpeg.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/openjpeg2/libopenjp2-7_2.5.3-2.1~deb13u2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/openjpeg2/libopenjp2-7_2.5.3-2.1~deb13u2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "07e72f2421f5a7f6692e7ca04b879709"
SRC_URI[deb0.sha1sum] = "c8d0d044ab847f9a7e167761ed2a94817d9dd719"
SRC_URI[deb0.sha256sum] = "7ddf6360e8845853ba3c9cfaefc2ad6b92b2627eb8564a257f5f2a4c857f8748"
SRC_URI[deb0.sha512sum] = "37269c8d05e0d01039afbf843cd0fe26bd38f3f658be6a47e4805ad76da255854d89356408cfa42e15273e18fff70a35ca2f36f52bfee4678112397c6c08966d"
SRC_URI[deb1.md5sum] = "16a645f8864b137943408400498e6b36"
SRC_URI[deb1.sha1sum] = "6aed8fdf5c8fcd01c112e73a8e1a9fc1760358de"
SRC_URI[deb1.sha256sum] = "e27f4d03d4b5836473be3210b16567aa9435a337f8c4537868773a123f9c9e57"
SRC_URI[deb1.sha512sum] = "d4c7147d4099787e99ae2424052fe3a99108ab9954d611528dccefb3761bbe6c306c3cb22c348d7f6d64735315d77e7a6ced850078ef23af84a8f12ba799d317"

RDEPENDS = " \
    libc6 \
"

