# This was autogenerated! Do not modify
SUMMARY = "Support for extra binary formats"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "binfmt-support"
HOMEPAGE = "https://nongnu.org/binfmt-support/"

inherit dpkg-prebuilt

DPKG_ARCH = "amd64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/binfmt-support/binfmt-support_2.2.2-7_amd64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "6fb08dc9e6e65346433b8fdff637d4ac"
SRC_URI[deb0.sha1sum] = "a56ad2e94db12e87c120e09e973dd7c2b87abfe6"
SRC_URI[deb0.sha256sum] = "ff4aa9049a20d22679d41ca4000db17fb661631304a446d12782fbf8efbd2c61"
SRC_URI[deb0.sha512sum] = "d2fb63243be321762a2cac0da1c2ae93dcafa93397df7857753dca8cd1029da32d1be25f7ef0bfffa9c8bf4a025ca598bf616353912fbc16a54b6971345077e2"

RDEPENDS = " \
    init-system-helpers \
    libc6 \
    libpipeline1 \
"

