# This was autogenerated! Do not modify
SUMMARY = "OSSP uuid ISO-C and C++ - shared library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "ossp-uuid"
HOMEPAGE = "http://www.ossp.org/pkg/lib/uuid/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/ossp-uuid/libossp-uuid16_1.6.4-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/ossp-uuid/libossp-uuid16_1.6.4-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e391a3b15653d486d67662aff12c7463"
SRC_URI[deb0.sha1sum] = "6323e5f88ea1ddaafdb2210ab0c6be913088fcdf"
SRC_URI[deb0.sha256sum] = "b8c4a71ed1899281e5bb2e6f2c497171af5b13b38ae69bc477160ff0ba5b7084"
SRC_URI[deb0.sha512sum] = "fb751fa8b84d4db8cd6a2c7a6db9ae692bfa26ba2c797c97cb7d5a2f95e03a899bc8cd9e74624ec23340699a3a0edb9bc27cd6379ee9676f0250a2876fe2775f"
SRC_URI[deb1.md5sum] = "14b7b14088f1e921ada5461014cda9bb"
SRC_URI[deb1.sha1sum] = "e8c17bfad7797efc422798cca3b6cc9be9e8cded"
SRC_URI[deb1.sha256sum] = "cd0819947988b5969d53dfda142b431981732abe979e457ddf30edca440cd04d"
SRC_URI[deb1.sha512sum] = "ef3f32d99ee970263657eea2eb250d4631473426411ec96ed6cd2e88671de5c965f34b36a89d93c39dcedefd009b3798ff3fd485887805497f892124aa28437e"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libmd0 \
    libstdc++6 \
"

