# This was autogenerated! Do not modify
SUMMARY = "high performance general RPC framework - protobuf plugin"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "grpc"
HOMEPAGE = "https://www.grpc.io/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/grpc/protobuf-compiler-grpc_1.51.1-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/grpc/protobuf-compiler-grpc_1.51.1-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8dde62bf415af469229f093f0f054b11"
SRC_URI[deb0.sha1sum] = "92cdf98b31798ab48442d1d8e7808fb041a6afff"
SRC_URI[deb0.sha256sum] = "d0188dfc5ec03568dede313506037bf11acdf15c04c8f83b09d10997e0b5cb32"
SRC_URI[deb0.sha512sum] = "02acd77313ef98161280602fd24cec0cd6eed91f0838ef01087bdc2f820f53fbbb33909faf00c897c491f204270404504b6070fba0e46c389d1388f33acf556d"
SRC_URI[deb1.md5sum] = "56491356afe5382098e9b942edf1f779"
SRC_URI[deb1.sha1sum] = "fdde31c17ac5366b022ed6a598768355b432c258"
SRC_URI[deb1.sha256sum] = "6bf888c924b68b3651010a8b9843cb04a3077308a0b0987689eeddbf150cd1c6"
SRC_URI[deb1.sha512sum] = "94ff687200ac438c40293100841270379fad19b8c74650b69efca8fe28521d29713b5173eeb092a73cb19a2149b057fef1162ac643121eefb9dec2d44ad0c06b"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libgrpc29t64 \
    libprotobuf32t64 \
    libprotoc32t64 \
    libstdc++6 \
    protobuf-compiler \
"

