# This was autogenerated! Do not modify
SUMMARY = "Modular compiler and toolchain technologies - Plugins"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-17"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-17/llvm-17-linker-tools_17.0.6-22+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-17/llvm-17-linker-tools_17.0.6-22+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "44eae27d4ce9b7aefe81084154815088"
SRC_URI[deb0.sha1sum] = "320309e732fa1f8385ef715f4eb330637b6f49fb"
SRC_URI[deb0.sha256sum] = "96a59e532c37864a93238dd89aab193d459c9f23eca4f0d85828417699383fc9"
SRC_URI[deb0.sha512sum] = "ec3f4f87424568cb9b801fdfe891cd83567b90e5fa1a7afc56b0a6440b091371aab1b762cd0c056636f655ce4f1a5c44531dd3b072f6a94254ff5bbcacd85c1a"
SRC_URI[deb1.md5sum] = "35c93117dd1fd3ec344cb10128f47bed"
SRC_URI[deb1.sha1sum] = "24a453d0bb410d65a44f7f7969cc4b9ee05cda99"
SRC_URI[deb1.sha256sum] = "f56fa769da50566c51ab7ad593a146573bdba39d4335f0fa1f60e7df273ed2e5"
SRC_URI[deb1.sha512sum] = "e6d4c05521e6aa06741860aaa7296f14bc4599e4f77055995f431e17efc98211a54918a17580756305a9af2c62b5756b2f5eb7a2e9105843ac503a43effff86e"

RDEPENDS = " \
    libc6 \
    libllvm17t64 \
    libstdc++6 \
"

