# This was autogenerated! Do not modify
SUMMARY = "wayland compositor infrastructure - server library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "wayland"
HOMEPAGE = "https://wayland.freedesktop.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/w/wayland/libwayland-server0_1.23.1-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/w/wayland/libwayland-server0_1.23.1-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "56d202e0f34b4571a0a16427f818e43f"
SRC_URI[deb0.sha1sum] = "0a0b5182a51f771b9af0487f8c3a79415da98b3b"
SRC_URI[deb0.sha256sum] = "2967212bd582e0dffca443fdc44f4c660e7368d41f7ee3a7f6314e0c3abfe9ea"
SRC_URI[deb0.sha512sum] = "940d08d88029564160ab4445b16a7b59a2842b201d5abf344c43cd9973da2415e297929541bce88e2f158d384dda06a002d1b711c23d680632756a1740057192"
SRC_URI[deb1.md5sum] = "af321952ad41c00bdde312b4caeb98c3"
SRC_URI[deb1.sha1sum] = "e6fda30118e1f4d1161a6f0e2317d800b7d86662"
SRC_URI[deb1.sha256sum] = "062702d57cf07b42ab7f0fa1aac8bc3f605eb47f2f0b9ecb1614674140d79f1b"
SRC_URI[deb1.sha512sum] = "893581e1356b143d5d995eb6a96adca75fe087368b4eba741eadaf14d88dde054937a7252a2baf62fe57f82fa7b79fc6155ca0dccd0b04f54495277054489ca7"

RDEPENDS = " \
    libc6 \
    libffi8 \
"

