# This was autogenerated! Do not modify
SUMMARY = "Universally Unique Identifier Command-Line Tool"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "ossp-uuid"
HOMEPAGE = "http://www.ossp.org/pkg/lib/uuid/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/ossp-uuid/uuid_1.6.4-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/o/ossp-uuid/uuid_1.6.4-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "a75f77386697897472ffde6e48136674"
SRC_URI[deb0.sha1sum] = "0e95262e77b9158cb8a439456681f24bd8246164"
SRC_URI[deb0.sha256sum] = "dd31f4545e01834c7983684c7282c772f95a889269df2e5f3ce6728509b15269"
SRC_URI[deb0.sha512sum] = "a9a82d364793d9bd46d2175cced721895c6c9613074caa8f3e102fceb472f5057fa7c991813ba374680e59c81effd3e72e6b78d195b3d856b361118242ab88c5"
SRC_URI[deb1.md5sum] = "9038708aa826643bf3cc4169e30d3301"
SRC_URI[deb1.sha1sum] = "4a25fa0dcff06e5fa206b422cec7caf24e06c2ca"
SRC_URI[deb1.sha256sum] = "03e5f63eae3586e27549e268808875c2b96d05d9504f35915f26cfd2edb7907d"
SRC_URI[deb1.sha512sum] = "773cc5e685555df9d147056d9ab829f6232214fded00b1bd85e404fac2ca3835f8a7d1bc052ce9852677a6ac9118125c69099f02ffe2202ed9c4e3ad7b8e5f19"

RDEPENDS = " \
    libc6 \
    libossp-uuid16 \
"

