# This was autogenerated! Do not modify
SUMMARY = "library for serialising LV2 atoms to/from Turtle"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "sratom"
HOMEPAGE = "https://drobilla.net/software/sratom/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sratom/libsratom-0-0_0.6.18-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/s/sratom/libsratom-0-0_0.6.18-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "a3000c749f2f29aa4f87659a70bed014"
SRC_URI[deb0.sha1sum] = "9091d150b7b23197f60ad3a42103dbfbb15cd0ea"
SRC_URI[deb0.sha256sum] = "63195bd9233678ed397cfded0aae85d85cf2584ff7c638b34013ca34544962d7"
SRC_URI[deb0.sha512sum] = "1b87d8ffc206538a9d174f85c23c6efea2e54d065bf153fec78395f26a34e303384183f7979847e726a08738e7187b30f9449cccce2a93b205be4f231196f6da"
SRC_URI[deb1.md5sum] = "d30d1bba5bb03979f774e7f1ac18a6f0"
SRC_URI[deb1.sha1sum] = "23ae83ffc4b42b9014e0b6c1bfefcb37be9d0380"
SRC_URI[deb1.sha256sum] = "5ebc866e3632741477cc225a3a927ddacae432238494e73c50b07c00420d2406"
SRC_URI[deb1.sha512sum] = "38dcafdbfc084654f63eaebd8a5fcf1aa26cf48188205fcd13f938a2debf338762956e374ae42c54f948fb1528f6f49b532f9e7745f60f937235da77db32021b"

RDEPENDS = " \
    libc6 \
    libserd-0-0 \
    libsord-0-0 \
"

