# This was autogenerated! Do not modify
SUMMARY = "development library and header files for libpcap0.8t64"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "libpcap"
HOMEPAGE = "https://www.tcpdump.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libpcap/libpcap0.8-dev_1.10.5-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libp/libpcap/libpcap0.8-dev_1.10.5-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "408079c94392b923a704518eedfcd30c"
SRC_URI[deb0.sha1sum] = "c6323da348097812f855628d4b76f8b1f56642c1"
SRC_URI[deb0.sha256sum] = "ff09ac0f76e113ccdef974645a394788d1afd07c5de1c15a0408cfadf625e2a6"
SRC_URI[deb0.sha512sum] = "aac895afc5f99c257030e783b043e00a17fdf1931943a0920ea384e74febeaa9be8a0e23c11d5f15791d73002140d52a477af164bfa8d9911271d7481571d947"
SRC_URI[deb1.md5sum] = "2abc0ad99bd43d2ddf9a72dfcd4a28cf"
SRC_URI[deb1.sha1sum] = "85ba41842d5057d7ab16a56a5e2a1374cb0d45b1"
SRC_URI[deb1.sha256sum] = "180c4d6f3158305b06d116ece7bed14024c3f6a06da2b898a34a008a20b4faf5"
SRC_URI[deb1.sha512sum] = "8dadb667feb89baebd80a162e2a2e71734801639e5211acbe58add1610ce3db34c5c402f5829072940b3c9d87f794519459b5f9d99bce3ea3be8ce8c4edd15da"

RDEPENDS = " \
    libc6-dev \
    libdbus-1-dev \
    libpcap0.8t64 \
"

