# This was autogenerated! Do not modify
SUMMARY = "jaraco text manipulation functions"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "jaraco.text"
HOMEPAGE = "https://github.com/jaraco/jaraco.text"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/j/jaraco.text/python3-jaraco.text_4.0.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "7a503cf49a19aa6ad675719f2b8ccfb9"
SRC_URI[deb0.sha1sum] = "c757561a521b38acc838c025be29546bc8baf37c"
SRC_URI[deb0.sha256sum] = "d5e060c9ba9d5206b53670cf2473681b45030cc6a55d18a8c6d87419a924e502"
SRC_URI[deb0.sha512sum] = "caca71f751a303268926fa94945ee5203aee3b45399b51fbc18b18e72bffc3581de389bb7bd66618b12a3668273891aad9c94fe54639c7cca0750afa7f71c45c"

RDEPENDS = " \
    python3 \
    python3-autocommand \
    python3-importlib-resources \
    python3-inflect \
    python3-jaraco.context \
    python3-jaraco.functools \
    python3-more-itertools \
"

