# This was autogenerated! Do not modify
SUMMARY = "CMake data files (modules, templates and documentation)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "cmake"
HOMEPAGE = "https://cmake.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cmake/cmake-data_3.31.6-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f3eff7146b3c3afbbab54e41617a455d"
SRC_URI[deb0.sha1sum] = "d6c226e26a939d8da1f17f67c73cd231059f0bbe"
SRC_URI[deb0.sha256sum] = "d9060145be892f43cd1888024114ceab019c81479d4b0a3383fe14cebe2295cb"
SRC_URI[deb0.sha512sum] = "c1861ed7b7ddb3393a4b5ccb450220c381bf02cb45e0a8e476e8c6810ace8116e8c37893beebd7034cc67aa2e63b8471dc7e2580f4ef89e0b78ce9cba7c5b3c6"


