# This was autogenerated! Do not modify
SUMMARY = "debug symbols for ucode"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "ucode"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/u/ucode/ucode-dbgsym_0.0.20220322_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f33ae86840c919b832f56f6b6de3624e"
SRC_URI[deb0.sha1sum] = "913cf8877639880dc8153b5972056c92f2d5a6e9"
SRC_URI[deb0.sha256sum] = "d5754cafc1b485de3937db4af7298764344532d51f5b24b6252d065b2a4329f2"

RDEPENDS = " \
    ucode \
"

