# This was autogenerated! Do not modify
SUMMARY = "Perl module for runtime module handling"
DESCRIPTION = ""
SECTION = "perl"
SOURCE_PACKAGE = "libmodule-runtime-perl"
HOMEPAGE = "https://metacpan.org/release/Module-Runtime"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libm/libmodule-runtime-perl/libmodule-runtime-perl_0.018-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f09acea67d7caedf58138e2af988e152"
SRC_URI[deb0.sha1sum] = "fa115f879f903dd034373e0b8a034121bc896c7c"
SRC_URI[deb0.sha256sum] = "e0244fda81ace4f75ef26bef83362742468f229bb0fa4b531b4be583100a5505"
SRC_URI[deb0.sha512sum] = "d772fa37d526f47afdd089d6d6a89d08f270e442bb5c2f7b99dcacd86af24a4bda5fcb9e03d06cf4995b84fcc1e15074b43d04fb89789fc1bb76b0f86d8ea765"

RDEPENDS = " \
    libparams-classify-perl \
    perl \
"

