# This was autogenerated! Do not modify
SUMMARY = "Library for direct userspace use of RDMA (InfiniBand/iWARP)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "rdma-core"
HOMEPAGE = "https://github.com/linux-rdma/rdma-core"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rdma-core/libibverbs1_56.1-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rdma-core/libibverbs1_56.1-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "ae96ed777402805895368057699d3c41"
SRC_URI[deb0.sha1sum] = "da9c18b3101ef181e22c9a25093b2b011958f186"
SRC_URI[deb0.sha256sum] = "4c3b889607586e6328964a5f98e01ef01daa415be24334d743d6654aab4c47a4"
SRC_URI[deb0.sha512sum] = "62ae9c09123735bca7ec9f03a151c994dbfc935b3044b53168a32308889c0009095174ba18c6835522abc06cfba2cbfede5281d29a211861dd15048e3fcabbf4"
SRC_URI[deb1.md5sum] = "5d8854783afb1ca7e3d55a3c56ebe7e0"
SRC_URI[deb1.sha1sum] = "efc951670bbbe31f861b4765a4ba31ab443b1296"
SRC_URI[deb1.sha256sum] = "c3c57dcc2d4bf2ac2d73a4c93da3d0939198ad6f1de80f10b60b9042d33cbe54"
SRC_URI[deb1.sha512sum] = "2c48b3356833eea0b78f8e6a89a5e1712a20d3436ffada084716a4d3c22bf9d8839dda22d0306ad49fd430924bfb02ab2ab290401731421d91ec78c309dd89b3"

RDEPENDS = " \
    adduser \
    libc6 \
    libnl-3-200 \
    libnl-route-3-200 \
"

