# This was autogenerated! Do not modify
SUMMARY = "Library for managing RDMA connections"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "rdma-core"
HOMEPAGE = "https://github.com/linux-rdma/rdma-core"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rdma-core/librdmacm1t64_56.1-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rdma-core/librdmacm1t64_56.1-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4924655136c7260f69b5c217e4168161"
SRC_URI[deb0.sha1sum] = "98db477969cbcbf373c3661624b4c5140cb25626"
SRC_URI[deb0.sha256sum] = "5b56911725905b8e2a8389c99416ca078395c4ca8ce0d516bc758d5be0134687"
SRC_URI[deb0.sha512sum] = "fccb157e52b1646796dca4b99da3af91876f266b7a7af9ef0697ff681b4d8e01eaff3a96f0f40ebf29556818a191558d2c4afea3027cd0ab1e7b01e608bd9df2"
SRC_URI[deb1.md5sum] = "2c7fe11dfd8eb670876b30c2144b2e41"
SRC_URI[deb1.sha1sum] = "69e71f958852d8dedbceab92f4f8a06f86bc8da3"
SRC_URI[deb1.sha256sum] = "5e60c3b1ae5f0ac3e68afcf1af6531bd8da6b255f6703de42af5a53f5c3153ad"
SRC_URI[deb1.sha512sum] = "7b582f5c01970d4ef5d2a2f666a7016c6aa00933ebea08b40204c82d7eef4cac53353eec54ecb3251793925c6700ddc3029e177d952cbb1842ce35239afb76ff"

RDEPENDS = " \
    libc6 \
    libibverbs1 \
    libnl-3-200 \
"

RPROVIDES = " \
    librdmacm1 \
"
