# This was autogenerated! Do not modify
SUMMARY = "charset, encoding and language detection (Python 3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-charset-normalizer"
HOMEPAGE = "https://github.com/ousret/charset_normalizer"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-charset-normalizer/python3-charset-normalizer_3.4.2-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-charset-normalizer/python3-charset-normalizer_3.4.2-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1222a8066e4390319c37d6fea6517fab"
SRC_URI[deb0.sha1sum] = "3efacc156f6ff055003b459c7fd925cc9635cc00"
SRC_URI[deb0.sha256sum] = "84acc2d79eb675e00c41a8031157e87529a97bc550430d9a6146069285fee8bc"
SRC_URI[deb0.sha512sum] = "6aada6345296251d23f391246eb18a8d404be4454b33fb5af7e04aae301f44680b0b0c2e032fffa815abf5ef97076e48a4dbf52b87c6e3da917c527920126837"
SRC_URI[deb1.md5sum] = "97315102618f6b60777c5931f4a13228"
SRC_URI[deb1.sha1sum] = "79ab4bdaeea5a0a26fd287aeb7ce954c904ff461"
SRC_URI[deb1.sha256sum] = "4844d40bd20bb7576a4d4588c876c775dc373ec05e9a92fd5a8799b3dca91870"
SRC_URI[deb1.sha512sum] = "fd98ae6d525602df3c23c3462aed86882a123ded4a4400027a4186e801303f40c0cd1d6d0244b7505656fa43ab23c8fb8423a733b8ac249fc7f5ba842d7a4878"

RDEPENDS = " \
    libc6 \
    python3 \
"

