# This was autogenerated! Do not modify
SUMMARY = "Debian base system master password and group files"
DESCRIPTION = ""
SECTION = "admin"
SOURCE_PACKAGE = "base-passwd"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/base-passwd/base-passwd_3.6.7_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/base-passwd/base-passwd_3.6.7_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "f7e42367f9aa329b83c4aecd865c8bc4"
SRC_URI[deb0.sha1sum] = "a729442bb25a09aa9f3fa19d540b1abb3ce1c17a"
SRC_URI[deb0.sha256sum] = "cf31c6956ab5f65815d9d9ea1615c4f78ecd2893c31119658248a4756cee83e7"
SRC_URI[deb0.sha512sum] = "f891f281e0bb9b1cdb175127763507833422070c9563ebd0361fbacd55c6987078cd77824cab2772f70fa23add8d427f87f1c6864932a9f725f7a2ec7b4b6734"
SRC_URI[deb1.md5sum] = "9b35ab2d7a45da0956167a0fc50df61d"
SRC_URI[deb1.sha1sum] = "024663b963cc61b5894fe9136f5fedb954f16bcf"
SRC_URI[deb1.sha256sum] = "c5755fd2cbf76961a1230e708b6bfc12c5400b57f3cd8a255675e9aa11d85848"
SRC_URI[deb1.sha512sum] = "86ff5040b506431e6940f2737534cd812ff3c7db1aee7bb76b99979d0e23bd0b32eb252ee56fe048e48022dcf34980ade16c52fc46e74f011e7dbdc9fb4730fb"

RDEPENDS = " \
    libc6 \
    libdebconfclient0 \
    libselinux1 \
"

