# This was autogenerated! Do not modify
SUMMARY = "caching algorithms in httplib2 for use with requests"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-cachecontrol"
HOMEPAGE = "https://github.com/ionrock/cachecontrol"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-cachecontrol/python3-cachecontrol_0.14.3-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e783df9dc0bc69c3ec467dc954877741"
SRC_URI[deb0.sha1sum] = "5277253e5b38a0e044a6723f0ff6b1bc70ff6696"
SRC_URI[deb0.sha256sum] = "287e9d11962d91d8a55ecb2df821cb71d85f94ea5d3c905b451e417362ecd29d"
SRC_URI[deb0.sha512sum] = "f692f4385c98aa3114d3630c869f0d56bdc82b9e13db8d07a70161e5f8d815f65a9f4542c173a99cdbe4036c1ccc850bb67e8d4061af31a1f295fb906182b3cd"

RDEPENDS = " \
    python3 \
    python3-msgpack \
    python3-requests \
"

