# This was autogenerated! Do not modify
SUMMARY = "Ultralightweight JSON parser in ANSI C"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "cjson"
HOMEPAGE = "https://github.com/DaveGamble/cJSON"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cjson/libcjson1_1.7.18-3.1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cjson/libcjson1_1.7.18-3.1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "66b9ac35f46c712e2c9e48f0ea52dddb"
SRC_URI[deb0.sha1sum] = "c46f18a32dd4ddf8d79c3983229ed4230ec77cbd"
SRC_URI[deb0.sha256sum] = "e10b7fb966251f4f09690cb35f9e8fed6924194ec2d6973910d9e157cda82657"
SRC_URI[deb0.sha512sum] = "3d26d98331969c9646a83e753efbaf48dfb2495ade337c3acef5d1537cbac440a58e1d6e1979ce4b7c88d0049187edeafff104d38c7edd84e349e9d7306df365"
SRC_URI[deb1.md5sum] = "48dbe2b526f992932b1eb0ad78d33f05"
SRC_URI[deb1.sha1sum] = "c3ea82d2e4188ed935b56b7bd482ededa273377d"
SRC_URI[deb1.sha256sum] = "f8a6ce78b0d4b1db40b16e0330fb1dfcd54a15c4a1f6798afd631e99f30fe707"
SRC_URI[deb1.sha512sum] = "1366bf7cd278c5a5c14c2bc5b030cef308582e5d4321857b2bae2ebe3c50f897a0bb392111e7f19ab4e83279d2218994693ea56fc72359cc4fee27413583c031"

RDEPENDS = " \
    libc6 \
"

