# This was autogenerated! Do not modify
SUMMARY = "library for loading and coordinating access to PKCS#11 modules - development"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "p11-kit"
HOMEPAGE = "https://p11-glue.github.io/p11-glue/p11-kit.html"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/p11-kit/libp11-kit-dev_0.25.5-3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/p11-kit/libp11-kit-dev_0.25.5-3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "57bb5a0594d7ceeb81f6ce269594bd2a"
SRC_URI[deb0.sha1sum] = "27c5e65366b3646dc8d216bc4acb1ee9fe079c6e"
SRC_URI[deb0.sha256sum] = "6a19763ae89f584085cd7333f1923ccbd9eaeccb9fd2bf32e7cedd302e720b9a"
SRC_URI[deb0.sha512sum] = "0c33872d6434630dc5329541705c29cb6949bc3afeb211986d07ff39010e73bbfcaba7cc1e8859b4ade7315afc2cf1005da65867c24225ac3ca07698a8487448"
SRC_URI[deb1.md5sum] = "81fce1945f5a607d8375e8e9cec35191"
SRC_URI[deb1.sha1sum] = "03f2825ae315e49b5185713ac4e5658ebea1d45c"
SRC_URI[deb1.sha256sum] = "dfa60658ea83b7e558bf019152ddd9563d96e2fce24d2385158fe10987be38e7"
SRC_URI[deb1.sha512sum] = "38e4f5b1344b00f738578a1deecbe6ad0bfdd760a988161b0a28f22d5552996cb5d37efbdd7c3037cfe73e767de7d0c930df90393f60c01fe86744a0d919c98e"

RDEPENDS = " \
    libp11-kit0 \
"

