# This was autogenerated! Do not modify
SUMMARY = "Linux kernel io_uring access library - shared library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "liburing"
HOMEPAGE = "https://github.com/axboe/liburing"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libu/liburing/liburing2_2.9-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libu/liburing/liburing2_2.9-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "e570394577e65a9f90f2d1932cb1b889"
SRC_URI[deb0.sha1sum] = "33ef25b563c7d80871510357af6092d6887736f8"
SRC_URI[deb0.sha256sum] = "4b589c00c7a51172aace2cb2fb3d3ff32daf86c644023126dcfcaa840cc941ea"
SRC_URI[deb0.sha512sum] = "569b20060bc12ed6aaad34938d6a207c1071eaab838226607d573f40363b324ae529b159ce4a186380693a0389507772c4b0c4c1bf0880bcabe6794576b0971b"
SRC_URI[deb1.md5sum] = "9bac4a00db0f6a4bb6d93397b203fa2e"
SRC_URI[deb1.sha1sum] = "d7c55422c2a8682fda35ce227c88b2cea97e96a0"
SRC_URI[deb1.sha256sum] = "523dfbe829acf3aeae6df81528426a75995944923fd6bd35f6ccd0332034c713"
SRC_URI[deb1.sha512sum] = "4f3f4e3bc9d6f62e7747238c2ceb118d295e2f546fadeefe90d3b34edfa0872a01bf7de0af2f06d05300876635ad5fd10d466fe566e11b4e5113f866b72a0ef3"

RDEPENDS = " \
    libc6 \
"

