# This was autogenerated! Do not modify
SUMMARY = "clang-based tools for C/C++ developments"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-19"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-19/clang-tools-19_19.1.7-3+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-19/clang-tools-19_19.1.7-3+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1a549a46f000827a8d2abfc9e74b512d"
SRC_URI[deb0.sha1sum] = "b07a2c96a25c4fd671fb60b78800b2a4a15ef51b"
SRC_URI[deb0.sha256sum] = "27fa6cb89386dc4c3dcbec5b6bd0839863ebd97316d21f44cdb42b6d9c9b1a2a"
SRC_URI[deb0.sha512sum] = "10e207eba562763e16ca0359d6a0c69f9b0a17de30fda043bfd5c42a6f78590a64971a04e241a504e5b5b56e16c406a4868f28f8998c7a6f147575cfb261bcc2"
SRC_URI[deb1.md5sum] = "c3debd8a1ddd8616c5d9a05207600a02"
SRC_URI[deb1.sha1sum] = "77073c6775a2d4f9a6ed3bddab2fa5ef4b410fe0"
SRC_URI[deb1.sha256sum] = "9d5673effd96d33248203facead5aab1e7e1c6f93bb2e52bde69a0d7aa3225c1"
SRC_URI[deb1.sha512sum] = "849ab642de082fabd59d40cfc881475670a212b745eb7f7c99100ce1f300eb4683c4bd6eeb9e6ed528a260ed9beb6b6b7d4a7eccb5c56ba50e2f73d3aa2fc106"

RDEPENDS = " \
    clang-19 \
    libc6 \
    libclang-cpp19 \
    libclang1-19 \
    libgcc-s1 \
    libllvm19 \
    libstdc++6 \
    libxml2 \
    libz3-4 \
    libzstd1 \
    python3 \
    zlib1g \
"

