# This was autogenerated! Do not modify
SUMMARY = "clang-based C++ linter tool"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-19"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-19/clang-tidy-19_19.1.7-3+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-toolchain-19/clang-tidy-19_19.1.7-3+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "3997dde3e572cacec8e13750129c3ff2"
SRC_URI[deb0.sha1sum] = "47acbd50aacb3912ffb737b872a22d7d38e4e619"
SRC_URI[deb0.sha256sum] = "3cec90f1f995f6967832dfdf9725b12411502de0d7c89901376f6486db7fdd25"
SRC_URI[deb0.sha512sum] = "6dee73cfef69e4649f70c94cb40e2fed6761ced2cbc9b9f529ecffe697155f69bd6ea90ee8f57c681f2a4d3afcb68fc7449ffe41e79caad535a063585e108fef"
SRC_URI[deb1.md5sum] = "eb41b21a1185eddcd8f593d149e622f8"
SRC_URI[deb1.sha1sum] = "f6123fd4fcedb4d5eefa4a6f6bf60f2ceecd157b"
SRC_URI[deb1.sha256sum] = "5802aeea936d710229f5131dcd559a3547b4fd6a865c84efd4e968ce30210db6"
SRC_URI[deb1.sha512sum] = "6d31ad2049631a6d13cf32db2639baf4cde593d6207d367d09a7168171315738eceaa2f9e7cbfc60bcaaa26f1f33291d4bb9230838f8328426be22b17d2d4e9e"

RDEPENDS = " \
    clang-tools-19 \
    libc6 \
    libclang-common-19-dev \
    libclang-cpp19 \
    libgcc-s1 \
    libllvm19 \
    libstdc++6 \
    python3 \
    python3-yaml \
"

