# This was autogenerated! Do not modify
SUMMARY = "LLVM low level support for a standard C++ library"
DESCRIPTION = "libc++abi is another implementation of low level support for a standard C++ \
library. \
 \
Features and Goals \
 \
  * Correctness as defined by the C++ standards. \
  * Provide a portable sublayer to ease the porting of libc++"
SECTION = "libs"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libc++abi1_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libc++abi1_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "592fcde49c85e30e9c40603a04d95381"
SRC_URI[deb0.sha1sum] = "3aff11bdf54dfd4b9c01284f322260d37a87fae0"
SRC_URI[deb0.sha256sum] = "65c9b117e43fbbbc78d260bfe570bc4cab3e7bbab50140844f522790adef8bf4"
SRC_URI[deb0.sha512sum] = "ae67fc6d9aba01175df307279d98fa84288ecf8b104fbc8b2bbfe635adfc3ab0d2c74378f5e697ad567f338048894c876633b6a40346b4b5537438df12b41d81"
SRC_URI[deb1.md5sum] = "b2fbf4bf0b2e12f5c7bcac5587125fc3"
SRC_URI[deb1.sha1sum] = "7c5152e4e9126e0961912e25cc73744d0559b373"
SRC_URI[deb1.sha256sum] = "9b3f3fabe185c4997a58b0509b04fdddd5c666221ecacb357307d648336f68fa"
SRC_URI[deb1.sha512sum] = "718abe8b168af3cae57cabb1d60e7c3bd6fe04de68b004a38328eaa225e31470dbfb9661e549aa75f91465ad96ef51ae06d9a6d8b8beeedd907d637f213affbe"

RDEPENDS = " \
    libc6 \
    libunwind \
"

RPROVIDES = " \
    libc++abi-x.y \
"
