# This was autogenerated! Do not modify
SUMMARY = "Modular compiler and toolchain technologies, runtime library"
DESCRIPTION = "LLVM is a collection of libraries and tools that make it easy to build \
compilers, optimizers, just-in-time code generators, and many other \
compiler-related programs. \
 \
This package contains the LLVM runtime library."
SECTION = "libs"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libllvm20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libllvm20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "46a4e7700642518423f46433d923830a"
SRC_URI[deb0.sha1sum] = "e3d24de591ab614e509f29eab9ad2d76a0f47cbf"
SRC_URI[deb0.sha256sum] = "6a3a9e4408dfaa09a2c9d96d343a1caefa40fb10a438f465590b7d2fbafc38ce"
SRC_URI[deb0.sha512sum] = "e91285425d5a3401e5fa4c6c7313d00dde080a556973c1d942618c3db2833b16da071ff57d5bbb805fac91146ed5b8d0b3d3e98fca6d9bf70d03aba083c2d797"
SRC_URI[deb1.md5sum] = "e3df35c92075ee8338dd7799fe52bf93"
SRC_URI[deb1.sha1sum] = "42e44ded339d3b817db7a4cc24962ec982978615"
SRC_URI[deb1.sha256sum] = "324616a0ea1da6cab9f92b0dd32f3dbf7acb3505e4280e04d6911ae627d4ab21"
SRC_URI[deb1.sha512sum] = "2d5df8ddda1776d5c6b24f7155e6428a9e6c11bad869e20e6c2ad4f3b7729194dad0966053db073d342b797b153984bd07cff4c94a1eeecee09eb0870c80aacc"

RDEPENDS = " \
    libc6 \
    libedit2 \
    libffi8 \
    libgcc-s1 \
    libstdc++6 \
    libxml2 \
    libz3-4 \
    libzstd1 \
    zlib1g \
"

