# This was autogenerated! Do not modify
SUMMARY = "Multi-Level Intermediate Representation library"
DESCRIPTION = "Novel approach to building reusable and extensible compiler infrastructure. \
MLIR aims to address software fragmentation, improve compilation for \
heterogeneous hardware, significantly reduce the cost of building domain \
specific compilers, and aid in connecting existing compilers together."
SECTION = "libs"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libmlir-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/libmlir-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "67802171240e758f11c199ab28dc9e1a"
SRC_URI[deb0.sha1sum] = "aaf3b959c8f947fd76149234d2f964a5bd764aac"
SRC_URI[deb0.sha256sum] = "a6186a69f12aa2c061b8d0c44566b730a32db746290946757176995649929bdd"
SRC_URI[deb0.sha512sum] = "88939fc5e02f57d5729d8d6cecba56ae1fdd0e05a9898556a7057f89858c9983e0d736aa513ae9f956b234242d6b739fcf6e2791cb05b4f671ee13143f6143f3"
SRC_URI[deb1.md5sum] = "96eb2f614bccd3b57abd2c27a6bfa729"
SRC_URI[deb1.sha1sum] = "5af28e69db2a6ca34f1be421eddce167e7e2dda5"
SRC_URI[deb1.sha256sum] = "77f4568165a67e0391991d6507154e745b2428e75a2ae8f4599c053c690a9fcd"
SRC_URI[deb1.sha512sum] = "cab96ea67b7b5e543cdc3d0e3f3b72cfd9acb01cdf4d15a332fb1d1bf0ae19d68d7b42212ce24d18bd97a835b8045fba4e5e4e8ad4557535f9a090895cba689d"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libllvm20 \
    libstdc++6 \
"

RPROVIDES = " \
    libmlir-x.y \
"
