# This was autogenerated! Do not modify
SUMMARY = "library for reading DVDs"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libdvdread"
HOMEPAGE = "https://www.videolan.org/developers/libdvdnav.html"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libdvdread/libdvdread8t64_6.1.3-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libd/libdvdread/libdvdread8t64_6.1.3-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b23af4fb2da4f764a25a999888db8e52"
SRC_URI[deb0.sha1sum] = "b55971e899112444fcb137bd4f5c881f665c27fa"
SRC_URI[deb0.sha256sum] = "f753a23580c00a2166211607a5511a9c25d75c9ebfc34598b6526637de150fec"
SRC_URI[deb0.sha512sum] = "6c1ed5736260021e2aca6da5be2af739b9f969e03413a759c85b8b056c5af45724b5b85615bec6077946993d5ffc64470997bb548b77516672dfc3317d456479"
SRC_URI[deb1.md5sum] = "b1f35bc17a613bc0f0b1be4d99954bef"
SRC_URI[deb1.sha1sum] = "eb6541deb4d0f1001cc52ba3b24a60b95ce2ae3a"
SRC_URI[deb1.sha256sum] = "92d848dcdb5c44bf14b4448c0d8a05c7397069888d9df0189191fa4d9706758c"
SRC_URI[deb1.sha512sum] = "3b2242e44cbbeab6dbe31a51d3fa0b91ff4e35fdcf819497da4452bcecb9318d102a9dce78337aa06afd9bab99cea57e446a333a911377b2174c60229cd96ee6"

RDEPENDS = " \
    libc6 \
"

RPROVIDES = " \
    libdvdread8 \
"
