# Copyright 2026 Elektrobit. All rights reserved.

# This was autogenerated! Do not modify
SUMMARY = "Rust systems programming language"
DESCRIPTION = ""
SECTION = "rust"
SOURCE_PACKAGE = "rustc"
HOMEPAGE = "http://www.rust-lang.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_YORIITO_DEBIAN_UPSTREAM_APT}/pool/main/r/rustc/rustc_1.95.0+dfsg1-2~bpo13+1_amd64.deb;name=deb0 \
    ${REPO_YORIITO_DEBIAN_UPSTREAM_APT}/pool/main/r/rustc/rustc_1.95.0+dfsg1-2~bpo13+1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c77e50fa9c0e7831eb7cccaa6652dc24"
SRC_URI[deb0.sha1sum] = "2be7e40c45c5e7d2bd5ff01d340f2f9aa622618f"
SRC_URI[deb0.sha256sum] = "46222c7b55ffb3f7fabc1c6630f5635a3eb01dde15d9a9b71f0d7b766f62bce3"
SRC_URI[deb0.sha512sum] = "5cad6e57a2a7fc6b8af4f9ed0ce3d69c5c8dc64d7a2608c525f7204e25c5e2de549aeddcf1376483fa625c3050fca499a0408795439faf0f7709992ff0763d69"
SRC_URI[deb1.md5sum] = "6ead4f35921f415cba1cc0f48b2a7f27"
SRC_URI[deb1.sha1sum] = "b0b2912747f308d7607d76dd6d4d854aec688656"
SRC_URI[deb1.sha256sum] = "b5aa1cf5b834fa17d1bae664c69cd1fd968404099ca6106fc22180c00036dc49"
SRC_URI[deb1.sha512sum] = "47ee8687b8db508c000016c4bb34bc031b235e43ce3f17a6d7d2b11389f7f0d3599bbef220b1543995a395992f90458e39cd6f5e8fb1d3acf3012ae645361a84"

RDEPENDS = " \
    binutils \
    gcc \
    libc-dev \
    libc6 \
    libgcc-s1 \
    libstd-rust-dev \
"
