# This was autogenerated! Do not modify
SUMMARY = "Library with convenience functions for writing tests"
DESCRIPTION = "Allows you to easily create configuration mock-ups from strings if you write \
test where samconf is used."
SECTION = "libs"
SOURCE_PACKAGE = "samconf"
HOMEPAGE = "https://github.com/Elektrobit/samconf"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/s/samconf/libsamconf-test-utils0_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "64435c939e11a2da8a29e77eec94288c"
SRC_URI[deb0.sha1sum] = "36cbea9b72bd3641d152869baad52ef4e607b123"
SRC_URI[deb0.sha256sum] = "3ce2155437d15932f5cd452b2a078e28355cffc9f026609ccf79c9a0c81585d2"

RDEPENDS = " \
    libsamconf0 \
"

