# This was autogenerated! Do not modify
SUMMARY = "Lightweight, extensible data validation library for Python"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-cerberus"
HOMEPAGE = "https://python-cerberus.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-cerberus/python3-cerberus_1.3.7-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "9435c19abc28f69053989c3e52b995df"
SRC_URI[deb0.sha1sum] = "8b37e647557d118893ca2771ecfbfad4f9501622"
SRC_URI[deb0.sha256sum] = "b12302070fe5cc9c4799b07fbcaf588c630a6ce0f485a94a030942067e986c3b"
SRC_URI[deb0.sha512sum] = "4d3c1b91c73ea7f4f22c3c1dd119a2b66ac425e0e93b5c00b1a54efd3580efd2aa550138e14d96435b065241db2a73c417683b36fa5bd7220772836fa7b22e33"

RDEPENDS = " \
    python3 \
"

