# This was autogenerated! Do not modify
SUMMARY = "GNU C preprocessor (cpp) for the arm64 architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-defaults"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/cpp-aarch64-linux-gnu_14.2.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/cpp-aarch64-linux-gnu_14.2.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "0ac7f4a1c8d7eab45c96644448431978"
SRC_URI[deb0.sha1sum] = "c962c03c443b5762945a0abc5b16b94be0e6ee3d"
SRC_URI[deb0.sha256sum] = "4480016c11678c1a391f8b3d77d8c87915af5e5aaa96c21dcf69a9c516979e63"
SRC_URI[deb0.sha512sum] = "36bb90f39db946c5eb04608715502dc0d5a897243728d993e9509b48620de906165933a37f714fd5b30d1e64ed0e3fda74d8c2b816660b922e53aafaad1dc8f7"
SRC_URI[deb1.md5sum] = "5f8d14cf8a31889547a609ec658ee46c"
SRC_URI[deb1.sha1sum] = "e9b3bbb7ae125ff127e6da66f570b1b8b0d7de83"
SRC_URI[deb1.sha256sum] = "bd9c9f4536a0aea285c4735d2dfedff624f8457b8f1bb3d15ab924e029cd7aff"
SRC_URI[deb1.sha512sum] = "5122356f6e4ea1a07a4a30cc4f16d6f308bc60a3162d56fbb02b5ae5faaa7608abef2181f5ff1a3d1bc79d1cfb0d6559ddd05386594c6170dc67858807edcf79"

RDEPENDS = " \
    cpp-14-aarch64-linux-gnu \
"

