# This was autogenerated! Do not modify
SUMMARY = "GNU C preprocessor (cpp) for the amd64 architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-defaults"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/cpp-x86-64-linux-gnu_14.2.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/cpp-x86-64-linux-gnu_14.2.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "239e9350ca49d4412b581242c1d02a67"
SRC_URI[deb0.sha1sum] = "145f1be0efb24a586282758ea5ea5e3496e2b8dc"
SRC_URI[deb0.sha256sum] = "d902f484e38bce59e82efc0df2fe20139a0932ca759ecafdfe6e5b6c72238eb8"
SRC_URI[deb0.sha512sum] = "d291eb132ca1b3d4c1128a0e03708ceadf329acddb5be51ce119a56b753dd8a78ee3614c7d859578cd74eeb9aba35df69926e399edb90e6f631ca99927e28809"
SRC_URI[deb1.md5sum] = "5e89368bb2ae915739eb5121e0263423"
SRC_URI[deb1.sha1sum] = "3de4d1711e4492a22907532e6776c7d4de8fd6af"
SRC_URI[deb1.sha256sum] = "6886e27105ed89cbe776727ef666a2316b39c4a5758f16b1bfdf6846aa42cc53"
SRC_URI[deb1.sha512sum] = "1ef9638557e2f594350c655324ef976f0f6e4448c707b6f4337588e4b80ca6916f8dd9115047b4e94e969d6a70ddecf0ed9dd812259a44bb553edb4f5f4515b3"

RDEPENDS = " \
    cpp-14-x86-64-linux-gnu \
"

