# This was autogenerated! Do not modify
SUMMARY = "GNU C++ compiler for the arm64 architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-defaults"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/g++-aarch64-linux-gnu_14.2.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/g++-aarch64-linux-gnu_14.2.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "501a66aec8efff7472dc5000bc9eb37a"
SRC_URI[deb0.sha1sum] = "52471e9feadc7045e2199f0cfc9cbf4e48da4438"
SRC_URI[deb0.sha256sum] = "7bf2009e0449b44b12856a9d5521bc3f352abb422a3280e11c3be296e22d2eb5"
SRC_URI[deb0.sha512sum] = "c86d9d4c843f59910bafd3b642a9548853d1e35089c85428d25e37d96fb98885f0d1839f02ea6a41a0c312b66cf024654c84ef9d0300826840d9022e68573b32"
SRC_URI[deb1.md5sum] = "f07cd22eaba06afa74b1df8b5d073260"
SRC_URI[deb1.sha1sum] = "86c89dfae08a9218f9ba7188f4cdcc702922bdf4"
SRC_URI[deb1.sha256sum] = "655d9a7cb70b0342f5f1bf4f2a7b0241df15d49ab9a2567445c785b7592122f9"
SRC_URI[deb1.sha512sum] = "56e185678b1e15c756c1833886d295b11955987f019baad508924e240dd5ba1355981a4c5f074368590e8f0e2b85c065918acda2ed2435e99f328edcd62b0ebb"

RDEPENDS = " \
    cpp-aarch64-linux-gnu \
    g++-14-aarch64-linux-gnu \
    gcc-aarch64-linux-gnu \
"

