# This was autogenerated! Do not modify
SUMMARY = "GNU C++ compiler for the amd64 architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-defaults"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/g++-x86-64-linux-gnu_14.2.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/g++-x86-64-linux-gnu_14.2.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "1b29d910e99e16e9750f80d93af8a40a"
SRC_URI[deb0.sha1sum] = "e9ead5081c3b70e5b5831f6324910c883dd7ef40"
SRC_URI[deb0.sha256sum] = "15e10fc3948ec76be8d51b23e75ad9df9c39588c94f1f47059cee02c117c7583"
SRC_URI[deb0.sha512sum] = "a1ee6b937db367d62322d3db138da383fed59c2f01b994487d4fb2f0b3f659c5c3fad2b3fb35bda661355481f6de89d7d23233a547309cdab312ab5a5516a58f"
SRC_URI[deb1.md5sum] = "1e61b9e2dbc01106a82fdf7e2700daec"
SRC_URI[deb1.sha1sum] = "bfb67102825eb3139d67172cff774b6097bd5ce6"
SRC_URI[deb1.sha256sum] = "3a16938ce670a5c850618528c5910c874e8d311191e753acb72f724849a50e2b"
SRC_URI[deb1.sha512sum] = "9ba57b0b5722e86cc8c858cd2f9484222a966ee597e15570f03dd28575d99fcfea3d28d0fe71c7f1f7ab493312b317c82f5ce20b4163bad5d49445d65fd8b591"

RDEPENDS = " \
    cpp-x86-64-linux-gnu \
    g++-14-x86-64-linux-gnu \
    gcc-x86-64-linux-gnu \
"

