# This was autogenerated! Do not modify
SUMMARY = "GNU C compiler for the arm64 architecture"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gcc-defaults"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/gcc-aarch64-linux-gnu_14.2.0-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-defaults/gcc-aarch64-linux-gnu_14.2.0-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "5f527ec7365d2035d10819931ce44402"
SRC_URI[deb0.sha1sum] = "1399af37c28cf1b0da30f7eaf94c137a22d4aa75"
SRC_URI[deb0.sha256sum] = "ff536dd2b6a7f2879cf83ebadd7cc4af3e7234a87226a2ba97bbf0a857e930da"
SRC_URI[deb0.sha512sum] = "77d2d92cec79530a748eccb336042c55b560cdc8a3aeded258378e0913448e2f743f116416fce29863ff14e70eebd808c769dde2389ace1ab8e01dccab096bb8"
SRC_URI[deb1.md5sum] = "675a2731ee68e64f3eaf0fe7a8a33536"
SRC_URI[deb1.sha1sum] = "d1129fa4ee8672e492ece8e24cf128ba19358914"
SRC_URI[deb1.sha256sum] = "c8390408ed90cc96d4fead68e313ed5ce147f1654807c23235818d535d2d7d7e"
SRC_URI[deb1.sha512sum] = "6fe6f81241f01572c346df4d720c4691b510df6e284b34c8bf64815284c3cade848573db3015086dd3da86b5962a3b675c3efdb2ccf3e1f03b15f61148074c86"

RDEPENDS = " \
    cpp-aarch64-linux-gnu \
    gcc-14-aarch64-linux-gnu \
"

