# This was autogenerated! Do not modify
SUMMARY = "X C Binding, xfixes extension"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxcb"
HOMEPAGE = "https://xcb.freedesktop.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxcb/libxcb-xfixes0_1.17.0-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxcb/libxcb-xfixes0_1.17.0-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "2edb431d6ebcebbdaab224f97a2aedc2"
SRC_URI[deb0.sha1sum] = "8426502a6c0de401f1e00d38070b6800d0e5db41"
SRC_URI[deb0.sha256sum] = "f9c1aafc18bf9e4662e34bbaf3bb00f1f4e8c2fc1dd786fdfb6cb9cb6c64fae7"
SRC_URI[deb0.sha512sum] = "2084649e0817400081cdedfc47bf1324e6c8d29d810ce7b6c3e81e9e8b358f21b5c6ca4e170ef26efc7522836f17d41396a614587557bc5c6bb890a381f28e68"
SRC_URI[deb1.md5sum] = "9cd0238b44d4c929c5b8ba7c3bd1002e"
SRC_URI[deb1.sha1sum] = "baf74e4d3452b1dd4d0736160c01b9a5702ae2d5"
SRC_URI[deb1.sha256sum] = "19cdb8502827bc010993e69eaba09c670024976f7edd35b2b504bd646b141b0a"
SRC_URI[deb1.sha512sum] = "4423203933803d6633841e2a966315a1c173ec2dd5610cffbed7fc8619592079347e216cf8a5c0569417921bb9b75326cdf9b43b0c2fe9fb2974d8ccb51d7d74"

RDEPENDS = " \
    libc6 \
    libxcb1 \
"

