# This was autogenerated! Do not modify
SUMMARY = "X C Binding, present extension"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxcb"
HOMEPAGE = "https://xcb.freedesktop.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxcb/libxcb-present0_1.17.0-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxcb/libxcb-present0_1.17.0-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "faf7455c8a5ae14d1334088474f06ca9"
SRC_URI[deb0.sha1sum] = "ce90d188c23fa598213e9a33e55ecb45c881b6f6"
SRC_URI[deb0.sha256sum] = "db95ea4630c55bd7f3281cb60ccf75b1627ef2f4399e1939f8f6161e584a92fb"
SRC_URI[deb0.sha512sum] = "af6052ed87c36c7e7111eec27f3ac70a95be07cc4a3ec6b51492b398eef74ccbfb091eda98ef48f529ce37d7bee685b0242de6d42c798984bbb1ef990ea85ff7"
SRC_URI[deb1.md5sum] = "ae4345b6c812b55d4b8b049b448f9b59"
SRC_URI[deb1.sha1sum] = "08bccc8b89f3c419fa58f639999e4b9fbe88b3bb"
SRC_URI[deb1.sha256sum] = "73521d715554a2230901d1d480465d6358b3083a5ce8801639595ffde6f31441"
SRC_URI[deb1.sha512sum] = "cf9dfe0d900af796fa91ce1058ce1a565f8f3a3ccf0d5a90f967440d091d4866c388263a075d81985503c3a971b57f1f455e7290e75aa01f9520809dcf761106"

RDEPENDS = " \
    libc6 \
    libxcb1 \
"

