# This was autogenerated! Do not modify
SUMMARY = "X C Binding, xinput extension"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libxcb"
HOMEPAGE = "https://xcb.freedesktop.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxcb/libxcb-xinput0_1.17.0-2+b1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libx/libxcb/libxcb-xinput0_1.17.0-2+b1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "427a74fb952f6adf06165563be016d7e"
SRC_URI[deb0.sha1sum] = "c5fa094c1a70e2d5e6c6fa02caabe7eb6e7890d8"
SRC_URI[deb0.sha256sum] = "10f588b006a5a1a527c9971f4e9712d9aac12b98acd5d65c3f7b53a10ac36198"
SRC_URI[deb0.sha512sum] = "2fb9289c7a4d7d48af0f34bf21794c7960b4ec062cbe7869483a80df3d3641afe2f60cf1fff269e0620fc621556234e73290b1e3ec94e01293c860cc18cf4386"
SRC_URI[deb1.md5sum] = "042cde9ac1833f26fdad474216356497"
SRC_URI[deb1.sha1sum] = "f0de1de30b9fdf954b8f2116d3ec14be656ec1da"
SRC_URI[deb1.sha256sum] = "ebc39f2f1940a03963b0c1db916b19178e8078132adb669a27cfa8dd38c5d3c3"
SRC_URI[deb1.sha512sum] = "e249631d145db903486c2b9c9237d52a9e7c712fb49ac472a0c122300b628b7b7d9e98612551de6591dfe66f711aec0ecff99fda579dc13906ef02f5526a3981"

RDEPENDS = " \
    libc6 \
    libxcb1 \
"

