# This was autogenerated! Do not modify
SUMMARY = "validation of JSON documents by JSON schema drafts 04/06/07"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-fastjsonschema"
HOMEPAGE = "https://github.com/horejsek/python-fastjsonschema"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-fastjsonschema/python3-fastjsonschema_2.21.1-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "51ef64a217987e2d320f5a75265023c1"
SRC_URI[deb0.sha1sum] = "f0eb0d238816015ebf2b5b13c456679180ba6e28"
SRC_URI[deb0.sha256sum] = "11c899ee8ab50534756cce0b5e03a78ecf19dc46f876fac48bf3071849d80e31"
SRC_URI[deb0.sha512sum] = "855b034550c8ed6b8f185629acff0c22b7f8c039fd2472705f2328883a4e1cded41b4c83b609b7a476d31777889adb6137d39962a41aa316a9f2a312abb84037"

RDEPENDS = " \
    python3 \
"

