# This was autogenerated! Do not modify
SUMMARY = "GCC, the GNU Compiler Collection (base package)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gcc-13"
HOMEPAGE = "http://gcc.gnu.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13/gcc-13-base_13.3.0-16_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gcc-13/gcc-13-base_13.3.0-16_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "cd604eb3e39fca2835675633c93a94e4"
SRC_URI[deb0.sha1sum] = "eb36a2b74138989228ae59a21012b292a9e37fcd"
SRC_URI[deb0.sha256sum] = "e503620c4d78bc3bd14cc3ba44f604f0156154dca76fe7817c2bea03d6ff4c93"
SRC_URI[deb0.sha512sum] = "f0243d890727f2294a1724406ef9c0b8ba282ef3ef49a40dece9c3931874cf93f07c17de72256cac7e398fa3f58c51831fbab43ad155b5f59b74f1199abe46e8"
SRC_URI[deb1.md5sum] = "b0bcf1645b9523fed01f401631c7e72d"
SRC_URI[deb1.sha1sum] = "c23f5b53d58802ac2ec569786d87756ca91022df"
SRC_URI[deb1.sha256sum] = "7ec774b02a78ab10b9b5d9daf60d174b1d7bbb91d2c3a420c9caf6d553f154e5"
SRC_URI[deb1.sha512sum] = "f1053fd96d18552d4b58919216bbaecacd930b5b44519beb08925d297527154db9304ba137c70ed3d282eb985b0f8b65484fed44c4432d39e4f1df7b57deae6d"


