# This was autogenerated! Do not modify
SUMMARY = "Linux Kernel Headers for development (for cross-compiling)"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "cross-toolchain-base"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cross-toolchain-base/linux-libc-dev-arm64-cross_6.12.38-1cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "0f5139674b5f10c7033231228d6de129"
SRC_URI[deb0.sha1sum] = "2a242bc2c5fffb2f11348703cdd918b0acef8623"
SRC_URI[deb0.sha256sum] = "fd77c13fedf057038732ef1c4fc06edd753d08092fd5f92c4629551f1f69870f"
SRC_URI[deb0.sha512sum] = "2a1bb7eb8bd127b1f286ed1e8fb936dfafd0d498a65bb30428c146cc81c3a994240c82c98111fe75f684821f04c690a97c369dc5f410889296590d0919ebae9f"


RPROVIDES = " \
    linux-kernel-headers-arm64-cross \
    linux-libc-dev-arm64-dcv1 \
"
