# This was autogenerated! Do not modify
SUMMARY = "library implementing brotli encoder and decoder (development files)"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "brotli"
HOMEPAGE = "https://github.com/google/brotli"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/brotli/libbrotli-dev_1.1.0-2+b7_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/b/brotli/libbrotli-dev_1.1.0-2+b7_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "800d91cb93c7e44d7de9f7589400fcda"
SRC_URI[deb0.sha1sum] = "67290e4649a0d82cce65f67ffb4535711fc513d0"
SRC_URI[deb0.sha256sum] = "7149124783ccc38764f8b869ea2e4bde319c3d0872b248b7ab472b47d41c5176"
SRC_URI[deb0.sha512sum] = "9753eebfef25a5ba7a319d1af0087f7431356e3aaff1029dc7a2612d6871a59e8d890fe7393d344514b62d47a9832483168d4bdff464ec7d409018bcaf9a88b3"
SRC_URI[deb1.md5sum] = "7c7f08715f37cd8b798bc27b9a1544ec"
SRC_URI[deb1.sha1sum] = "4b6b55791ed5c6c17a994b94791159f34b33903b"
SRC_URI[deb1.sha256sum] = "6c1fb26205d7241406511b0b3e9b05d87d25c2288ac4dcc9d5d2ab3af5bd9116"
SRC_URI[deb1.sha512sum] = "17747cf116ceffc79a93634c407fc137824c7a86c6c1dbd105acc412d0db03cec9b5386e305469799ade5d48d873c7fb063610f574170b2f8ddd660dafd98c45"

RDEPENDS = " \
    libbrotli1 \
"

