# This was autogenerated! Do not modify
SUMMARY = "small build system closest in spirit to Make"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "ninja-build"
HOMEPAGE = "https://ninja-build.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/n/ninja-build/ninja-build_1.12.1-1+b1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "8c08b3f325b9098aa99537a21dd01115"
SRC_URI[deb0.sha1sum] = "bdbcc55f38ed8e108465465df76e1f6baba41686"
SRC_URI[deb0.sha256sum] = "4afc3194ca4d4f051893f169daa48ba9eac769d76f3f13839e5ad0a9688b5fe6"
SRC_URI[deb0.sha512sum] = "ccf6499de202942b5859d15d0fa4857f9f154bd51dc67aaf2d023341aeae6018ec54345a301d1b1994cef65a1e32e4bca4d83fb4ad0b85870c6853f875769151"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
"

