# This was autogenerated! Do not modify
SUMMARY = "fast, scalable, distributed revision control system"
DESCRIPTION = ""
SECTION = "vcs"
SOURCE_PACKAGE = "git"
HOMEPAGE = "https://git-scm.com/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/git/git_2.47.3-0+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/git/git_2.47.3-0+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "26aa869d049c8cddc78ca94f56ad3510"
SRC_URI[deb0.sha1sum] = "bb5947667cef07307ce77aeb86fd95c2a3e85472"
SRC_URI[deb0.sha256sum] = "3e35662fd5c46add561703e54031a1d8ad9df45811927689f0a51122b13be722"
SRC_URI[deb0.sha512sum] = "2af0550f3693258fee61426770ecbf7226f6f9e5d24a9bc530b4ccfcdf3a627d60bccf61104911f849290caf2020f9cbe7d43277947c5dc456f83a936c824d65"
SRC_URI[deb1.md5sum] = "32448034e5535d3571213e4248b798ed"
SRC_URI[deb1.sha1sum] = "dac3541a184cbadf9424aba0709c77058bc86b02"
SRC_URI[deb1.sha256sum] = "8c6b1e96b226211260d7814472215a8a1ed38ee37400c421d454391c1807cb5a"
SRC_URI[deb1.sha512sum] = "3897897495b69d424df48b55fd512db20521c491e4e1a954f76f32c416dabfad7eaf1b5c043a90c24053ddcc5b5d82d808d1e37d4f3d8036f53051b5f605d029"

RDEPENDS = " \
    git-man \
    libc6 \
    libcurl3t64-gnutls \
    liberror-perl \
    libexpat1 \
    libpcre2-8-0 \
    perl \
    zlib1g \
"

RPROVIDES = " \
    git-completion \
    git-core \
"
