# This was autogenerated! Do not modify
SUMMARY = "Common files for github.com/containers repositories"
DESCRIPTION = ""
SECTION = "golang"
SOURCE_PACKAGE = "golang-github-containers-common"
HOMEPAGE = "https://github.com/containers/common"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/golang-github-containers-common/golang-github-containers-common_0.62.2+ds1-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "1e026a1501630a43332aa8021d14df41"
SRC_URI[deb0.sha1sum] = "9c23855f6bffb2bd595eb8903f2f404bd33776bd"
SRC_URI[deb0.sha256sum] = "de4a8a0fe1d55a259b7f615c67a9fe25fb98715fff51d0922bfad73e1045bce1"
SRC_URI[deb0.sha512sum] = "f9a58353c8735dba3a7ca4d4735c69452eb93df79a0381732f9ea0675b70bc8065d5413791bc60a9ae3b7acb0ab671a019829d02969c858b763d65d93791d254"

RDEPENDS = " \
    container-network-stack \
    golang-github-containers-image \
"

