# This was autogenerated! Do not modify
SUMMARY = "GNU C Library: Shared libraries (for cross-compiling)"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "cross-toolchain-base"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cross-toolchain-base/libc6-arm64-cross_2.41-11cross1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "c1a95a1bb20d438335080da1b77bddff"
SRC_URI[deb0.sha1sum] = "900a38db971ee6be2f4e1b7bb99b07111404b245"
SRC_URI[deb0.sha256sum] = "82cd3a0c6754d36cb5a7acbd9fa64c38080a681608c41165736dc88438acfc71"
SRC_URI[deb0.sha512sum] = "2c1d29d57f0c3b86b3d2518ef1d165ad8ae2e8086b62951797ef5518de8ad0b72b68daf889cabb08fd55890ded5a4486fd8e5865c5a86b29e4d1d0998c6514ca"


RPROVIDES = " \
    libc6-arm64-dcv1 \
"
