# This was autogenerated! Do not modify
SUMMARY = "Poetry PEP 517 Build Backend"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "poetry-core"
HOMEPAGE = "https://github.com/python-poetry/poetry-core"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/poetry-core/python3-poetry-core_2.1.2-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "3b30b4f62a89d8b6961d1ce5f51c2b72"
SRC_URI[deb0.sha1sum] = "1a9d8a2a01c58ae49e9c39e44215e9b76ab590fe"
SRC_URI[deb0.sha256sum] = "84e1d1e2a6d36119e1d1c2550b64d3ef9c6d92a1b9a1b61712ffc026a9b9a2db"
SRC_URI[deb0.sha512sum] = "d7f0a48bacbabb31709d60fda3f709eb04c46c900ec307c8bac144821dc111b1e9a39daf425ab7f9b54033baa7cccc1e8999ebfd463965449f73a6a4a5d256bf"

RDEPENDS = " \
    python3 \
"

