# This was autogenerated! Do not modify
SUMMARY = "implementation of the EBU R128 loudness standard"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "libebur128"
HOMEPAGE = "https://github.com/jiixyj/libebur128"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libe/libebur128/libebur128-1_1.2.6-1+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/libe/libebur128/libebur128-1_1.2.6-1+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "4c4b1b68c6e66286ec5c3f029bc5ebbb"
SRC_URI[deb0.sha1sum] = "2f35b9de8feb60c33fb9505a42c501f2f35c326f"
SRC_URI[deb0.sha256sum] = "ffeea31cb2a88deee3cb76ac04b8a4d4aa3d9e3e7ca3ca8485b0eefc6f3ba26f"
SRC_URI[deb0.sha512sum] = "24750f9964f8bafe25a4456f0b02a7061b1297541bfba030182f926e69a0fdc6d63989da9061f14e13268e4314ebf9656403888e2c302d83d65b0d091b5b4f74"
SRC_URI[deb1.md5sum] = "f5525c3261334dfa45e9418e34f9617b"
SRC_URI[deb1.sha1sum] = "12a3b67e932988ef3608cc40f573f38f0a1782ec"
SRC_URI[deb1.sha256sum] = "3b7ac8f30620590a710e6c8877bb28aad295e253a87a173f05f852a953be3326"
SRC_URI[deb1.sha512sum] = "2327500749dd52548efa2f54790a9fa1fd1afa2e25469f6dfcc78e7069fd78eee71050f4296fb358b55ee528cc758d6c6d579ac984e625276a6acf93a55b4966"

RDEPENDS = " \
    libc6 \
"

