# This was autogenerated! Do not modify
SUMMARY = "debug symbols for libblobmsg-json1"
DESCRIPTION = ""
SECTION = "debug"
SOURCE_PACKAGE = "libubox"
HOMEPAGE = ""

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/libu/libubox/libblobmsg-json1-dbgsym_20250807_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "20d7659e5e9ff430cc8af8e26d56b78e"
SRC_URI[deb0.sha1sum] = "168631780bf1474e47b0d058e2a67041852ba842"
SRC_URI[deb0.sha256sum] = "30cc72156209d2b4b494e41a954a05b7d27b1d98ffb5ee9058a3e45cb93ac3ee"

RDEPENDS = " \
    libblobmsg-json1 \
"

