# This was autogenerated! Do not modify
SUMMARY = "Vertical Blanking Interval decoder (VBI) - runtime files"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "zvbi"
HOMEPAGE = "https://github.com/zapping-vbi/zvbi"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/z/zvbi/libzvbi0t64_0.2.44-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/z/zvbi/libzvbi0t64_0.2.44-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "db577be5617782a5c66435350467fb1f"
SRC_URI[deb0.sha1sum] = "b9c88db3853d54947af28fb970b111d5bae186ec"
SRC_URI[deb0.sha256sum] = "ff9b1227f8812b4d51d24130bfeb436a3cc3159410d507cb370f6908e9059112"
SRC_URI[deb0.sha512sum] = "b65303c390544feac59fe7f9171d6205455075ab0ab226f74f49d43663a5746e82d44513722079076a38cc7b16a332005c66872f63b5966d11d16cf9f4883ff6"
SRC_URI[deb1.md5sum] = "b2e436ad074105e84f0edbb18d68c709"
SRC_URI[deb1.sha1sum] = "bd8459fbd5b2169662d974f3fee122a0948e8fca"
SRC_URI[deb1.sha256sum] = "ce0fa37ceeffcf844bbee9b00eba8e8dcffc1bf1a772007c8710ac6491598941"
SRC_URI[deb1.sha512sum] = "f48cd01453b2625fdaf718bda2a05f2b104979a04ac41d11d4113f96b3877037c5dd21d3d4480619f482c99b0b9110595966c50cd5f1a5404d87d0e56c8c7541"

RDEPENDS = " \
    libc6 \
    libpng16-16t64 \
    libzvbi-common \
"

RPROVIDES = " \
    libzvbi0 \
"
