# This was autogenerated! Do not modify
SUMMARY = "Python module to validate configuration files"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "cfgv"
HOMEPAGE = "https://github.com/asottile/cfgv"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/c/cfgv/python3-cfgv_3.4.0-5_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "a1026c3a1534c4587fe25e7efd9557fd"
SRC_URI[deb0.sha1sum] = "12f3cfeb47775008b281261af9a1c65d1067fb68"
SRC_URI[deb0.sha256sum] = "af91d588de6ed16563aa3063c7e7cc5a6db52d7f223b94130c71838000440dec"
SRC_URI[deb0.sha512sum] = "05d9325dfb69d6d728d6151914d00b4e828294b0f7b14510552a9f2c8cacd096a2c3af7019632d337be9a1f5493c5895b8dc3407567b9951965a3d176c743182"

RDEPENDS = " \
    python3 \
"

