# This was autogenerated! Do not modify
SUMMARY = "UEFI firmware for 64-bit x86 virtual machines"
DESCRIPTION = ""
SECTION = "misc"
SOURCE_PACKAGE = "edk2"
HOMEPAGE = "http://www.tianocore.org"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/e/edk2/ovmf_2025.02-8+deb13u1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "7e01c942793d698d775583239d42c008"
SRC_URI[deb0.sha1sum] = "e22ebb3da0cbf61fb9b0fefa2d7f79d08c878885"
SRC_URI[deb0.sha256sum] = "78e0d54df11fc77406cb7a0bc9a39e5bca6d1cbe06556b91d9a73491c52decdf"
SRC_URI[deb0.sha512sum] = "128581ccada5e5d888aa71bcffd83708341070e1273456c6aff1e0e7cd3c749310174ba59f69a3519f3bb9bd809abfa033d144305cb90cd2a0dac3ce74e633c1"


