# This was autogenerated! Do not modify
SUMMARY = "lightweight crypto and SSL/TLS library - development files"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "mbedtls"
HOMEPAGE = "https://www.trustedfirmware.org/projects/mbed-tls/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/mbedtls/libmbedtls-dev_3.6.5-0.1~deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/m/mbedtls/libmbedtls-dev_3.6.5-0.1~deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "634f6b0c16fac5872821da9026e98ba7"
SRC_URI[deb0.sha1sum] = "26e316e931597e8e3c195f2ba647bddf24e79049"
SRC_URI[deb0.sha256sum] = "e5ea5b0e9fa5019d3706ee65d734d50cb10b9dae9936e6d0ce441fe3d220fa05"
SRC_URI[deb0.sha512sum] = "54822512caa01ee6067ccfa4d9ddc63e7fbb0b3a9f58efc7381f5b38b9c1a5365f3f8d8ae0d454d7f9ea732693628a8758fa5ae0bb598dc01b7c92e5aa8e8ea9"
SRC_URI[deb1.md5sum] = "721feda73700352e119033faea72493d"
SRC_URI[deb1.sha1sum] = "fcf7fed6097cd1eefc4b953dd2e32056a972bc0c"
SRC_URI[deb1.sha256sum] = "e6d58a3c240cc3e98acd35a3f02cf25ed30fd7e69f269b6ce8671f6b33772311"
SRC_URI[deb1.sha512sum] = "c17b6af19d8d96fbbfa480c68f90199324f2dedc34aca608443ddea2c2e93afbdafb7f75b54c5b2a573936492f09ca63c0503619ac06f19d43584d521ce93e65"

RDEPENDS = " \
    libmbedcrypto16 \
    libmbedtls21 \
    libmbedx509-7 \
"

