# This was autogenerated! Do not modify
SUMMARY = "Library of linear algebra routines 3 - shared version"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "lapack"
HOMEPAGE = "https://www.netlib.org/lapack/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lapack/liblapack3_3.12.1-6_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/lapack/liblapack3_3.12.1-6_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "070d94c9032ed79d6d1a7a3b992ac78c"
SRC_URI[deb0.sha1sum] = "98374b9cf4381f8a153df76787fc312bc3af4875"
SRC_URI[deb0.sha256sum] = "abfc59c8410beee738617bb6daf86b295e45ec0bd08cc0e97bfecc3cfa40fe75"
SRC_URI[deb0.sha512sum] = "d32f971802ce7f1cc24ac210743056723081bf0a5453f9643e3e516f078a44f106432764d72383537b6af80838fbe51555efb0643baf5837dba70286e9c93a1d"
SRC_URI[deb1.md5sum] = "89539bd01fe844e233908bbfd85cf7f5"
SRC_URI[deb1.sha1sum] = "77649991ce7b282aaf4d603946f558c35beb323e"
SRC_URI[deb1.sha256sum] = "b1375f31fd6977f0cdacdd1de44a5f5081433d91737ea8fe9d0e64ab2ccfab12"
SRC_URI[deb1.sha512sum] = "c8e1be6d83e723857a857c8a60fbd033724818ce2dbd1f0aa62ed0258f8b75595b7ac461f972826129f4c16363e34151e0ba566908c291cf2a7ffb6129d7dc7f"

RDEPENDS = " \
    libblas3 \
    libc6 \
    libgcc-s1 \
    libgfortran5 \
"

RPROVIDES = " \
    liblapack.so.3 \
"
