# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format coredump"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Coredump utility package."
SECTION = "utils"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elos-coredump_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "073e6bce9fed714c21a17a7d7e406b73"
SRC_URI[deb0.sha1sum] = "618b12291c2a25eb20009fb6027f50c957f5e2a5"
SRC_URI[deb0.sha256sum] = "5e3f183af4582533328c08e4d5bff5ad08019b4365872906673be551e0e83fc1"

RDEPENDS = " \
    libc6 \
    libelos1 \
    libsafu0 \
    libsamconf0 \
"

