# This was autogenerated! Do not modify
SUMMARY = "Event logging and management with normalized output-format client"
DESCRIPTION = "elos is a tool to collect, store and publish various system events (i.e. \
syslogs, core dumps, measurements obtained from proc- and sys-fs, ...) \
while providing easy access to the collected data. \
 \
Client package."
SECTION = "utils"
SOURCE_PACKAGE = "elos"
HOMEPAGE = "https://github.com/Elektrobit/elos"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_THIRD_PARTY_REBUILT_BY_ELEKTROBIT}/pool/main/e/elos/elosc_0.0.1_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "4a2efed322feba7bd0531b9eb4d50d1f"
SRC_URI[deb0.sha1sum] = "b413e069c4312d451dffbaaa25261e3cc272b419"
SRC_URI[deb0.sha256sum] = "f58b571b591866dd768862855d436320c7a94c6c2ddbceee9cbf24ef910e58a2"

RDEPENDS = " \
    libc6 \
    libelos-common1 \
    libelos1 \
    libsafu0 \
"

