# This was autogenerated! Do not modify
SUMMARY = "clang-based tools for C/C++ developments"
DESCRIPTION = "Clang project is a C, C++, Objective C and Objective C++ front-end \
based on the LLVM compiler. Its goal is to offer a replacement to the \
GNU Compiler Collection (GCC). \
 \
Clang implements all of the ISO C++ 1998, 11, 14 and 17 standards and also \
provides most of the support of C++20. \
 \
This package contains some clang-based tools like scan-build, clang-cl, etc."
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clang-tools-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clang-tools-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "d5e57c7be52d75a2bc3ebb48586c8d28"
SRC_URI[deb0.sha1sum] = "83440e12323474899d25deb85a5f996f7e0f9b80"
SRC_URI[deb0.sha256sum] = "b4cffff82814114279cad979e430e7d84a801f21c7e8dfaa5901e982c6340214"
SRC_URI[deb0.sha512sum] = "8b991ff8dfd688a7fa93506a56610d61712a7fb146de8577543bf4fd59ce25399df530f431ef2b545b17e380805589b5bc669c87a0be61eb50d8e387a2710f95"
SRC_URI[deb1.md5sum] = "e5fc9ae875ea452540e6601ada20146b"
SRC_URI[deb1.sha1sum] = "95ec5a7421f37416ef895e94853f0d3d8a1b98a6"
SRC_URI[deb1.sha256sum] = "1927b0eab7740aa80e485671c1fa5d9bcbc736b21ae1f5ebb2ceed31f6c8a0ef"
SRC_URI[deb1.sha512sum] = "2955563a98c9a22da8247c384b02d1640f0b7ea28a60038595abc5302c2bc198b3c91a0fc8de86e52c8c24ea948f176cd41add95be4c4fea26a70a35ece25d7e"

RDEPENDS = " \
    clang-20 \
    libc6 \
    libclang-cpp20 \
    libclang1-20 \
    libgcc-s1 \
    libllvm20 \
    libstdc++6 \
    libxml2 \
    libz3-4 \
    libzstd1 \
    python3 \
    zlib1g \
"

