# This was autogenerated! Do not modify
SUMMARY = "Tool to format C/C++/Obj-C code"
DESCRIPTION = "Clang-format is both a library and a stand-alone tool with the goal of \
automatically reformatting C++ sources files according to configurable \
style guides. To do so, clang-format uses Clang's Lexer to transform an \
input file into a token stream and then changes all the whitespace around \
those tokens. The goal is for clang-format to both serve both as a user \
tool (ideally with powerful IDE integrations) and part of other \
refactoring tools, e.g. to do a reformatting of all the lines changed \
during a renaming. \
 \
This package also provides vim and emacs plugins."
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clang-format-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clang-format-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "5f08df0e8685592fb0a8d3932eb44a86"
SRC_URI[deb0.sha1sum] = "99bb8e1344464b83f45d48e6a3f8c8370905187d"
SRC_URI[deb0.sha256sum] = "cd7b48ee0d6df2fbcf7649b02b1c584d25980ff8193191eb6ed3c9b40981c976"
SRC_URI[deb0.sha512sum] = "a5fd1629fac99748b29d48ec260c62b594964ce60fae6aed341fa7be2da6526bc39da90c344efcd3d66acc797f5ba4a4bc936317ea2aec0df4aca42db31e14ca"
SRC_URI[deb1.md5sum] = "19007e0cedceb9679c26d66e4f6f481a"
SRC_URI[deb1.sha1sum] = "90261d0862b05f33d0f1bd360f9ba8e801b0a3d7"
SRC_URI[deb1.sha256sum] = "ba47573fdab0019aba8474fe208e5a2b8fb268146730ac56881b0d3a0828ebfa"
SRC_URI[deb1.sha512sum] = "a75a0c39dacd85ede9148e62a88d5b33635242f94cfdf75b5331db39084210e41c30c74d31eef3bef3b461c4e66e622556b46cbcde69c59c79e047bd98fdd1e9"

RDEPENDS = " \
    libc6 \
    libclang-cpp20 \
    libgcc-s1 \
    libllvm20 \
    libstdc++6 \
    python3 \
"

