# This was autogenerated! Do not modify
SUMMARY = "Language server that provides IDE-like features to editors"
DESCRIPTION = "clangd understands your C++ code and adds smart features to your editor: \
 - code completion \
 - compile errors \
 - go-to-definition \
 - and more. \
 \
clangd is a language server that implements the Language Server Protocol; \
it can work with many editors through a plugin."
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clangd-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clangd-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b7932cd88918bec133c82d66919edbb0"
SRC_URI[deb0.sha1sum] = "6502c8b42ebb5572db7252868e4360c0e07a782d"
SRC_URI[deb0.sha256sum] = "542e40e788404227dafa07a63e9e57700eb25c901a1e87bec3b42712085ff296"
SRC_URI[deb0.sha512sum] = "347fb1f924a02cd5a7a8ab090508ea69916eec49d166201233c28f100dd25c121ae73af2298d128fd572df503c1c42d184cf9008e752a399ebdbc096f3951737"
SRC_URI[deb1.md5sum] = "183297f945848dee48580ce509504acb"
SRC_URI[deb1.sha1sum] = "5a668b34bda31cdb17b8c0a7f1c0fd1a0972bebf"
SRC_URI[deb1.sha256sum] = "7817caa40241270fb1d7dec84ae89dac061b5c9fcf878c057615211480ac126d"
SRC_URI[deb1.sha512sum] = "71e08448315e67f440a122be27f6d60229a92fc6f38c39ae43379ea9850ce8273272a50ab44f8287ed5f2ee863902395d896ce4dabb2821da439ad8efc750ce5"

RDEPENDS = " \
    libabsl20240722 \
    libc6 \
    libclang-common-20-dev \
    libclang-cpp20 \
    libgcc-s1 \
    libgrpc++1.51t64 \
    libgrpc29t64 \
    libllvm20 \
    libprotobuf32t64 \
    libstdc++6 \
"

