# This was autogenerated! Do not modify
SUMMARY = "C, C++ and Objective-C compiler"
DESCRIPTION = "Clang project is a C, C++, Objective C and Objective C++ front-end \
based on the LLVM compiler. Its goal is to offer a replacement to the \
GNU Compiler Collection (GCC). \
 \
Clang implements all of the ISO C++ 1998, 11, 14 and 17 standards and also \
provides most of the support of C++20."
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clang-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/clang-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "eb0a7cc9cc2b98dead5d697575c367e0"
SRC_URI[deb0.sha1sum] = "f1d055423b306df5d7fb7ecfc5462d76d0b0af92"
SRC_URI[deb0.sha256sum] = "9c33d0d0809abb48891f6f69c2eb31af31d8b73b6fb223dbd12c6e78edbc42cf"
SRC_URI[deb0.sha512sum] = "3a0236741cf38662d57b95bb5545ffa3a901800e558e820415de8dee9246056af2abc8394035e32f7fd0099abefd44a70b72169fe04d65b0d82c32272035c068"
SRC_URI[deb1.md5sum] = "3771e73b80802be60954053f70987e1f"
SRC_URI[deb1.sha1sum] = "2f89c5439d43bf24a8bfc59040bc6483a6608b08"
SRC_URI[deb1.sha256sum] = "b8295bd9d7d3090fbaf40495224466684bde6e0ceb5fa385c596a1312b64a1f6"
SRC_URI[deb1.sha512sum] = "402ac857c5dc606a37b4d920100ecb9366189dd0bda43033acaa4a3f782165dfe0fa6a50763792d07e6c213904c7eaec4251bda84239e13ef9a685872e542188"

RDEPENDS = " \
    binutils \
    libc6 \
    libc6-dev \
    libclang-common-20-dev \
    libclang-cpp20 \
    libclang1-20 \
    libgcc-14-dev \
    libgcc-s1 \
    libllvm20 \
    libobjc-14-dev \
    libstdc++-14-dev \
    libstdc++6 \
    llvm-20-linker-tools \
"

RPROVIDES = " \
    c++-compiler \
    c-compiler \
    objc++-compiler \
    objc-compiler \
"
