# This was autogenerated! Do not modify
SUMMARY = "Offload Library"
DESCRIPTION = "The offload library facilitates efficient task distribution by offloading \
specific computational tasks from the CPU to alternative hardware accelerators \
such as GPUs or FPGAs."
SECTION = "devel"
SOURCE_PACKAGE = "llvm-toolchain-20"
HOMEPAGE = "https://www.llvm.org/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/liboffload-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_amd64.deb;name=deb0 \
    ${REPO_LLVM}/pool/llvm_20/l/llvm-toolchain-20/liboffload-20_20.1.8~++20250809043815+87f0227cb601-1~exp1~20250809163919.3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "fc6f8612a41e8b953c522a123bbfface"
SRC_URI[deb0.sha1sum] = "0ac3f4de875566dc783f584e689f902520b8355f"
SRC_URI[deb0.sha256sum] = "03717eecf013ffd6f1b689603930439e22eda47df7f7a51df4e0f412814d1394"
SRC_URI[deb0.sha512sum] = "deaf0971451afe6aeb2bbeb05b97fd379066f1fc64a3525053cec0301927f10732fce8d8bafc7abe846171587e1bee3fa2d05f9582a260b6ef98b6bc91fa9c28"
SRC_URI[deb1.md5sum] = "a5c0fff3e931509c2d84f77c1d6b4a25"
SRC_URI[deb1.sha1sum] = "2001b444b6eb75fc951c5078819fca19eace477e"
SRC_URI[deb1.sha256sum] = "c55371490dd25bf759cba406f1be02e235490421bdf845cae745589fd22eba07"
SRC_URI[deb1.sha512sum] = "8cea167cf2597c30a7756be9f5d6651e59a2944f8039c02ff1d41581a9f19cf8defe7ab240a7b7f9ce0f5236ed0509e4b1257bcaf269705d56786084bdf9fe33"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libllvm20 \
    libstdc++6 \
"

RPROVIDES = " \
    liboffload-x.y \
"
