# This was autogenerated! Do not modify
SUMMARY = "bash/zsh tab completion for argparse (for Python 3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-argcomplete"
HOMEPAGE = "https://github.com/kislyuk/argcomplete"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-argcomplete/python3-argcomplete_3.6.2-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "b2f39dde1ae2f46b2373fe2803e4aa09"
SRC_URI[deb0.sha1sum] = "4d01f798958fd8976b810ec489ad2d331afc5933"
SRC_URI[deb0.sha256sum] = "6972b4787fe900b1ec093f7828fd7d96dff59bbb1ef6763664921fc997a82475"
SRC_URI[deb0.sha512sum] = "fc57101f320ed0544b8673b00980ff452e6f0a878db6d3f9a320ffd90d37d357c4f792932f968559ccb183a7dab7d322c9ebaa341bb39a966c698a6470f72321"

RDEPENDS = " \
    python3 \
"

