# This was autogenerated! Do not modify
SUMMARY = "reference implementation of a wayland compositor"
DESCRIPTION = ""
SECTION = "x11"
SOURCE_PACKAGE = "weston"
HOMEPAGE = "https://wayland.pages.freedesktop.org/weston/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/w/weston/weston_14.0.2-1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/w/weston/weston_14.0.2-1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "c8047647ba69289ced78fc8ecc37a2d3"
SRC_URI[deb0.sha1sum] = "4e8613eac1f1ccf4d3a4edd98f384dfb44f85fbf"
SRC_URI[deb0.sha256sum] = "cb2cddfc082a6f14d15e4682cdbb9778439f9b89123ed41356f108ccb3ebb48e"
SRC_URI[deb0.sha512sum] = "71c237a87a887aaec2c0dc294a7761ef2f7f6e8d9fe179b037466fa0d03b4097cb7b21c1516e2ba14ae2f70f642ca005242c95d16c5ca44e805d1e0e13b5948c"
SRC_URI[deb1.md5sum] = "d63050e8d51afdaf7b6e6675dbe4bc8a"
SRC_URI[deb1.sha1sum] = "019bf4e0c431ee7d9689c8999b2a171619b783cd"
SRC_URI[deb1.sha256sum] = "712a752afbef1c0b75fd199ed2de87f9c225ffe4f03845bbf601add3df89a5a3"
SRC_URI[deb1.sha512sum] = "007408e057f9b000c752f632c7f71350189385c5ca5a90197d16374236ce42fe12dce85edac109da2b4fd1af84df5cb8006d10a2e3f9bcac139f01a037e740f1"

RDEPENDS = " \
    libc6 \
    libcairo2 \
    libdrm2 \
    libegl1 \
    libevdev2 \
    libfontconfig1 \
    libgbm1 \
    libgles2 \
    libglib2.0-0t64 \
    libinput10 \
    libjpeg62-turbo \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpixman-1-0 \
    libpng16-16t64 \
    libsystemd0 \
    libudev1 \
    libwayland-client0 \
    libwayland-cursor0 \
    libwayland-egl1 \
    libwayland-server0 \
    libwebp7 \
    libweston-14-0 \
    libxkbcommon0 \
"

