# This was autogenerated! Do not modify
SUMMARY = "module providing convenience functions for managing processes (Python3)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-psutil"
HOMEPAGE = "https://github.com/giampaolo/psutil"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-psutil/python3-psutil_7.0.0-2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-psutil/python3-psutil_7.0.0-2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "923bd2b2a751e955892bddad2cc4997d"
SRC_URI[deb0.sha1sum] = "604b484a1cf2050a9b88fb415d3bfdc450bffd45"
SRC_URI[deb0.sha256sum] = "6ff93ff86128c8cd8bfbd72350ca5eede97a174a1f990d80403a0b9c4edf85e0"
SRC_URI[deb0.sha512sum] = "4b91b8ca0831560fc7790af493acc33706c9a20905804fe6d75d192a8e61b291d4f62d0d7912f88c1f3cbf7fc1a1f15c4fa5700fd68a68c3598f4e9627be6d0e"
SRC_URI[deb1.md5sum] = "7c953795dd559d0cd1375b707d409570"
SRC_URI[deb1.sha1sum] = "e1735934a9036c1b03bf6bb25709f3a7a47d9091"
SRC_URI[deb1.sha256sum] = "95ba29d7142893a04c8f1e4024985f4981f8a31a9a1f03a5c647df872921452f"
SRC_URI[deb1.sha512sum] = "9d42707ab66d3b53d86b34dc3b91f94a6c5e58c7135f40d4c49c87facc59d100573b4c37ac901b397e4b5e8619a8a4863109a1f8fc4ed1a4d59d700cb08feead"

RDEPENDS = " \
    libc6 \
    python3 \
"

