# This was autogenerated! Do not modify
SUMMARY = "Roundtrip YAML parser/emitter (Python 3 module)"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "ruamel.yaml"
HOMEPAGE = "https://yaml.readthedocs.io"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/ruamel.yaml/python3-ruamel.yaml_0.18.10+ds-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "28410c31002a81f0adc0d166e99bbcda"
SRC_URI[deb0.sha1sum] = "489ab51c0c122ae632b35f1f8a3c0e0c4bebe9ec"
SRC_URI[deb0.sha256sum] = "366255ee65bea104f920e21928c0e930bc34e8b569d30494f66cfac73047db98"
SRC_URI[deb0.sha512sum] = "db194eddb781caa92cbb47ee62d97220b0c5a14ca1aa207f1d181ab7d936ccc3d4e2a1b3b6fc042b31e6e6a1b6bc0c43bad8634977cfc5a641881ac754b57290"

RDEPENDS = " \
    python3 \
    python3-ruamel.yaml.clib \
"

