# This was autogenerated! Do not modify
SUMMARY = "Tool to format C/C++/Obj-C code"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "llvm-defaults"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-defaults/clang-format_19.0-63_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/l/llvm-defaults/clang-format_19.0-63_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "b31c782cf7df28106a3eabf0f4cc527d"
SRC_URI[deb0.sha1sum] = "304d6b16353e3a61a87b9a9a6ab94a760fb367d0"
SRC_URI[deb0.sha256sum] = "c9ed32a010b98bc4d092c283771c17a6c639d5c5362031526fed152c3a90e52b"
SRC_URI[deb0.sha512sum] = "e6fce417a79bb3ee57799c01fe2416e91d288fecf8f95266a7ade4702b855279c8e4f645093ff44d327ced839ae268b92b3c19ad1f6edc8c78c416de1a351a03"
SRC_URI[deb1.md5sum] = "5105a218cbf1b0a8fab0b22122c5aaee"
SRC_URI[deb1.sha1sum] = "ca633bc9003fe2216958505567bb22300ad51a05"
SRC_URI[deb1.sha256sum] = "69fbe20ecd2613f8b933b76318305f4d1fd249def402a454f283cbfa6865c71b"
SRC_URI[deb1.sha512sum] = "1801e27960f16a217952b6c438f478542c14d22b91bbd1c9abd6ebacbec267ceed16d4d5695442957739ad40f739468d17b744658199f7722c88b5490e7eea18"

RDEPENDS = " \
    clang-format-19 \
"

