# This was autogenerated! Do not modify
SUMMARY = "Linux kernel debugging symbols for 6.12.94-cip26-ebclfsa1"
DESCRIPTION = "This package will come in handy if you need to debug the kernel. It provides \
all the necessary debug symbols for the kernel and its modules."
SECTION = "debug"
SOURCE_PACKAGE = "linux-ebclfsa-fastdev"
HOMEPAGE = "http://www.kernel.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "arm64"
SRC_URI = " \
    ${REPO_EBCLFSA_PUBLIC}/pool/main/l/linux-ebclfsa-fastdev/linux-image-ebclfsa-fastdev-dbg_6.12.94-cip26-ebclfsa1+r0_arm64.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "cdbbbd92ebbe5235ab2a7e648faed2ab"
SRC_URI[deb0.sha1sum] = "89136fa096946d0bfe3059fe7873b2a4763c2afa"
SRC_URI[deb0.sha256sum] = "e0c124a6a6d955c61c524b677e7a9f6f6bb90362c68acc074ddd6e8725c1ac85"


