# This was autogenerated! Do not modify
SUMMARY = "Python 3 wrapper around the OpenSSL library"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "pyopenssl"
HOMEPAGE = "https://pyopenssl.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/pyopenssl/python3-openssl_25.0.0-1+deb13u1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "78234ee4582e7620dc020eac776b7bf3"
SRC_URI[deb0.sha1sum] = "8af375b94f6ae969b62afcefb85b1a4086186768"
SRC_URI[deb0.sha256sum] = "c5487d811afd22921820e7cb38d2c6bc7e9a2428d9ce34c60738c36e0d7b1fa4"
SRC_URI[deb0.sha512sum] = "ff41f2c71549fd359a149621c0c970f8fad05c584f6b379343399917867feaee4c0a73aaf694eb8c8514286d23594ff9ea10d9b0a057a09cec21d8e74d93fe0b"

RDEPENDS = " \
    python3 \
    python3-cryptography \
    python3-typing-extensions \
"

