# This was autogenerated! Do not modify
SUMMARY = "GNU C Library: Development binaries"
DESCRIPTION = ""
SECTION = "libdevel"
SOURCE_PACKAGE = "glibc"
HOMEPAGE = "https://www.gnu.org/software/libc/libc.html"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/glibc/libc-dev-bin_2.41-12+deb13u3_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/glibc/libc-dev-bin_2.41-12+deb13u3_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "141b21da7ff6f9771ca8a950375083de"
SRC_URI[deb0.sha1sum] = "4a63880454e8cdb1c0fb13d23f472d8244039aad"
SRC_URI[deb0.sha256sum] = "2eb5db4cb16a42850ed9d3ca8b2b1aeda91dd00d248f6068f49d641321748308"
SRC_URI[deb0.sha512sum] = "3d2930c0de4e1427d51aa730f9112125033e0d19dcf9ddc77436b4a70ac22823ac617a98f78d3b5adb9a17a121e14ab32f865d7679ab57505439c132afbf206c"
SRC_URI[deb1.md5sum] = "9f2e9bfc6038f0a20802e20ea7f914da"
SRC_URI[deb1.sha1sum] = "dee4f891c433575b8bff6999ab48af9b571156c3"
SRC_URI[deb1.sha256sum] = "abe73702b06627e16b95b7928200f67385a14ad1f1c6edd9af135dd26092a485"
SRC_URI[deb1.sha512sum] = "49f7470fc1dc77138a237bc2bb2e12f8fcf57a0502cd4ce59f9c5bd977e42ad6d7e2c76ba52880dcac74baeef34e71184ee98468fc939b7de91b8809ddb447f9"

RDEPENDS = " \
    libc6 \
"

