# This was autogenerated! Do not modify
SUMMARY = "Miscellaneous utilities specific to Debian"
DESCRIPTION = ""
SECTION = "utils"
SOURCE_PACKAGE = "debianutils"
HOMEPAGE = ""

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/debianutils/debianutils_5.23.2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/d/debianutils/debianutils_5.23.2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "84739088394105b79e8df877d907c753"
SRC_URI[deb0.sha1sum] = "84c4bfe0a69ec1610d389f505356fee1654d79b8"
SRC_URI[deb0.sha256sum] = "720e43fda316676076498b4224ad3318049deafe60cc7c601011048de03ee97d"
SRC_URI[deb0.sha512sum] = "3ddad7312a36aa9114bd25638a0b52f73f6d5d3c2bda796c90028f68db92033bd7b8b903beb06755b6d41a35ec421bf93b6ed57e4d57cda790c2a8daeec0949d"
SRC_URI[deb1.md5sum] = "b0919e377c0a37de5fcc48aae17e7f5a"
SRC_URI[deb1.sha1sum] = "bc19c0300462bf0737556c0281c16f527ae7cd9a"
SRC_URI[deb1.sha256sum] = "662d59d9cd0d46f0250ddcd997353be915fbc6be692d7c676c73dc33c90715e8"
SRC_URI[deb1.sha512sum] = "dc3d4eafd191c81b47437f1341bdd4452ff4b8e65920be43e2aacad9ee05e91460aaa1f69c6b33c744e799b2b414434ba36dc2dfdb0a40e98b9a11c134962db7"

RDEPENDS = " \
    libc6 \
"

