# This was autogenerated! Do not modify
SUMMARY = "GNU troff text-formatting system (base system components)"
DESCRIPTION = ""
SECTION = "text"
SOURCE_PACKAGE = "groff"
HOMEPAGE = "https://www.gnu.org/software/groff/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/groff/groff-base_1.23.0-9_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/groff/groff-base_1.23.0-9_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "8ba16ca8313a50b2f8e70361499bf6de"
SRC_URI[deb0.sha1sum] = "9a82002970d520964b316c33be2644f04b2039e9"
SRC_URI[deb0.sha256sum] = "cb13bd856be0837d683377d618f2c0cc9b56b4abb2a821aafe33baf2b8ac215c"
SRC_URI[deb0.sha512sum] = "76116516baa426d66662a3ddc0a1e4937afcd86139c5cb18e4d78444a4ef524da3c78e5aae6b68cc750d80e8914da1c80cf81a57e00886d339838b939405b8cb"
SRC_URI[deb1.md5sum] = "141ce302b57978fa75ada3fcb82be06d"
SRC_URI[deb1.sha1sum] = "8cc86a32fe1d14ba7654d7d5b05ecd97fe190878"
SRC_URI[deb1.sha256sum] = "b41d0607b3357a8e1c7a277c486682fbbd703d39289f5ef6bbe6bdf48a939eed"
SRC_URI[deb1.sha512sum] = "bb7ea4f2e847f836fca988ce654252c13758175b9f32b4f0c4b21a3318364a279a53ca4a40e3ed39908f91eebac8585f3a555c8e3e7c0f380a6d6948ee744955"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
    libstdc++6 \
    libuchardet0 \
"

