# This was autogenerated! Do not modify
SUMMARY = "Fastest and safest AV1 encoder - shared library"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "rust-rav1e"
HOMEPAGE = "https://github.com/xiph/rav1e/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rust-rav1e/librav1e0.7_0.7.1-9+b2_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/r/rust-rav1e/librav1e0.7_0.7.1-9+b2_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "fab57a130388143574c34f30d233d3fa"
SRC_URI[deb0.sha1sum] = "417273de843f92ff68e85700ba2dac58a081e564"
SRC_URI[deb0.sha256sum] = "d5b1373a8d6905ee4523faf1db7a626dc660e03836ec91b616e57ba386f47eb6"
SRC_URI[deb0.sha512sum] = "978ba2fb4a31210494e367f165ab7363ff89de2e53e7b090ccfde46e527f99a89bb42ec1ed781288709f9544b84bd64f5769c960709c86759d691cbd3fab9487"
SRC_URI[deb1.md5sum] = "49241cffe82f76c19884d0f676359707"
SRC_URI[deb1.sha1sum] = "da45bb0633bcab08213dc5ddab0ef41e983c3860"
SRC_URI[deb1.sha256sum] = "1b81b3c3494033bb32573442ce49f253dc76e262de8b28d4bfa3f433cd9783d4"
SRC_URI[deb1.sha512sum] = "86eae2625ca6a2731fd632ac645aa574c19018ee7abe7ef8d8351637e957f7534276482e8af7292b52c9ab7e9607f6f1a10759d4c5e93a65cd7b746217ce4f62"

RDEPENDS = " \
    libc6 \
    libgcc-s1 \
"

