# This was autogenerated! Do not modify
SUMMARY = "GDK Pixbuf library - data files"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "gdk-pixbuf"
HOMEPAGE = "https://www.gtk.org/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gdk-pixbuf/libgdk-pixbuf2.0-common_2.42.12+dfsg-4+deb13u1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "4a155847d916d6db4bb869eb468341ed"
SRC_URI[deb0.sha1sum] = "1cfd8f9053c0b42bd1b63044865a0679a3963cca"
SRC_URI[deb0.sha256sum] = "9f0c64e33cf5bb3226a5a6ddf630dd76530596e476e6b47a8b27da444ff43a03"
SRC_URI[deb0.sha512sum] = "5ae6c58bc776868c9a19d5dc052a0fef65872fec88034602d398cae1f01866701970b98c77c54554925f9e9b84e601e6555bb9a5c2d35a4e6231f6f0a5b502ed"


