# This was autogenerated! Do not modify
SUMMARY = "http client/server for asyncio"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-aiohttp"
HOMEPAGE = "https://aiohttp.readthedocs.org"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-aiohttp/python3-aiohttp_3.11.16-1+deb13u1_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-aiohttp/python3-aiohttp_3.11.16-1+deb13u1_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "831439a8a390cb72059733588f5bd21c"
SRC_URI[deb0.sha1sum] = "95e5e8e7394cac6e55650eb806ee618be0307c03"
SRC_URI[deb0.sha256sum] = "bfd26da23cb1d797121644a62c88deb9dc3c48bbf2dd1024facde12711aae845"
SRC_URI[deb0.sha512sum] = "1724a4721ee51d2216c993a7c2c5bceb56609ee99244ef6a5679c4825010dc26b24b8b25cde6bc5aed8584f78cbda2102dd7d3e9f2b053e91783ad2899a28685"
SRC_URI[deb1.md5sum] = "2df698b00976a4431c8e344df2c8f897"
SRC_URI[deb1.sha1sum] = "f61920f416a48dcb8c82895df7e7671ad0ba316b"
SRC_URI[deb1.sha256sum] = "6d52eef46715be12818cc03e5f687916811a7dc2c5dbe679672cb9af47d642e0"
SRC_URI[deb1.sha512sum] = "448d7230671c6d1ac4d83618c034fc752885eebd601c987ff2c35f6213e4b52896480b8f06500ebd1d554c07cc2083f9b23ec970aba4cb18c8ffb34f40e87716"

RDEPENDS = " \
    libc6 \
    python3 \
    python3-aiohappyeyeballs \
    python3-aiosignal \
    python3-async-timeout \
    python3-attr \
    python3-frozenlist \
    python3-multidict \
    python3-propcache \
    python3-yarl \
"

