# This was autogenerated! Do not modify
SUMMARY = "core utilities for python3 packages"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "python-packaging"
HOMEPAGE = "https://github.com/pypa/packaging"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/p/python-packaging/python3-packaging_25.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "c2613ed1eb06bc2cbffaa5729f3e2306"
SRC_URI[deb0.sha1sum] = "75bb370f7a4abf46f27d2f7e692ad9c0340a2c5a"
SRC_URI[deb0.sha256sum] = "d70c8469f6e9c6105e1ebcd3ebdc963f11dadbeddd89d2d1a2a3cb1c97d2ecbc"
SRC_URI[deb0.sha512sum] = "11035c1b4841ad61db8d9ef051375d02206f1746f11083d3383ced43e537e9b6af2ebc66cb03f3b0b7e026d830cb3ea1ba0a472fe0010c5fe5472ba82888812e"

RDEPENDS = " \
    python3 \
"

