# This was autogenerated! Do not modify
SUMMARY = "Qt 6 Wayland platform plugin"
DESCRIPTION = ""
SECTION = "libs"
SOURCE_PACKAGE = "qt6-wayland"
HOMEPAGE = "https://www.qt.io/developers/"

inherit dpkg-prebuilt


SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-wayland/qt6-wayland_6.8.2-4_amd64.deb;name=deb0 \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/q/qt6-wayland/qt6-wayland_6.8.2-4_arm64.deb;name=deb1 \
"

SRC_URI[deb0.md5sum] = "93aad1cfa40755b1153cdf6bc7a8c0de"
SRC_URI[deb0.sha1sum] = "7915a0f2c5afeca205e6d35f86b2d671360c1c19"
SRC_URI[deb0.sha256sum] = "87b0905041f8f43164f9ff72ca00143a5c12bdcc2f06aacc0f7b178b16fa2c62"
SRC_URI[deb0.sha512sum] = "7cf8bc3bf796a1e67a27415ceb16be8d3a133f8bbf1976777b715074dc32082cf7044e25e4499d278ff3263233fa8a8002d35ae86d069cd5298ebf204acd84f7"
SRC_URI[deb1.md5sum] = "4ad9768f0119555eca22c275be6b2e1a"
SRC_URI[deb1.sha1sum] = "cd5269429fe636cae04b3ca398b2777790a0c2fe"
SRC_URI[deb1.sha256sum] = "1443cad2078e3f8fc6474a27ed5dfe418694037940c68e0def48cc1444685ad1"
SRC_URI[deb1.sha512sum] = "eee9ab1917d3ee625ba4661842e5cca4866954f42d7192199f1f58041185da84eb36dc5ad2a6cf4761aa68d380b40b2d14c739d1025a66a438c0ad987c14152c"

RDEPENDS = " \
    libc6 \
    libegl1 \
    libopengl0 \
    libqt6core6t64 \
    libqt6dbus6 \
    libqt6gui6 \
    libqt6opengl6 \
    libqt6svg6 \
    libqt6waylandclient6 \
    libqt6waylandcompositor6 \
    libqt6wlshellintegration6 \
    libstdc++6 \
    libwayland-client0 \
    libwayland-egl1 \
    libwayland-server0 \
    qt6-base-private-abi \
    qt6-waylandclient-private-abi \
    qt6-waylandcompositor-private-abi \
"

