# This was autogenerated! Do not modify
SUMMARY = "additional routines for obtaining class names"
DESCRIPTION = ""
SECTION = "python"
SOURCE_PACKAGE = "jaraco.classes"
HOMEPAGE = "https://github.com/jaraco/jaraco.classes"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/j/jaraco.classes/python3-jaraco.classes_3.4.0-1_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "e4480fb5b05fb4c6f70f20fe8268d087"
SRC_URI[deb0.sha1sum] = "23d56583aea79bef828a5742491339e3cd0b7e12"
SRC_URI[deb0.sha256sum] = "d13f5de725725597d6d348b80989b462d94bd7a613424267850880dae78fff7d"
SRC_URI[deb0.sha512sum] = "a16b9b8dfbead018ee1b47a6e8b28bd4176cc1c0be00519eba522c7fa5eef64f0b83b0d6992c9126e51d1a0995ec79ffa63c554b1068f07e83f4744926f7882a"

RDEPENDS = " \
    python3 \
    python3-more-itertools \
"

