# This was autogenerated! Do not modify
SUMMARY = "tool for setting up gettext infrastructure in a source package"
DESCRIPTION = ""
SECTION = "devel"
SOURCE_PACKAGE = "gettext"
HOMEPAGE = "https://www.gnu.org/software/gettext/"

inherit dpkg-prebuilt

DPKG_ARCH = "all"
SRC_URI = " \
    ${REPO_EB_UPSTREAM_BASELINE}/pool/trixie_main/g/gettext/autopoint_0.23.1-2_all.deb;name=deb0 \
"

SRC_URI[deb0.md5sum] = "f79fea3eff68e1ba172c17255d0d6f96"
SRC_URI[deb0.sha1sum] = "fe9bb2a40a8aa3f28df64b20dc72b8ec08e80d30"
SRC_URI[deb0.sha256sum] = "18696c3e02f2be55be0096ea510b2d82e602a47fc746ae41c91bbe680b06a569"
SRC_URI[deb0.sha512sum] = "3d272c23b4513c552c6121d8f12811734459b5290b3142d094fcfcec421223ff5241ce85247953745ab83656772a34fd567948e4a4781629129fdcd396391ce6"

RDEPENDS = " \
    xz-utils \
"

